# Generated by Django 4.2.7 on 2026-03-05 12:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('agent_space_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('icon_url', models.URLField(blank=True, default='')),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '已启用'), ('disabled', '已停用')], db_index=True, default='draft', max_length=20)),
                ('source', models.CharField(choices=[('agent_generated', 'Agent 生成'), ('user_created', '用户创建'), ('market', '市场安装'), ('shared', '团队共享')], default='agent_generated', max_length=30)),
                ('activation_mode', models.CharField(choices=[('auto', '自动展开'), ('suggest', '提示激活'), ('manual', '仅手动')], default='auto', max_length=20)),
                ('activation_rules', models.JSONField(default=list, help_text='激活规则列表，如 [{type, patterns, ...}]')),
                ('activation_match', models.CharField(default='any', help_text='规则匹配逻辑: any / all', max_length=10)),
                ('variables_schema', models.JSONField(default=dict, help_text='变量 schema，如 {name: {type, label, default, ...}}')),
                ('permissions', models.JSONField(default=list, help_text="权限声明列表，如 ['page_content', 'table_write']")),
                ('panel_position', models.CharField(choices=[('sidebar_right', '右侧边栏'), ('sidebar_left', '左侧边栏'), ('bottom_panel', '底部面板'), ('overlay', '浮层')], default='sidebar_right', max_length=20)),
                ('panel_width', models.IntegerField(default=360)),
                ('package_url', models.URLField(blank=True, default='', help_text='OSS 上的 zip 包地址')),
                ('manifest', models.JSONField(default=dict, help_text='完整的 manifest.json 内容')),
                ('panel_html', models.TextField(blank=True, default='', help_text='UI 面板 HTML 源码（用于快速渲染，避免每次下载 zip）')),
                ('content_script', models.TextField(blank=True, default='', help_text='页面注入脚本源码')),
                ('background_script', models.TextField(blank=True, default='', help_text='后台脚本源码')),
                ('agent_instructions', models.TextField(blank=True, default='', help_text='Agent 可读的上下文指令（Markdown）')),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tins_tin',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TinInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('agent_space_id', models.UUIDField(db_index=True)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('pinned', models.BooleanField(default=False, help_text='钉选常驻（即使规则不匹配也显示在 Tray 中）')),
                ('user_variables', models.JSONField(default=dict, help_text='用户自定义变量值，覆盖 Tin 的 variables_schema 默认值')),
                ('last_activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='tins.tin')),
            ],
            options={
                'db_table': 'tins_instance',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TinRunLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(help_text='操作类型：activate / deactivate / script_run / agent_invoke / goal_trigger', max_length=50)),
                ('input_data', models.JSONField(default=dict)),
                ('output_data', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_logs', to='tins.tininstance')),
            ],
            options={
                'db_table': 'tins_run_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tin',
            index=models.Index(fields=['workspace_id', 'status'], name='tins_tin_workspa_658977_idx'),
        ),
        migrations.AddIndex(
            model_name='tinrunlog',
            index=models.Index(fields=['instance', '-created_at'], name='tins_run_lo_instanc_42f803_idx'),
        ),
        migrations.AddIndex(
            model_name='tininstance',
            index=models.Index(fields=['agent_space_id', 'is_enabled'], name='tins_instan_agent_s_63b06b_idx'),
        ),
        migrations.AddConstraint(
            model_name='tininstance',
            constraint=models.UniqueConstraint(fields=('tin', 'agent_space_id'), name='uq_tin_instance_per_space'),
        ),
    ]
