# Generated by Django 4.2.7 on 2026-03-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tin',
            name='activation_match',
            field=models.CharField(choices=[('any', '任一匹配'), ('all', '全部匹配')], default='any', help_text='规则匹配逻辑: any / all', max_length=10),
        ),
    ]
