# Generated by Django 4.2.7 on 2026-03-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tins', '0002_add_activation_match_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinrunlog',
            name='action',
            field=models.CharField(choices=[('activate', '激活'), ('deactivate', '停用'), ('script_run', '脚本运行'), ('agent_invoke', 'Agent 调用'), ('goal_trigger', 'Goal 触发'), ('variable_update', '变量更新'), ('error', '错误')], help_text='操作类型：activate / deactivate / script_run / agent_invoke / goal_trigger', max_length=50),
        ),
    ]
