# Generated by Django 4.2.7 on 2026-03-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tins', '0003_add_runlog_action_choices'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tininstance',
            name='uq_tin_instance_per_space',
        ),
        migrations.RemoveIndex(
            model_name='tininstance',
            name='tins_instan_agent_s_63b06b_idx',
        ),
        migrations.AlterField(
            model_name='tin',
            name='agent_space_id',
            field=models.UUIDField(blank=True, db_column='agent_space_id', db_index=True, null=True),
        ),
        migrations.RenameField(
            model_name='tin',
            old_name='agent_space_id',
            new_name='space_id',
        ),
        migrations.AlterField(
            model_name='tininstance',
            name='agent_space_id',
            field=models.UUIDField(db_column='agent_space_id', db_index=True),
        ),
        migrations.RenameField(
            model_name='tininstance',
            old_name='agent_space_id',
            new_name='space_id',
        ),
        migrations.AddIndex(
            model_name='tininstance',
            index=models.Index(fields=['space_id', 'is_enabled'], name='tins_instan_agent_s_63b06b_idx'),
        ),
        migrations.AddConstraint(
            model_name='tininstance',
            constraint=models.UniqueConstraint(fields=('tin', 'space_id'), name='uq_tin_instance_per_space'),
        ),
    ]
