# Generated by Django 4.2.7 on 2026-03-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tins', '0004_remove_tininstance_uq_tin_instance_per_space_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tininstance',
            new_name='tins_instan_space_i_4aaf52_idx',
            old_name='tins_instan_agent_s_63b06b_idx',
        ),
        migrations.AlterField(
            model_name='tin',
            name='space_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='tininstance',
            name='space_id',
            field=models.UUIDField(db_index=True),
        ),
    ]
