# Generated by Django 4.2.7 on 2026-03-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tins', '0006_workspace_to_workteam_rename'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tin',
            name='tins_tin_workspa_658977_idx',
        ),
        migrations.AddIndex(
            model_name='tin',
            index=models.Index(fields=['workteam_id', 'status'], name='tins_tin_worktea_f48a73_idx'),
        ),
    ]
