# Generated by Django 4.2.7 on 2026-07-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tins', '0008_rename_workteam_to_organization'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tin',
            new_name='tins_tin_organiz_66a403_idx',
            old_name='tins_tin_worktea_f48a73_idx',
        ),
        migrations.AlterField(
            model_name='tin',
            name='source',
            field=models.CharField(choices=[('agent_generated', 'Agent 生成'), ('user_created', '用户创建'), ('market', '市场安装'), ('shared', '组织共享')], default='agent_generated', max_length=30),
        ),
    ]
