# Generated by Django 4.2.7 on 2026-03-04 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tabdata', '0001_initial'),
        ('oss', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tablewebhook',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabdata_webhooks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tableview',
            name='created_by',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='tableview',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='tabdata.table', verbose_name='所属表格'),
        ),
        migrations.AddField(
            model_name='tablesnapshot',
            name='base_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diffs', to='tabdata.tablesnapshot', verbose_name='增量 diff 的基版本'),
        ),
        migrations.AddField(
            model_name='tablesnapshot',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='tabdata.table', verbose_name='所属表格'),
        ),
        migrations.AddField(
            model_name='tableshare',
            name='created_by',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='tableshare',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='tabdata.table', verbose_name='所属表格'),
        ),
        migrations.AddField(
            model_name='tableshare',
            name='view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tabdata.tableview', verbose_name='分享的视图'),
        ),
        migrations.AddField(
            model_name='tablerecord',
            name='created_by',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_records', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='tablerecord',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='tabdata.table', verbose_name='所属表格'),
        ),
        migrations.AddField(
            model_name='tablerecord',
            name='updated_by',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_records', to=settings.AUTH_USER_MODEL, verbose_name='最后修改者'),
        ),
        migrations.AddField(
            model_name='tablepermission',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='tabdata.table'),
        ),
        migrations.AddField(
            model_name='tablenamedversion',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='tablenamedversion',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='named_versions', to='tabdata.table', verbose_name='所属表格'),
        ),
        migrations.AddField(
            model_name='tablefield',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='tabdata.table', verbose_name='所属表格'),
        ),
        migrations.AddField(
            model_name='tableapitoken',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddIndex(
            model_name='tableadminactionlog',
            index=models.Index(fields=['action_type', 'created_at'], name='tabdata_adm_action__92e78e_idx'),
        ),
        migrations.AddIndex(
            model_name='tableadminactionlog',
            index=models.Index(fields=['operator_id', 'created_at'], name='tabdata_adm_operato_c7dc45_idx'),
        ),
        migrations.AddIndex(
            model_name='tableadminactionlog',
            index=models.Index(fields=['success', 'created_at'], name='tabdata_adm_success_fca9a6_idx'),
        ),
        migrations.AddIndex(
            model_name='tableadminactionlog',
            index=models.Index(fields=['dry_run', 'created_at'], name='tabdata_adm_dry_run_b5a862_idx'),
        ),
        migrations.AddField(
            model_name='table',
            name='default_view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tabdata.tableview', verbose_name='默认视图'),
        ),
        migrations.AddField(
            model_name='table',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tables', to=settings.AUTH_USER_MODEL, verbose_name='所有者'),
        ),
        migrations.AddField(
            model_name='recordhistoryitem',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tabdata.recordhistory', verbose_name='所属历史'),
        ),
        migrations.AddField(
            model_name='recordhistoryitem',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_items', to='tabdata.tablerecord', verbose_name='所属记录'),
        ),
        migrations.AddField(
            model_name='recordhistoryitem',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作者'),
        ),
        migrations.AddField(
            model_name='recordhistory',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tabdata.tablerecord', verbose_name='所属记录'),
        ),
        migrations.AddField(
            model_name='recordhistory',
            name='undone_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undone_histories', to=settings.AUTH_USER_MODEL, verbose_name='撤销者'),
        ),
        migrations.AddField(
            model_name='recordhistory',
            name='user',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作者'),
        ),
        migrations.AddField(
            model_name='recordcomment',
            name='author',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论者'),
        ),
        migrations.AddField(
            model_name='recordcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tabdata.recordcomment', verbose_name='父评论'),
        ),
        migrations.AddField(
            model_name='recordcomment',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tabdata.tablerecord', verbose_name='所属记录'),
        ),
        migrations.AddField(
            model_name='linkrecord',
            name='foreign_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='tabdata.tablerecord', verbose_name='目标记录'),
        ),
        migrations.AddField(
            model_name='linkrecord',
            name='link_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_records', to='tabdata.tablefield', verbose_name='关联字段'),
        ),
        migrations.AddField(
            model_name='linkrecord',
            name='self_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='tabdata.tablerecord', verbose_name='源记录'),
        ),
        migrations.AddField(
            model_name='fieldsequence',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_states', to='tabdata.tablefield', verbose_name='自动标识字段'),
        ),
        migrations.AddField(
            model_name='fieldreference',
            name='from_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_refs', to='tabdata.tablefield', verbose_name='被依赖字段'),
        ),
        migrations.AddField(
            model_name='fieldreference',
            name='to_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_refs', to='tabdata.tablefield', verbose_name='依赖方字段'),
        ),
        migrations.AddField(
            model_name='fieldexecutionrecord',
            name='adopted_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adopted_executions', to=settings.AUTH_USER_MODEL, verbose_name='采纳者'),
        ),
        migrations.AddField(
            model_name='fieldexecutionrecord',
            name='executed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_executions', to=settings.AUTH_USER_MODEL, verbose_name='执行者'),
        ),
        migrations.AddField(
            model_name='fieldexecutionrecord',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_records', to='tabdata.tablefield', verbose_name='Skill 字段'),
        ),
        migrations.AddField(
            model_name='fieldexecutionrecord',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_executions', to='tabdata.tablerecord', verbose_name='所属记录'),
        ),
        migrations.AddField(
            model_name='fieldexecutionrecord',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_executions', to='tabdata.table', verbose_name='所属表格'),
        ),
        migrations.AddField(
            model_name='dbreadonlyconnection',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='db_connections', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='attachmentupload',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attachment_uploads', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='attachmentupload',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_uploads', to='tabdata.tablefield', verbose_name='所属字段'),
        ),
        migrations.AddField(
            model_name='attachmentupload',
            name='file_record',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabdata_uploads', to='oss.filerecord', verbose_name='上传生成的文件'),
        ),
        migrations.AddField(
            model_name='attachmentupload',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachment_uploads', to='tabdata.tablerecord', verbose_name='所属记录'),
        ),
        migrations.AddField(
            model_name='attachmentupload',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_uploads', to='tabdata.table', verbose_name='所属表格'),
        ),
        migrations.AddField(
            model_name='attachmentupload',
            name='upload_task',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='tabdata_uploads', to='oss.uploadtask', verbose_name='OSS上传任务'),
        ),
        migrations.AddField(
            model_name='attachmentreference',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attachment_references', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='attachmentreference',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_references', to='tabdata.tablefield', verbose_name='所属字段'),
        ),
        migrations.AddField(
            model_name='attachmentreference',
            name='file',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='tabdata_references', to='oss.filerecord', verbose_name='文件记录'),
        ),
        migrations.AddField(
            model_name='attachmentreference',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachment_references', to='tabdata.tablerecord', verbose_name='所属记录'),
        ),
        migrations.AddField(
            model_name='attachmentreference',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_references', to='tabdata.table', verbose_name='所属表格'),
        ),
        migrations.AddField(
            model_name='attachmentreference',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='references', to='tabdata.attachmentupload', verbose_name='上传任务'),
        ),
        migrations.AddIndex(
            model_name='tablewebhook',
            index=models.Index(fields=['agent_space_id', 'is_active'], name='tabdata_web_agent_s_6ad41d_idx'),
        ),
        migrations.AddIndex(
            model_name='tablewebhook',
            index=models.Index(fields=['table_id', 'is_active'], name='tabdata_web_table_i_2ef1e6_idx'),
        ),
        migrations.AddIndex(
            model_name='tableview',
            index=models.Index(fields=['table', 'order'], name='tabdata_vie_table_i_344c7a_idx'),
        ),
        migrations.AddIndex(
            model_name='tablesnapshot',
            index=models.Index(fields=['table', 'created_at'], name='tabdata_snap_tbl_created_idx'),
        ),
        migrations.AddIndex(
            model_name='tablesnapshot',
            index=models.Index(fields=['table', 'is_snapshot'], name='tabdata_snap_table_snap_idx'),
        ),
        migrations.AddIndex(
            model_name='tablesnapshot',
            index=models.Index(fields=['table', 'is_named'], name='tabdata_snap_table_named_idx'),
        ),
        migrations.AddIndex(
            model_name='tableshare',
            index=models.Index(fields=['share_id'], name='tabdata_sha_share_i_0e6a19_idx'),
        ),
        migrations.AddIndex(
            model_name='tableshare',
            index=models.Index(fields=['table', 'created_at'], name='tabdata_sha_table_i_de5df2_idx'),
        ),
        migrations.AddIndex(
            model_name='tablerecord',
            index=models.Index(fields=['table', 'is_deleted', 'order'], name='tabdata_rec_table_i_e0e207_idx'),
        ),
        migrations.AddIndex(
            model_name='tablerecord',
            index=models.Index(fields=['table', 'created_at'], name='tabdata_rec_table_i_8a8b63_idx'),
        ),
        migrations.AddIndex(
            model_name='tablerecord',
            index=models.Index(fields=['created_by', 'created_at'], name='tabdata_rec_created_66776f_idx'),
        ),
        migrations.AddIndex(
            model_name='tablerecord',
            index=models.Index(fields=['status'], name='tabdata_rec_status_a1a8cf_idx'),
        ),
        migrations.AddIndex(
            model_name='tablerecord',
            index=models.Index(fields=['table', 'version'], name='tabdata_rec_table_i_4ea604_idx'),
        ),
        migrations.AddIndex(
            model_name='tablepermission',
            index=models.Index(fields=['table', 'is_active'], name='tabdata_perm_tbl_active_idx'),
        ),
        migrations.AddIndex(
            model_name='tablepermission',
            index=models.Index(fields=['subject_type', 'subject_id'], name='tabdata_perm_subject_idx'),
        ),
        migrations.AddConstraint(
            model_name='tablepermission',
            constraint=models.UniqueConstraint(fields=('table', 'subject_type', 'subject_id'), name='tabdata_perm_unique_subject'),
        ),
        migrations.AddIndex(
            model_name='tablenamedversion',
            index=models.Index(fields=['table', 'created_at'], name='tabdata_nv_table_created_idx'),
        ),
        migrations.AddIndex(
            model_name='tablefield',
            index=models.Index(fields=['table', 'order'], name='tabdata_fie_table_i_52b134_idx'),
        ),
        migrations.AddIndex(
            model_name='tablefield',
            index=models.Index(fields=['table', 'is_primary'], name='tabdata_fie_table_i_e6a7ee_idx'),
        ),
        migrations.AddConstraint(
            model_name='tablefield',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('table', 'name'), name='uniq_active_field_name_per_table'),
        ),
        migrations.AddIndex(
            model_name='tableapitoken',
            index=models.Index(fields=['user', 'is_active'], name='tabdata_api_user_id_193c3a_idx'),
        ),
        migrations.AddIndex(
            model_name='tableapitoken',
            index=models.Index(fields=['token_id'], name='tabdata_api_token_i_81aaac_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['workspace_id', 'is_archived'], name='tabdata_tab_workspa_a7bd70_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['agent_space_id', 'is_archived'], name='tabdata_tab_agent_s_abfb07_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['agent_space_id', 'visibility'], name='tabdata_tab_agent_s_483646_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['owner', 'is_archived'], name='tabdata_tab_owner_i_3764f6_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['is_template', 'is_public'], name='tabdata_tab_is_temp_75cf92_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['created_at'], name='tabdata_tab_created_f40db3_idx'),
        ),
        migrations.AddIndex(
            model_name='recordhistoryitem',
            index=models.Index(fields=['history', 'created_at'], name='thi_hist_cre_idx'),
        ),
        migrations.AddIndex(
            model_name='recordhistoryitem',
            index=models.Index(fields=['record', 'created_at'], name='thi_rec_cre_idx'),
        ),
        migrations.AddIndex(
            model_name='recordhistoryitem',
            index=models.Index(fields=['field_key', 'created_at'], name='thi_fkey_cre_idx'),
        ),
        migrations.AddIndex(
            model_name='recordhistoryitem',
            index=models.Index(fields=['user', 'created_at'], name='thi_user_cre_idx'),
        ),
        migrations.AddIndex(
            model_name='recordhistory',
            index=models.Index(fields=['record', 'created_at'], name='th_rec_cre_idx'),
        ),
        migrations.AddIndex(
            model_name='recordhistory',
            index=models.Index(fields=['user', 'created_at'], name='th_user_cre_idx'),
        ),
        migrations.AddIndex(
            model_name='recordhistory',
            index=models.Index(fields=['action', 'created_at'], name='th_act_cre_idx'),
        ),
        migrations.AddIndex(
            model_name='recordhistory',
            index=models.Index(fields=['record', 'is_undone', 'created_at'], name='th_rec_undo_cre_idx'),
        ),
        migrations.AddIndex(
            model_name='recordhistory',
            index=models.Index(fields=['record', 'window_id', 'is_undone', 'created_at'], name='th_rec_win_undo_idx'),
        ),
        migrations.AddIndex(
            model_name='recordhistory',
            index=models.Index(fields=['operation_group_id'], name='th_opgrp_idx'),
        ),
        migrations.AddIndex(
            model_name='recordcomment',
            index=models.Index(fields=['record', 'created_at'], name='tabdata_com_record__f52afc_idx'),
        ),
        migrations.AddIndex(
            model_name='recordcomment',
            index=models.Index(fields=['author', 'created_at'], name='tabdata_com_author__07364b_idx'),
        ),
        migrations.AddIndex(
            model_name='linkrecord',
            index=models.Index(fields=['link_field', 'self_record'], name='tabdata_lin_link_fi_dc0f61_idx'),
        ),
        migrations.AddIndex(
            model_name='linkrecord',
            index=models.Index(fields=['link_field', 'foreign_record'], name='tabdata_lin_link_fi_0128f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='linkrecord',
            unique_together={('link_field', 'self_record', 'foreign_record')},
        ),
        migrations.AddIndex(
            model_name='fieldsequence',
            index=models.Index(fields=['field', 'reset_key', 'group_key'], name='tabdata_fie_field_i_3ffe19_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldsequence',
            index=models.Index(fields=['next_value'], name='tabdata_fie_next_va_0b5d62_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldsequence',
            index=models.Index(fields=['updated_at'], name='tabdata_fie_updated_c954ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='fieldsequence',
            constraint=models.UniqueConstraint(fields=('field', 'reset_key', 'group_key'), name='uniq_field_sequence_scope'),
        ),
        migrations.AddIndex(
            model_name='fieldreference',
            index=models.Index(fields=['from_field'], name='tabdata_fie_from_fi_7b3226_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldreference',
            index=models.Index(fields=['to_field'], name='tabdata_fie_to_fiel_b06097_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fieldreference',
            unique_together={('from_field', 'to_field')},
        ),
        migrations.AddIndex(
            model_name='fieldexecutionrecord',
            index=models.Index(fields=['table', 'field', 'created_at'], name='tabdata_fie_table_i_f802a3_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldexecutionrecord',
            index=models.Index(fields=['record', 'field', 'created_at'], name='tabdata_fie_record__3feff1_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldexecutionrecord',
            index=models.Index(fields=['batch_id'], name='tabdata_fie_batch_i_32bc87_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldexecutionrecord',
            index=models.Index(fields=['status'], name='tabdata_fie_status_deddcf_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldexecutionrecord',
            index=models.Index(fields=['bound_app_id', 'created_at'], name='tabdata_fie_bound_a_284b43_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldexecutionrecord',
            index=models.Index(fields=['batch_id', 'adoption_status'], name='tabdata_fie_batch_i_6a3214_idx'),
        ),
        migrations.AddIndex(
            model_name='attachmentupload',
            index=models.Index(fields=['table', 'field', 'status'], name='tabdata_att_table_i_e7bd52_idx'),
        ),
        migrations.AddIndex(
            model_name='attachmentupload',
            index=models.Index(fields=['upload_task', 'status'], name='tabdata_att_upload__17ebf6_idx'),
        ),
        migrations.AddIndex(
            model_name='attachmentreference',
            index=models.Index(fields=['table', 'field', 'is_deleted'], name='tabdata_att_table_i_e3a132_idx'),
        ),
        migrations.AddIndex(
            model_name='attachmentreference',
            index=models.Index(fields=['file', 'is_deleted'], name='tabdata_att_file_id_c3aa35_idx'),
        ),
        migrations.AddConstraint(
            model_name='attachmentreference',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('record', 'field', 'file'), name='uniq_active_attachment_reference'),
        ),
    ]
