# Generated by Django 4.2.7 on 2026-03-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabdata', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableview',
            name='view_type',
            field=models.CharField(choices=[('grid', '表格视图'), ('kanban', '看板视图'), ('calendar', '日历视图'), ('gallery', '画廊视图'), ('list', '列表视图'), ('flashcard', '闪卡视图')], default='grid', max_length=50, verbose_name='视图类型'),
        ),
    ]
