# Generated by Django 4.2.7 on 2026-03-06 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabdata', '0003_add_trash_fields'),
        ('tabdata', '0003_alter_tableview_view_type'),
    ]

    operations = [
    ]
