# Generated by Django 4.2.7 on 2026-03-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabdata', '0004_merge_20260306_1746'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='table',
            name='tabdata_tab_agent_s_abfb07_idx',
        ),
        migrations.RemoveIndex(
            model_name='table',
            name='tabdata_tab_agent_s_483646_idx',
        ),
        migrations.RemoveIndex(
            model_name='tablewebhook',
            name='tabdata_web_agent_s_6ad41d_idx',
        ),
        migrations.AlterField(
            model_name='attachmentreference',
            name='agent_space_id',
            field=models.UUIDField(blank=True, db_column='agent_space_id', db_index=True, null=True, verbose_name='所属 AgentSpace'),
        ),
        migrations.RenameField(
            model_name='attachmentreference',
            old_name='agent_space_id',
            new_name='space_id',
        ),
        migrations.AlterField(
            model_name='attachmentupload',
            name='agent_space_id',
            field=models.UUIDField(blank=True, db_column='agent_space_id', db_index=True, null=True, verbose_name='所属 AgentSpace'),
        ),
        migrations.RenameField(
            model_name='attachmentupload',
            old_name='agent_space_id',
            new_name='space_id',
        ),
        migrations.AlterField(
            model_name='dbreadonlyconnection',
            name='agent_space_id',
            field=models.UUIDField(db_column='agent_space_id', unique=True, verbose_name='AgentSpace ID'),
        ),
        migrations.RenameField(
            model_name='dbreadonlyconnection',
            old_name='agent_space_id',
            new_name='space_id',
        ),
        migrations.AlterField(
            model_name='table',
            name='agent_space_id',
            field=models.UUIDField(db_column='agent_space_id', db_index=True, verbose_name='所属 AgentSpace'),
        ),
        migrations.RenameField(
            model_name='table',
            old_name='agent_space_id',
            new_name='space_id',
        ),
        migrations.AlterField(
            model_name='tablewebhook',
            name='agent_space_id',
            field=models.UUIDField(db_column='agent_space_id', db_index=True, help_text='关联的 AgentSpace ID'),
        ),
        migrations.RenameField(
            model_name='tablewebhook',
            old_name='agent_space_id',
            new_name='space_id',
        ),
        migrations.AddField(
            model_name='table',
            name='rls_enabled',
            field=models.BooleanField(default=False, help_text='启用后，对 Open API 访问自动注入 RowPolicy 行级过滤条件', verbose_name='启用行级安全'),
        ),
        migrations.AddField(
            model_name='table',
            name='rls_force',
            field=models.BooleanField(default=False, help_text='启用后，JWT 用户（表格 Owner）也受 RLS 策略约束', verbose_name='强制 RLS'),
        ),
        migrations.AddField(
            model_name='table',
            name='schema_version',
            field=models.PositiveIntegerField(default=0, help_text='每次字段结构变更（增删改字段）时自动递增', verbose_name='Schema 版本号'),
        ),
        migrations.AddField(
            model_name='tablefield',
            name='api_name',
            field=models.CharField(blank=True, default='', help_text='给 SDK/API 用的稳定标识，不跟随 name (display_name) 变更。留空时 SDK 退化使用 name 作为 key。', max_length=255, verbose_name='API 稳定名称'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['space_id', 'is_archived'], name='tabdata_tab_agent_s_abfb07_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['space_id', 'visibility'], name='tabdata_tab_agent_s_483646_idx'),
        ),
        migrations.AddIndex(
            model_name='tablewebhook',
            index=models.Index(fields=['space_id', 'is_active'], name='tabdata_web_agent_s_6ad41d_idx'),
        ),
        migrations.AddConstraint(
            model_name='tablefield',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('api_name', ''), _negated=True)), fields=('table', 'api_name'), name='uniq_active_api_name_per_table'),
        ),
    ]
