# Generated by Django 4.2.7 on 2026-03-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabdata', '0005_remove_table_tabdata_tab_agent_s_abfb07_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='table',
            new_name='tabdata_tab_space_i_26c1b0_idx',
            old_name='tabdata_tab_agent_s_abfb07_idx',
        ),
        migrations.RenameIndex(
            model_name='table',
            new_name='tabdata_tab_space_i_817d1a_idx',
            old_name='tabdata_tab_agent_s_483646_idx',
        ),
        migrations.AlterField(
            model_name='attachmentreference',
            name='space_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='所属 Space'),
        ),
        migrations.AlterField(
            model_name='attachmentupload',
            name='space_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='所属 Space'),
        ),
        migrations.AlterField(
            model_name='table',
            name='space_id',
            field=models.UUIDField(db_index=True, verbose_name='所属 Space'),
        ),
    ]
