# Generated by Django 4.2.7 on 2026-03-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabdata', '0006_rename_tabdata_tab_agent_s_abfb07_idx_tabdata_tab_space_i_26c1b0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='source_type',
            field=models.CharField(choices=[('native', '原生表'), ('mirror', '镜像表'), ('proxy', '代理表')], db_index=True, default='native', help_text='native=本地存储, mirror=外部镜像, proxy=外部代理', max_length=16, verbose_name='数据源类型'),
        ),
        migrations.CreateModel(
            name='ApiUsageSummary',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=100, verbose_name='工作空间 ID')),
                ('space_id', models.UUIDField(blank=True, null=True, verbose_name='Space ID')),
                ('token_id', models.CharField(blank=True, default='', max_length=20, verbose_name='Token 标识')),
                ('path_template', models.CharField(blank=True, default='', max_length=200, verbose_name='路径模板')),
                ('period_type', models.CharField(choices=[('hour', 'Hour'), ('day', 'Day')], max_length=8, verbose_name='聚合粒度')),
                ('period_start', models.DateTimeField(verbose_name='周期起始时间')),
                ('total_requests', models.PositiveIntegerField(default=0, verbose_name='总请求数')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='成功数（2xx）')),
                ('client_error_count', models.PositiveIntegerField(default=0, verbose_name='客户端错误数（4xx）')),
                ('server_error_count', models.PositiveIntegerField(default=0, verbose_name='服务端错误数（5xx）')),
                ('rate_limited_count', models.PositiveIntegerField(default=0, verbose_name='限流数（429）')),
                ('avg_duration_ms', models.PositiveIntegerField(default=0, verbose_name='平均耗时（ms）')),
                ('p95_duration_ms', models.PositiveIntegerField(default=0, verbose_name='P95 耗时（ms）')),
                ('max_duration_ms', models.PositiveIntegerField(default=0, verbose_name='最大耗时（ms）')),
                ('total_response_bytes', models.BigIntegerField(default=0, verbose_name='总响应字节数')),
            ],
            options={
                'verbose_name': 'API 用量摘要',
                'verbose_name_plural': 'API 用量摘要',
                'db_table': 'tabdata_api_usage_summary',
                'indexes': [models.Index(fields=['workspace_id', 'period_type', 'period_start'], name='tabdata_api_workspa_85ef5d_idx'), models.Index(fields=['token_id', 'period_type', 'period_start'], name='tabdata_api_token_i_e02a02_idx')],
                'unique_together': {('workspace_id', 'space_id', 'token_id', 'path_template', 'period_type', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='ApiCallLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('request_id', models.CharField(db_index=True, max_length=36, verbose_name='请求 ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='请求时间')),
                ('workspace_id', models.CharField(db_index=True, max_length=100, verbose_name='工作空间 ID')),
                ('space_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Space ID')),
                ('token_id', models.CharField(blank=True, default='', max_length=20, verbose_name='Token 标识')),
                ('user_id', models.CharField(blank=True, default='', max_length=100, verbose_name='用户 ID')),
                ('auth_type', models.CharField(choices=[('jwt', 'JWT'), ('token', 'Token')], max_length=8, verbose_name='认证方式')),
                ('method', models.CharField(max_length=8, verbose_name='HTTP 方法')),
                ('path', models.CharField(max_length=500, verbose_name='请求路径')),
                ('path_template', models.CharField(max_length=200, verbose_name='路径模板')),
                ('status_code', models.SmallIntegerField(verbose_name='HTTP 状态码')),
                ('response_size', models.PositiveIntegerField(default=0, verbose_name='响应大小（字节）')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='耗时（毫秒）')),
                ('table_id', models.UUIDField(blank=True, null=True, verbose_name='关联表格 ID')),
                ('error_code', models.CharField(blank=True, default='', max_length=64, verbose_name='错误码')),
                ('error_message', models.CharField(blank=True, default='', max_length=500, verbose_name='错误信息')),
                ('rate_limit_remaining', models.SmallIntegerField(blank=True, null=True, verbose_name='剩余配额')),
                ('is_rate_limited', models.BooleanField(default=False, verbose_name='是否被限流')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='客户端 IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=200, verbose_name='User-Agent')),
                ('sdk_version', models.CharField(blank=True, default='', max_length=32, verbose_name='SDK 版本')),
            ],
            options={
                'verbose_name': 'API 调用日志',
                'verbose_name_plural': 'API 调用日志',
                'db_table': 'tabdata_api_call_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['workspace_id', 'timestamp'], name='tabdata_api_workspa_8c0dfd_idx'), models.Index(fields=['token_id', 'timestamp'], name='tabdata_api_token_i_949e46_idx'), models.Index(fields=['workspace_id', 'path_template', 'timestamp'], name='tabdata_api_workspa_be0f45_idx'), models.Index(fields=['workspace_id', 'status_code', 'timestamp'], name='tabdata_api_workspa_45587e_idx'), models.Index(fields=['table_id', 'timestamp'], name='tabdata_api_table_i_ca26ed_idx')],
            },
        ),
    ]
