# Generated by Django 4.2.7 on 2026-03-08 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tabdata', '0007_table_source_type_apiusagesummary_apicalllog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataConnector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(db_index=True, verbose_name='工作空间 ID')),
                ('space_id', models.UUIDField(db_index=True, verbose_name='所属 Space')),
                ('connector_type', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('http_api', 'HTTP API')], max_length=32, verbose_name='连接器类型')),
                ('config_encrypted', models.TextField(help_text='Fernet 加密的 JSON，包含连接详情（host/port/password 等）', verbose_name='加密配置')),
                ('name', models.CharField(max_length=200, verbose_name='连接器名称')),
                ('status', models.CharField(choices=[('pending', '待连接'), ('connected', '已连接'), ('error', '连接异常'), ('disabled', '已禁用')], default='pending', max_length=20, verbose_name='连接状态')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='最近错误信息')),
                ('last_probe_at', models.DateTimeField(blank=True, null=True, verbose_name='最近探测时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='data_connectors', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '数据连接器',
                'verbose_name_plural': '数据连接器',
                'db_table': 'tabdata_connector',
            },
        ),
        migrations.CreateModel(
            name='ConnectorTableMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_schema', models.CharField(blank=True, default='', max_length=200, verbose_name='外部 Schema')),
                ('external_table', models.CharField(max_length=200, verbose_name='外部表名')),
                ('sync_mode', models.CharField(choices=[('proxy', '代理（实时转发）'), ('mirror', '镜像（定时同步）')], max_length=16, verbose_name='同步模式')),
                ('mirror_interval_minutes', models.PositiveIntegerField(default=60, verbose_name='镜像间隔（分钟）')),
                ('mirror_strategy', models.CharField(choices=[('full', '全量刷新'), ('incremental', '增量同步')], default='full', max_length=16, verbose_name='镜像策略')),
                ('incremental_column', models.CharField(blank=True, default='', help_text='增量模式下用于判断变更的列名（如 updated_at）', max_length=200, verbose_name='增量同步列')),
                ('field_mapping', models.JSONField(default=dict, verbose_name='字段映射')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='最近同步时间')),
                ('last_sync_status', models.CharField(blank=True, default='', max_length=16, verbose_name='最近同步状态')),
                ('last_sync_error', models.TextField(blank=True, default='', verbose_name='最近同步错误')),
                ('last_sync_row_count', models.PositiveIntegerField(default=0, verbose_name='最近同步行数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='tabdata.dataconnector', verbose_name='所属连接器')),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connector_mapping', to='tabdata.table', verbose_name='TabData 表')),
            ],
            options={
                'verbose_name': '连接器表映射',
                'verbose_name_plural': '连接器表映射',
                'db_table': 'tabdata_connector_table_mapping',
            },
        ),
        migrations.CreateModel(
            name='RowPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='策略名称')),
                ('operation', models.CharField(choices=[('SELECT', 'SELECT'), ('INSERT', 'INSERT'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE'), ('ALL', 'ALL')], default='ALL', max_length=10, verbose_name='操作类型')),
                ('policy_type', models.CharField(choices=[('PERMISSIVE', 'Permissive (OR)'), ('RESTRICTIVE', 'Restrictive (AND)')], default='PERMISSIVE', help_text='PERMISSIVE 策略之间 OR 合并，RESTRICTIVE 策略之间 AND 合并', max_length=12, verbose_name='策略类型')),
                ('condition', models.JSONField(help_text='Filter DSL 条件，支持 $token.user_id / $current_user_id 等运行时变量', verbose_name='策略条件')),
                ('apply_to_tokens', models.BooleanField(default=True, verbose_name='API Token 访问时生效')),
                ('apply_to_jwt', models.BooleanField(default=False, verbose_name='JWT 用户访问时是否也生效')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_policies', to='tabdata.table', verbose_name='表格')),
            ],
            options={
                'verbose_name': '行级安全策略',
                'verbose_name_plural': '行级安全策略',
                'db_table': 'tabdata_row_policy',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['table', 'is_active'], name='tabdata_row_table_i_19b72a_idx'), models.Index(fields=['table', 'operation'], name='tabdata_row_table_i_90dd7a_idx')],
                'unique_together': {('table', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name='dataconnector',
            index=models.Index(fields=['space_id', 'status'], name='tabdata_con_space_i_008d7b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='connectortablemapping',
            unique_together={('connector', 'external_schema', 'external_table')},
        ),
    ]
