# Generated by Django 4.2.7 on 2026-03-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabdata', '0008_dataconnector_connectortablemapping_rowpolicy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataconnector',
            name='connector_type',
            field=models.CharField(choices=[('postgresql', 'PostgreSQL')], max_length=32, verbose_name='连接器类型'),
        ),
    ]
