# Generated by Django 4.2.7 on 2026-03-09 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabdata', '0009_alter_dataconnector_connector_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableapitoken',
            name='parent_token',
            field=models.ForeignKey(blank=True, help_text='null 表示根 Token；非空表示由父 Token 委托派生', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_tokens', to='tabdata.tableapitoken', verbose_name='父 Token'),
        ),
    ]
