# Generated by Django 4.2.7 on 2026-03-09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0001_initial'),
        ('tabdata', '0010_tableapitoken_parent_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableapitoken',
            name='space',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text='Token 归属的 Space；null 表示历史遗留的全局 Token',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='api_tokens',
                to='tabtinspace.space',
                verbose_name='所属 Space',
            ),
        ),
        migrations.AddIndex(
            model_name='tableapitoken',
            index=models.Index(
                fields=['space', 'user', 'is_active'],
                name='tabdata_token_space_user_idx',
            ),
        ),
    ]
