# Generated by Django 4.2.7 on 2026-03-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabdata', '0011_tableapitoken_space'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tableapitoken',
            new_name='tabdata_api_space_i_e3e530_idx',
            old_name='tabdata_token_space_user_idx',
        ),
        migrations.RenameIndex(
            model_name='tablewebhook',
            new_name='tabdata_web_space_i_b5398e_idx',
            old_name='tabdata_web_agent_s_6ad41d_idx',
        ),
        migrations.AlterField(
            model_name='dbreadonlyconnection',
            name='space_id',
            field=models.UUIDField(unique=True, verbose_name='Space ID'),
        ),
        migrations.AlterField(
            model_name='tablewebhook',
            name='space_id',
            field=models.UUIDField(db_index=True, help_text='关联的 Space ID'),
        ),
        migrations.AlterField(
            model_name='tablewebhook',
            name='table_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='关联的表格 ID（null=全 Space）', null=True),
        ),
    ]
