# Generated by Django 4.2.7 on 2026-03-10 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabdata', '0013_rename_token_agent_space_ids_to_space_ids'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fieldsequence',
            name='tabdata_fie_field_i_3ffe19_idx',
        ),
        migrations.RemoveIndex(
            model_name='tableshare',
            name='tabdata_sha_share_i_0e6a19_idx',
        ),
    ]
