# Generated by Django 4.2.7 on 2026-03-11 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tabdata', '0014_remove_fieldsequence_tabdata_fie_field_i_3ffe19_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablewebhook',
            name='created_by',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='tabdata_webhooks', to=settings.AUTH_USER_MODEL),
        ),
    ]
