# Generated by Django 4.2.7 on 2026-03-19 02:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tabdata', '0017_workspace_to_workteam_rename'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookDeliveryFailure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('webhook_id', models.CharField(db_index=True, max_length=64)),
                ('space_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('event_type', models.CharField(blank=True, default='', max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tabdata_webhook_delivery_failure',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='apicalllog',
            name='tabdata_api_workspa_8c0dfd_idx',
        ),
        migrations.RemoveIndex(
            model_name='apicalllog',
            name='tabdata_api_workspa_be0f45_idx',
        ),
        migrations.RemoveIndex(
            model_name='apicalllog',
            name='tabdata_api_workspa_45587e_idx',
        ),
        migrations.RemoveIndex(
            model_name='apiusagesummary',
            name='tabdata_api_workspa_85ef5d_idx',
        ),
        migrations.RemoveIndex(
            model_name='table',
            name='tabdata_tab_workspa_a7bd70_idx',
        ),
        migrations.AlterField(
            model_name='apicalllog',
            name='workteam_id',
            field=models.CharField(db_index=True, max_length=100, verbose_name='工作团队 ID'),
        ),
        migrations.AlterField(
            model_name='apiusagesummary',
            name='workteam_id',
            field=models.CharField(max_length=100, verbose_name='工作团队 ID'),
        ),
        migrations.AlterField(
            model_name='attachmentreference',
            name='workteam_id',
            field=models.UUIDField(db_index=True, verbose_name='所属工作团队'),
        ),
        migrations.AlterField(
            model_name='attachmentupload',
            name='workteam_id',
            field=models.UUIDField(db_index=True, verbose_name='所属工作团队'),
        ),
        migrations.AlterField(
            model_name='dataconnector',
            name='workteam_id',
            field=models.UUIDField(db_index=True, verbose_name='工作团队 ID'),
        ),
        migrations.AlterField(
            model_name='table',
            name='workteam_id',
            field=models.UUIDField(db_index=True, verbose_name='所属工作团队'),
        ),
        migrations.AlterField(
            model_name='tablenamedversion',
            name='workteam_id',
            field=models.UUIDField(verbose_name='所属工作团队'),
        ),
        migrations.AlterField(
            model_name='tablesnapshot',
            name='workteam_id',
            field=models.UUIDField(verbose_name='所属工作团队'),
        ),
        migrations.AddIndex(
            model_name='apicalllog',
            index=models.Index(fields=['workteam_id', 'timestamp'], name='tabdata_api_worktea_1e337f_idx'),
        ),
        migrations.AddIndex(
            model_name='apicalllog',
            index=models.Index(fields=['workteam_id', 'path_template', 'timestamp'], name='tabdata_api_worktea_0490f8_idx'),
        ),
        migrations.AddIndex(
            model_name='apicalllog',
            index=models.Index(fields=['workteam_id', 'status_code', 'timestamp'], name='tabdata_api_worktea_0ab6fc_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusagesummary',
            index=models.Index(fields=['workteam_id', 'period_type', 'period_start'], name='tabdata_api_worktea_e2ca4a_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['workteam_id', 'is_archived'], name='tabdata_tab_worktea_9a8af1_idx'),
        ),
    ]
