# Generated by Django 4.2.7 on 2026-03-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabdata', '0018_webhookdeliveryfailure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordhistory',
            name='action',
            field=models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('restore', '恢复')], max_length=20, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='tableview',
            name='view_type',
            field=models.CharField(choices=[('grid', '表格视图'), ('kanban', '看板视图'), ('calendar', '日历视图'), ('gallery', '画廊视图'), ('list', '列表视图'), ('flashcard', '闪卡视图'), ('form', '表单视图')], default='grid', max_length=50, verbose_name='视图类型'),
        ),
    ]
