# Generated by Django 4.2.7 on 2026-03-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabdata', '0019_add_form_view_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableshare',
            name='login_required',
            field=models.BooleanField(default=False, verbose_name='需要登录'),
        ),
        migrations.AddField(
            model_name='tableshare',
            name='share_type',
            field=models.CharField(choices=[('form', '表单分享'), ('data', '数据只读'), ('workteam', '团队限定')], default='form', max_length=20, verbose_name='分享类型'),
        ),
        migrations.AddField(
            model_name='tableshare',
            name='workteam_id',
            field=models.CharField(blank=True, default='', help_text='share_type=workteam 时填写', max_length=36, verbose_name='限定 Workteam ID'),
        ),
    ]
