# Generated by Django 4.2.7 on 2026-04-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabdata', '0025_backfill_schema_version_token_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablerecord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddIndex(
            model_name='tablerecord',
            index=models.Index(fields=['table', 'is_deleted', 'deleted_at'], name='tabdata_rec_table_i_9fc185_idx'),
        ),
    ]
