# Generated by Django 4.2.7 on 2026-04-23 06:42

import apps.tabdata.models_shadow
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tabdata', '0029_shadow_comparison'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckpointRollbackSaga',
        ),
        migrations.AlterField(
            model_name='shadowcomparison',
            name='compared_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='比对时间'),
        ),
        migrations.AlterField(
            model_name='shadowcomparison',
            name='field_id',
            field=models.UUIDField(verbose_name='字段 ID'),
        ),
        migrations.AlterField(
            model_name='shadowcomparison',
            name='id',
            field=models.CharField(default=apps.tabdata.models_shadow._gen_shadow_id, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shadowcomparison',
            name='legacy_value',
            field=models.TextField(blank=True, default='', verbose_name='Legacy 计算值(JSON 序列化)'),
        ),
        migrations.AlterField(
            model_name='shadowcomparison',
            name='match',
            field=models.BooleanField(verbose_name='是否一致'),
        ),
        migrations.AlterField(
            model_name='shadowcomparison',
            name='outbox_task_id',
            field=models.CharField(max_length=32, verbose_name='关联的 Outbox 任务 ID'),
        ),
        migrations.AlterField(
            model_name='shadowcomparison',
            name='outbox_value',
            field=models.TextField(blank=True, default='', verbose_name='Outbox 计算值(JSON 序列化)'),
        ),
        migrations.AlterField(
            model_name='shadowcomparison',
            name='record_id',
            field=models.UUIDField(verbose_name='记录 ID'),
        ),
        migrations.AlterField(
            model_name='shadowcomparison',
            name='table_id',
            field=models.UUIDField(verbose_name='表 ID'),
        ),
        migrations.AlterField(
            model_name='shadowlegacysnapshot',
            name='field_id',
            field=models.UUIDField(verbose_name='字段 ID'),
        ),
        migrations.AlterField(
            model_name='shadowlegacysnapshot',
            name='id',
            field=models.CharField(default=apps.tabdata.models_shadow._gen_shadow_id, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shadowlegacysnapshot',
            name='legacy_value',
            field=models.TextField(blank=True, default='', verbose_name='Legacy 计算值(JSON 序列化)'),
        ),
        migrations.AlterField(
            model_name='shadowlegacysnapshot',
            name='outbox_task_id',
            field=models.CharField(max_length=32, verbose_name='关联的 Outbox 任务 ID'),
        ),
        migrations.AlterField(
            model_name='shadowlegacysnapshot',
            name='record_id',
            field=models.UUIDField(verbose_name='记录 ID'),
        ),
        migrations.AlterField(
            model_name='shadowlegacysnapshot',
            name='snapshot_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='快照时间'),
        ),
        migrations.AlterField(
            model_name='shadowlegacysnapshot',
            name='table_id',
            field=models.UUIDField(verbose_name='表 ID'),
        ),
    ]
