# Generated by Django 4.2.7 on 2026-06-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabdata', '0038_attachment_oss_physical_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='space_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='兼容旧接口和 TabData native 分区；资源归属以 workteam_id 为准', null=True, verbose_name='Space 上下文'),
        ),
    ]
