# Generated by Django 4.2.7 on 2026-06-30 09:35

from django.db import migrations, models


def backfill_webhook_workteam_id(apps, schema_editor):
    TableWebhook = apps.get_model('tabdata', 'TableWebhook')
    Space = apps.get_model('tabtinspace', 'Space')
    db_alias = schema_editor.connection.alias

    try:
        space_ids = list(
            TableWebhook.objects.using(db_alias)
            .exclude(space_id__isnull=True)
            .values_list('space_id', flat=True)
        )
        space_to_workteam = dict(
            Space.objects.using(db_alias)
            .filter(id__in=space_ids)
            .values_list('id', 'workteam_id')
        )
        for webhook in TableWebhook.objects.using(db_alias).filter(workteam_id__isnull=True).exclude(space_id__isnull=True):
            workteam_id = space_to_workteam.get(webhook.space_id)
            if workteam_id:
                webhook.workteam_id = workteam_id
                webhook.save(update_fields=['workteam_id'])
    except Exception:
        # TabData 可运行在独立库；跨库历史回填失败时保留旧记录的 space_id 兼容查询兜底。
        return


class Migration(migrations.Migration):

    dependencies = [
        ('tabdata', '0039_alter_table_space_id'),
        ('tabtinspace', '0073_alter_space_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablewebhook',
            name='workteam_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='归属 Workteam ID', null=True),
        ),
        migrations.AlterField(
            model_name='tablewebhook',
            name='space_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Space 上下文 ID（兼容字段）', null=True),
        ),
        migrations.AlterField(
            model_name='tablewebhook',
            name='table_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='关联的表格 ID（null=全 Workteam）', null=True),
        ),
        migrations.RunPython(backfill_webhook_workteam_id, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='tablewebhook',
            index=models.Index(fields=['workteam_id', 'is_active'], name='tabdata_web_worktea_442c4e_idx'),
        ),
    ]
