# Generated by Django 4.2.7 on 2026-07-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabdata', '0041_tableview_config_rev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableadminactionlog',
            name='action_type',
            field=models.CharField(choices=[('batch_archive', '批量归档'), ('batch_restore', '批量恢复'), ('batch_trash', '批量逻辑删除'), ('batch_untrash', '批量回收站恢复'), ('batch_search_index_repair', '批量索引修复'), ('single_archive', '单表归档'), ('single_restore', '单表恢复'), ('single_trash', '单表逻辑删除'), ('single_untrash', '单表回收站恢复'), ('single_search_index_repair', '单表索引修复'), ('delete_table', '删除表格')], db_index=True, max_length=64, verbose_name='动作类型'),
        ),
    ]
