# Generated by Django 4.2.7 on 2026-07-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabdata', '0043_rename_workteam_to_organization'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apicalllog',
            new_name='tabdata_api_organiz_1f949b_idx',
            old_name='tabdata_api_worktea_1e337f_idx',
        ),
        migrations.RenameIndex(
            model_name='apicalllog',
            new_name='tabdata_api_organiz_0efeee_idx',
            old_name='tabdata_api_worktea_0490f8_idx',
        ),
        migrations.RenameIndex(
            model_name='apicalllog',
            new_name='tabdata_api_organiz_4c1b4c_idx',
            old_name='tabdata_api_worktea_0ab6fc_idx',
        ),
        migrations.RenameIndex(
            model_name='apiusagesummary',
            new_name='tabdata_api_organiz_2018c5_idx',
            old_name='tabdata_api_worktea_e2ca4a_idx',
        ),
        migrations.RenameIndex(
            model_name='table',
            new_name='tabdata_tab_organiz_d26b3b_idx',
            old_name='tabdata_tab_worktea_9a8af1_idx',
        ),
        migrations.RenameIndex(
            model_name='tablewebhook',
            new_name='tabdata_web_organiz_440e5a_idx',
            old_name='tabdata_web_worktea_442c4e_idx',
        ),
        migrations.AlterField(
            model_name='apicalllog',
            name='organization_id',
            field=models.CharField(db_index=True, max_length=100, verbose_name='组织 ID'),
        ),
        migrations.AlterField(
            model_name='apiusagesummary',
            name='organization_id',
            field=models.CharField(max_length=100, verbose_name='组织 ID'),
        ),
        migrations.AlterField(
            model_name='attachmentreference',
            name='organization_id',
            field=models.UUIDField(db_index=True, verbose_name='所属组织'),
        ),
        migrations.AlterField(
            model_name='attachmentupload',
            name='organization_id',
            field=models.UUIDField(db_index=True, verbose_name='所属组织'),
        ),
        migrations.AlterField(
            model_name='computedoutbox',
            name='organization_id',
            field=models.UUIDField(help_text='多租户隔离主键，admin 过滤 / Pause Registry 必备', verbose_name='所属组织'),
        ),
        migrations.AlterField(
            model_name='computedoutboxdlq',
            name='organization_id',
            field=models.UUIDField(help_text='多租户隔离主键，admin 过滤 / Pause Registry 必备', verbose_name='所属组织'),
        ),
        migrations.AlterField(
            model_name='dataconnector',
            name='organization_id',
            field=models.UUIDField(db_index=True, verbose_name='组织 ID'),
        ),
        migrations.AlterField(
            model_name='table',
            name='organization_id',
            field=models.UUIDField(db_index=True, verbose_name='所属组织'),
        ),
        migrations.AlterField(
            model_name='table',
            name='space_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='兼容旧接口和 TabData native 分区；资源归属以 organization_id 为准', null=True, verbose_name='Space 上下文'),
        ),
        migrations.AlterField(
            model_name='tablenamedversion',
            name='organization_id',
            field=models.UUIDField(verbose_name='所属组织'),
        ),
        migrations.AlterField(
            model_name='tableshare',
            name='organization_id',
            field=models.CharField(blank=True, default='', help_text='share_type=organization 时填写', max_length=36, verbose_name='限定 Organization ID'),
        ),
        migrations.AlterField(
            model_name='tableshare',
            name='share_type',
            field=models.CharField(choices=[('form', '表单分享'), ('data', '数据只读'), ('organization', '组织限定')], default='form', max_length=20, verbose_name='分享类型'),
        ),
        migrations.AlterField(
            model_name='tablesnapshot',
            name='organization_id',
            field=models.UUIDField(verbose_name='所属组织'),
        ),
        migrations.AlterField(
            model_name='tablewebhook',
            name='organization_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='归属 Organization ID', null=True),
        ),
        migrations.AlterField(
            model_name='tablewebhook',
            name='table_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='关联的表格 ID（null=全 Organization）', null=True),
        ),
    ]
