# Generated by Django 4.2.7 on 2026-08-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabdata', '0047_remove_orphaned_managed_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='space_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='#3266：软 UUID（非 FK）。值为 Workspace.id 或 Project.id（历史 id-reuse）；列名暂保留 space_id。资源归属以 organization_id 为准；宿主解析走 host_resolver。', null=True, verbose_name='宿主上下文 ID'),
        ),
    ]
