# Generated by Django 5.1.6 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabdata", "0050_recordcomment_api_foundation"),
    ]

    operations = [
        migrations.AddField(
            model_name="tablerecord",
            name="position_id",
            field=models.TextField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="协作排序位置标识",
            ),
        ),
    ]
