# Generated by Django 4.2.7 on 2026-03-04 20:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatContext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_agent_space_id', models.CharField(blank=True, max_length=100, verbose_name='当前智能体空间ID')),
                ('current_table_id', models.CharField(blank=True, max_length=100, verbose_name='当前表格ID')),
                ('current_view_id', models.CharField(blank=True, max_length=100, verbose_name='当前视图ID')),
                ('recent_agent_spaces', models.JSONField(default=list, verbose_name='最近智能体空间列表')),
                ('recent_tables', models.JSONField(default=list, verbose_name='最近表格列表')),
                ('recent_views', models.JSONField(default=list, verbose_name='最近视图列表')),
                ('context_data', models.JSONField(default=dict, verbose_name='其他上下文数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '会话上下文',
                'verbose_name_plural': '会话上下文',
                'db_table': 'chat_context',
            },
        ),
        migrations.CreateModel(
            name='ChatGlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_identity_prompt', models.TextField(blank=True, default='', help_text='为空时使用 prompts/base/identity.py 内置默认值', verbose_name='Agent 角色身份提示词 <identity>')),
                ('system_persistence_prompt', models.TextField(blank=True, default='', help_text='映射到 <execution> section。为空时使用 prompts/base/execution.py 内置默认值', verbose_name='执行策略提示词 <execution>（旧名 persistence）')),
                ('system_response_style_prompt', models.TextField(blank=True, default='', help_text='v3 起不再单独注入，保留字段仅作向后兼容', verbose_name='回复风格提示词（已合并到 identity 行为准则，此字段弃用）')),
                ('system_reasoning_prompt', models.TextField(blank=True, default='', help_text='v3 起作为 execution 的 fallback override，保留字段仅作向后兼容', verbose_name='推理框架提示词（已合并到 execution，此字段弃用）')),
                ('system_safety_prompt', models.TextField(blank=True, default='', help_text='为空时使用 prompts/base/safety.py 内置默认值', verbose_name='安全规则提示词 <safety>')),
                ('title_enabled', models.BooleanField(default=True, verbose_name='启用自动标题')),
                ('title_model_id', models.CharField(blank=True, default='', help_text='为空时使用系统默认模型', max_length=100, verbose_name='标题生成模型ID')),
                ('title_system_prompt', models.TextField(blank=True, default='', help_text='为空时使用内置默认提示词', verbose_name='标题生成系统提示词')),
                ('title_temperature', models.FloatField(default=0.7, verbose_name='标题生成温度')),
                ('title_max_tokens', models.IntegerField(default=50, verbose_name='标题生成最大tokens')),
                ('title_max_length', models.IntegerField(default=20, verbose_name='标题最大字符数')),
                ('title_retry_count', models.IntegerField(default=2, verbose_name='标题生成重试次数')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '对话全局配置',
                'verbose_name_plural': '对话全局配置',
                'db_table': 'chat_global_config',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=20, verbose_name='角色')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('trace_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Trace ID')),
                ('blocks_json', models.JSONField(blank=True, default=list, help_text='v2 结构化消息块列表', verbose_name='消息块')),
                ('attachments_json', models.JSONField(blank=True, default=list, help_text='图片/文件附件的元数据', verbose_name='附件元信息')),
                ('external_task_id', models.CharField(blank=True, db_index=True, help_text='Daemon 端 ACP 任务 ID，用于防止离线回放重复持久化', max_length=100, null=True, verbose_name='外部Agent任务ID')),
                ('agent_type', models.CharField(blank=True, max_length=50, verbose_name='Agent类型')),
                ('intent', models.CharField(blank=True, max_length=50, verbose_name='识别意图')),
                ('intent_confidence', models.FloatField(default=0.0, verbose_name='意图置信度')),
                ('checkpoint_hash', models.CharField(blank=True, db_index=True, help_text='Shadow Git commit hash，标识该消息对应的文件快照', max_length=64, null=True, verbose_name='检查点哈希')),
                ('checkpoint_state_index', models.IntegerField(blank=True, help_text='创建检查点时 ConversationState.messages_json 的长度', null=True, verbose_name='检查点状态索引')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '聊天消息',
                'verbose_name_plural': '聊天消息',
                'db_table': 'chat_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=100, verbose_name='工作空间ID')),
                ('thread_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Agent 线程ID')),
                ('parent_id', models.UUIDField(blank=True, db_index=True, help_text='子 Agent 创建的 child session 指向父会话', null=True, verbose_name='父会话ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='会话标题')),
                ('status', models.CharField(default='active', max_length=20, verbose_name='会话状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='最后消息时间')),
                ('input_tokens', models.BigIntegerField(default=0, verbose_name='输入Token数')),
                ('output_tokens', models.BigIntegerField(default=0, verbose_name='输出Token数')),
                ('total_tokens', models.BigIntegerField(default=0, verbose_name='总Token数')),
                ('context_tokens', models.IntegerField(default=0, verbose_name='上下文Token数')),
                ('compaction_count', models.IntegerField(default=0, verbose_name='压缩次数')),
                ('last_compaction_at', models.DateTimeField(blank=True, null=True, verbose_name='最后压缩时间')),
                ('revert_message_id', models.UUIDField(blank=True, db_index=True, help_text='非空时表示会话处于已回滚状态，该 ID 为回滚的目标消息', null=True, verbose_name='回滚点消息ID')),
                ('revert_snapshot_hash', models.CharField(blank=True, help_text='回滚前创建的 safety checkpoint hash，用于 unrevert 时恢复文件', max_length=64, null=True, verbose_name='回滚前快照哈希')),
                ('revert_state_index', models.IntegerField(blank=True, help_text='cleanup 时用于截断 ConversationState.messages_json 的索引', null=True, verbose_name='回滚目标PG状态索引')),
                ('revert_at', models.DateTimeField(blank=True, null=True, verbose_name='回滚时间')),
            ],
            options={
                'verbose_name': '聊天会话',
                'verbose_name_plural': '聊天会话',
                'db_table': 'chat_session',
                'ordering': ['-updated_at'],
            },
        ),
    ]
