# Generated by Django 4.2.7 on 2026-03-04 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('llm', '0001_initial'),
        ('conversation', '0001_initial'),
        ('tabtinspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='agent_space',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='tabtinspace.agentspace', verbose_name='所属智能体空间'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='current_model',
            field=models.ForeignKey(blank=True, help_text='用户当前选择的 LLM 模型', null=True, on_delete=django.db.models.deletion.SET_NULL, db_constraint=False, related_name='current_sessions', to='llm.llmmodel', verbose_name='当前使用的模型'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='default_model',
            field=models.ForeignKey(blank=True, help_text='会话创建时的初始模型', null=True, on_delete=django.db.models.deletion.SET_NULL, db_constraint=False, related_name='default_sessions', to='llm.llmmodel', verbose_name='会话默认模型'),
        ),
    ]
