# Generated by Django 4.2.7 on 2026-03-04 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('llm', '0001_initial'),
        ('conversation', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='model',
            field=models.ForeignKey(blank=True, help_text='生成此消息的 LLM 模型', null=True, on_delete=django.db.models.deletion.SET_NULL, db_constraint=False, related_name='messages', to='llm.llmmodel', verbose_name='使用的模型'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversation.chatsession', verbose_name='所属会话'),
        ),
        migrations.AddField(
            model_name='chatcontext',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='context', to='conversation.chatsession', verbose_name='所属会话'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', '-updated_at'], name='chat_sessio_user_id_6380f6_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['workspace_id', '-updated_at'], name='chat_sessio_workspa_faf76f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['agent_space', '-updated_at'], name='chat_sess_proj_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['current_model'], name='chat_sess_curr_model_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='chat_messag_session_4940cf_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['role', 'created_at'], name='chat_messag_role_35f48a_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['model'], name='chat_messag_model_i_98036c_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['checkpoint_hash'], name='chat_msg_ckpt_hash_idx'),
        ),
        migrations.AddIndex(
            model_name='chatcontext',
            index=models.Index(fields=['session'], name='chat_contex_session_284b00_idx'),
        ),
        migrations.AddIndex(
            model_name='chatcontext',
            index=models.Index(fields=['current_agent_space_id'], name='chat_contex_current_e0cc8a_idx'),
        ),
        migrations.AddIndex(
            model_name='chatcontext',
            index=models.Index(fields=['current_table_id'], name='chat_contex_current_753a0e_idx'),
        ),
    ]
