# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='external_session_id',
            field=models.CharField(
                blank=True,
                help_text='ACP session ID，用于 Daemon 重启后恢复外部 Agent 会话上下文',
                max_length=255,
                null=True,
                verbose_name='外部 Agent 会话 ID',
            ),
        ),
    ]
