# Generated by Django 4.2.7 on 2026-03-08 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0007_alter_space_options_alter_spaceappsettings_options_and_more'),
        ('conversation', '0006_rename_agent_space_to_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatcontext',
            name='current_space_id',
            field=models.CharField(blank=True, db_column='current_agent_space_id', max_length=100, verbose_name='当前 Space ID'),
        ),
        migrations.AlterField(
            model_name='chatcontext',
            name='recent_spaces',
            field=models.JSONField(db_column='recent_agent_spaces', default=list, verbose_name='最近 Space 列表'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='space',
            field=models.ForeignKey(blank=True, db_column='agent_space_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='tabtinspace.space', verbose_name='所属智能体空间'),
        ),
    ]
