# Generated by Django 4.2.7 on 2026-03-10 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0012_alter_device_options_alter_agent_control_device_and_more'),
        ('conversation', '0008_rename_chat_contex_current_e0cc8a_idx_chat_contex_current_a4f536_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatcontext',
            name='chat_contex_session_284b00_idx',
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='space',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='tabtinspace.space', verbose_name='所属智能体空间'),
        ),
    ]
