# Generated by Django 4.2.7 on 2026-03-11 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0009_remove_chatcontext_chat_contex_session_284b00_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='memory_extracted_index',
            field=models.IntegerField(default=0, help_text='L2 增量提取的消息索引游标，仅处理此索引之后的新消息', verbose_name='记忆已提取消息游标'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='memory_quick_settled',
            field=models.BooleanField(default=False, help_text='新 session 首条消息时对前序未结算 session 做的轻量结算标记', verbose_name='记忆已快速结算'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='memory_settled',
            field=models.BooleanField(default=False, help_text='L4 空闲结算完成后标记为 True', verbose_name='记忆已完整结算'),
        ),
    ]
