# Generated by Django 4.2.7 on 2026-03-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0010_memory_v2_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='agent_run_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='关联的 Agent Run ID，用于按 run 聚合消息与资源变更', max_length=64, verbose_name='Agent Run ID'),
        ),
    ]
