# Generated by Django 4.2.7 on 2026-03-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0011_add_agent_run_id_to_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='revert_resource_state',
            field=models.JSONField(blank=True, default=None, help_text='记录 rollback_resources 执行前各资源的当前版本 ID，用于 unrevert 时反向恢复', null=True, verbose_name='回退前的资源版本状态'),
        ),
    ]
