# Generated by Django 4.2.7 on 2026-03-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0012_add_revert_resource_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='revert_history',
            field=models.JSONField(blank=True, default=None, help_text='按时间顺序记录本 session 的每次回退/撤销回退操作，格式: [{type, target_message_id, snapshot_hash, messages_removed, resources, created_at}, ...]', null=True, verbose_name='回退操作历史'),
        ),
    ]
