# Generated by Django 4.2.7 on 2026-03-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0013_add_revert_history'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['space', 'memory_settled', '-updated_at'], name='idx_session_memory_settle'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['space', 'memory_quick_settled', '-updated_at'], name='idx_session_quick_settle'),
        ),
    ]
