# Generated by Django 4.2.7 on 2026-03-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0015_workspace_to_workteam_rename'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatsession',
            name='chat_sessio_workspa_faf76f_idx',
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='workteam_id',
            field=models.CharField(max_length=100, verbose_name='工作团队ID'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['workteam_id', '-updated_at'], name='chat_sessio_worktea_29ea6d_idx'),
        ),
    ]
