# Generated by Django 4.2.7 on 2026-03-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0016_remove_chatsession_chat_sessio_workspa_faf76f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='diff_summary',
            field=models.JSONField(blank=True, help_text='Shadow Git 计算的文件变更摘要，包含 changed/insertions/deletions/files 等信息', null=True, verbose_name='文件变更摘要'),
        ),
    ]
