# Generated by Django 4.2.7 on 2026-03-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0017_chatmessage_diff_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='changed_files',
            field=models.JSONField(blank=True, help_text='该 checkpoint 关联的变更文件路径数组，由 Agent Turn 执行期间收集', null=True, verbose_name='变更文件列表'),
        ),
    ]
