# Generated by Django 4.2.7 on 2026-03-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0018_chatmessage_changed_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sender_user_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='消息发送者用户ID'),
        ),
    ]
