# Generated by Django 4.2.7 on 2026-03-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0019_add_sender_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='fork_point_message_id',
            field=models.UUIDField(blank=True, help_text='Fork 时的最后一条消息 ID（源 session 中的 message PK）', null=True, verbose_name='分叉点消息ID'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='forked_from_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Fork 创建时记录来源 session，用于 UI 展示分叉关系', null=True, verbose_name='源会话ID'),
        ),
    ]
