# Generated by Django 4.2.7 on 2026-04-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0021_chatmessage_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatglobalconfig',
            name='identity_override_mode',
            field=models.CharField(choices=[('replace', 'Replace'), ('prepend', 'Prepend')], default='replace', help_text='replace: admin override 完全替换 identity section；prepend: admin override 作为前缀拼接在 persona 之前', max_length=10, verbose_name='Identity Override 模式'),
        ),
    ]
