# Generated by Django 4.2.7 on 2026-04-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0022_add_identity_override_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatglobalconfig',
            name='subagent_advanced_model_id',
            field=models.CharField(blank=True, default='', help_text='task 工具 model="advanced" 时使用的模型，为空时由引擎自行决定', max_length=100, verbose_name='子Agent advanced 模型ID'),
        ),
        migrations.AddField(
            model_name='chatglobalconfig',
            name='subagent_standard_model_id',
            field=models.CharField(blank=True, default='', help_text='task 工具 model="standard" 时使用的模型，为空时由引擎自行决定', max_length=100, verbose_name='子Agent standard 模型ID'),
        ),
    ]
