# Generated by Django 4.2.7 on 2026-05-05 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0023_alter_llmadminauditlog_options_and_more'),
        ('conversation', '0030_engineruntimeconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='model',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='生成此消息的 LLM 模型（v0.1：services_llm 已迁 PG，跨库软引用）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='llm.llmmodel', verbose_name='使用的模型'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='current_model',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='用户当前选择的 LLM 模型（v0.1：services_llm 已迁 PG，跨库软引用）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_sessions', to='llm.llmmodel', verbose_name='当前使用的模型'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='default_model',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='会话创建时的初始模型（v0.1：services_llm 已迁 PG，跨库软引用）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_sessions', to='llm.llmmodel', verbose_name='会话默认模型'),
        ),
    ]
