"""v0.1 宪法收尾：ChatSession.current_model / default_model 与 ChatMessage.model
跨库 FK 退化为 UUIDField 软引用。

== 背景 ==
0031 给三个 FK 加了 ``db_constraint=False``（去掉 DB 层物理约束）但保留 ORM 的
ForeignKey 类型。结果：

    >>> ChatSession.objects.create(current_model=llm_model_instance, ...)
    ValueError: Cannot assign "<LLMModel: ...>": the current database router
    prevents this relation.

Django ORM 在赋值阶段调用 ``router.allow_relation(LLMModel, ChatSession)``
校验跨库关系，被 LlmRouter 拒绝。POST /api/chat/sessions 直接 500，整个 Chat
入口瘫痪。

宪法本意是"软引用 = CharField/UUIDField 软引用，业务层显式 fetch"——0031 只
做了一半（去 DB 约束），FK 类型没拆。本 migration 收尾：

    FK(to='llm.LLMModel') ─→ UUIDField

字段名同步加 ``_id`` 后缀（current_model → current_model_id 等），让底层 DB
column 名跟 FK 自动生成的 ``current_model_id`` column 完全一致——**数据零迁移**。

== 实现 ==
``SeparateDatabaseAndState`` 模式：
- ``state_operations``：在 Django ORM 元数据里把 FK 字段换成 UUIDField，刷
  新 ``Meta.indexes`` 引用名（'current_model' → 'current_model_id'）。
- ``database_operations=[]``：DB 层零变更（column 名不变、column 类型 UUID
  保持、原 FK implicit index 物理保留——MySQL 优化器仍可用，只是 Django state
  里换了个逻辑名）。

== 不动的东西 ==
- 现有 chat_session / chat_message 表数据
- 现有 column 名 (``current_model_id`` / ``default_model_id`` / ``model_id``)
- 现有索引（包括 0031 之前 FK implicit 索引）

== 业务侧配套 ==
- ``ChatSession.current_model`` / ``ChatMessage.model`` 改为 ``@property`` 软引用
  accessor，链式访问 ``session.current_model.model_name`` 仍可用（懒查询）。
- 列表场景调 ``apps.chat.conversation.services.llm_model_loader.attach_llm_models_to_*``
  helper 批量预加载，避免 N+1。
- ``ChatSession.objects.prefetch_related('current_model')`` 全部已替换为 attach
  helper（详见同 PR 内 session.py / fork.py / chat_service.py 等改造）。
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0032_drop_chat_global_config_and_rename_engine_runtime_table'),
        # llm 0023 是当前最新 LLMModel schema，本迁移不再依赖（软引用解耦），
        # 但保留依赖让 dependency graph 顺序稳定。
        ('llm', '0023_alter_llmadminauditlog_options_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='chatsession',
                    name='chat_sess_curr_model_idx',
                ),
                # 0003 给 fields=['model'] 起的匿名 index 名（autogenerated 命名）。
                # 字段移除后 state 不会自动清理它，必须显式 RemoveIndex。
                migrations.RemoveIndex(
                    model_name='chatmessage',
                    name='chat_messag_model_i_98036c_idx',
                ),
                migrations.RemoveField(
                    model_name='chatsession',
                    name='current_model',
                ),
                migrations.RemoveField(
                    model_name='chatsession',
                    name='default_model',
                ),
                migrations.RemoveField(
                    model_name='chatmessage',
                    name='model',
                ),
                migrations.AddField(
                    model_name='chatsession',
                    name='current_model_id',
                    field=models.UUIDField(
                        blank=True,
                        null=True,
                        verbose_name='当前使用的模型 ID',
                        help_text='当前 LLM 模型 UUID（软引用 llm.LLMModel）',
                    ),
                ),
                migrations.AddField(
                    model_name='chatsession',
                    name='default_model_id',
                    field=models.UUIDField(
                        blank=True,
                        null=True,
                        verbose_name='会话默认模型 ID',
                        help_text='会话创建时的初始 LLM 模型 UUID（软引用 llm.LLMModel）',
                    ),
                ),
                migrations.AddField(
                    model_name='chatmessage',
                    name='model_id',
                    field=models.UUIDField(
                        blank=True,
                        null=True,
                        verbose_name='使用的模型 ID',
                        help_text='生成此消息的 LLM 模型 UUID（软引用 llm.LLMModel）',
                    ),
                ),
                migrations.AddIndex(
                    model_name='chatsession',
                    index=models.Index(
                        fields=['current_model_id'],
                        name='chat_sess_curr_model_idx',
                    ),
                ),
                migrations.AddIndex(
                    model_name='chatmessage',
                    index=models.Index(
                        fields=['model_id'],
                        name='chat_msg_model_id_idx',
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
