# Generated by Django 4.2.7 on 2026-06-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0050_add_compaction_summary_message_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_kind',
            field=models.CharField(choices=[('llm', 'LLM Output'), ('tool_artifact', 'Tool Artifact'), ('error_envelope', 'Error Envelope'), ('environment_context', 'Environment Context'), ('compaction_summary', 'Compaction Summary')], default='llm', help_text='ChatMessage 语义类型——区分 LLM 输出 / 工具产物气泡 / 错误文案。替换原来用 model_id 字面量 + synthetic 隐式判别的协议层 hack。daemon 主循环 push 的 role=user + 含 tool_result block 的合成消息走合并路径，不会作为独立 ChatMessage 落表（在 reassembler 层合并到对应 LLM 消息）。', max_length=24, verbose_name='消息语义类型'),
        ),
    ]
