# Generated by Django 4.2.7 on 2026-07-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0055_rename_workteam_to_organization'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatsession',
            new_name='chat_sessio_organiz_6b5b41_idx',
            old_name='chat_sessio_worktea_29ea6d_idx',
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='organization_id',
            field=models.CharField(max_length=100, verbose_name='组织ID'),
        ),
    ]
