# Generated by Django 4.2.7 on 2026-07-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0090_alter_organization_options_and_more'),
        ('conversation', '0056_rename_chat_sessio_worktea_29ea6d_idx_chat_sessio_organiz_6b5b41_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='cache_creation_input_tokens',
            field=models.BigIntegerField(default=0, verbose_name='缓存写入Token数'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='cache_read_input_tokens',
            field=models.BigIntegerField(default=0, verbose_name='缓存命中Token数'),
        ),
    ]
