# Generated by Django 4.2.7 on 2026-07-14 02:12
#
#  方案 B：ChatMessage 增加对话时间权威列 arrival_seq（epoch 微秒，
# runtime emit 单调分配）。回退边界（preview / 可见性过滤 / cleanup）改以
# 本列为准；NULL = legacy 行，边界计算回落 created_at，无需 backfill。
#
# 注：makemigrations 自动探测到的 chatsession.space AlterField 是本改动之外的
# 既有 model/migration 漂移（本 PR 未触碰该字段），已从本 migration 中剔除，
# 由字段归属方自行收敛。

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0058_backfill_chatsession_cache_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='arrival_seq',
            field=models.BigIntegerField(blank=True, default=None, help_text='agent-runtime emit 分配的单调对话时间；回退边界的权威时间轴，NULL 表示 legacy 行（边界计算回落 created_at）', null=True, verbose_name='对话时间序（epoch 微秒）'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'arrival_seq'], name='chat_msg_sess_arrival_idx'),
        ),
    ]
