# Generated by Django 4.2.7 on 2026-07-13 13:07
#
# ：ChatMessage.message_kind choices 增加 hitl_interaction（纯校验层，无 schema 变更）。
# 注意：makemigrations 同时探测到 chatsession.space 的既有模型漂移（先于本改动存在，
# 与 HITL 无关），已从本 migration 中剔除，另行登记处理。

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0059_chatmessage_arrival_seq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_kind',
            field=models.CharField(choices=[('llm', 'LLM Output'), ('tool_artifact', 'Tool Artifact'), ('error_envelope', 'Error Envelope'), ('environment_context', 'Environment Context'), ('compaction_summary', 'Compaction Summary'), ('hitl_interaction', 'HITL Interaction')], default='llm', help_text='ChatMessage 语义类型——区分 LLM 输出 / 工具产物气泡 / 错误文案。替换原来用 model_id 字面量 + synthetic 隐式判别的协议层 hack。daemon 主循环 push 的 role=user + 含 tool_result block 的合成消息走合并路径，不会作为独立 ChatMessage 落表（在 reassembler 层合并到对应 LLM 消息）。', max_length=24, verbose_name='消息语义类型'),
        ),
    ]
