# Generated by Django 4.2.7 on 2026-07-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0060_chatmessage_hitl_interaction_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineruntimeconfig',
            name='cleanup_llm_snapshot_retention_days',
            field=models.IntegerField(default=90),
        ),
        # 注：makemigrations 同时检测到 chatsession.space 的 AlterField（模型与
        # 历史 migration 的基线漂移，与本 PR 无关），已从本 migration 移除。
        migrations.CreateModel(
            name='ChatLLMSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, help_text='ChatSession.id（UUID 字符串软引用，不建 FK）', max_length=64, verbose_name='会话 ID')),
                ('thread_id', models.CharField(blank=True, default='', help_text='runtime 侧业务 thread id（与本地 snapshots.jsonl 目录对齐）', max_length=128, verbose_name='线程 ID')),
                ('run_id', models.CharField(help_text='本次 query 的 runId（= trace_id），与 iteration 组合唯一定位一次 LLM 调用', max_length=64, verbose_name='Run ID')),
                ('iteration', models.IntegerField(default=0, verbose_name='迭代序号')),
                ('model', models.CharField(blank=True, default='', max_length=128, verbose_name='模型')),
                ('snapshot_json', models.JSONField(help_text='LLMCallSnapshot 完整体（system sections / messages 摘要 / tools schema / response 元信息）；客户端超限时按字段截断并带 truncated 标记', verbose_name='快照体')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'LLM 调用快照',
                'verbose_name_plural': 'LLM 调用快照',
                'db_table': 'chat_llm_snapshot',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['session_id', 'created_at'], name='llm_snap_sess_created_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='chatllmsnapshot',
            constraint=models.UniqueConstraint(fields=('session_id', 'run_id', 'iteration'), name='uq_llm_snapshot_call'),
        ),
    ]
