# Generated by Django 4.2.7 on 2026-07-17 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0098_strip_agent_approval_config'),
        ('conversation', '0062_agent_workspace_turn_binding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='assistant/tool_artifact 消息的实际执行者；历史归属不随会话当前指针变化。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tabtinspace.agent', verbose_name='本轮执行 Agent'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='agent',
            field=models.ForeignKey(blank=True, db_column='agent_id', db_index=False, help_text='会话的执行 Agent（tabtinspace.Agent）；一 Agent 管多会话的直挂锚点。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tabtinspace.agent', verbose_name='执行 Agent'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='agent_mode',
            field=models.CharField(blank=True, default='', help_text='会话级 AgentMode 记忆（ask/agent/plan/study/yolo/group）；空 = 未显式设置。不承载授权语义。', max_length=16, verbose_name='会话交互模式'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='approval_mode',
            field=models.CharField(choices=[('always_ask', '每次询问'), ('auto', '自动批准低风险操作'), ('full_access', '完全访问')], default='always_ask', help_text='仅表达本会话请求档位，不能突破 Workspace 授权与 Organization 天花板。', max_length=16, verbose_name='会话审批请求档位'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='space',
            field=models.ForeignKey(blank=True, db_column='space_id', db_index=False, help_text='所属 Agent 工作区（tabtinspace.Space）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tabtinspace.space', verbose_name='所属 Agent 空间'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='workspace',
            field=models.ForeignKey(blank=True, db_column='workspace_id', help_text='会话的执行现场（tabtinspace.Workspace）；在哪台设备哪个目录干活的直挂锚点。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tabtinspace.workspace', verbose_name='执行现场'),
        ),
    ]
