# Generated by Django 4.2.7 on 2026-07-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0064_agent_fk_to_agent_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_paused',
            field=models.BooleanField(default=False, help_text='协作式暂停：当前步骤完成后在下一轮推理前挂起；resume 后继续。', verbose_name='当前任务是否暂停'),
        ),
    ]
