# Generated by Django 4.2.7 on 2026-07-25 19:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0072_merge_agent_profile_context_and_session_agents'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.CharField(db_index=True, help_text='共享边界：grantee 必须是该 Organization 成员（创建时快照自 session）。', max_length=100, verbose_name='组织ID')),
                ('owner_user_id', models.CharField(help_text='创建时快照自 session.user_id；仅 owner 可授予 / 撤销。', max_length=100, verbose_name='会话 owner 用户ID')),
                ('grantee_user_id', models.CharField(db_index=True, max_length=100, verbose_name='被授权用户ID')),
                ('can_fork', models.BooleanField(default=False, help_text='允许接收人把脱敏投影抄写成自己的新会话。', verbose_name='允许 fork')),
                ('can_chat', models.BooleanField(default=False, help_text='本期仅存储、无任何行为；后续版本再接行为。', verbose_name='允许对话（预留）')),
                ('status', models.CharField(choices=[('active', '生效中'), ('revoked', '已撤销')], default='active', max_length=16, verbose_name='共享状态')),
                ('card_conversation_id', models.CharField(blank=True, default='', help_text='tabchat Conversation 软引用（IM 发卡编排在 tabchat 侧回填）。', max_length=100, verbose_name='IM 卡片会话ID')),
                ('card_message_id', models.BigIntegerField(blank=True, help_text='tabchat Message 主键（BigAuto）软引用，tabchat 侧回填。', null=True, verbose_name='IM 卡片消息ID')),
                ('forked_session_id', models.UUIDField(blank=True, help_text='shared-fork 成功后回填；重复 fork 幂等返回该会话（已删则允许重建）。', null=True, verbose_name='接收人 fork 出的会话ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='conversation.chatsession', verbose_name='被共享会话')),
            ],
            options={
                'verbose_name': '会话共享授权',
                'verbose_name_plural': '会话共享授权',
                'db_table': 'chat_session_share',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionShareEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actor_user_id', models.CharField(max_length=100, verbose_name='操作者用户ID')),
                ('event_type', models.CharField(choices=[('created', '创建'), ('updated', '更新权限'), ('viewed', '查看'), ('forked', 'Fork'), ('revoked', '撤销')], max_length=16, verbose_name='事件类型')),
                ('payload_json', models.JSONField(blank=True, default=dict, verbose_name='事件载荷')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='conversation.sessionshare', verbose_name='所属共享')),
            ],
            options={
                'verbose_name': '会话共享审计事件',
                'verbose_name_plural': '会话共享审计事件',
                'db_table': 'chat_session_share_event',
                'indexes': [models.Index(fields=['share', '-created_at'], name='chat_share_evt_share_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='sessionshare',
            constraint=models.UniqueConstraint(fields=('session', 'grantee_user_id'), name='uq_session_share_grantee'),
        ),
    ]
