# Generated by Django 4.2.7 on 2026-07-26 06:28
#
#  文档协同式共享：can_chat 从「预留位」转为发言驱动行为位；
# SessionShareEvent 新增 'chatted' 事件类型。纯 state-only 迁移
# （help_text / verbose_name / choices），不产生任何 DDL。

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0073_sessionshare_sessionshareevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionshare',
            name='can_chat',
            field=models.BooleanField(default=False, help_text='允许接收人经 shared-chat 端点发言驱动本会话（执行在 owner 设备、费用归 owner）。', verbose_name='允许对话'),
        ),
        migrations.AlterField(
            model_name='sessionshare',
            name='can_fork',
            field=models.BooleanField(default=False, help_text='允许接收人把会话快照抄写成自己的新会话。', verbose_name='允许 fork'),
        ),
        migrations.AlterField(
            model_name='sessionshareevent',
            name='event_type',
            field=models.CharField(choices=[('created', '创建'), ('updated', '更新权限'), ('viewed', '查看'), ('forked', 'Fork'), ('chatted', '发言驱动'), ('revoked', '撤销')], max_length=16, verbose_name='事件类型'),
        ),
    ]
