# Generated by Django 4.2.7 on 2026-07-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0074_alter_sessionshare_can_chat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionshare',
            name='forked_session_id',
            field=models.UUIDField(blank=True, help_text='shared-fork 成功后回填最新一份副本；每次显式 fork 都新建，旧副本保留。', null=True, verbose_name='接收人 fork 出的会话ID'),
        ),
    ]
