# Generated by Django 4.2.7 on 2026-08-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0081_session_workspace_file_ref_and_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionworkspacefilereference',
            name='source_kind',
            field=models.CharField(choices=[('local_file', 'local_file 产物卡'), ('tool_mutation', 'write/edit 工具产物'), ('shell_history', '终端 file_history'), ('resource_link', 'tabtin://resource/file/ 链接')], max_length=32),
        ),
        migrations.AlterField(
            model_name='sessionworkspacefilesnapshot',
            name='status',
            field=models.CharField(choices=[('pending', '物化中'), ('ready', '就绪'), ('failed', '失败'), ('revoked', '已撤销')], default='pending', max_length=16),
        ),
    ]
