# Generated by Django 4.2.7 on 2026-08-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0085_reconcile_unpublished_chatmessage_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='model_param_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='会话级 Runtime Profile 意图(v2: thinking_mode 等)。切模型时保留意图并按新模型重解析；不持久化 resolved。', verbose_name='模型运行参数'),
        ),
    ]
