# Generated by Django 4.2.7 on 2026-07-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_config', '0002_rename_workteam_config_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformruntimeconfigitem',
            name='key',
            field=models.CharField(help_text='建议使用命名空间格式，例如 product_limits.max_organizations_per_user', max_length=120, unique=True, verbose_name='配置键'),
        ),
    ]
