# Generated by Django 4.2.7 on 2026-03-04 20:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', '待解析'), ('parsing', '解析中'), ('ready', '已就绪'), ('failed', '解析失败')], default='pending', max_length=20)),
                ('parse_method', models.CharField(blank=True, choices=[('text_layer', '文本层提取'), ('vision', 'Vision 模型'), ('structural', '结构化提取'), ('text_read', '纯文本读取')], max_length=20)),
                ('total_pages', models.IntegerField(default=0, verbose_name='总页数')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='文档标题')),
                ('language', models.CharField(blank=True, max_length=10, verbose_name='语言')),
                ('summary_text', models.TextField(blank=True, verbose_name='全文摘要')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('parse_model', models.CharField(blank=True, max_length=100, verbose_name='使用的 VL 模型')),
                ('parsed_pages', models.IntegerField(default=0, help_text='断点续传：记录已成功写入 DB 的页数', verbose_name='已完成页数')),
                ('parsed_at', models.DateTimeField(blank=True, null=True, verbose_name='解析完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('file_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_doc', to='oss.filerecord', verbose_name='源文件')),
            ],
            options={
                'verbose_name': '解析文档',
                'verbose_name_plural': '解析文档',
                'db_table': 'services_docparse_document',
            },
        ),
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.IntegerField(verbose_name='页码')),
                ('width', models.FloatField(default=0, verbose_name='页面宽度(pt)')),
                ('height', models.FloatField(default=0, verbose_name='页面高度(pt)')),
                ('thumbnail_url', models.URLField(blank=True, verbose_name='缩略图 URL')),
                ('text_content', models.TextField(blank=True, verbose_name='整页纯文本')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='docparse.parseddocument')),
            ],
            options={
                'verbose_name': '文档页面',
                'verbose_name_plural': '文档页面',
                'db_table': 'services_docparse_page',
                'ordering': ['document', 'page_number'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_type', models.CharField(choices=[('heading', '标题'), ('paragraph', '段落'), ('table', '表格'), ('image', '图片'), ('list', '列表'), ('field', '表单字段'), ('note', '备注')], max_length=30)),
                ('content', models.TextField(verbose_name='文本内容')),
                ('sequence', models.IntegerField(verbose_name='页内排序')),
                ('bbox_x0', models.FloatField(blank=True, null=True, verbose_name='左上 x')),
                ('bbox_y0', models.FloatField(blank=True, null=True, verbose_name='左上 y')),
                ('bbox_x1', models.FloatField(blank=True, null=True, verbose_name='右下 x')),
                ('bbox_y1', models.FloatField(blank=True, null=True, verbose_name='右下 y')),
                ('heading_level', models.IntegerField(blank=True, null=True, verbose_name='标题级别')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='docparse.documentpage')),
            ],
            options={
                'verbose_name': '文档内容块',
                'verbose_name_plural': '文档内容块',
                'db_table': 'services_docparse_chunk',
                'ordering': ['page', 'sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='parseddocument',
            index=models.Index(fields=['status', 'created_at'], name='services_do_status_394c68_idx'),
        ),
        migrations.AddIndex(
            model_name='documentpage',
            index=models.Index(fields=['document', 'page_number'], name='services_do_documen_c62498_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['page', 'sequence'], name='services_do_page_id_95c4d2_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['page', 'chunk_type'], name='services_do_page_id_97b5fd_idx'),
        ),
    ]
