# Generated by W1 file pipeline error refactor on 2026-05-13.
#
# 添加 ParsedDocument.failure_code 字段（W1 / L9 收口）。
# 字段 choices 与 `@tabtin/file-pipeline-errors` 包的 FilePipelineErrorCode
# SSoT 对齐——13 类全局错误码。客户端 UI 按本字段路由到 i18n 文案。
#
# **W1.2 Review 收尾（2026-05-13）**：`db_index=True` —— 后续可观测 / metric
# 需要"过去 7 天解析失败原因 top 5"等聚合分析按 failure_code group by，
# 没有索引时单字段扫表成本高（百万级 ParsedDocument 时尤甚）。D1 原则：
# 产品未上线，索引一次到位，避免 0003 微迁移。

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('docparse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseddocument',
            name='failure_code',
            field=models.CharField(
                blank=True,
                choices=[
                    ('file_not_found', '文件不存在'),
                    ('file_too_large', '文件过大'),
                    ('permission_denied', '无权访问'),
                    ('encrypted', '文件已加密'),
                    ('corrupted', '文件已损坏'),
                    ('scanned_pdf', '扫描件 PDF'),
                    ('garbled_text_layer', '文本层乱码'),
                    ('unsupported_format', '格式不支持'),
                    ('parse_timeout', '解析超时'),
                    ('aborted', '用户取消'),
                    ('network_failed', '网络异常'),
                    ('invalid_param_format', '参数无效'),
                    ('upstream_error', '未知错误'),
                ],
                db_index=True,
                help_text=(
                    'W1 / L9：与 @tabtin/file-pipeline-errors SSoT 对齐的 13 类失败码。'
                    'status=FAILED 时必填，客户端 UI 按此字段路由到 i18n 文案。'
                ),
                max_length=32,
                verbose_name='失败结构化分类',
            ),
        ),
    ]
