# Generated by Django 4.2.7 on 2026-07-29 12:57

import apps.extensions.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeishuImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('space_id', models.UUIDField(blank=True, null=True)),
                ('collection_id', models.UUIDField(blank=True, null=True)),
                ('tables', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('success', '成功'), ('failed', '失败')], db_index=True, default='pending', max_length=32)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feishu_import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'integrations_feishu_import_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeishuOAuthConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('tokens', apps.extensions.fields.EncryptedJSONField(default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('open_id', models.CharField(blank=True, default='', max_length=128)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('connected', '已连接'), ('revoked', '已撤销')], db_index=True, default='connected', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feishu_oauth_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'integrations_feishu_oauth_connection',
                'indexes': [models.Index(fields=['organization_id', 'status'], name='integration_organiz_0092cf_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='feishuoauthconnection',
            constraint=models.UniqueConstraint(fields=('user', 'organization_id'), name='uniq_feishu_oauth_user_org'),
        ),
        migrations.AddIndex(
            model_name='feishuimportjob',
            index=models.Index(fields=['user', 'organization_id', '-created_at'], name='integration_user_id_b82b2f_idx'),
        ),
    ]
