# Generated by Django 4.2.7 on 2026-03-04 20:27

import apps.users.auth.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.CharField(default=apps.users.auth.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, help_text='用于@username主页标识，可选', max_length=150, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='用户名只能包含字母、数字和下划线', regex='^[a-zA-Z0-9_]+$')], verbose_name='用户名')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='请输入有效的中国手机号', regex='^1[3-9]\\d{9}$')], verbose_name='手机号')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='昵称')),
                ('avatar', models.URLField(blank=True, verbose_name='头像URL')),
                ('bio', models.TextField(blank=True, verbose_name='个人简介')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_staff', models.BooleanField(default=False, verbose_name='是否为员工')),
                ('is_verified_email', models.BooleanField(default=False, verbose_name='邮箱是否验证')),
                ('is_verified_phone', models.BooleanField(default=False, verbose_name='手机是否验证')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('login_count', models.PositiveIntegerField(default=0, verbose_name='登录次数')),
                ('failed_login_attempts', models.PositiveIntegerField(default=0, verbose_name='登录失败次数')),
                ('last_failed_login', models.DateTimeField(blank=True, null=True, verbose_name='最后失败登录时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users_auth_user',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public_profile', models.BooleanField(default=True, verbose_name='公开资料')),
                ('allow_email_notifications', models.BooleanField(default=True, verbose_name='允许邮件通知')),
                ('allow_sms_notifications', models.BooleanField(default=True, verbose_name='允许短信通知')),
                ('timezone', models.CharField(default='Asia/Shanghai', max_length=50, verbose_name='时区')),
                ('language', models.CharField(choices=[('system', '跟随系统'), ('zh-CN', '简体中文'), ('en-US', 'English')], default='system', max_length=10, verbose_name='语言')),
                ('theme', models.CharField(choices=[('light', '浅色主题'), ('dark', '深色主题'), ('auto', '自动切换')], default='light', max_length=20, verbose_name='主题')),
                ('homepage_template', models.CharField(default='default', max_length=50, verbose_name='主页模板')),
                ('max_collections', models.PositiveIntegerField(default=100, verbose_name='最大收藏数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户配置',
                'verbose_name_plural': '用户配置',
                'db_table': 'users_auth_user_profile',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.CharField(default=apps.users.auth.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='组名')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('group_type', models.CharField(choices=[('system', '系统组'), ('business', '业务组'), ('custom', '自定义组')], default='custom', max_length=20, verbose_name='组类型')),
                ('max_members', models.PositiveIntegerField(blank=True, null=True, verbose_name='最大成员数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission', verbose_name='权限')),
                ('users', models.ManyToManyField(blank=True, related_name='user_groups', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户组',
                'verbose_name_plural': '用户组',
                'db_table': 'users_auth_user_group',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.CharField(default=apps.users.auth.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='会话密钥')),
                ('session_type', models.CharField(choices=[('web', '网页'), ('mobile', '移动端'), ('api', 'API')], default='web', max_length=20, verbose_name='会话类型')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('device_info', models.JSONField(default=dict, verbose_name='设备信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='最后活动时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('refresh_token_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='刷新令牌哈希')),
                ('refresh_token_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='刷新令牌更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户会话',
                'verbose_name_plural': '用户会话',
                'db_table': 'users_auth_user_session',
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='users_auth__user_id_8184ae_idx'), models.Index(fields=['session_key'], name='users_auth__session_a7f88a_idx'), models.Index(fields=['expires_at'], name='users_auth__expires_b9baa2_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.CharField(default=apps.users.auth.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('login', '登录'), ('logout', '登出'), ('register', '注册'), ('password_change', '修改密码'), ('password_reset', '重置密码'), ('profile_update', '更新资料'), ('email_verify', '邮箱验证'), ('phone_verify', '手机验证'), ('avatar_upload', '上传头像'), ('account_lock', '账号锁定'), ('account_unlock', '账号解锁')], max_length=50, verbose_name='操作类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('request_data', models.JSONField(default=dict, verbose_name='请求数据')),
                ('success', models.BooleanField(default=True, verbose_name='是否成功')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户操作日志',
                'verbose_name_plural': '用户操作日志',
                'db_table': 'users_auth_user_action_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='users_auth__user_id_4d6673_idx'), models.Index(fields=['action_type', 'created_at'], name='users_auth__action__4e8dbf_idx'), models.Index(fields=['success', 'created_at'], name='users_auth__success_feb716_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_auth__email_6d4832_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='users_auth__phone_8d4410_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_auth__usernam_16d1e3_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'date_joined'], name='users_auth__is_acti_418ff2_idx'),
        ),
    ]
