# Generated by Django 4.2.7 on 2026-03-20 17:51

import apps.users.auth.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApiKey',
            fields=[
                ('id', models.CharField(default=apps.users.auth.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('key_id', models.CharField(db_index=True, max_length=16, unique=True, verbose_name='Key 标识')),
                ('sign_hash', models.CharField(max_length=64, verbose_name='签名 Hash')),
                ('scopes', models.JSONField(default=list, verbose_name='权限范围')),
                ('rate_limit', models.PositiveIntegerField(default=60, verbose_name='限流(次/分钟)')),
                ('expired_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('use_count', models.PositiveIntegerField(default=0, verbose_name='使用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户 API Key',
                'verbose_name_plural': '用户 API Key',
                'db_table': 'users_auth_user_api_key',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='users_auth__user_id_92d11b_idx'), models.Index(fields=['key_id'], name='users_auth__key_id_459fa5_idx')],
            },
        ),
    ]
