# Generated by Django 4.2.7 on 2026-04-01 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0003_apikey_workteam_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userapikey',
            options={'ordering': ['-created_at'], 'verbose_name': 'API Key', 'verbose_name_plural': 'API Key'},
        ),
        migrations.RenameIndex(
            model_name='userapikey',
            new_name='users_auth__worktea_d77dd7_idx',
            old_name='users_auth__workteam_4d6e8a_idx',
        ),
        migrations.AlterField(
            model_name='userapikey',
            name='workteam_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='为空时等价于用户本人登录（可操作所有团队）；填写后仅限该团队', max_length=36, verbose_name='限定工作团队'),
        ),
    ]
