# Generated by Django 4.2.7 on 2026-04-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0004_alter_userapikey_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='session_key',
            field=models.CharField(max_length=64, unique=True, verbose_name='会话密钥'),
        ),
    ]
