# Generated by Django 4.2.7 on 2026-04-07 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0005_extend_session_key_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='请输入有效的手机号码', regex='^\\+?[1-9]\\d{6,14}$')], verbose_name='手机号'),
        ),
    ]
