# Generated by Django 4.2.7 on 2026-04-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0006_internationalize_phone_regex'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='approval_preferences',
            field=models.JSONField(blank=True, default=dict, verbose_name='审批偏好'),
        ),
    ]
