# Generated by Django 4.2.7 on 2026-04-23 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0007_add_approval_preferences_to_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAgentApprovalMemo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_id', models.UUIDField(db_index=True, help_text='指向 tabtinspace.Agent.id；跨库不做 FK', verbose_name='Agent ID')),
                ('action_type', models.CharField(help_text='如 execute_in_terminal / write_file / browser_navigate 等', max_length=64, verbose_name='动作类型')),
                ('pattern', models.CharField(help_text='bash 类命令 = normalizeCommand 后的整条命令字符串；其他类型按 action_type 各自约定（不支持通配符）', max_length=512, verbose_name='匹配模式')),
                ('rule_kind', models.CharField(choices=[('allow', '总是允许'), ('deny', '总是拒绝')], max_length=16, verbose_name='规则类型')),
                ('created_in_session_id', models.UUIDField(blank=True, help_text='审计用：记录这条规则是哪次对话产生的，指向 conversation.ChatSession.id。不做 FK 的原因：users_auth 是 dual_db（MySQL + PostgreSQL 影子库），而 conversation 仅在 MySQL，跨库无法建 FK 约束。语义上接受 dangling 引用——会话被删除时该字段保留，仅作为审计线索。', null=True, verbose_name='创建于会话 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_matched_at', models.DateTimeField(blank=True, help_text='find_match 命中时更新；用于 UI 展示和未来"长期未用清理"', null=True, verbose_name='最后命中时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_memos', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户 Agent 审批记忆',
                'verbose_name_plural': '用户 Agent 审批记忆',
                'db_table': 'users_auth_user_agent_approval_memo',
                'indexes': [models.Index(fields=['user', 'agent_id', 'action_type'], name='idx_memo_user_agent_action')],
            },
        ),
        migrations.AddConstraint(
            model_name='useragentapprovalmemo',
            constraint=models.UniqueConstraint(fields=('user', 'agent_id', 'action_type', 'pattern'), name='uniq_user_agent_action_pattern'),
        ),
    ]
