# Generated by Django 4.2.7 on 2026-05-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0008_user_agent_approval_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useragentapprovalmemo',
            name='created_in_session_id',
            field=models.UUIDField(blank=True, help_text='审计用：记录这条规则是哪次对话产生的，指向 conversation.ChatSession.id。不做 FK 的原因：users_auth 在 db_router 里被列为 _dual_db_labels，PG 侧也建影子表；而 conversation 只在 MySQL default 库，PG 侧没有 chat_session 表 → migrate PG 影子时 FK 创建失败。语义上接受 dangling 引用——会话被删除时该字段保留，仅作为审计线索；UI 渲染时若该 session 已不存在应做 fallback 文案。', null=True, verbose_name='创建于会话 ID'),
        ),
    ]
