# Generated by Django 4.2.7 on 2026-06-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0009_alter_useragentapprovalmemo_created_in_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ui_settings',
            field=models.JSONField(blank=True, default=dict, verbose_name='UI/个人偏好'),
        ),
    ]
