# Generated by Django 4.2.7 on 2026-06-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0010_userprofile_ui_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='personal_rules',
            field=models.TextField(blank=True, default='', help_text='对所有 Agent 生效的个人通用规则，运行时作为三层规则的个人基线层注入 system prompt。', verbose_name='个人 Agent 规则'),
        ),
    ]
