import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


ADMIN_PERMISSIONS = [
    ("user:list", "用户列表", "user", "low"),
    ("user:update_status", "启停客户用户账号", "user", "high"),
    ("intent_user:list", "意向用户列表", "user", "low"),
    ("invite_code:list", "邀请码列表", "user", "low"),
    ("invite_code:disable", "停用邀请码", "user", "high"),
    ("workteam:list", "团队列表", "workteam", "low"),
    ("workteam:view", "团队详情", "workteam", "low"),
    ("workteam:create", "创建团队", "workteam", "medium"),
    ("workteam:update", "更新团队", "workteam", "medium"),
    ("workteam:disable", "禁用团队", "workteam", "high"),
    ("workteam:delete", "删除团队", "workteam", "high"),
    ("workteam:transfer_owner", "转让 Owner", "workteam", "high"),
    ("workteam:view_members", "查看团队成员", "workteam", "low"),
    ("workteam:view_entitlements", "查看团队权益", "workteam", "low"),
    ("workteam:view_wallet", "查看团队钱包", "workteam", "medium"),
    ("workteam:view_usage", "查看团队用量", "workteam", "low"),
    ("workteam:view_billing", "查看团队计费", "workteam", "medium"),
    ("space:list", "Space 列表", "space", "low"),
    ("team_member:list", "成员列表", "team_member", "low"),
    ("team_member:view", "成员详情", "team_member", "low"),
    ("team_member:update_role", "修改成员角色", "team_member", "high"),
    ("team_member:remove", "移除成员", "team_member", "high"),
    ("team_member:view_budget", "查看成员预算", "team_member", "low"),
    ("team_member:update_budget", "修改成员预算", "team_member", "medium"),
    ("team_member:view_usage", "查看成员用量", "team_member", "low"),
    ("plan:list", "套餐列表", "plan", "low"),
    ("plan:view", "套餐详情", "plan", "low"),
    ("plan:create", "创建套餐", "plan", "high"),
    ("plan:update", "更新套餐", "plan", "high"),
    ("plan:disable", "停用套餐", "plan", "high"),
    ("plan:publish", "发布套餐", "plan", "high"),
    ("entitlement:view", "查看权益", "entitlement", "low"),
    ("entitlement:grant", "发放权益", "entitlement", "high"),
    ("entitlement:update", "更新权益", "entitlement", "high"),
    ("entitlement:revoke", "回收权益", "entitlement", "high"),
    ("credit_account:view", "查看点券账户", "credit", "medium"),
    ("credit_ledger:view", "查看点券流水", "credit", "medium"),
    ("credit:grant", "赠送点券", "credit", "high"),
    ("credit:deduct", "扣减点券", "credit", "high"),
    ("credit:adjust", "调整点券", "credit", "high"),
    ("credit:reverse", "冲正点券", "credit", "high"),
    ("credit_package:list", "点券资源包列表", "credit", "low"),
    ("credit_package:create", "创建点券资源包", "credit", "high"),
    ("credit_package:update", "更新点券资源包", "credit", "high"),
    ("credit_package:disable", "停用点券资源包", "credit", "high"),
    ("wallet:list", "钱包列表", "wallet", "medium"),
    ("wallet:view", "钱包详情", "wallet", "medium"),
    ("wallet:recharge", "钱包充值", "wallet", "high"),
    ("wallet:adjust", "钱包调账", "wallet", "high"),
    ("wallet:deduct", "钱包扣减", "wallet", "high"),
    ("wallet:freeze", "钱包冻结", "wallet", "high"),
    ("wallet:unfreeze", "钱包解冻", "wallet", "high"),
    ("wallet:refund", "钱包退款", "wallet", "high"),
    ("wallet:view_transactions", "查看钱包流水", "wallet", "medium"),
    ("wallet:export", "导出钱包流水", "wallet", "medium"),
    ("billing_dashboard:view", "计费大盘", "billing", "medium"),
    ("usage_event:list", "用量事件列表", "billing", "low"),
    ("usage_event:view", "用量事件详情", "billing", "low"),
    ("usage_event:export", "导出用量事件", "billing", "medium"),
    ("billing_event:list", "计费事件列表", "billing", "medium"),
    ("billing_event:view", "计费事件详情", "billing", "medium"),
    ("billing_event:retry", "重试计费事件", "billing", "high"),
    ("billing_event:reverse", "冲正计费事件", "billing", "high"),
    ("billing_event:export", "导出计费事件", "billing", "medium"),
    ("budget_policy:list", "预算策略列表", "billing", "low"),
    ("budget_policy:update", "更新预算策略", "billing", "high"),
    ("pricing_rule:list", "定价规则列表", "billing", "medium"),
    ("pricing_rule:update", "更新定价规则", "billing", "high"),
    ("product_config:list", "商品配置列表", "billing", "low"),
    ("addon_package:list", "权益扩容包列表", "billing", "low"),
    ("addon_package:update", "更新权益扩容包", "billing", "high"),
    ("storage_billing:list", "存储计费列表", "billing", "low"),
    ("invoice:list", "账单列表", "invoice", "medium"),
    ("invoice:view", "账单详情", "invoice", "medium"),
    ("invoice:refund", "账单退款", "invoice", "high"),
    ("invoice:export", "导出账单", "invoice", "medium"),
    ("order:list", "订单列表", "order", "medium"),
    ("order:view", "订单详情", "order", "medium"),
    ("order:create", "创建订单", "order", "high"),
    ("order:cancel", "取消订单", "order", "high"),
    ("order:refund", "订单退款", "order", "high"),
    ("order:export", "导出订单", "order", "medium"),
    ("reconciliation:list", "对账中心", "finance", "medium"),
    ("anomaly_alert:list", "异常告警列表", "risk", "medium"),
    ("anomaly_alert:view", "异常告警详情", "risk", "medium"),
    ("anomaly_alert:resolve", "处理异常告警", "risk", "high"),
    ("cost_analysis:view", "成本分析", "finance", "medium"),
    ("dispute:list", "争议单列表", "support", "medium"),
    ("risk:list", "风控列表", "risk", "medium"),
    ("risk:view", "风控详情", "risk", "medium"),
    ("risk:update", "更新风控", "risk", "high"),
    ("limit_rule:list", "限流规则列表", "risk", "medium"),
    ("limit_rule:create", "创建限流规则", "risk", "high"),
    ("limit_rule:update", "更新限流规则", "risk", "high"),
    ("limit_rule:disable", "停用限流规则", "risk", "high"),
    ("provider:list", "Provider 列表", "model", "medium"),
    ("provider:view", "Provider 详情", "model", "medium"),
    ("provider:create", "创建 Provider", "model", "high"),
    ("provider:update", "更新 Provider", "model", "high"),
    ("provider:delete", "删除 Provider", "model", "high"),
    ("provider:disable", "停用 Provider", "model", "high"),
    ("provider_key:delete", "删除 Provider Key", "model", "high"),
    ("search_provider:delete", "删除搜索 Provider", "model", "high"),
    ("model:list", "Model 列表", "model", "medium"),
    ("model:view", "Model 详情", "model", "medium"),
    ("model:create", "创建 Model", "model", "high"),
    ("model:update", "更新 Model", "model", "high"),
    ("model:disable", "停用 Model", "model", "high"),
    ("model:update_price", "更新模型价格", "model", "high"),
    ("ai_scene:list", "Scene 列表", "model", "low"),
    ("ai_prompt:list", "Prompt 列表", "model", "low"),
    ("ai_embedding:list", "Embedding 管理", "model", "medium"),
    ("ai_multimodal:list", "Multimodal 管理", "model", "medium"),
    ("ai_service:list", "AI 服务列表", "model", "medium"),
    ("ai_service:update_status", "更新 AI 服务状态", "model", "high"),
    ("ai_service:update_pricing", "更新 AI 服务计费", "model", "high"),
    ("ai_ops:view", "AI 治理查看", "model", "medium"),
    ("app_install:list", "App 安装列表", "app_tool", "medium"),
    ("app_authorization:list", "应用授权列表", "app_tool", "medium"),
    ("app_authorization:update", "更新应用授权", "app_tool", "high"),
    ("connect:list", "Connect 列表", "app_tool", "medium"),
    ("connect:view", "Connect 详情", "app_tool", "medium"),
    ("connect:revoke", "撤销 Connect", "app_tool", "high"),
    ("connect:bulk_revoke", "批量撤销 Connect", "app_tool", "high"),
    ("cli_audit:list", "CLI 审计列表", "app_tool", "medium"),
    ("cli_audit:export", "导出 CLI 审计", "app_tool", "medium"),
    ("tool:list", "工具列表", "app_tool", "medium"),
    ("tool:view", "工具详情", "app_tool", "medium"),
    ("tool:update_status", "更新工具状态", "app_tool", "high"),
    ("tool:sync", "同步工具", "app_tool", "high"),
    ("tool_audit:list", "工具审计列表", "app_tool", "medium"),
    ("skill_review:list", "Skill 审核列表", "app_tool", "medium"),
    ("skill_review:approve", "Skill 审核通过", "app_tool", "high"),
    ("skill_review:reject", "Skill 审核拒绝", "app_tool", "high"),
    ("agent_debug:list", "Agent 调试列表", "risk_ops", "medium"),
    ("agent_debug:view", "Agent 调试详情", "risk_ops", "medium"),
    ("trace:view", "Trace 详情", "risk_ops", "medium"),
    ("incident:view", "事故中心查看", "risk_ops", "medium"),
    ("incident:resolve", "事故处理", "risk_ops", "high"),
    ("client_error:list", "客户端错误列表", "risk_ops", "medium"),
    ("client_error:update_status", "更新客户端错误状态", "risk_ops", "medium"),
    ("desktop_update:list", "桌面更新列表", "risk_ops", "medium"),
    ("desktop_update:create", "创建桌面更新", "risk_ops", "high"),
    ("desktop_update:update", "更新桌面版本", "risk_ops", "high"),
    ("desktop_update:publish", "发布桌面版本", "risk_ops", "high"),
    ("desktop_update:rollout", "灰度桌面版本", "risk_ops", "high"),
    ("desktop_update:deprecate", "废弃桌面版本", "risk_ops", "high"),
    ("monitor:view", "系统监控查看", "risk_ops", "medium"),
    ("celery:view", "Celery 查看", "risk_ops", "medium"),
    ("celery_task:retry", "重试 Celery 任务", "risk_ops", "high"),
    ("celery_task:resolve", "解决 Celery 任务", "risk_ops", "high"),
    ("trash:list", "回收站列表", "risk_ops", "medium"),
    ("trash:restore", "恢复回收站资源", "risk_ops", "high"),
    ("trash:delete", "永久删除回收站资源", "risk_ops", "high"),
    ("trash:cleanup", "强制清理回收站", "risk_ops", "high"),
    ("workteam_cleanup:list", "Workteam 清理任务列表", "risk_ops", "medium"),
    ("workteam_cleanup:retry", "重试 Workteam 清理任务", "risk_ops", "high"),
    ("host_debug:view", "Host 调试查看", "risk_ops", "medium"),
    ("table:delete", "归档表格", "risk_ops", "high"),
    ("table:restore", "恢复表格", "risk_ops", "high"),
    ("table:repair", "修复表格索引", "risk_ops", "high"),
    ("doc:delete", "归档文档", "risk_ops", "high"),
    ("doc:restore", "恢复文档", "risk_ops", "high"),
    ("slide:delete", "归档演示文稿", "risk_ops", "high"),
    ("slide:restore", "恢复演示文稿", "risk_ops", "high"),
    ("asset:delete", "删除 OSS 文件", "risk_ops", "high"),
    ("asset:repair", "修复 OSS 文件归属", "risk_ops", "high"),
    ("platform_limit:view", "平台限制查看", "risk_ops", "medium"),
    ("platform_limit:update", "更新平台限制", "risk_ops", "high"),
    ("adjustment:list", "调整单列表", "adjustment", "medium"),
    ("adjustment:view", "调整单详情", "adjustment", "medium"),
    ("adjustment:create", "创建调整单", "adjustment", "high"),
    ("adjustment:approve", "审批调整单", "adjustment", "high"),
    ("adjustment:execute", "执行调整单", "adjustment", "high"),
    ("refund:list", "退款列表", "refund", "medium"),
    ("refund:view", "退款详情", "refund", "medium"),
    ("refund:create", "创建退款", "refund", "high"),
    ("refund:approve", "审批退款", "refund", "high"),
    ("refund:execute", "执行退款", "refund", "high"),
    ("compensation:create", "创建补偿", "compensation", "high"),
    ("compensation:approve", "审批补偿", "compensation", "high"),
    ("audit_log:list", "审计日志列表", "audit", "medium"),
    ("audit_log:view", "审计日志详情", "audit", "medium"),
    ("audit_log:export", "导出审计日志", "audit", "medium"),
    ("admin_account:list", "后台账号列表", "admin_governance", "high"),
    ("admin_account:view", "后台账号详情", "admin_governance", "high"),
    ("admin_account:create", "创建后台账号", "admin_governance", "high"),
    ("admin_account:update", "更新后台账号", "admin_governance", "high"),
    ("admin_account:disable", "禁用后台账号", "admin_governance", "high"),
    ("admin_account:assign_role", "分配后台角色", "admin_governance", "high"),
    ("admin_role:list", "后台角色列表", "admin_governance", "high"),
    ("admin_role:update", "更新后台角色", "admin_governance", "high"),
    ("admin_permission:list", "权限点列表", "admin_governance", "high"),
    ("admin_permission:update", "更新权限点", "admin_governance", "high"),
    ("sensitive_action:list", "敏感操作审计列表", "admin_governance", "high"),
    ("sensitive_action:view", "敏感操作审计详情", "admin_governance", "high"),
    ("admin_login_log:list", "后台登录日志列表", "admin_governance", "medium"),
    ("platform_config:list", "平台配置列表", "admin_governance", "high"),
    ("platform_config:update", "更新平台配置", "admin_governance", "high"),
    ("billing_runtime_config:view", "计费运行配置", "admin_governance", "high"),
    ("billing_runtime_config:update", "更新计费运行配置", "admin_governance", "high"),
]


ROLE_DEFINITIONS = {
    "super_admin": {
        "name": "Super Admin",
        "description": "全部后台权限。",
        "permissions": "*",
    },
    "billing_admin": {
        "name": "Billing Admin",
        "description": "计费、钱包、点券、账单、冲正和退款管理。",
        "permissions": [
            "workteam:list", "workteam:view", "workteam:view_members",
            "workteam:view_entitlements", "workteam:view_wallet",
            "workteam:view_usage", "workteam:view_billing",
            "team_member:list", "team_member:view", "team_member:view_budget",
            "team_member:update_budget", "team_member:view_usage",
            "plan:list", "plan:view", "plan:create", "plan:update",
            "plan:disable", "plan:publish", "entitlement:view",
            "entitlement:grant", "entitlement:update", "entitlement:revoke",
            "credit_account:view", "credit_ledger:view", "credit:grant",
            "credit:deduct", "credit:adjust", "credit:reverse",
            "credit_package:list", "credit_package:create",
            "credit_package:update", "credit_package:disable",
            "wallet:list", "wallet:view", "wallet:recharge", "wallet:adjust",
            "wallet:deduct", "wallet:freeze", "wallet:unfreeze",
            "wallet:refund", "wallet:view_transactions", "wallet:export",
            "billing_dashboard:view", "usage_event:list", "usage_event:view",
            "usage_event:export", "billing_event:list", "billing_event:view",
            "billing_event:retry", "billing_event:reverse",
            "billing_event:export", "budget_policy:list", "budget_policy:update",
            "pricing_rule:list", "pricing_rule:update",
            "product_config:list", "addon_package:list", "addon_package:update",
            "storage_billing:list", "invoice:list", "invoice:view",
            "invoice:refund", "invoice:export", "order:list", "order:view",
            "order:refund", "order:export", "reconciliation:list",
            "anomaly_alert:list", "anomaly_alert:view", "cost_analysis:view",
            "dispute:list", "adjustment:list", "adjustment:view",
            "adjustment:create", "adjustment:execute", "refund:list",
            "refund:view", "refund:create", "refund:execute",
            "compensation:create", "audit_log:list", "audit_log:view",
        ],
    },
    "support_agent": {
        "name": "Support Agent",
        "description": "客服排障只读角色，可查团队、成员、用量、流水、账单。",
        "permissions": [
            "user:list", "intent_user:list", "workteam:list", "workteam:view",
            "workteam:view_members", "workteam:view_entitlements",
            "workteam:view_wallet", "workteam:view_usage",
            "workteam:view_billing", "space:list", "team_member:list",
            "team_member:view", "team_member:view_budget",
            "team_member:view_usage", "entitlement:view",
            "credit_account:view", "credit_ledger:view", "wallet:list",
            "wallet:view", "wallet:view_transactions",
            "billing_dashboard:view", "usage_event:list", "usage_event:view",
            "billing_event:list", "billing_event:view", "invoice:list",
            "invoice:view", "order:list", "order:view",
            "anomaly_alert:list", "anomaly_alert:view", "dispute:list",
        ],
    },
    "model_admin": {
        "name": "Model Admin",
        "description": "AI Provider、Model、服务开关和模型健康管理。",
        "permissions": [
            "workteam:list", "workteam:view", "workteam:view_usage",
            "usage_event:list", "usage_event:view", "billing_event:list",
            "billing_event:view", "provider:list", "provider:view",
            "provider:create", "provider:update", "provider:delete", "provider:disable",
            "provider_key:delete", "search_provider:delete",
            "model:list", "model:view", "model:create", "model:update",
            "model:disable", "model:update_price", "ai_scene:list",
            "ai_prompt:list", "ai_embedding:list", "ai_multimodal:list",
            "ai_service:list", "ai_service:update_status",
            "ai_service:update_pricing", "ai_ops:view",
            "app_authorization:list", "connect:list", "connect:view",
            "anomaly_alert:list", "anomaly_alert:view",
            "cost_analysis:view", "audit_log:list", "audit_log:view",
        ],
    },
    "risk_admin": {
        "name": "Risk / Ops Admin",
        "description": "风控与运维角色，可查看事故、异常、调试、客户端错误、桌面更新和任务状态。",
        "permissions": [
            "user:list", "user:update_status", "intent_user:list", "workteam:list", "workteam:view",
            "workteam:view_members", "workteam:view_usage", "workteam:view_billing",
            "space:list", "team_member:list", "team_member:view",
            "usage_event:list", "usage_event:view", "billing_event:list",
            "billing_event:view", "ai_ops:view", "anomaly_alert:list",
            "anomaly_alert:view", "anomaly_alert:resolve", "risk:list",
            "risk:view", "risk:update", "limit_rule:list", "limit_rule:create",
            "limit_rule:update", "limit_rule:disable", "agent_debug:list",
            "agent_debug:view", "trace:view", "incident:view", "incident:resolve",
            "client_error:list", "client_error:update_status",
            "desktop_update:list", "desktop_update:create", "desktop_update:update",
            "desktop_update:publish", "desktop_update:rollout",
            "desktop_update:deprecate", "monitor:view", "celery:view",
            "celery_task:retry", "celery_task:resolve", "trash:list",
            "trash:restore", "trash:delete", "trash:cleanup",
            "workteam_cleanup:list", "workteam_cleanup:retry",
            "host_debug:view", "table:delete", "table:restore", "table:repair",
            "doc:delete", "doc:restore", "slide:delete", "slide:restore",
            "asset:delete", "asset:repair", "platform_limit:view", "platform_limit:update",
            "audit_log:list", "audit_log:view", "sensitive_action:list",
        ],
    },
    "finance_viewer": {
        "name": "Finance Viewer",
        "description": "财务只读，可查看和导出账单、订单、流水、对账。",
        "permissions": [
            "workteam:list", "workteam:view", "workteam:view_wallet",
            "workteam:view_billing", "team_member:list", "team_member:view",
            "credit_account:view", "credit_ledger:view", "wallet:list",
            "wallet:view", "wallet:view_transactions", "wallet:export",
            "billing_dashboard:view", "usage_event:list", "usage_event:view",
            "usage_event:export", "billing_event:list", "billing_event:view",
            "billing_event:export", "invoice:list", "invoice:view",
            "invoice:export", "order:list", "order:view", "order:export",
            "reconciliation:list", "cost_analysis:view", "audit_log:list",
            "audit_log:view", "audit_log:export",
        ],
    },
    "auditor": {
        "name": "Auditor",
        "description": "审计只读，可查看后台操作、计费审计和变更记录。",
        "permissions": [
            "user:list", "workteam:list", "workteam:view",
            "workteam:view_members", "workteam:view_entitlements",
            "workteam:view_wallet", "workteam:view_usage",
            "workteam:view_billing", "space:list", "team_member:list",
            "team_member:view", "team_member:view_budget",
            "team_member:view_usage", "plan:list", "plan:view",
            "entitlement:view", "credit_account:view", "credit_ledger:view",
            "wallet:list", "wallet:view", "wallet:view_transactions",
            "billing_dashboard:view", "usage_event:list", "usage_event:view",
            "usage_event:export", "billing_event:list", "billing_event:view",
            "billing_event:export", "invoice:list", "invoice:view",
            "invoice:export", "order:list", "order:view", "order:export",
            "provider:list", "provider:view", "model:list", "model:view",
            "ai_scene:list", "ai_prompt:list", "ai_embedding:list",
            "ai_multimodal:list", "ai_ops:view", "app_install:list",
            "app_authorization:list", "connect:list", "connect:view",
            "cli_audit:list", "tool:list", "tool:view", "tool_audit:list",
            "skill_review:list", "agent_debug:list", "agent_debug:view",
            "trace:view", "incident:view", "anomaly_alert:list", "anomaly_alert:view",
            "audit_log:list", "audit_log:view", "audit_log:export",
        ],
    },
}


def seed_admin_rbac(apps, schema_editor):
    User = apps.get_model("users_auth", "User")
    AdminAccount = apps.get_model("users_auth", "AdminAccount")
    AdminPermission = apps.get_model("users_auth", "AdminPermission")
    AdminRole = apps.get_model("users_auth", "AdminRole")
    AdminRolePermission = apps.get_model("users_auth", "AdminRolePermission")
    AdminAccountRole = apps.get_model("users_auth", "AdminAccountRole")

    permission_by_code = {}
    for code, name, category, risk_level in ADMIN_PERMISSIONS:
        permission, _ = AdminPermission.objects.update_or_create(
            code=code,
            defaults={
                "name": name,
                "category": category,
                "risk_level": risk_level,
                "is_active": True,
            },
        )
        permission_by_code[code] = permission

    for code, definition in ROLE_DEFINITIONS.items():
        role, _ = AdminRole.objects.update_or_create(
            code=code,
            defaults={
                "name": definition["name"],
                "description": definition["description"],
                "is_system": True,
                "is_active": True,
            },
        )
        permission_codes = (
            permission_by_code.keys()
            if definition["permissions"] == "*"
            else definition["permissions"]
        )
        for permission_code in permission_codes:
            permission = permission_by_code.get(permission_code)
            if permission is not None:
                AdminRolePermission.objects.get_or_create(role=role, permission=permission)

    super_role = AdminRole.objects.filter(code="super_admin").first()
    support_role = AdminRole.objects.filter(code="support_agent").first()
    for user in User.objects.filter(is_staff=True):
        account, _ = AdminAccount.objects.get_or_create(
            user_id=user.id,
            defaults={
                "display_name": user.get_display_name() if hasattr(user, "get_display_name") else "",
                "status": "active",
                "admin_login_enabled": True,
            },
        )
        role = super_role if getattr(user, "is_superuser", False) else support_role
        if role is not None:
            AdminAccountRole.objects.get_or_create(admin_account=account, role=role)


def unseed_admin_rbac(apps, schema_editor):
    AdminRole = apps.get_model("users_auth", "AdminRole")
    AdminPermission = apps.get_model("users_auth", "AdminPermission")
    AdminRole.objects.filter(code__in=ROLE_DEFINITIONS.keys(), is_system=True).delete()
    AdminPermission.objects.filter(code__in=[item[0] for item in ADMIN_PERMISSIONS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users_auth", "0014_intent_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminPermission",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=128, unique=True, verbose_name="权限编码")),
                ("name", models.CharField(max_length=100, verbose_name="权限名称")),
                ("category", models.CharField(db_index=True, max_length=64, verbose_name="权限分类")),
                (
                    "risk_level",
                    models.CharField(
                        choices=[("low", "低风险"), ("medium", "中风险"), ("high", "高风险"), ("critical", "极高风险")],
                        db_index=True,
                        default="low",
                        max_length=20,
                        verbose_name="风险等级",
                    ),
                ),
                ("description", models.CharField(blank=True, default="", max_length=255, verbose_name="说明")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="是否启用")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "后台权限点",
                "verbose_name_plural": "后台权限点",
                "db_table": "users_auth_admin_permission",
                "ordering": ["category", "code"],
                "indexes": [
                    models.Index(fields=["category", "is_active"], name="admin_perm_category_active"),
                    models.Index(fields=["risk_level", "is_active"], name="admin_perm_risk_active"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AdminRole",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=64, unique=True, verbose_name="角色编码")),
                ("name", models.CharField(max_length=100, verbose_name="角色名称")),
                ("description", models.CharField(blank=True, default="", max_length=255, verbose_name="说明")),
                ("is_system", models.BooleanField(db_index=True, default=False, verbose_name="系统内置")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="是否启用")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "后台角色",
                "verbose_name_plural": "后台角色",
                "db_table": "users_auth_admin_role",
                "ordering": ["code"],
                "indexes": [
                    models.Index(fields=["is_active", "is_system"], name="admin_role_active_system"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AdminAccount",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("display_name", models.CharField(blank=True, default="", max_length=100, verbose_name="后台显示名")),
                ("employee_no", models.CharField(blank=True, db_index=True, default="", max_length=64, verbose_name="员工编号")),
                ("department", models.CharField(blank=True, db_index=True, default="", max_length=100, verbose_name="部门")),
                ("position", models.CharField(blank=True, default="", max_length=100, verbose_name="岗位")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "启用"), ("disabled", "禁用"), ("locked", "锁定")],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="后台账号状态",
                    ),
                ),
                ("admin_login_enabled", models.BooleanField(db_index=True, default=True, verbose_name="允许后台登录")),
                ("last_admin_login_at", models.DateTimeField(blank=True, null=True, verbose_name="最近后台登录时间")),
                ("last_admin_login_ip", models.GenericIPAddressField(blank=True, null=True, verbose_name="最近后台登录 IP")),
                ("disabled_reason", models.CharField(blank=True, default="", max_length=500, verbose_name="禁用原因")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_admin_accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "disabled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disabled_admin_accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="禁用人",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_account",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "后台账号",
                "verbose_name_plural": "后台账号",
                "db_table": "users_auth_admin_account",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "admin_login_enabled"], name="admin_account_status_login"),
                    models.Index(fields=["department", "status"], name="admin_account_dept_status"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AdminSensitiveActionLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("permission_code", models.CharField(db_index=True, max_length=128, verbose_name="权限点")),
                ("action", models.CharField(blank=True, db_index=True, default="", max_length=128, verbose_name="操作动作")),
                ("target_type", models.CharField(db_index=True, max_length=64, verbose_name="目标类型")),
                ("target_id", models.CharField(blank=True, db_index=True, default="", max_length=128, verbose_name="目标 ID")),
                ("reason", models.CharField(max_length=500, verbose_name="操作原因")),
                ("ticket_id", models.CharField(blank=True, db_index=True, default="", max_length=128, verbose_name="工单 ID")),
                (
                    "related_billing_event_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=128, verbose_name="关联计费事件"),
                ),
                (
                    "related_wallet_transaction_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=128, verbose_name="关联钱包流水"),
                ),
                ("before_json", models.JSONField(blank=True, default=dict, verbose_name="变更前")),
                ("after_json", models.JSONField(blank=True, default=dict, verbose_name="变更后")),
                ("ip", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP 地址")),
                ("user_agent", models.TextField(blank=True, default="", verbose_name="User-Agent")),
                ("request_id", models.CharField(blank=True, db_index=True, default="", max_length=128, verbose_name="请求 ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                (
                    "actor_admin_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sensitive_action_logs",
                        to="users_auth.adminaccount",
                        verbose_name="操作后台账号",
                    ),
                ),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_sensitive_action_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
            ],
            options={
                "verbose_name": "后台敏感操作审计",
                "verbose_name_plural": "后台敏感操作审计",
                "db_table": "users_auth_admin_sensitive_action_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["permission_code", "created_at"], name="admin_action_perm_created"),
                    models.Index(fields=["target_type", "target_id"], name="admin_action_target"),
                    models.Index(fields=["actor_admin_account", "created_at"], name="admin_action_account_time"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AdminLoginLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("user_id", models.CharField(blank=True, db_index=True, default="", max_length=36, verbose_name="User ID")),
                ("ip", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP 地址")),
                ("user_agent", models.TextField(blank=True, default="", verbose_name="User-Agent")),
                ("login_method", models.CharField(blank=True, db_index=True, default="", max_length=32, verbose_name="登录方式")),
                ("success", models.BooleanField(db_index=True, default=True, verbose_name="是否成功")),
                ("fail_reason", models.CharField(blank=True, default="", max_length=255, verbose_name="失败原因")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                (
                    "admin_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="login_logs",
                        to="users_auth.adminaccount",
                        verbose_name="后台账号",
                    ),
                ),
            ],
            options={
                "verbose_name": "后台登录日志",
                "verbose_name_plural": "后台登录日志",
                "db_table": "users_auth_admin_login_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["admin_account", "created_at"], name="admin_login_account_time"),
                    models.Index(fields=["success", "created_at"], name="admin_login_success_time"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AdminOperationLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("action", models.CharField(db_index=True, max_length=128, verbose_name="操作动作")),
                ("target_type", models.CharField(blank=True, db_index=True, default="", max_length=64, verbose_name="目标类型")),
                ("target_id", models.CharField(blank=True, db_index=True, default="", max_length=128, verbose_name="目标 ID")),
                ("detail_json", models.JSONField(blank=True, default=dict, verbose_name="详情")),
                ("ip", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP 地址")),
                ("user_agent", models.TextField(blank=True, default="", verbose_name="User-Agent")),
                ("request_id", models.CharField(blank=True, db_index=True, default="", max_length=128, verbose_name="请求 ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                (
                    "actor_admin_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operation_logs",
                        to="users_auth.adminaccount",
                        verbose_name="操作后台账号",
                    ),
                ),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_operation_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "后台操作日志",
                "verbose_name_plural": "后台操作日志",
                "db_table": "users_auth_admin_operation_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["action", "created_at"], name="admin_op_action_time"),
                    models.Index(fields=["target_type", "target_id"], name="admin_op_target"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AdminRolePermission",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="users_auth.adminpermission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="users_auth.adminrole",
                    ),
                ),
            ],
            options={
                "verbose_name": "后台角色权限关系",
                "verbose_name_plural": "后台角色权限关系",
                "db_table": "users_auth_admin_role_permission",
                "constraints": [
                    models.UniqueConstraint(fields=("role", "permission"), name="uniq_admin_role_permission"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AdminAccountRole",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("reason", models.CharField(blank=True, default="", max_length=500, verbose_name="分配原因")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "admin_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to="users_auth.adminaccount",
                        verbose_name="后台账号",
                    ),
                ),
                (
                    "assigned_by_admin_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_account_roles",
                        to="users_auth.adminaccount",
                        verbose_name="分配后台账号",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_assignments",
                        to="users_auth.adminrole",
                    ),
                ),
            ],
            options={
                "verbose_name": "后台账号角色关系",
                "verbose_name_plural": "后台账号角色关系",
                "db_table": "users_auth_admin_account_role",
                "constraints": [
                    models.UniqueConstraint(fields=("admin_account", "role"), name="uniq_admin_account_role"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AdminUserRole",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_admin_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="分配人",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_assignments",
                        to="users_auth.adminrole",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_role_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "后台用户角色关系",
                "verbose_name_plural": "后台用户角色关系",
                "db_table": "users_auth_admin_user_role",
                "constraints": [
                    models.UniqueConstraint(fields=("user", "role"), name="uniq_admin_user_role"),
                ],
            },
        ),
        migrations.AddField(
            model_name="adminrole",
            name="permissions",
            field=models.ManyToManyField(
                related_name="roles",
                through="users_auth.AdminRolePermission",
                to="users_auth.adminpermission",
                verbose_name="权限点",
            ),
        ),
        migrations.RunPython(seed_admin_rbac, unseed_admin_rbac),
    ]
