# Generated by Django 4.2.7 on 2026-07-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0023_rename_workteam_to_organization'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userapikey',
            new_name='users_auth__organiz_606ddd_idx',
            old_name='users_auth__worktea_d77dd7_idx',
        ),
        migrations.AlterField(
            model_name='userapikey',
            name='organization_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='为空时等价于用户本人登录（可操作所有组织）；填写后仅限该组织', max_length=36, verbose_name='限定组织'),
        ),
    ]
