# Generated by Django 4.2.7 on 2026-07-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0027_backfill_analytics_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useragentapprovalmemo',
            name='agent_id',
            field=models.UUIDField(db_index=True, help_text='指向 agent.Agent.id；跨库不做 FK', verbose_name='Agent ID'),
        ),
    ]
