# Generated by Django 4.2.7 on 2026-07-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0028_alter_useragentapprovalmemo_agent_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_revision',
            field=models.PositiveBigIntegerField(
                default=0,
                help_text='昵称、用户名或头像更新时单调递增，供跨端缓存拒绝旧资料。',
                verbose_name='公开资料版本',
            ),
        ),
    ]
