# Generated by Django 4.2.7 on 2026-03-10 06:51

import apps.services.common.base_models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('space_id', models.UUIDField(db_index=True)),
                ('owner_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='站点名称')),
                ('slug', models.SlugField(help_text='站点访问地址标识，如 site.example.com/s/{slug}', max_length=100, unique=True, verbose_name='URL 标识')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('icon', models.CharField(blank=True, default='', max_length=50, verbose_name='图标')),
                ('code_project_path', models.CharField(blank=True, default='', help_text='关联的本地代码项目路径', max_length=1024, verbose_name='TabCode 项目路径')),
                ('tabdata_table_ids', models.JSONField(blank=True, default=list, help_text='站点关联的 TabData 表 ID 列表', verbose_name='绑定的 TabData 表')),
                ('tabdata_token_id', models.CharField(blank=True, default='', help_text='为站点创建的数据访问 Token', max_length=255, verbose_name='TabData API Token ID')),
                ('framework', models.CharField(choices=[('vanilla', '原生 HTML'), ('react', 'React + Vite')], default='react', max_length=20, verbose_name='技术栈')),
                ('published_url', models.URLField(blank=True, default='', max_length=2048, verbose_name='发布地址')),
                ('current_version', models.PositiveIntegerField(default=0, verbose_name='当前版本号')),
                ('dist_oss_url', models.URLField(blank=True, default='', help_text='当前激活版本的 dist 产物 OSS 根地址', max_length=2048, verbose_name='当前版本 OSS 地址')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('password', models.CharField(blank=True, default='', help_text='非空时需要输入密码才能访问', max_length=128, verbose_name='访问密码')),
                ('custom_domain', models.CharField(blank=True, default='', max_length=255, verbose_name='自定义域名')),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='总访问量')),
                ('template', models.CharField(blank=True, default='', help_text='创建时使用的模板: blank/dashboard/landing', max_length=50, verbose_name='模板标识')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], db_index=True, default='draft', max_length=20, verbose_name='状态')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tabsite_site',
                'ordering': ['-created_at'],
            },
            bases=(models.Model, apps.services.common.base_models.ContextSyncMixin),
        ),
        migrations.CreateModel(
            name='SiteVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(verbose_name='版本号')),
                ('message', models.CharField(blank=True, default='', max_length=500, verbose_name='版本说明')),
                ('dist_url', models.URLField(max_length=2048, verbose_name='OSS 打包产物地址')),
                ('file_count', models.PositiveIntegerField(default=0, verbose_name='文件数量')),
                ('total_size', models.PositiveIntegerField(default=0, verbose_name='总大小(bytes)')),
                ('is_current', models.BooleanField(default=False, verbose_name='是否当前版本')),
                ('published_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='tabsite.site')),
            ],
            options={
                'db_table': 'tabsite_version',
                'ordering': ['-version'],
                'indexes': [models.Index(fields=['site', '-version'], name='ts_ver_site_ver_idx')],
                'unique_together': {('site', 'version')},
            },
        ),
        migrations.CreateModel(
            name='SiteFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(help_text='相对路径，如 index.html, styles/main.css', max_length=500, verbose_name='文件路径')),
                ('content', models.TextField(blank=True, default='', verbose_name='文件内容')),
                ('content_type', models.CharField(blank=True, default='text/html', max_length=100, verbose_name='MIME 类型')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='文件大小(bytes)')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tabsite.site')),
            ],
            options={
                'db_table': 'tabsite_file',
                'ordering': ['path'],
                'unique_together': {('site', 'path')},
            },
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['workspace_id', 'space_id', 'status'], name='ts_ws_sp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['workspace_id', 'space_id', '-created_at'], name='ts_ws_sp_created_idx'),
        ),
    ]
