# Generated by Django 4.2.7 on 2026-03-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabsite', '0002_workspace_to_workteam_rename'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='site',
            name='ts_ws_sp_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='site',
            name='ts_ws_sp_created_idx',
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['workteam_id', 'space_id', 'status'], name='ts_ws_sp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['workteam_id', 'space_id', '-created_at'], name='ts_ws_sp_created_idx'),
        ),
    ]
