# Generated by Django 4.2.7 on 2026-06-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabsite', '0004_alter_site_created_by_alter_site_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='space_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
