/**
 * 配置管理统一导出
 */

export {
  DEFAULT_CONFIG,
  DEFAULT_SCRAPE_OPTIONS,
  DEFAULT_ENGINE_CONFIG,
  DEFAULT_STRATEGY_CONFIG,
  DEFAULT_QUEUE_CONFIG,
  DEFAULT_CACHE_CONFIG,
  DEFAULT_SECURITY_CONFIG,
  DEFAULT_LOG_CONFIG,
  DEFAULT_PERFORMANCE_CONFIG,
  ENVIRONMENT_CONFIGS
} from './default.js';

export type {
  CrawlConfig
} from './default.js';
