# Generated by Django 4.2.7 on 2026-03-04 20:27

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
from tabtin.migration_utils import PostgresOnlyOperation


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tabtinspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemember',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tabtinspace.workspace', verbose_name='工作空间'),
        ),
        migrations.AddField(
            model_name='workspaceinvitation',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tabtinspace.workspace', verbose_name='工作空间'),
        ),
        migrations.AddIndex(
            model_name='workspaceactivity',
            index=models.Index(fields=['workspace_id', 'created_at'], name='ctx_act_ws_time_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceactivity',
            index=models.Index(fields=['workspace_id', 'resource_type'], name='ctx_act_ws_restype_idx'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='owner',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL, verbose_name='所有者'),
        ),
        migrations.AddIndex(
            model_name='spaceadminactionlog',
            index=models.Index(fields=['action_type', 'created_at'], name='ctx_admin_action_time_idx'),
        ),
        migrations.AddIndex(
            model_name='spaceadminactionlog',
            index=models.Index(fields=['target_type', 'target_id'], name='ctx_admin_target_idx'),
        ),
        migrations.AddIndex(
            model_name='spaceadminactionlog',
            index=models.Index(fields=['workspace_id', 'created_at'], name='ctx_admin_ws_time_idx'),
        ),
        migrations.AddIndex(
            model_name='spaceadminactionlog',
            index=models.Index(fields=['agent_space_id', 'created_at'], name='ctx_admin_as_time_idx'),
        ),
        migrations.AddIndex(
            model_name='spaceadminactionlog',
            index=models.Index(fields=['operator_id', 'created_at'], name='ctx_admin_operator_time_idx'),
        ),
        migrations.AddIndex(
            model_name='spaceadminactionlog',
            index=models.Index(fields=['success', 'created_at'], name='ctx_admin_success_time_idx'),
        ),
        migrations.AddField(
            model_name='securecredential',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='secure_credentials', to=settings.AUTH_USER_MODEL, verbose_name='创建用户'),
        ),
        migrations.AddField(
            model_name='securecredential',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secure_credentials', to='tabtinspace.workspace', verbose_name='所属工作空间'),
        ),
        migrations.AddField(
            model_name='remoteserver',
            name='credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers', to='tabtinspace.securecredential', verbose_name='关联凭据'),
        ),
        migrations.AddField(
            model_name='remoteserver',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssh_servers', to='tabtinspace.device', verbose_name='所属设备'),
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='注册用户'),
        ),
        migrations.AddField(
            model_name='device',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='tabtinspace.workspace', verbose_name='所属工作空间'),
        ),
        migrations.AddField(
            model_name='delegationgrant',
            name='agent_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegation_grants', to='tabtinspace.agentspace', verbose_name='所属智能体空间'),
        ),
        migrations.AddField(
            model_name='delegationgrant',
            name='from_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_sent', to='tabtinspace.agent', verbose_name='委托发起 Agent'),
        ),
        migrations.AddField(
            model_name='delegationgrant',
            name='to_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to='tabtinspace.agent', verbose_name='委托接收 Agent'),
        ),
        migrations.AddField(
            model_name='contextitem',
            name='agent_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_items', to='tabtinspace.agentspace', verbose_name='所属智能体空间'),
        ),
        migrations.AddField(
            model_name='contextitem',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_context_items', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='contextitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_context_items', to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
        ),
        migrations.AddField(
            model_name='agentspaceshare',
            name='agent_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='tabtinspace.agentspace', verbose_name='所属智能体空间'),
        ),
        migrations.AddField(
            model_name='agentspaceshare',
            name='from_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_sent', to='tabtinspace.agent', verbose_name='共享发起 Agent'),
        ),
        migrations.AddField(
            model_name='agentspaceshare',
            name='to_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_received', to='tabtinspace.agent', verbose_name='共享接收 Agent'),
        ),
        migrations.AddField(
            model_name='agentspacepermission',
            name='agent_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='tabtinspace.agentspace'),
        ),
        migrations.AddField(
            model_name='agentspacemembership',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_space_memberships', to='tabtinspace.agent', verbose_name='所属 Agent'),
        ),
        migrations.AddField(
            model_name='agentspacemembership',
            name='agent_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tabtinspace.agentspace', verbose_name='所属智能体空间'),
        ),
        migrations.AddField(
            model_name='agentspaceappsettings',
            name='agent_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_settings', to='tabtinspace.agentspace', verbose_name='所属智能体空间'),
        ),
        migrations.AddField(
            model_name='agentspaceappsettings',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='agent_space_app_settings', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='agentspace',
            name='bound_device',
            field=models.ForeignKey(blank=True, help_text='绑定的执行设备，决定 Agent 的工具可用性。为空时仅支持后端工具（SQL/RAG/对话）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_spaces', to='tabtinspace.device', verbose_name='绑定设备'),
        ),
        migrations.AddField(
            model_name='agentspace',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_spaces', to='tabtinspace.workspace', verbose_name='所属工作空间'),
        ),
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to=settings.AUTH_USER_MODEL, verbose_name='绑定用户'),
        ),
        migrations.AddField(
            model_name='agent',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='tabtinspace.workspace', verbose_name='所属工作空间'),
        ),
        migrations.AddIndex(
            model_name='workspacemember',
            index=models.Index(fields=['workspace', 'role'], name='ctx_wm_workspace_role_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacemember',
            index=models.Index(fields=['user', 'joined_at'], name='ctx_wm_user_joined_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workspacemember',
            unique_together={('workspace', 'user')},
        ),
        migrations.AddIndex(
            model_name='workspaceinvitation',
            index=models.Index(fields=['workspace', 'status'], name='ctx_inv_ws_status_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceinvitation',
            index=models.Index(fields=['email', 'status'], name='ctx_inv_email_status_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceinvitation',
            index=models.Index(fields=['expires_at'], name='ctx_inv_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceinvitation',
            index=models.Index(fields=['workspace', 'email', 'invite_type', 'status'], name='ctx_inv_composite_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['owner', 'created_at'], name='ctx_ws_owner_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('owner',), name='ctx_ws_owner_default_unique'),
        ),
        migrations.AddIndex(
            model_name='remoteserver',
            index=models.Index(fields=['device', 'status'], name='ctx_rs_device_status_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['workspace', 'status'], name='ctx_device_ws_status_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user', 'status'], name='ctx_device_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='delegationgrant',
            index=models.Index(fields=['agent_space', 'status'], name='ctx_dg_as_status_idx'),
        ),
        migrations.AddIndex(
            model_name='delegationgrant',
            index=models.Index(fields=['to_agent', 'status'], name='ctx_dg_to_status_idx'),
        ),
        migrations.AddIndex(
            model_name='contextitem',
            index=models.Index(fields=['agent_space', 'item_type'], name='ctx_item_as_type_idx'),
        ),
        migrations.AddIndex(
            model_name='contextitem',
            index=models.Index(fields=['agent_space', 'is_archived'], name='ctx_item_as_archived_idx'),
        ),
        migrations.AddIndex(
            model_name='contextitem',
            index=models.Index(fields=['agent_space', 'order'], name='ctx_item_as_order_idx'),
        ),
        PostgresOnlyOperation(
            migrations.AddIndex(
                model_name='contextitem',
                index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='ctx_item_search_gin_idx'),
            ),
        ),
        migrations.AddIndex(
            model_name='agentspaceshare',
            index=models.Index(fields=['agent_space', 'status'], name='ctx_ass_as_status_idx'),
        ),
        migrations.AddIndex(
            model_name='agentspaceshare',
            index=models.Index(fields=['to_agent', 'status'], name='ctx_ass_to_status_idx'),
        ),
        migrations.AddIndex(
            model_name='agentspacepermission',
            index=models.Index(fields=['agent_space', 'is_active'], name='ctx_asp_as_active_idx'),
        ),
        migrations.AddIndex(
            model_name='agentspacepermission',
            index=models.Index(fields=['subject_type', 'subject_id'], name='ctx_asp_subject_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentspacepermission',
            constraint=models.UniqueConstraint(fields=('agent_space', 'subject_type', 'subject_id'), name='ctx_asp_unique_subject'),
        ),
        migrations.AddIndex(
            model_name='agentspacemembership',
            index=models.Index(fields=['agent_space', 'role'], name='ctx_asm_as_role_idx'),
        ),
        migrations.AddIndex(
            model_name='agentspacemembership',
            index=models.Index(fields=['agent', 'joined_at'], name='ctx_asm_agent_joined_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentspacemembership',
            unique_together={('agent_space', 'agent')},
        ),
        migrations.AddIndex(
            model_name='agentspaceappsettings',
            index=models.Index(fields=['agent_space', 'user'], name='ctx_as_app_user_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentspaceappsettings',
            unique_together={('agent_space', 'user')},
        ),
        migrations.AddIndex(
            model_name='agentspace',
            index=models.Index(fields=['workspace', 'status'], name='ctx_as_ws_status_idx'),
        ),
        migrations.AddIndex(
            model_name='agentspace',
            index=models.Index(fields=['workspace', 'is_archived'], name='ctx_as_ws_archived_idx'),
        ),
        migrations.AddIndex(
            model_name='agentspace',
            index=models.Index(fields=['workspace', 'order'], name='ctx_as_ws_order_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentspace',
            unique_together={('workspace', 'name')},
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['workspace', 'type'], name='ctx_agent_ws_type_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['workspace', 'user'], name='ctx_agent_ws_user_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['workspace', 'is_active'], name='ctx_agent_ws_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('workspace', 'user'), name='ctx_agent_workspace_user_unique'),
        ),
    ]
