# Generated by Django 4.2.7 on 2026-03-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentspace',
            name='previous_status',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='回收前状态'),
        ),
        migrations.AddField(
            model_name='agentspace',
            name='trashed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='进入回收站的时间，为 NULL 表示不在回收站', null=True, verbose_name='回收站时间'),
        ),
        migrations.AddField(
            model_name='agentspace',
            name='trashed_by',
            field=models.UUIDField(blank=True, null=True, verbose_name='回收站操作人'),
        ),
        migrations.AddField(
            model_name='contextitem',
            name='previous_status',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='回收前状态'),
        ),
        migrations.AddField(
            model_name='contextitem',
            name='trashed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='回收站时间'),
        ),
        migrations.AddField(
            model_name='contextitem',
            name='trashed_by',
            field=models.UUIDField(blank=True, null=True, verbose_name='回收站操作人'),
        ),
        migrations.AlterField(
            model_name='agentspace',
            name='status',
            field=models.CharField(choices=[('active', '进行中'), ('paused', '暂停'), ('completed', '已完成'), ('archived', '已归档'), ('trashed', '已删除')], default='active', max_length=20, verbose_name='Agent 状态'),
        ),
    ]
