# Generated by Django 4.2.7 on 2026-03-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0003_add_trash_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('online', '在线'), ('busy', '忙碌'), ('offline', '离线')], default='offline', max_length=20, verbose_name='在线状态'),
        ),
    ]
