# Generated by Django 4.2.7 on 2026-03-08 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tabtinspace', '0006_rename_agentspace_to_space'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='space',
            options={'ordering': ['order', '-created_at'], 'verbose_name': '协作空间', 'verbose_name_plural': '协作空间'},
        ),
        migrations.AlterModelOptions(
            name='spaceappsettings',
            options={'verbose_name': 'Space 应用设置', 'verbose_name_plural': 'Space 应用设置'},
        ),
        migrations.AlterModelOptions(
            name='spacemembership',
            options={'verbose_name': 'Space 成员', 'verbose_name_plural': 'Space 成员'},
        ),
        migrations.AlterModelOptions(
            name='spacepermission',
            options={'verbose_name': 'Space 权限', 'verbose_name_plural': 'Space 权限'},
        ),
        migrations.AlterModelOptions(
            name='spaceshare',
            options={'verbose_name': 'Space 共享', 'verbose_name_plural': 'Space 共享'},
        ),
        migrations.AddField(
            model_name='spacemembership',
            name='persona_override',
            field=models.TextField(blank=True, default='', verbose_name='身份覆写'),
        ),
        migrations.AddField(
            model_name='spacemembership',
            name='responsibility',
            field=models.TextField(blank=True, default='', verbose_name='职责描述'),
        ),
        migrations.AddField(
            model_name='spacemembership',
            name='role_label',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='角色标签'),
        ),
        migrations.AlterField(
            model_name='contextitem',
            name='space',
            field=models.ForeignKey(db_column='agent_space_id', on_delete=django.db.models.deletion.CASCADE, related_name='context_items', to='tabtinspace.space', verbose_name='所属 Space'),
        ),
        migrations.AlterField(
            model_name='delegationgrant',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegation_grants', to='tabtinspace.space', verbose_name='所属 Space'),
        ),
        migrations.AlterField(
            model_name='space',
            name='agent_config',
            field=models.JSONField(default=dict, verbose_name='[deprecated] Agent 安全配置'),
        ),
        migrations.AlterField(
            model_name='space',
            name='bound_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spaces', to='tabtinspace.device', verbose_name='[deprecated] 绑定设备'),
        ),
        migrations.AlterField(
            model_name='space',
            name='color',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='标签颜色'),
        ),
        migrations.AlterField(
            model_name='space',
            name='config_version',
            field=models.PositiveIntegerField(default=0, help_text='乐观并发控制版本号', verbose_name='配置版本号'),
        ),
        migrations.AlterField(
            model_name='space',
            name='crawl_config',
            field=models.JSONField(default=dict, verbose_name='[deprecated] 抓取配置'),
        ),
        migrations.AlterField(
            model_name='space',
            name='custom_rules',
            field=models.TextField(blank=True, default='', verbose_name='[deprecated] 自定义规则'),
        ),
        migrations.AlterField(
            model_name='space',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='space',
            name='goal',
            field=models.TextField(blank=True, default='', verbose_name='[deprecated] Agent 目标'),
        ),
        migrations.AlterField(
            model_name='space',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='是否默认'),
        ),
        migrations.AlterField(
            model_name='space',
            name='keywords',
            field=models.JSONField(default=list, verbose_name='[deprecated] 关键词列表'),
        ),
        migrations.AlterField(
            model_name='space',
            name='name',
            field=models.CharField(max_length=255, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='space',
            name='persona_prompt',
            field=models.TextField(blank=True, default='', verbose_name='[deprecated] 身份设定'),
        ),
        migrations.AlterField(
            model_name='space',
            name='tags',
            field=models.JSONField(default=list, verbose_name='[deprecated] 标签'),
        ),
        migrations.AlterField(
            model_name='space',
            name='trashed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='回收站时间'),
        ),
        migrations.AlterField(
            model_name='space',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='tabtinspace.workspace', verbose_name='所属工作空间'),
        ),
        migrations.AlterField(
            model_name='spaceadminactionlog',
            name='space_id',
            field=models.UUIDField(blank=True, db_column='agent_space_id', db_index=True, null=True, verbose_name='Space ID'),
        ),
        migrations.AlterField(
            model_name='spaceappsettings',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_settings', to='tabtinspace.space', verbose_name='所属 Space'),
        ),
        migrations.AlterField(
            model_name='spaceappsettings',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='space_app_settings', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='spacemembership',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space_memberships', to='tabtinspace.agent', verbose_name='Agent 身份'),
        ),
        migrations.AlterField(
            model_name='spacemembership',
            name='role',
            field=models.CharField(choices=[('owner', '所有者'), ('admin', '管理员'), ('editor', '编辑者'), ('viewer', '查看者'), ('participant', '参与者')], default='viewer', max_length=20, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='spacemembership',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tabtinspace.space', verbose_name='所属 Space'),
        ),
        migrations.AlterField(
            model_name='spacepermission',
            name='space',
            field=models.ForeignKey(db_column='agent_space_id', on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='tabtinspace.space'),
        ),
        migrations.AlterField(
            model_name='spaceshare',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='tabtinspace.space', verbose_name='所属 Space'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='space_count',
            field=models.IntegerField(db_column='agent_space_count', default=0, help_text='由 signal 维护的非规范化计数，实际数以 Space 查询为准。', verbose_name='Space 数量'),
        ),
    ]
