# Generated by Django 4.2.7 on 2026-03-08 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0007_alter_space_options_alter_spaceappsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextitem',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_items', to='tabtinspace.space', verbose_name='所属 Space'),
        ),
        migrations.AlterField(
            model_name='spaceadminactionlog',
            name='space_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Space ID'),
        ),
        migrations.AlterField(
            model_name='spacepermission',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='tabtinspace.space'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='space_count',
            field=models.IntegerField(default=0, help_text='由 signal 维护的非规范化计数，实际数以 Space 查询为准。', verbose_name='Space 数量'),
        ),
    ]
