# Generated by Django 4.2.7 on 2026-03-10 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0011_rename_tables_agent_space_to_space'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-created_at'], 'verbose_name': '设备', 'verbose_name_plural': '设备'},
        ),
        migrations.AlterField(
            model_name='agent',
            name='control_device',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'control'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_agents', to='tabtinspace.device', verbose_name='执行设备'),
        ),
        migrations.AlterField(
            model_name='device',
            name='capabilities',
            field=models.JSONField(default=list, help_text='如 ["terminal_execute", "file", "code_search"]，决定 Space 可用工具域', verbose_name='设备能力列表'),
        ),
        migrations.AlterField(
            model_name='device',
            name='role',
            field=models.CharField(choices=[('control', '执行设备'), ('data', '能力设备')], default='control', help_text='control=执行设备，data=能力设备', max_length=20, verbose_name='设备角色'),
        ),
    ]
