# Generated by Django 4.2.7 on 2026-03-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0012_alter_device_options_alter_agent_control_device_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contextitem',
            options={'ordering': ['-is_pinned', '-pinned_at', 'order', '-created_at'], 'verbose_name': '上下文条目', 'verbose_name_plural': '上下文条目'},
        ),
        migrations.AddField(
            model_name='contextitem',
            name='is_pinned',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否置顶'),
        ),
        migrations.AddField(
            model_name='contextitem',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='置顶时间'),
        ),
        migrations.AddIndex(
            model_name='contextitem',
            index=models.Index(fields=['space', '-is_pinned', '-pinned_at'], name='ctx_item_pinned_idx'),
        ),
    ]
