# Generated by Django 4.2.7 on 2026-03-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0013_add_pinned_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceinvitation',
            name='invited_user_id',
            field=models.CharField(blank=True, default='', help_text='direct 类型邀请时填写目标用户 ID', max_length=64, verbose_name='被邀请用户 ID'),
        ),
        migrations.AlterField(
            model_name='workspaceinvitation',
            name='invite_type',
            field=models.CharField(choices=[('email', '邮件邀请'), ('link', '链接邀请'), ('direct', '直接邀请')], max_length=10, verbose_name='邀请类型'),
        ),
        migrations.AlterField(
            model_name='workspaceinvitation',
            name='status',
            field=models.CharField(choices=[('pending', '待接受'), ('accepted', '已接受'), ('rejected', '已拒绝'), ('expired', '已过期'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AddIndex(
            model_name='workspaceinvitation',
            index=models.Index(fields=['invited_user_id', 'status'], name='ctx_inv_user_status_idx'),
        ),
    ]
