# Generated by Django 4.2.7 on 2026-03-19 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0015_add_invitation_reject_action'),
        ('tabtinspace', '0015_workspace_to_workteam_rename'),
    ]

    operations = [
    ]
