# Generated by Django 4.2.7 on 2026-03-19 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tabtinspace', '0016_merge_20260319_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workteam',
            options={'ordering': ['-updated_at'], 'verbose_name': '工作团队', 'verbose_name_plural': '工作团队'},
        ),
        migrations.AlterModelOptions(
            name='workteamactivity',
            options={'ordering': ['-created_at'], 'verbose_name': '工作团队活动', 'verbose_name_plural': '工作团队活动'},
        ),
        migrations.AlterModelOptions(
            name='workteaminvitation',
            options={'ordering': ['-created_at'], 'verbose_name': '工作团队邀请', 'verbose_name_plural': '工作团队邀请'},
        ),
        migrations.AlterModelOptions(
            name='workteammember',
            options={'verbose_name': '工作团队成员', 'verbose_name_plural': '工作团队成员'},
        ),
        migrations.RemoveConstraint(
            model_name='agent',
            name='ctx_agent_workspace_user_unique',
        ),
        migrations.RemoveIndex(
            model_name='agent',
            name='ctx_agent_ws_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='agent',
            name='ctx_agent_ws_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='agent',
            name='ctx_agent_ws_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='device',
            name='ctx_device_ws_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='space',
            name='ctx_as_ws_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='space',
            name='ctx_as_ws_archived_idx',
        ),
        migrations.RemoveIndex(
            model_name='space',
            name='ctx_as_ws_order_idx',
        ),
        migrations.RemoveIndex(
            model_name='space',
            name='ctx_space_ws_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='space',
            name='ctx_space_ws_activity_idx',
        ),
        migrations.RemoveIndex(
            model_name='spaceadminactionlog',
            name='ctx_admin_ws_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='workteamactivity',
            name='ctx_act_ws_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='workteamactivity',
            name='ctx_act_ws_restype_idx',
        ),
        migrations.RemoveIndex(
            model_name='workteaminvitation',
            name='ctx_inv_ws_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='workteaminvitation',
            name='ctx_inv_composite_idx',
        ),
        migrations.RemoveIndex(
            model_name='workteammember',
            name='ctx_wm_workspace_role_idx',
        ),
        migrations.AlterField(
            model_name='agent',
            name='workteam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='tabtinspace.workteam', verbose_name='所属工作团队'),
        ),
        migrations.AlterField(
            model_name='device',
            name='workteam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='tabtinspace.workteam', verbose_name='所属工作团队'),
        ),
        migrations.AlterField(
            model_name='securecredential',
            name='workteam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secure_credentials', to='tabtinspace.workteam', verbose_name='所属工作团队'),
        ),
        migrations.AlterField(
            model_name='space',
            name='workteam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='tabtinspace.workteam', verbose_name='所属工作团队'),
        ),
        migrations.AlterField(
            model_name='spaceadminactionlog',
            name='action_type',
            field=models.CharField(choices=[('workteam_create', '创建工作团队'), ('workteam_update', '更新工作团队'), ('workteam_delete', '删除工作团队'), ('space_create', '创建 Space'), ('space_update', '更新 Space'), ('space_archive', '归档 Space'), ('space_restore', '恢复 Space'), ('space_delete', '删除 Space'), ('member_add', '添加成员'), ('member_remove', '移除成员'), ('member_role_change', '变更成员角色'), ('invitation_create', '创建邀请'), ('invitation_accept', '接受邀请'), ('invitation_cancel', '取消邀请'), ('invitation_reject', '拒绝邀请'), ('ownership_transfer', '转让所有权'), ('permission_grant', '授予权限'), ('permission_revoke', '撤销权限'), ('resource_create', '创建资源'), ('resource_update', '更新资源'), ('resource_delete', '删除资源'), ('resource_share', '共享资源'), ('user_delete_cleanup', '用户删除跨库清理')], db_index=True, max_length=64, verbose_name='动作类型'),
        ),
        migrations.AlterField(
            model_name='spaceadminactionlog',
            name='target_type',
            field=models.CharField(choices=[('workteam', '工作团队'), ('space', '协作空间'), ('member', '成员'), ('invitation', '邀请'), ('table', '表格'), ('document', '文档'), ('slide', '幻灯片'), ('permission', '权限'), ('user', '用户')], db_index=True, max_length=32, verbose_name='目标类型'),
        ),
        migrations.AlterField(
            model_name='spaceadminactionlog',
            name='workteam_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='工作团队 ID'),
        ),
        migrations.AlterField(
            model_name='workteam',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='是否为默认工作团队'),
        ),
        migrations.AlterField(
            model_name='workteam',
            name='member_count',
            field=models.IntegerField(default=0, help_text='由 signal 维护的非规范化计数，实际成员数以 WorkteamMember 查询为准。初始值 0，由 provision_workteam_defaults 最终覆写为正确值。', verbose_name='成员数量'),
        ),
        migrations.AlterField(
            model_name='workteam',
            name='name',
            field=models.CharField(max_length=255, verbose_name='工作团队名称'),
        ),
        migrations.AlterField(
            model_name='workteam',
            name='owner',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='owned_workteams', to=settings.AUTH_USER_MODEL, verbose_name='所有者'),
        ),
        migrations.AlterField(
            model_name='workteam',
            name='settings',
            field=models.JSONField(default=dict, verbose_name='工作团队设置'),
        ),
        migrations.AlterField(
            model_name='workteamactivity',
            name='workteam_id',
            field=models.UUIDField(db_index=True, verbose_name='工作团队 ID'),
        ),
        migrations.AlterField(
            model_name='workteaminvitation',
            name='workteam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tabtinspace.workteam', verbose_name='工作团队'),
        ),
        migrations.AlterField(
            model_name='workteammember',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='workteam_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='workteammember',
            name='workteam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tabtinspace.workteam', verbose_name='工作团队'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['workteam', 'type'], name='ctx_agent_ws_type_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['workteam', 'user'], name='ctx_agent_ws_user_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['workteam', 'is_active'], name='ctx_agent_ws_active_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['workteam', 'status'], name='ctx_device_ws_status_idx'),
        ),
        migrations.AddIndex(
            model_name='space',
            index=models.Index(fields=['workteam', 'status'], name='ctx_as_ws_status_idx'),
        ),
        migrations.AddIndex(
            model_name='space',
            index=models.Index(fields=['workteam', 'is_archived'], name='ctx_as_ws_archived_idx'),
        ),
        migrations.AddIndex(
            model_name='space',
            index=models.Index(fields=['workteam', 'order'], name='ctx_as_ws_order_idx'),
        ),
        migrations.AddIndex(
            model_name='space',
            index=models.Index(fields=['workteam', 'type'], name='ctx_space_ws_type_idx'),
        ),
        migrations.AddIndex(
            model_name='space',
            index=models.Index(fields=['workteam', 'last_activity_at'], name='ctx_space_ws_activity_idx'),
        ),
        migrations.AddIndex(
            model_name='spaceadminactionlog',
            index=models.Index(fields=['workteam_id', 'created_at'], name='ctx_admin_ws_time_idx'),
        ),
        migrations.AddIndex(
            model_name='workteamactivity',
            index=models.Index(fields=['workteam_id', 'created_at'], name='ctx_act_ws_time_idx'),
        ),
        migrations.AddIndex(
            model_name='workteamactivity',
            index=models.Index(fields=['workteam_id', 'resource_type'], name='ctx_act_ws_restype_idx'),
        ),
        migrations.AddIndex(
            model_name='workteaminvitation',
            index=models.Index(fields=['workteam', 'status'], name='ctx_inv_ws_status_idx'),
        ),
        migrations.AddIndex(
            model_name='workteaminvitation',
            index=models.Index(fields=['workteam', 'email', 'invite_type', 'status'], name='ctx_inv_composite_idx'),
        ),
        migrations.AddIndex(
            model_name='workteammember',
            index=models.Index(fields=['workteam', 'role'], name='ctx_wm_workspace_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('workteam', 'user'), name='ctx_agent_workspace_user_unique'),
        ),
    ]
