# Generated by Django 4.2.7 on 2026-03-20 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tabtinspace', '0017_alter_workteam_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkteamAppInstall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_id', models.CharField(db_index=True, help_text='CORE_APPS key 或 TinAppRegistry.app_id', max_length=64, verbose_name='应用 ID')),
                ('app_source', models.CharField(choices=[('core', '核心应用'), ('tinapp', 'TinApp 扩展')], default='core', max_length=16, verbose_name='应用来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='安装时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('installed_by', models.ForeignKey(blank=True, db_constraint=False, help_text='CORE_APPS 自动安装时为 Workteam owner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installed_apps', to=settings.AUTH_USER_MODEL, verbose_name='安装人')),
                ('workteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_installs', to='tabtinspace.workteam', verbose_name='所属工作团队')),
            ],
            options={
                'verbose_name': 'Workteam 应用安装',
                'verbose_name_plural': 'Workteam 应用安装',
                'db_table': 'tabtinspace_workteam_app_install',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['workteam', 'app_source'], name='ctx_wai_ws_source_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='workteamappinstall',
            constraint=models.UniqueConstraint(fields=('workteam', 'app_id'), name='ctx_wai_workteam_app_unique'),
        ),
    ]
