# Generated by Django 4.2.7 on 2026-03-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0019_backfill_core_apps'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='avatar',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='头像图片 URL'),
        ),
    ]
