# Generated by Django 4.2.7 on 2026-03-27 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0022_workteam_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='agent_config',
        ),
        migrations.RemoveField(
            model_name='space',
            name='bound_device',
        ),
        migrations.RemoveField(
            model_name='space',
            name='crawl_config',
        ),
        migrations.RemoveField(
            model_name='space',
            name='custom_rules',
        ),
        migrations.RemoveField(
            model_name='space',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='space',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='space',
            name='persona_prompt',
        ),
        migrations.RemoveField(
            model_name='space',
            name='tags',
        ),
        migrations.AddField(
            model_name='space',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spaces', to='tabtinspace.agent', verbose_name='关联 Agent（bot Space 必填）'),
        ),
        migrations.AlterField(
            model_name='space',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='图标（已废弃，使用 avatar）'),
        ),
    ]
