# Generated by Django 4.2.7 on 2026-03-27 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0024_agent_runtime_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegationgrant',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='撤销时间'),
        ),
        migrations.AddField(
            model_name='delegationgrant',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_delegations', to='tabtinspace.agent', verbose_name='撤销者'),
        ),
        migrations.AddField(
            model_name='delegationgrant',
            name='trigger_config',
            field=models.JSONField(default=dict, help_text='格式: {"type": "offline"} / {"type": "always"} / {"type": "manual"}', verbose_name='触发条件配置'),
        ),
        migrations.AddField(
            model_name='spaceshare',
            name='billing_mode',
            field=models.CharField(choices=[('owner', 'Space 所有者承担'), ('user', '使用者承担')], default='owner', help_text='仅对平台渠道生效；BYOK 渠道的实际 API 费用始终归 Key 持有者', max_length=20, verbose_name='费用归属'),
        ),
        migrations.AddField(
            model_name='spaceshare',
            name='context_mode',
            field=models.CharField(choices=[('independent', '独立会话'), ('shared', '共享对话上下文')], default='independent', max_length=20, verbose_name='对话上下文模式'),
        ),
        migrations.AddField(
            model_name='spaceshare',
            name='inherit_owner_provider',
            field=models.BooleanField(default=False, help_text='启用后共享用户使用 Space 所有者的个人 LLM 渠道配置', verbose_name='继承所有者 LLM 渠道'),
        ),
        migrations.AddField(
            model_name='spaceshare',
            name='monthly_credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='月度消耗上限（点券）'),
        ),
        migrations.AlterField(
            model_name='spaceshare',
            name='status',
            field=models.CharField(choices=[('pending', '待接受'), ('active', '已生效'), ('revoked', '已撤销'), ('expired', '已过期'), ('suspended', '已暂停')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
