# Generated by Django 4.2.7 on 2026-03-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0025_sharing_delegation_phase1'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='space',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('type', 'bot'), _negated=True), ('agent__isnull', False), _connector='OR'), name='ctx_space_bot_requires_agent'),
        ),
    ]
