# Generated by Django 4.2.7 on 2026-04-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0028_tabagenda_core_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacepermission',
            name='permission',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('admin', 'Admin'), ('owner', 'Owner')], default='viewer', max_length=20),
        ),
    ]
