# Generated by Django 4.2.7 on 2026-04-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0030_alter_spacepermission_granted_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoulPreset',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='预设标识')),
                ('name', models.CharField(max_length=64, verbose_name='显示名称')),
                ('tagline', models.CharField(max_length=128, verbose_name='一句话描述')),
                ('description', models.TextField(blank=True, default='', verbose_name='详细描述')),
                ('icon', models.CharField(default='bot', max_length=32, verbose_name='图标标识')),
                ('order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_default', models.BooleanField(default=False, help_text='创建 Agent 时默认高亮的预设，最多一个为 True', verbose_name='是否默认推荐')),
                ('personality', models.JSONField(default=dict, help_text='{"identity": "角色描述", "behavior_rules": ["规则1", ...]}', verbose_name='人格配置')),
                ('agent_config_overrides', models.JSONField(default=dict, help_text='选择此 Soul 时自动应用到 agent_config 的配置项', verbose_name='Agent 配置覆盖')),
                ('default_mode', models.CharField(default='agent', help_text='agent / plan / study / ask', max_length=16, verbose_name='默认交互模式')),
                ('translations', models.JSONField(default=dict, verbose_name='多语言翻译')),
                ('version', models.CharField(default='1.0', max_length=16, verbose_name='预设版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Soul 内核预设',
                'verbose_name_plural': 'Soul 内核预设',
                'db_table': 'tabtinspace_soul_preset',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
