# Generated by Django 4.2.7 on 2026-04-07 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tabtinspace', '0035_one_active_bot_space_per_agent'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='space',
            name='ctx_space_bot_requires_agent',
        ),
        migrations.AddField(
            model_name='agent',
            name='suggested_prompts',
            field=models.JSONField(blank=True, default=list, help_text='对话空状态展示的推荐问题，创建时从 SoulPreset 快照，用户可覆写', verbose_name='推荐问题'),
        ),
        migrations.AddField(
            model_name='soulpreset',
            name='suggested_prompts',
            field=models.JSONField(blank=True, default=list, help_text='对话空状态时展示的推荐问题列表，如 ["帮我整理会议纪要", ...]', verbose_name='推荐问题'),
        ),
        migrations.AlterField(
            model_name='workteam',
            name='owner',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='owned_workteams', to=settings.AUTH_USER_MODEL, verbose_name='所有者'),
        ),
        migrations.AddIndex(
            model_name='delegationgrant',
            index=models.Index(fields=['from_agent', 'status'], name='ctx_dg_from_status_idx'),
        ),
        migrations.AddIndex(
            model_name='spaceshare',
            index=models.Index(fields=['from_agent', 'status'], name='ctx_ss_from_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='space',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('type', 'bot'), _negated=True), ('agent__isnull', False), ('trashed_at__isnull', False), _connector='OR'), name='ctx_space_bot_requires_agent'),
        ),
        migrations.AddConstraint(
            model_name='spaceshare',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'pending'])), fields=('space', 'from_agent', 'to_agent'), name='ctx_ss_unique_active_share'),
        ),
    ]
