# Generated by Django 4.2.7 on 2026-04-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0036_add_suggested_prompts'),
    ]

    operations = [
        migrations.AddField(
            model_name='soulpreset',
            name='welcome_message',
            field=models.TextField(blank=True, default='', help_text='新 Space 空消息列表时展示的欢迎引导消息，支持 Markdown', verbose_name='欢迎消息'),
        ),
    ]
