# Generated by Django 4.2.7 on 2026-04-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0039_remove_section_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='preferred_model_id',
            field=models.CharField(blank=True, default='', help_text='用户最后一次在对话中选择的模型 ID，新对话时优先使用。', max_length=255, verbose_name='偏好模型 ID'),
        ),
    ]
