# Generated by Django 4.2.7 on 2026-04-18 03:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0042_collection_system_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workteamappinstall',
            name='app_id',
            field=models.CharField(db_index=True, help_text='CORE_APPS key 或 MARKETPLACE_APPS key', max_length=64, verbose_name='应用 ID'),
        ),
        migrations.CreateModel(
            name='DeviceAppInstallSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.UUIDField(db_index=True, help_text='软引用 tabtinspace.Device.id', verbose_name='设备 ID')),
                ('workteam_id', models.UUIDField(db_index=True, help_text='冗余索引，加速 admin 按 workteam 过滤', verbose_name='工作团队 ID')),
                ('app_id', models.CharField(db_index=True, max_length=64, verbose_name='应用 ID')),
                ('version', models.CharField(default='', max_length=64, verbose_name='版本号')),
                ('last_seen_at', models.DateTimeField(verbose_name='最后心跳时间')),
                ('install_status', models.CharField(choices=[('installed', '已安装'), ('stale', '心跳超时'), ('missing', '缺失')], db_index=True, default='installed', max_length=16, verbose_name='安装状态')),
                ('extra', models.JSONField(blank=True, default=dict, help_text='预留：本地 binary 路径 / SHA256 校验结果等', verbose_name='扩展信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Device App 安装快照',
                'verbose_name_plural': 'Device App 安装快照',
                'db_table': 'tabtinspace_device_app_install_snapshot',
                'indexes': [models.Index(fields=['workteam_id', 'app_id'], name='ctx_dais_wt_app_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='deviceappinstallsnapshot',
            constraint=models.UniqueConstraint(fields=('device_id', 'app_id'), name='ctx_dais_device_app_unique'),
        ),
    ]
