# Generated by Django 4.2.7 on 2026-05-05 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0045_remove_skill_configs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spaceshare',
            name='billing_mode',
        ),
    ]
