# Generated by Django 4.2.7 on 2026-05-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabtinspace", "0049_rename_yolo_mode_to_allow_yolo_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spaceadminactionlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("workteam_create", "创建工作团队"),
                    ("workteam_update", "更新工作团队"),
                    ("workteam_delete", "删除工作团队"),
                    ("space_create", "创建 Space"),
                    ("space_update", "更新 Space"),
                    ("space_archive", "归档 Space"),
                    ("space_restore", "恢复 Space"),
                    ("space_delete", "删除 Space"),
                    ("member_add", "添加成员"),
                    ("member_remove", "移除成员"),
                    ("member_role_change", "变更成员角色"),
                    ("invitation_create", "创建邀请"),
                    ("invitation_accept", "接受邀请"),
                    ("invitation_cancel", "取消邀请"),
                    ("invitation_reject", "拒绝邀请"),
                    ("ownership_transfer", "转让所有权"),
                    ("permission_grant", "授予权限"),
                    ("permission_revoke", "撤销权限"),
                    ("resource_create", "创建资源"),
                    ("resource_update", "更新资源"),
                    ("resource_delete", "删除资源"),
                    ("resource_share", "共享资源"),
                    ("agent_security_update", "更新 Agent 安全配置"),
                    ("user_delete_cleanup", "用户删除跨库清理"),
                ],
                db_index=True,
                max_length=64,
                verbose_name="动作类型",
            ),
        ),
    ]
