# Generated by Django 4.2.7 on 2026-05-30 02:48

from django.db import migrations, models


def drop_soul_subtree(apps, schema_editor):
    """清理存量 ``Agent.agent_config`` 里的 ``soul`` 子树（Soul 概念整体移除）。

    runtime 已不再读 soul（service 层 ``_validate_and_merge_config`` 会 ``pop('soul')``，
    ``agent_config_v2`` 的 ``_SKIP_KEYS`` 也会在 v1→v2 normalize 时丢弃），存量 soul
    子树只是历史脏数据，这里一次性清净。幂等：无 soul 子树的行不写库。
    """
    Agent = apps.get_model("tabtinspace", "Agent")
    db_alias = schema_editor.connection.alias
    for agent in Agent.objects.using(db_alias).only("id", "agent_config").iterator():
        cfg = agent.agent_config
        if isinstance(cfg, dict) and "soul" in cfg:
            cfg.pop("soul", None)
            agent.agent_config = cfg
            agent.save(using=db_alias, update_fields=["agent_config"])


class Migration(migrations.Migration):

    dependencies = [
        ("tabtinspace", "0052_alter_spaceadminactionlog_action_type_and_more"),
    ]

    operations = [
        # 数据清理放删表前：清存量 agent_config.soul（与 SoulPreset 表无外键依赖，先后
        # 皆可，置顶表意清晰）。reverse=noop——soul 已废弃，无需也无法恢复。
        migrations.RunPython(drop_soul_subtree, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="SoulPreset",
        ),
        migrations.AlterField(
            model_name="agent",
            name="suggested_prompts",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="对话空状态展示的推荐问题，用户可覆写",
                verbose_name="推荐问题",
            ),
        ),
    ]
