# Generated by Django 4.2.7 on 2026-05-31 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tabtinspace", "0055_strip_retired_agent_config_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="persona_prompt",
        ),
    ]
