# Generated by Django 4.2.7 on 2026-06-04 17:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0056_remove_agent_persona_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='securecredential',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secure_credentials_device', to='tabtinspace.device', verbose_name='归属设备（仅本机用凭证）'),
        ),
        migrations.AlterField(
            model_name='securecredential',
            name='credential_type',
            field=models.CharField(choices=[('ssh_key', 'SSH 私钥'), ('ssh_password', 'SSH 密码'), ('api_key', 'API Key / Token')], max_length=50, verbose_name='凭据类型'),
        ),
        migrations.CreateModel(
            name='MCPConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='如：本地文件 MCP', max_length=200, verbose_name='连接名称')),
                ('scope', models.CharField(choices=[('local', '本地（跟设备）'), ('remote', '远程（跟团队）')], db_index=True, default='local', help_text='由 save() 按 device/workteam 归属自动归一，无需手动维护', max_length=20, verbose_name='作用域')),
                ('transport', models.CharField(choices=[('stdio', 'Stdio'), ('http', 'Streamable HTTP')], default='stdio', max_length=20, verbose_name='传输方式')),
                ('command', models.TextField(blank=True, default='', help_text='stdio：MCP server 可执行命令', verbose_name='启动命令')),
                ('args', models.JSONField(blank=True, default=list, help_text='stdio：命令行参数数组', verbose_name='启动参数')),
                ('cwd', models.TextField(blank=True, default='', help_text='stdio：进程工作目录', verbose_name='工作目录')),
                ('endpoint', models.URLField(blank=True, default='', help_text='http：Streamable HTTP url', verbose_name='服务地址')),
                ('config', models.JSONField(blank=True, default=dict, help_text='env / headers 的 key 名等非敏感配置；敏感值走 credential', verbose_name='非敏感配置')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('last_probe', models.JSONField(blank=True, default=dict, help_text='Electron 端 probe 回写的健康检查结果（后端只存不真连）', verbose_name='最近探针结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcp_connections', to='tabtinspace.securecredential', verbose_name='关联加密凭据')),
                ('device', models.ForeignKey(blank=True, help_text='对仗 RemoteServer.device：连接活在设备上，设备删除则连接一并级联删除', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcp_connections', to='tabtinspace.device', verbose_name='归属设备（scope=local）')),
                ('workteam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcp_connections', to='tabtinspace.workteam', verbose_name='归属工作团队（scope=remote，本期预留）')),
            ],
            options={
                'verbose_name': 'MCP 连接',
                'verbose_name_plural': 'MCP 连接',
                'db_table': 'tabtinspace_mcp_connection',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', 'enabled'], name='ctx_mcp_device_enabled_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='mcpconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('device__isnull', False)), fields=('device', 'name'), name='ctx_mcp_device_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='mcpconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('workteam__isnull', False)), fields=('workteam', 'name'), name='ctx_mcp_workteam_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='mcpconnection',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('device__isnull', False), ('workteam__isnull', True)), models.Q(('device__isnull', True), ('workteam__isnull', False)), _connector='OR'), name='ctx_mcp_owner_xor'),
        ),
    ]
