# Generated by Django 4.2.7 on 2026-06-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0057_securecredential_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workteam',
            name='agent_rules',
            field=models.TextField(blank=True, default='', help_text='对团队下所有 Agent 生效的团队级通用规则，运行时作为三层规则的团队基线层注入 system prompt。', verbose_name='团队 Agent 规则'),
        ),
    ]
