# Generated by Django 4.2.7 on 2026-06-06

from django.db import migrations


class Migration(migrations.Migration):
    """下线团队 prompt（团队 Agent 规则·团队基线层）。

    团队级一刀切 prompt 难以适配不同岗位、配不好反伤效果，岗位差异化改由 skill
    系统按需装载承担。分层规则降为两层（个人 + Agent）。删除 Workteam.agent_rules
    字段（dogfood 阶段，存量团队规则数据直接丢弃）。

    依赖单库改造的 0059（单 PG 基线 alter）之后，避免与其形成 migration 双 leaf。
    """

    dependencies = [
        ("tabtinspace", "0059_alter_agent_user_alter_collection_created_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workteam",
            name="agent_rules",
        ),
    ]
