# Generated by Django 4.2.7 on 2026-06-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabtinspace", "0060_remove_workteam_agent_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="workteam",
            name="status",
            field=models.CharField(
                choices=[("active", "正常"), ("deleting", "删除中")],
                db_index=True,
                default="active",
                max_length=20,
                verbose_name="生命周期状态",
            ),
        ),
    ]
