# Generated by Django 4.2.7 on 2026-06-20 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0062_agent_owner_user_private_agents'),
        ('tabtinspace', '0062_space_avatar_file_ref'),
    ]

    operations = [
    ]
