# Generated by Django 4.2.7 on 2026-06-23 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0064_workteammember_workteam_joined_index'),
        ('tabtinspace', '0067_rename_default_agent_spaces'),
    ]

    operations = [
    ]
