# Generated by Django 4.2.7 on 2026-06-26 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tabtinspace', '0070_restore_default_agent_onboarding_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_visited_at', models.DateTimeField(verbose_name='最近访问时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='首次访问时间')),
                ('context_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='tabtinspace.contextitem', verbose_name='资源条目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_accesses', to=settings.AUTH_USER_MODEL, verbose_name='访问用户')),
            ],
            options={
                'verbose_name': '资源访问记录',
                'verbose_name_plural': '资源访问记录',
                'db_table': 'tabtinspace_resource_access',
                'indexes': [models.Index(fields=['user', '-last_visited_at'], name='res_access_user_visited_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='resourceaccess',
            constraint=models.UniqueConstraint(fields=('user', 'context_item'), name='uniq_resource_access_user_item'),
        ),
    ]
