# Generated by Django 4.2.7 on 2026-06-30 08:57

import logging

from django.db import migrations, models

_logger = logging.getLogger(__name__)


def dedupe_conflicting_workspace_dirs(apps, schema_editor):
    """建唯一索引前消解存量重复，让本迁移在任何库（本地/test/生产）都能干净跑过。

    单根契约：同一 Team + 同一执行设备 + 同一标准化工作目录，只允许一个活跃
    Space。历史数据里可能存在多个 Agent 绑同一目录（约束加入前没有拦截），
    若不先收敛，``ctx_space_device_dir_unique`` 建索引会因重复键直接失败。

    收敛策略（保留信息、可恢复）：每个冲突组保留一个「胜者」，其余归档
    （``is_archived=True``）——归档态被唯一索引的 condition 排除，且数据不丢、
    可由用户从归档中恢复后改绑别的目录。胜者优先级：
    默认 Space > 最近活跃 > 最近更新 > 最早创建（稳定可复现）。

    幂等：clean DB 上没有冲突组即 no-op；本步骤跑过后再跑也不会再误伤
    （只在 count>1 的组里动手）。
    """
    Space = apps.get_model('tabtinspace', 'Space')

    active = (
        Space.objects.filter(
            type='bot',
            is_archived=False,
            trashed_at__isnull=True,
        )
        .exclude(normalized_working_dir='')
    )

    conflict_keys = (
        active.values('workteam_id', 'control_device_id', 'normalized_working_dir')
        .annotate(n=models.Count('id'))
        .filter(n__gt=1)
    )

    archived_total = 0
    for key in conflict_keys:
        members = list(
            active.filter(
                workteam_id=key['workteam_id'],
                control_device_id=key['control_device_id'],
                normalized_working_dir=key['normalized_working_dir'],
            ).order_by(
                '-is_default',
                models.F('last_activity_at').desc(nulls_last=True),
                '-updated_at',
                'created_at',
                'id',
            )
        )
        # 第 0 个是胜者，其余全部归档
        losers = members[1:]
        if not losers:
            continue
        loser_ids = [s.id for s in losers]
        archived = Space.objects.filter(id__in=loser_ids).update(is_archived=True)
        archived_total += archived
        _logger.warning(
            "[migration 0073] dedupe workspace dir conflict: workteam=%s device=%s dir=%r "
            "kept=%s archived=%s",
            key['workteam_id'],
            key['control_device_id'],
            key['normalized_working_dir'],
            members[0].id,
            loser_ids,
        )

    if archived_total:
        _logger.warning(
            "[migration 0073] dedupe complete: archived %s conflicting Space(s) before "
            "creating ctx_space_device_dir_unique",
            archived_total,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0072_space_execution_binding'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='space',
            unique_together=set(),
        ),
        migrations.RunPython(
            dedupe_conflicting_workspace_dirs,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='space',
            constraint=models.UniqueConstraint(condition=models.Q(('is_archived', False), ('trashed_at__isnull', True), ('type', 'bot'), models.Q(('normalized_working_dir', ''), _negated=True)), fields=('workteam', 'control_device', 'normalized_working_dir'), name='ctx_space_device_dir_unique'),
        ),
    ]
