# Generated by Django 4.2.7 on 2026-06-30 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0073_alter_space_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='space',
            name='ctx_one_active_bot_space_per_agent',
        ),
        migrations.RemoveConstraint(
            model_name='space',
            name='ctx_space_bot_requires_agent',
        ),
        migrations.AlterField(
            model_name='space',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spaces', to='tabtinspace.agent', verbose_name='兼容关联 Agent（可选）'),
        ),
    ]
