# Generated by Django 4.2.7 on 2026-07-03 10:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0077_team_space_execution_binding'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceActivityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('space_id', models.UUIDField(verbose_name='Space ID')),
                ('workteam_id', models.UUIDField(verbose_name='工作团队 ID')),
                ('event_type', models.CharField(choices=[('space_created', '创建团队 Space'), ('member_joined', '成员加入'), ('member_left', '成员退出'), ('member_role_changed', '成员角色变更'), ('asset_created', '新增资产'), ('asset_archived', '归档资产'), ('asset_restored', '恢复资产'), ('agent_run_started', 'Agent 任务开始'), ('agent_run_completed', 'Agent 任务完成'), ('agent_run_failed', 'Agent 任务失败'), ('settings_updated', '设置变更')], max_length=32, verbose_name='事件类型')),
                ('actor_user_id', models.CharField(blank=True, default='', max_length=64, verbose_name='操作人用户 ID')),
                ('actor_name', models.CharField(blank=True, default='', max_length=100, verbose_name='操作人展示名')),
                ('target_type', models.CharField(blank=True, default='', max_length=30, verbose_name='目标类型')),
                ('target_id', models.CharField(blank=True, default='', max_length=64, verbose_name='目标 ID')),
                ('target_name', models.CharField(blank=True, default='', max_length=255, verbose_name='目标名称')),
                ('metadata', models.JSONField(default=dict, verbose_name='附加数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'Space 动态事件',
                'verbose_name_plural': 'Space 动态事件',
                'db_table': 'tabtinspace_space_activity_event',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['space_id', 'created_at'], name='ctx_sae_space_time_idx')],
            },
        ),
    ]
