# Generated by Django 4.2.7 on 2026-07-06 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tabtinspace', '0082_backfill_team_space_tabdoc_assets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('avatar', models.CharField(blank=True, default='', max_length=500, verbose_name='头像文件引用')),
                ('color', models.CharField(blank=True, default='', max_length=20, verbose_name='标签颜色')),
                ('custom_rules', models.TextField(blank=True, default='', verbose_name='项目共享规则')),
                ('settings', models.JSONField(default=dict, verbose_name='项目协作配置')),
                ('status', models.CharField(choices=[('active', '进行中'), ('archived', '已归档'), ('trashed', '已删除')], default='active', max_length=20, verbose_name='状态')),
                ('is_archived', models.BooleanField(default=False, verbose_name='是否归档')),
                ('visibility', models.CharField(choices=[('private', '仅创建者'), ('shared', '已共享')], default='shared', help_text='Project 默认对团队成员共享；成员可见性仍要求 Workteam 成员 + ProjectMembership。', max_length=20, verbose_name='可见范围')),
                ('last_activity_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='最后活跃时间')),
                ('trashed_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='回收站时间')),
                ('trashed_by', models.UUIDField(blank=True, null=True, verbose_name='回收站操作人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('workteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='tabtinspace.workteam', verbose_name='所属工作团队')),
            ],
            options={
                'verbose_name': '协作项目',
                'verbose_name_plural': '协作项目',
                'db_table': 'tabtinspace_project',
                'ordering': ['-last_activity_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', '所有者'), ('admin', '管理员'), ('editor', '编辑者'), ('viewer', '查看者')], default='editor', max_length=20, verbose_name='角色')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tabtinspace.project', verbose_name='所属 Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL, verbose_name='成员用户')),
                ('workspace', models.ForeignKey(blank=True, help_text='成员在此 Project 里 Agent 落地执行的个人 Workspace；空表示尚未创建 / 选择。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_workspace_bindings', to='tabtinspace.space', verbose_name='成员执行 Workspace')),
            ],
            options={
                'verbose_name': 'Project 成员',
                'verbose_name_plural': 'Project 成员',
                'db_table': 'tabtinspace_project_membership',
                'indexes': [models.Index(fields=['project', 'role'], name='ctx_pm_project_role_idx'), models.Index(fields=['user', 'joined_at'], name='ctx_pm_user_joined_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='projectmembership',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='ctx_pm_project_user_unique'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['workteam', 'status'], name='ctx_proj_ws_status_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['workteam', 'is_archived'], name='ctx_proj_ws_archived_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['workteam', 'last_activity_at'], name='ctx_proj_ws_activity_idx'),
        ),
    ]
