# Generated by Django 4.2.7 on 2026-07-06 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0083_project_projectmembership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='room',
            field=models.ForeignKey(blank=True, help_text='承载本 Project 会话/频道/资产/动态的 Space；执行仍落到成员各自 Workspace。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_room_of', to='tabtinspace.space', verbose_name='底层协作房间（team_space Space）'),
        ),
    ]
