# Generated by Django 4.2.7 on 2026-07-06 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0084_project_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmembership',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectmembership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projectmembership',
            name='workspace',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectMembership',
        ),
    ]
