# Generated by Django 4.2.7 on 2026-07-06 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0085_remove_projectmembership_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='project',
            field=models.ForeignKey(blank=True, help_text='workspace 类型专用：记录该 Workspace 是哪个 team_space Project 的伴生执行现场。每个成员在一个 Project 下最多一个伴生 Workspace（由 ensure_project_workspace 幂等保证，因所有权落在 SpaceMembership/Agent 上而非本表直接字段，未加 DB 唯一约束）。team_space 类型该字段恒为空。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companion_workspaces', to='tabtinspace.space', verbose_name='伴生所属 Project'),
        ),
        migrations.AddIndex(
            model_name='space',
            index=models.Index(fields=['project'], name='ctx_space_project_idx'),
        ),
    ]
