# Generated by Django 4.2.7 on 2026-07-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0086_space_project_companion_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacemembership',
            name='invited_by',
            field=models.UUIDField(blank=True, help_text='pending 成员的邀请发起人；用于通知回执与审计。', null=True, verbose_name='邀请人用户 ID'),
        ),
        migrations.AddField(
            model_name='spacemembership',
            name='status',
            field=models.CharField(choices=[('active', '已生效'), ('pending', '待接受')], db_index=True, default='active', help_text='active=已生效；pending=已邀请待成员在 Electron 上显式接受。pending 成员 is_active=False，接受后转 active + is_active=True 并当场供给伴生 Workspace。', max_length=20, verbose_name='成员状态'),
        ),
        migrations.AddIndex(
            model_name='spacemembership',
            index=models.Index(fields=['user', 'status'], name='ctx_sm_user_status_idx'),
        ),
    ]
