# Generated by Django 4.2.7 on 2026-07-07 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users_auth', '0024_rename_users_auth__worktea_d77dd7_idx_users_auth__organiz_606ddd_idx_and_more'),
        ('tabtinspace', '0089_rename_workteam_to_organization'),
        # tracker.Tracker.organization 是引用本 app Organization 的唯一真 FK。
        # 必须让 tracker/0037 的 RenameField 在本迁移之前执行，否则
        # 「Workteam 已改名、tracker 字段未改」的中间态无法 render project state
        # （lazy reference 'tabtinspace.workteam' 解析失败）。
        ('tracker', '0037_rename_workteam_to_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['-updated_at'], 'verbose_name': '组织', 'verbose_name_plural': '组织'},
        ),
        migrations.AlterModelOptions(
            name='organizationactivity',
            options={'ordering': ['-created_at'], 'verbose_name': '组织活动', 'verbose_name_plural': '组织活动'},
        ),
        migrations.AlterModelOptions(
            name='organizationappinstall',
            options={'ordering': ['created_at'], 'verbose_name': 'Organization 应用安装', 'verbose_name_plural': 'Organization 应用安装'},
        ),
        migrations.AlterModelOptions(
            name='organizationcontrolpolicy',
            options={'verbose_name': 'Organization 控制策略', 'verbose_name_plural': 'Organization 控制策略'},
        ),
        migrations.AlterModelOptions(
            name='organizationinvitation',
            options={'ordering': ['-created_at'], 'verbose_name': '组织邀请', 'verbose_name_plural': '组织邀请'},
        ),
        migrations.AlterModelOptions(
            name='organizationmember',
            options={'verbose_name': '组织成员', 'verbose_name_plural': '组织成员'},
        ),
        # 0089 的 RenameField(mcpconnection.workteam→organization) 不会改写迁移状态里
        # Meta.constraints 的字段引用（Django RenameField 已知行为），导致旧状态中这两个
        # 约束仍指向 'workteam'，真正执行 RemoveConstraint 时 render from_state 会
        # FieldError。而 PG 侧约束定义已随列改名自动跟随，DB 无需任何变更——
        # 因此 Remove/Add 只做状态调和（state-only），数据库操作为空。
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='mcpconnection',
                    name='ctx_mcp_workteam_name_unique',
                ),
                migrations.RemoveConstraint(
                    model_name='mcpconnection',
                    name='ctx_mcp_owner_xor',
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='agent',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='tabtinspace.organization', verbose_name='所属组织'),
        ),
        migrations.AlterField(
            model_name='device',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='tabtinspace.organization', verbose_name='所属组织'),
        ),
        migrations.AlterField(
            model_name='deviceappinstallsnapshot',
            name='organization_id',
            field=models.UUIDField(db_index=True, help_text='冗余索引，加速 admin 按 organization 过滤', verbose_name='组织 ID'),
        ),
        migrations.AlterField(
            model_name='mcpconnection',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcp_connections', to='tabtinspace.organization', verbose_name='归属组织（scope=remote，本期预留）'),
        ),
        migrations.AlterField(
            model_name='mcpconnection',
            name='scope',
            field=models.CharField(choices=[('local', '本地（跟设备）'), ('remote', '远程（跟团队）')], db_index=True, default='local', help_text='由 save() 按 device/organization 归属自动归一，无需手动维护', max_length=20, verbose_name='作用域'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='是否为默认组织'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='member_count',
            field=models.IntegerField(default=0, help_text='由 signal 维护的非规范化计数，实际成员数以 OrganizationMember 查询为准。初始值 0，由 provision_organization_defaults 最终覆写为正确值。', verbose_name='成员数量'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, verbose_name='组织名称'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_organizations', to=settings.AUTH_USER_MODEL, verbose_name='所有者'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='settings',
            field=models.JSONField(default=dict, verbose_name='组织设置'),
        ),
        migrations.AlterField(
            model_name='organizationactivity',
            name='organization_id',
            field=models.UUIDField(db_index=True, verbose_name='组织 ID'),
        ),
        migrations.AlterField(
            model_name='organizationappinstall',
            name='installed_by',
            field=models.ForeignKey(blank=True, help_text='CORE_APPS 自动安装时为 Organization owner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installed_apps', to=settings.AUTH_USER_MODEL, verbose_name='安装人'),
        ),
        migrations.AlterField(
            model_name='organizationappinstall',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_installs', to='tabtinspace.organization', verbose_name='所属组织'),
        ),
        migrations.AlterField(
            model_name='organizationcontrolpolicy',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='control_policy', to='tabtinspace.organization', verbose_name='组织'),
        ),
        migrations.AlterField(
            model_name='organizationcontrolpolicy',
            name='updated_by_admin_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_organization_control_policies', to='users_auth.adminaccount', verbose_name='最近更新后台账号'),
        ),
        migrations.AlterField(
            model_name='organizationinvitation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tabtinspace.organization', verbose_name='组织'),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tabtinspace.organization', verbose_name='组织'),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='securecredential',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secure_credentials', to='tabtinspace.organization', verbose_name='所属组织'),
        ),
        migrations.AlterField(
            model_name='space',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='tabtinspace.organization', verbose_name='所属组织'),
        ),
        migrations.AlterField(
            model_name='spaceactivityevent',
            name='organization_id',
            field=models.UUIDField(verbose_name='组织 ID'),
        ),
        migrations.AlterField(
            model_name='spaceadminactionlog',
            name='action_type',
            field=models.CharField(choices=[('organization_create', '创建组织'), ('organization_update', '更新组织'), ('organization_delete', '删除组织'), ('space_create', '创建 Space'), ('space_update', '更新 Space'), ('space_archive', '归档 Space'), ('space_restore', '恢复 Space'), ('space_delete', '删除 Space'), ('member_add', '添加成员'), ('member_remove', '移除成员'), ('member_role_change', '变更成员角色'), ('invitation_create', '创建邀请'), ('invitation_accept', '接受邀请'), ('invitation_cancel', '取消邀请'), ('invitation_reject', '拒绝邀请'), ('ownership_transfer', '转让所有权'), ('permission_grant', '授予权限'), ('permission_revoke', '撤销权限'), ('resource_create', '创建资源'), ('resource_update', '更新资源'), ('resource_delete', '删除资源'), ('resource_share', '共享资源'), ('agent_security_update', '更新 Agent 安全配置'), ('agent_profile_update', '更新 Agent 资料'), ('agent_prompt_update', '更新 Agent 提示词'), ('agent_working_dir_update', '更新 Agent 运行目录'), ('agent_backend_update', '更新 Agent 后端配置'), ('agent_capability_update', '更新 Agent 能力配置'), ('user_delete_cleanup', '用户删除跨库清理')], db_index=True, max_length=64, verbose_name='动作类型'),
        ),
        migrations.AlterField(
            model_name='spaceadminactionlog',
            name='organization_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='组织 ID'),
        ),
        migrations.AlterField(
            model_name='spaceadminactionlog',
            name='target_type',
            field=models.CharField(choices=[('organization', '组织'), ('space', '协作空间'), ('agent', 'Agent'), ('member', '成员'), ('invitation', '邀请'), ('table', '表格'), ('document', '文档'), ('slide', '幻灯片'), ('permission', '权限'), ('user', '用户')], db_index=True, max_length=32, verbose_name='目标类型'),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddConstraint(
                    model_name='mcpconnection',
                    constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('organization', 'name'), name='ctx_mcp_workteam_name_unique'),
                ),
                migrations.AddConstraint(
                    model_name='mcpconnection',
                    constraint=models.CheckConstraint(check=models.Q(models.Q(('device__isnull', False), ('organization__isnull', True)), models.Q(('device__isnull', True), ('organization__isnull', False)), _connector='OR'), name='ctx_mcp_owner_xor'),
                ),
            ],
            database_operations=[],
        ),
    ]
