# Generated by Django 4.2.7 on 2026-07-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0091_strip_agent_yolo_gate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaceadminactionlog',
            name='action_type',
            field=models.CharField(choices=[('organization_create', '创建组织'), ('organization_update', '更新组织'), ('organization_delete', '删除组织'), ('space_create', '创建 Space'), ('space_update', '更新 Space'), ('space_archive', '归档 Space'), ('space_restore', '恢复 Space'), ('space_delete', '删除 Space'), ('member_add', '添加成员'), ('member_remove', '移除成员'), ('member_role_change', '变更成员角色'), ('invitation_create', '创建邀请'), ('invitation_accept', '接受邀请'), ('invitation_cancel', '取消邀请'), ('invitation_reject', '拒绝邀请'), ('ownership_transfer', '转让所有权'), ('permission_grant', '授予权限'), ('permission_revoke', '撤销权限'), ('resource_create', '创建资源'), ('resource_update', '更新资源'), ('resource_delete', '删除资源'), ('resource_share', '共享资源'), ('agent_security_update', '更新 Agent 安全配置'), ('agent_profile_update', '更新 Agent 资料'), ('agent_prompt_update', '更新 Agent 提示词'), ('agent_working_dir_update', '更新 Agent 运行目录'), ('agent_backend_update', '更新 Agent 后端配置'), ('agent_capability_update', '更新 Agent 能力配置'), ('user_delete_cleanup', '用户删除跨库清理'), ('organization_wallet_recharge', '调整组织 credits'), ('organization_quota_grant', '发放组织扩容权益'), ('organization_cash_wallet_recharge', '充值组织人民币钱包'), ('organization_cash_purchase_credit_package', '人民币钱包购买点券包'), ('organization_cash_purchase_addon_package', '人民币钱包购买扩容包')], db_index=True, max_length=64, verbose_name='动作类型'),
        ),
        migrations.AlterField(
            model_name='spaceadminactionlog',
            name='target_type',
            field=models.CharField(choices=[('organization', '组织'), ('space', '协作空间'), ('agent', 'Agent'), ('member', '成员'), ('invitation', '邀请'), ('table', '表格'), ('document', '文档'), ('slide', '幻灯片'), ('permission', '权限'), ('user', '用户'), ('entitlement', '权益')], db_index=True, max_length=32, verbose_name='目标类型'),
        ),
    ]
