# Generated by Django 4.2.7 on 2026-07-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0099_move_agent_to_agent_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='machine_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='客户端上报的 sha256(machineId+profile)[:32]；空表示未锚定的历史设备', max_length=64, verbose_name='机器锚定密钥'),
        ),
    ]
