# Generated by Django 4.2.7 on 2026-07-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0100_alter_device_machine_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacemembership',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='仅 Agent membership 使用；一个 Space / Project 最多一个生效主要 Agent。', verbose_name='是否主要负责 Agent'),
        ),
        migrations.AddConstraint(
            model_name='spacemembership',
            constraint=models.UniqueConstraint(condition=models.Q(('agent__isnull', False), ('is_active', True), ('is_primary', True)), fields=('space',), name='ctx_sm_space_primary_agent_unique'),
        ),
    ]
