# Generated by Django 4.2.7 on 2026-07-19 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def backfill_project_member_workspaces(apps, schema_editor):
    Space = apps.get_model('tabtinspace', 'Space')
    SpaceMembership = apps.get_model('tabtinspace', 'SpaceMembership')
    Workspace = apps.get_model('tabtinspace', 'Workspace')
    ProjectMemberWorkspace = apps.get_model('tabtinspace', 'ProjectMemberWorkspace')

    for shell in Space.objects.filter(
        type='workspace',
        project__type='team_space',
    ).exclude(project=None).iterator():
        workspace = Workspace.objects.filter(
            id=shell.id,
            organization_id=shell.organization_id,
        ).first()
        if workspace is None:
            continue
        user_id = (
            SpaceMembership.objects.filter(
                space_id=shell.id,
                user__isnull=False,
                role='owner',
                is_active=True,
            ).values_list('user_id', flat=True).first()
            or workspace.created_by_id
        )
        if user_id is None:
            continue
        ProjectMemberWorkspace.objects.get_or_create(
            project_id=shell.project_id,
            user_id=user_id,
            defaults={'workspace_id': workspace.id},
        )


def reverse_project_member_workspaces(apps, schema_editor):
    apps.get_model('tabtinspace', 'ProjectMemberWorkspace').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent', '0003_agent_goal_agent_settings_agent_template_id_and_more'),
        ('tabtinspace', '0101_spacemembership_is_primary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMemberWorkspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_workspaces', to='tabtinspace.space', verbose_name='所属 Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_workspaces', to=settings.AUTH_USER_MODEL, verbose_name='成员')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_memberships', to='tabtinspace.workspace', verbose_name='私有 Workspace')),
            ],
            options={
                'verbose_name': 'Project 成员 Workspace',
                'verbose_name_plural': 'Project 成员 Workspace',
                'db_table': 'tabtinspace_project_member_workspace',
            },
        ),
        migrations.RunPython(
            backfill_project_member_workspaces,
            reverse_project_member_workspaces,
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='任务标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='任务描述')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '紧急')], default='medium', max_length=16, verbose_name='优先级')),
                ('assignment_status', models.CharField(choices=[('pending', '待接单'), ('accepted', '已接单'), ('rejected', '已拒绝')], default='pending', max_length=16, verbose_name='接单状态')),
                ('work_status', models.CharField(choices=[('todo', '待执行'), ('in_progress', '执行中'), ('in_review', '待验收'), ('blocked', '受阻'), ('done', '已完成'), ('cancelled', '已取消')], default='todo', max_length=16, verbose_name='工作状态')),
                ('workspace_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Workspace 确认时间')),
                ('result_summary', models.TextField(blank=True, default='', verbose_name='验收结果摘要')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='乐观并发版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_project_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tasks', to='tabtinspace.space', verbose_name='所属 Project')),
                ('project_member_workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='tabtinspace.projectmemberworkspace', verbose_name='责任人确认的 Project Workspace')),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_project_tasks', to=settings.AUTH_USER_MODEL, verbose_name='责任人')),
                ('selected_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_tasks', to='agent.agent', verbose_name='执行 Agent')),
            ],
            options={
                'verbose_name': 'Project 任务',
                'verbose_name_plural': 'Project 任务',
                'db_table': 'tabtinspace_project_task',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='spaceactivityevent',
            name='event_type',
            field=models.CharField(choices=[('space_created', '创建团队 Space'), ('member_joined', '成员加入'), ('member_left', '成员退出'), ('member_role_changed', '成员角色变更'), ('asset_created', '新增资产'), ('asset_archived', '归档资产'), ('asset_restored', '恢复资产'), ('agent_run_started', 'Agent 任务开始'), ('agent_run_completed', 'Agent 任务完成'), ('agent_run_failed', 'Agent 任务失败'), ('settings_updated', '设置变更'), ('channel_created', '创建频道'), ('channel_renamed', '重命名频道'), ('channel_archived', '归档频道'), ('task_created', '创建任务'), ('task_assigned', '指派任务'), ('task_accepted', '接单'), ('task_rejected', '拒绝任务'), ('task_execution_configured', '确认任务执行配置'), ('task_review_requested', '任务待验收'), ('task_completed', '任务验收完成')], max_length=32, verbose_name='事件类型'),
        ),
        migrations.CreateModel(
            name='ProjectTaskEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_name', models.CharField(blank=True, default='', max_length=100, verbose_name='操作人快照')),
                ('event_type', models.CharField(db_index=True, max_length=40, verbose_name='事件类型')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='事件数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_task_events', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tabtinspace.projecttask', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': 'Project 任务事件',
                'verbose_name_plural': 'Project 任务事件',
                'db_table': 'tabtinspace_project_task_event',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['task', 'created_at'], name='ctx_pte_task_time_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['project', 'work_status'], name='ctx_pt_project_status_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['responsible_user', 'assignment_status'], name='ctx_pt_owner_assign_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['created_by', 'created_at'], name='ctx_pt_creator_time_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmemberworkspace',
            index=models.Index(fields=['user', 'project'], name='ctx_pmw_user_project_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmemberworkspace',
            index=models.Index(fields=['workspace'], name='ctx_pmw_workspace_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectmemberworkspace',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='ctx_pmw_project_user_unique'),
        ),
    ]
