# Generated by Django 4.2.7 on 2026-07-19 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0065_chatsession_is_paused'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent', '0003_agent_goal_agent_settings_agent_template_id_and_more'),
        ('tabtinspace', '0102_project_task_mvp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTaskRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', '等待执行'), ('running', '执行中'), ('completed', '执行完成'), ('failed', '执行失败'), ('cancelled', '已取消')], default='pending', max_length=16, verbose_name='执行状态')),
                ('binding_snapshot', models.JSONField(default=dict, verbose_name='执行绑定快照')),
                ('result_summary', models.TextField(blank=True, default='', verbose_name='执行结果摘要')),
                ('safe_failure_reason', models.TextField(blank=True, default='', verbose_name='脱敏失败原因')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_task_runs', to='agent.agent', verbose_name='Agent 快照')),
                ('chat_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_task_runs', to='conversation.chatsession', verbose_name='执行会话')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_task_runs', to='tabtinspace.device', verbose_name='Device 快照')),
                ('rerun_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reruns', to='tabtinspace.projecttaskrun', verbose_name='重跑来源')),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_task_runs', to=settings.AUTH_USER_MODEL, verbose_name='责任人快照')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='tabtinspace.projecttask', verbose_name='所属任务')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_task_runs', to='tabtinspace.workspace', verbose_name='Workspace 快照')),
            ],
            options={
                'verbose_name': 'Project 任务执行',
                'verbose_name_plural': 'Project 任务执行',
                'db_table': 'tabtinspace_project_task_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTaskDeliverable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('context_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_task_deliverable', to='tabtinspace.contextitem', verbose_name='Project 资产')),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_project_task_deliverables', to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='tabtinspace.projecttask', verbose_name='来源任务')),
                ('task_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliverables', to='tabtinspace.projecttaskrun', verbose_name='来源执行')),
            ],
            options={
                'verbose_name': 'Project 任务交付物',
                'verbose_name_plural': 'Project 任务交付物',
                'db_table': 'tabtinspace_project_task_deliverable',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='projecttaskrun',
            index=models.Index(fields=['task', 'created_at'], name='ctx_ptr_task_time_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttaskrun',
            index=models.Index(fields=['status', 'created_at'], name='ctx_ptr_status_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='projecttaskrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'running'])), fields=('task',), name='ctx_ptr_task_active_unique'),
        ),
    ]
