# Generated by Django 4.2.7 on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0103_project_task_run_mvp'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workspace',
            name='ctx_ws_device_home_unique',
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.UniqueConstraint(
                condition=models.Q(('kind', 'home')),
                fields=('organization', 'device'),
                name='ctx_ws_org_device_home_unique',
            ),
        ),
    ]
