# Generated by Django 4.2.7 on 2026-07-23 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0123_file_permission_6863'),
        ('tabtinspace', '0124_merge_6903_6846_provisioning'),
    ]

    operations = [
    ]
