# Generated by Django 4.2.7 on 2026-07-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0128_project_task_agent_time_index_7202'),
        ('tabtinspace', '0129_merge_contextitem_parent_and_workspace_description'),
    ]

    operations = [
    ]
