# Generated by Django 4.2.7 on 2026-08-01 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0135_mcpconnection_description'),
        ('tabtinspace', '0135_organization_first_team_claim'),
    ]

    operations = [
    ]
