# Generated by Django 4.2.7 on 2026-08-03 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0136_merge_20260801_1657'),
        ('tabtinspace', '0137_organizationinvitation_phone_invite'),
    ]

    operations = [
    ]
