# Generated by Django 4.2.7 on 2026-08-06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tabtinspace', '0138_merge_20260803_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpconnection',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                help_text='组织精选快照的创建者；旧数据与本地连接允许为空',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='shared_mcp_connections',
                to=settings.AUTH_USER_MODEL,
                verbose_name='分享者',
            ),
        ),
    ]
