# Generated by Django 4.2.7 on 2026-03-04 20:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='aliyun', max_length=50, verbose_name='服务提供商')),
                ('sign_name', models.CharField(max_length=100, verbose_name='短信签名')),
                ('region', models.CharField(default='cn-hangzhou', max_length=50, verbose_name='服务区域')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '短信服务配置',
                'verbose_name_plural': '短信服务配置',
                'db_table': 'services_sms_config',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmsTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_code', models.CharField(max_length=100, unique=True, verbose_name='模板代码')),
                ('template_name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('template_content', models.TextField(verbose_name='模板内容')),
                ('template_type', models.CharField(choices=[('verification', '验证码'), ('notification', '通知'), ('marketing', '营销'), ('other', '其他')], default='verification', max_length=20, verbose_name='模板类型')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('disabled', '已禁用')], default='pending', max_length=20, verbose_name='审核状态')),
                ('provider', models.CharField(default='aliyun', max_length=50, verbose_name='服务提供商')),
                ('required_params', models.JSONField(default=list, help_text='模板中需要的参数列表', verbose_name='必需参数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '短信模板',
                'verbose_name_plural': '短信模板',
                'db_table': 'services_sms_template',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['template_code'], name='services_sm_templat_0a8527_idx'), models.Index(fields=['template_type'], name='services_sm_templat_3cc559_idx'), models.Index(fields=['status'], name='services_sm_status_548d7a_idx')],
            },
        ),
        migrations.CreateModel(
            name='SmsStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, verbose_name='统计日期')),
                ('provider', models.CharField(db_index=True, max_length=50, verbose_name='服务提供商')),
                ('template_code', models.CharField(db_index=True, max_length=100, verbose_name='模板代码')),
                ('total_sent', models.PositiveIntegerField(default=0, verbose_name='发送总数')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='成功数量')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='失败数量')),
                ('delivered_count', models.PositiveIntegerField(default=0, verbose_name='送达数量')),
                ('total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='总费用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '短信统计',
                'verbose_name_plural': '短信统计',
                'db_table': 'services_sms_statistics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'provider'], name='services_sm_date_fe0377_idx'), models.Index(fields=['date', 'template_code'], name='services_sm_date_d55040_idx')],
                'unique_together': {('date', 'provider', 'template_code')},
            },
        ),
        migrations.CreateModel(
            name='SmsRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, max_length=20, verbose_name='手机号码')),
                ('template_code', models.CharField(db_index=True, max_length=100, verbose_name='模板代码')),
                ('template_params', models.JSONField(default=dict, verbose_name='模板参数')),
                ('sign_name', models.CharField(max_length=100, verbose_name='短信签名')),
                ('content', models.TextField(blank=True, verbose_name='短信内容')),
                ('status', models.CharField(choices=[('pending', '发送中'), ('success', '发送成功'), ('failed', '发送失败'), ('delivered', '已送达'), ('undelivered', '未送达')], db_index=True, default='pending', max_length=20, verbose_name='发送状态')),
                ('provider', models.CharField(default='aliyun', max_length=50, verbose_name='服务提供商')),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='消息ID')),
                ('request_id', models.CharField(blank=True, max_length=200, verbose_name='请求ID')),
                ('response_data', models.JSONField(default=dict, verbose_name='响应数据')),
                ('error_code', models.CharField(blank=True, max_length=100, verbose_name='错误代码')),
                ('error_message', models.TextField(blank=True, verbose_name='错误消息')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='送达时间')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='重试次数')),
                ('cost', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='费用')),
            ],
            options={
                'verbose_name': '短信发送记录',
                'verbose_name_plural': '短信发送记录',
                'db_table': 'services_sms_record',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'created_at'], name='services_sm_phone_n_e8699e_idx'), models.Index(fields=['template_code', 'created_at'], name='services_sm_templat_ba67ef_idx'), models.Index(fields=['status', 'created_at'], name='services_sm_status_b21860_idx'), models.Index(fields=['provider', 'created_at'], name='services_sm_provide_d59d69_idx')],
            },
        ),
    ]
