export const ADMIN_PERMISSION = {
  USER_LIST: 'user:list',
  USER_UPDATE_STATUS: 'user:update_status',
  DEVICE_VIEW: 'device:view',
  DEVICE_BLOCK: 'device:block',
  DEVICE_UNBLOCK: 'device:unblock',
  SESSION_VIEW: 'session:view',
  SESSION_REVOKE: 'session:revoke',
  INTENT_USER_LIST: 'intent_user:list',
  INVITE_CODE_LIST: 'invite_code:list',
  INVITE_CODE_DISABLE: 'invite_code:disable',
  ORGANIZATION_LIST: 'organization:list',
  ORGANIZATION_VIEW: 'organization:view',
  ORGANIZATION_CREATE: 'organization:create',
  ORGANIZATION_DISABLE: 'organization:disable',
  SPACE_LIST: 'space:list',
  WALLET_LIST: 'wallet:list',
  WALLET_VIEW: 'wallet:view',
  WALLET_ADJUST: 'wallet:adjust',
  WALLET_RECHARGE: 'wallet:recharge',
  WALLET_EXPORT: 'wallet:export',
  BILLING_DASHBOARD_VIEW: 'billing_dashboard:view',
  USAGE_EVENT_LIST: 'usage_event:list',
  BILLING_EVENT_LIST: 'billing_event:list',
  BILLING_EVENT_EXPORT: 'billing_event:export',
  BUDGET_POLICY_LIST: 'budget_policy:list',
  BUDGET_POLICY_UPDATE: 'budget_policy:update',
  PRICING_RULE_LIST: 'pricing_rule:list',
  PRICING_RULE_UPDATE: 'pricing_rule:update',
  PRODUCT_CONFIG_LIST: 'product_config:list',
  CREDIT_PACKAGE_UPDATE: 'credit_package:update',
  PLAN_LIST: 'plan:list',
  CREDIT_LEDGER_VIEW: 'credit_ledger:view',
  CREDIT_GRANT: 'credit:grant',
  CREDIT_DEDUCT: 'credit:deduct',
  CREDIT_REVERSE: 'credit:reverse',
  CREDIT_ADJUST: 'credit:adjust',
  COMPENSATION_CREATE: 'compensation:create',
  CREDIT_PACKAGE_LIST: 'credit_package:list',
  ADDON_PACKAGE_LIST: 'addon_package:list',
  ADDON_PACKAGE_UPDATE: 'addon_package:update',
  STORAGE_BILLING_LIST: 'storage_billing:list',
  INVOICE_LIST: 'invoice:list',
  RECONCILIATION_LIST: 'reconciliation:list',
  ANOMALY_ALERT_LIST: 'anomaly_alert:list',
  ANOMALY_ALERT_RESOLVE: 'anomaly_alert:resolve',
  COST_ANALYSIS_VIEW: 'cost_analysis:view',
  DISPUTE_LIST: 'dispute:list',
  PROVIDER_LIST: 'provider:list',
  MODEL_LIST: 'model:list',
  AI_SCENE_LIST: 'ai_scene:list',
  AI_PROMPT_LIST: 'ai_prompt:list',
  AI_EMBEDDING_LIST: 'ai_embedding:list',
  AI_MULTIMODAL_LIST: 'ai_multimodal:list',
  AI_OPS_VIEW: 'ai_ops:view',
  APP_INSTALL_LIST: 'app_install:list',
  APP_AUTHORIZATION_LIST: 'app_authorization:list',
  APP_AUTHORIZATION_UPDATE: 'app_authorization:update',
  CONNECT_LIST: 'connect:list',
  CONNECT_VIEW: 'connect:view',
  CONNECT_REVOKE: 'connect:revoke',
  CONNECT_BULK_REVOKE: 'connect:bulk_revoke',
  CLI_AUDIT_LIST: 'cli_audit:list',
  TOOL_LIST: 'tool:list',
  TOOL_AUDIT_LIST: 'tool_audit:list',
  SKILL_REVIEW_LIST: 'skill_review:list',
  AGENT_DEBUG_LIST: 'agent_debug:list',
  TRACE_VIEW: 'trace:view',
  INCIDENT_VIEW: 'incident:view',
  CLIENT_ERROR_LIST: 'client_error:list',
  DESKTOP_UPDATE_LIST: 'desktop_update:list',
  ANALYTICS_VIEW: 'analytics:view',
  ANALYTICS_MANAGE: 'analytics:manage',
  MONITOR_VIEW: 'monitor:view',
  CELERY_VIEW: 'celery:view',
  TRASH_LIST: 'trash:list',
  TRASH_RESTORE: 'trash:restore',
  TRASH_DELETE: 'trash:delete',
  TRASH_CLEANUP: 'trash:cleanup',
  ORGANIZATION_CLEANUP_LIST: 'organization_cleanup:list',
  ORGANIZATION_CLEANUP_RETRY: 'organization_cleanup:retry',
  HOST_DEBUG_VIEW: 'host_debug:view',
  TABLE_DELETE: 'table:delete',
  TABLE_RESTORE: 'table:restore',
  TABLE_REPAIR: 'table:repair',
  DOC_DELETE: 'doc:delete',
  DOC_RESTORE: 'doc:restore',
  DOC_PERMISSION_UPDATE: 'doc:permission_update',
  SLIDE_DELETE: 'slide:delete',
  SLIDE_RESTORE: 'slide:restore',
  ASSET_DELETE: 'asset:delete',
  ASSET_REPAIR: 'asset:repair',
  SHARE_LIST: 'share:list',
  SHARE_REVOKE: 'share:revoke',
  MAIL_UPDATE_STATUS: 'mail:update_status',
  AUDIT_LOG_LIST: 'audit_log:list',
  ADMIN_ACCOUNT_LIST: 'admin_account:list',
  ADMIN_ACCOUNT_VIEW: 'admin_account:view',
  ADMIN_ACCOUNT_CREATE: 'admin_account:create',
  ADMIN_ACCOUNT_UPDATE: 'admin_account:update',
  ADMIN_ACCOUNT_DISABLE: 'admin_account:disable',
  ADMIN_ACCOUNT_ASSIGN_ROLE: 'admin_account:assign_role',
  ADMIN_ROLE_LIST: 'admin_role:list',
  ADMIN_ROLE_CREATE: 'admin_role:create',
  ADMIN_ROLE_UPDATE: 'admin_role:update',
  ADMIN_ROLE_DELETE: 'admin_role:delete',
  ADMIN_PERMISSION_LIST: 'admin_permission:list',
  SENSITIVE_ACTION_LIST: 'sensitive_action:list',
  ADMIN_LOGIN_LOG_LIST: 'admin_login_log:list',
  PLATFORM_CONFIG_LIST: 'platform_config:list',
  PLATFORM_CONFIG_UPDATE: 'platform_config:update',
  BILLING_RUNTIME_CONFIG_VIEW: 'billing_runtime_config:view',
  PROVIDER_CREDIT_VIEW: 'provider_credit:view',
  PROVIDER_CREDIT_OPERATE: 'provider_credit:operate',
  PROVIDER_CREDIT_ADMIN: 'provider_credit:admin',
  PROVIDER_UPDATE: 'provider:update',
  PROVIDER_DELETE: 'provider:delete',
  PROVIDER_KEY_DELETE: 'provider_key:delete',
  SEARCH_PROVIDER_DELETE: 'search_provider:delete',
} as const

export type AdminPermissionCode = (typeof ADMIN_PERMISSION)[keyof typeof ADMIN_PERMISSION]

export function hasAdminPermission(
  permissions: string[] | null,
  required?: string | string[]
): boolean {
  if (!required) return true
  if (permissions === null) return false
  if (permissions.includes('*')) return true

  const requiredPermissions = Array.isArray(required) ? required : [required]
  return requiredPermissions.some((permission) => permissions.includes(permission))
}
