# Generated by Django 4.2.7 on 2026-03-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TTSVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, default='bytedance', max_length=50)),
                ('voice_type', models.CharField(help_text='音色 ID，如 zh_female_vv_uranus_bigtts', max_length=200, unique=True)),
                ('name', models.CharField(help_text='音色显示名称', max_length=100)),
                ('language', models.CharField(default='zh', help_text='支持语种，逗号分隔，如 zh,en,ja', max_length=100)),
                ('category', models.CharField(db_index=True, default='通用场景', help_text='场景分类：通用场景、角色扮演、视频配音 等', max_length=50)),
                ('model_version', models.CharField(default='1.0', help_text='模型版本: 1.0 / 2.0', max_length=20)),
                ('emotions', models.JSONField(blank=True, default=list, help_text='支持的情感列表，如 ["happy","sad","angry"]')),
                ('supports_mix', models.BooleanField(default=True, help_text='是否支持混音')),
                ('supports_bidirectional', models.BooleanField(default=True, help_text='是否支持双向流式接口')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('extra', models.JSONField(blank=True, default=dict, help_text='扩展字段（上线业务方、特殊能力等）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TTS Voice',
                'verbose_name_plural': 'TTS Voices',
                'db_table': 'speech_tts_voice',
                'ordering': ['category', 'name'],
            },
        ),
    ]
