# Generated by Django 4.2.7 on 2026-08-12 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('llm', '0059_llm_usage_invocation_attempt_settlement'),
        ('tabtinspace', '0141_organization_member_identity_snapshot'),
        ('agent_memory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceMemorySettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('personal', 'Personal'), ('organization', 'Organization')], max_length=20)),
                ('auto_memory_enabled', models.BooleanField(default=False, help_text='新 Workspace 默认关闭；存量兼容由独立数据迁移显式回填开启。', verbose_name='自动记忆增强')),
                ('memory_model_mode', models.CharField(choices=[('official_default', 'Official Default'), ('explicit_model', 'Explicit Model')], default='official_default', max_length=24, verbose_name='记忆模型模式')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workspace_memory_settings', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('memory_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workspace_memory_settings', to='llm.llmmodel', verbose_name='精确记忆模型')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memory_settings', to='tabtinspace.organization', verbose_name='Organization Workspace 所属组织')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_workspace_memory_settings', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_workspace_memory_settings', to=settings.AUTH_USER_MODEL, verbose_name='Personal Workspace 所属用户')),
            ],
            options={
                'verbose_name': 'Workspace Memory Settings',
                'verbose_name_plural': 'Workspace Memory Settings',
                'db_table': 'agent_memory_workspace_settings',
            },
        ),
        migrations.AddConstraint(
            model_name='workspacememorysettings',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('organization__isnull', True), ('scope', 'personal'), ('user__isnull', False)), models.Q(('organization__isnull', False), ('scope', 'organization'), ('user__isnull', True)), _connector='OR'), name='wm_settings_owner_scope_xor'),
        ),
        migrations.AddConstraint(
            model_name='workspacememorysettings',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('memory_model__isnull', True), ('memory_model_mode', 'official_default')), models.Q(('memory_model__isnull', False), ('memory_model_mode', 'explicit_model')), _connector='OR'), name='wm_settings_model_mode_shape'),
        ),
        migrations.AddConstraint(
            model_name='workspacememorysettings',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'personal')), fields=('user',), name='wm_settings_personal_user_uniq'),
        ),
        migrations.AddConstraint(
            model_name='workspacememorysettings',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'organization')), fields=('organization',), name='wm_settings_organization_uniq'),
        ),
    ]
