# Generated by Django 4.2.7 on 2026-03-04 20:27

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(help_text='API 调用时使用的模型标识', max_length=100, verbose_name='模型名称')),
                ('display_name', models.CharField(max_length=100, verbose_name='显示名称')),
                ('description', models.TextField(blank=True, verbose_name='模型描述')),
                ('task_type', models.CharField(choices=[('text2image', '文生图'), ('image2image', '图生图'), ('image_edit', '图像编辑'), ('text2video', '文生视频'), ('image2video', '图生视频'), ('video_edit', '视频编辑')], max_length=30, verbose_name='任务类型')),
                ('supported_sizes', models.JSONField(blank=True, default=list, help_text='如 ["1024*1024", "1280*720"]', verbose_name='支持的分辨率')),
                ('supported_durations', models.JSONField(blank=True, default=list, help_text='视频模型专用，如 [5, 10]', verbose_name='支持的时长(秒)')),
                ('max_prompt_length', models.IntegerField(default=500, verbose_name='最大提示词长度')),
                ('supports_negative_prompt', models.BooleanField(default=False, verbose_name='支持反向提示词')),
                ('supports_prompt_extend', models.BooleanField(default=True, verbose_name='支持提示词智能改写')),
                ('supports_audio', models.BooleanField(default=False, verbose_name='支持音频输入')),
                ('supports_multi_shot', models.BooleanField(default=False, verbose_name='支持多镜头叙事')),
                ('billing_type', models.CharField(choices=[('image_count', '按图片数量'), ('video_seconds', '按视频秒数'), ('resolution_seconds', '按分辨率×秒数'), ('request', '按请求次数')], default='image_count', max_length=30, verbose_name='计费类型')),
                ('price_per_unit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, verbose_name='单价')),
                ('price_unit', models.CharField(blank=True, default='', help_text='如 元/张, 元/秒', max_length=50, verbose_name='计费单位')),
                ('free_quota', models.IntegerField(default=0, verbose_name='免费额度')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '媒体生成模型',
                'verbose_name_plural': '媒体生成模型',
                'db_table': 'services_media_model',
                'ordering': ['task_type', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('dashscope', '阿里云百炼 DashScope')], max_length=50, verbose_name='提供商名称')),
                ('provider_key', models.CharField(blank=True, default='', help_text='同一提供商的不同渠道标识', max_length=100, verbose_name='渠道标识')),
                ('display_name', models.CharField(max_length=100, verbose_name='显示名称')),
                ('base_url', models.URLField(verbose_name='API基础URL')),
                ('api_key', models.CharField(max_length=500, verbose_name='API密钥')),
                ('user_id', models.CharField(blank=True, max_length=36, null=True, verbose_name='用户ID')),
                ('scope', models.CharField(choices=[('global', '全局'), ('workspace', '工作空间'), ('user', '个人')], default='global', max_length=20, verbose_name='配置范围')),
                ('workspace_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='工作空间ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级')),
                ('rate_limit', models.IntegerField(default=30, verbose_name='每分钟请求限制')),
                ('runtime_status', models.CharField(choices=[('unknown', '未知'), ('healthy', '健康'), ('degraded', '降级'), ('unhealthy', '异常')], default='unknown', max_length=20, verbose_name='运行状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '媒体生成提供商',
                'verbose_name_plural': '媒体生成提供商',
                'db_table': 'services_media_provider',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('text2image', '文生图'), ('image2image', '图生图'), ('image_edit', '图像编辑'), ('text2video', '文生视频'), ('image2video', '图生视频'), ('video_edit', '视频编辑')], max_length=30, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('pending', '排队中'), ('running', '处理中'), ('succeeded', '成功'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='任务状态')),
                ('user_id', models.CharField(max_length=36, verbose_name='用户ID')),
                ('workspace_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='工作空间ID')),
                ('provider_task_id', models.CharField(blank=True, db_index=True, default='', max_length=200, verbose_name='Provider任务ID')),
                ('prompt', models.TextField(verbose_name='提示词')),
                ('negative_prompt', models.TextField(blank=True, default='', verbose_name='反向提示词')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='分辨率、时长、种子等', verbose_name='生成参数')),
                ('input_resources', models.JSONField(blank=True, default=dict, help_text='图片/音频 URL', verbose_name='输入资源')),
                ('result_urls', models.JSONField(blank=True, default=list, help_text='Provider 返回的临时 URL（24h有效）', verbose_name='原始结果URL')),
                ('stored_urls', models.JSONField(blank=True, default=list, help_text='转存到 OSS 后的永久 URL', verbose_name='永久存储URL')),
                ('result_metadata', models.JSONField(blank=True, default=dict, help_text='如 actual_prompt、task_metrics 等', verbose_name='结果元数据')),
                ('cost_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, verbose_name='费用')),
                ('cost_unit', models.CharField(blank=True, default='', max_length=30, verbose_name='计费单位')),
                ('error_code', models.CharField(blank=True, default='', max_length=50, verbose_name='错误码')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('poll_count', models.IntegerField(default=0, verbose_name='轮询次数')),
                ('next_poll_at', models.DateTimeField(blank=True, null=True, verbose_name='下次轮询时间')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_generation.mediamodel', verbose_name='使用模型')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_generation.mediaprovider', verbose_name='服务提供商')),
            ],
            options={
                'verbose_name': '媒体生成任务',
                'verbose_name_plural': '媒体生成任务',
                'db_table': 'services_media_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mediaprovider',
            index=models.Index(fields=['name', 'is_active'], name='mg_provider_name_active_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaprovider',
            index=models.Index(fields=['scope', 'is_active'], name='mg_provider_scope_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mediaprovider',
            unique_together={('scope', 'workspace_id', 'user_id', 'provider_key')},
        ),
        migrations.AddField(
            model_name='mediamodel',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_generation.mediaprovider', verbose_name='服务提供商'),
        ),
        migrations.AddIndex(
            model_name='mediatask',
            index=models.Index(fields=['user_id', '-created_at'], name='mg_task_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='mediatask',
            index=models.Index(fields=['status', 'next_poll_at'], name='mg_task_poll_idx'),
        ),
        migrations.AddIndex(
            model_name='mediatask',
            index=models.Index(fields=['provider_task_id'], name='mg_task_provider_id_idx'),
        ),
        migrations.AddIndex(
            model_name='mediatask',
            index=models.Index(fields=['workspace_id', '-created_at'], name='mg_task_ws_created_idx'),
        ),
        migrations.AddIndex(
            model_name='mediamodel',
            index=models.Index(fields=['task_type', 'is_active'], name='mg_model_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='mediamodel',
            index=models.Index(fields=['model_name'], name='mg_model_name_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mediamodel',
            unique_together={('provider', 'model_name')},
        ),
    ]
