# Generated by Django 4.2.7 on 2026-03-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_generation', '0002_workspace_to_workteam_rename'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mediatask',
            name='mg_task_ws_created_idx',
        ),
        migrations.AlterField(
            model_name='mediaprovider',
            name='scope',
            field=models.CharField(choices=[('global', '全局'), ('workspace', '工作团队'), ('user', '个人')], default='global', max_length=20, verbose_name='配置范围'),
        ),
        migrations.AlterField(
            model_name='mediaprovider',
            name='workteam_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='工作团队ID'),
        ),
        migrations.AlterField(
            model_name='mediatask',
            name='workteam_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='工作团队ID'),
        ),
        migrations.AddIndex(
            model_name='mediatask',
            index=models.Index(fields=['workteam_id', '-created_at'], name='mg_task_ws_created_idx'),
        ),
    ]
