# Generated by Django 4.2.7 on 2026-03-27 00:39
"""scope 枚举值 'workspace' → 'workteam'"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_generation', '0003_remove_mediatask_mg_task_ws_created_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaprovider',
            name='scope',
            field=models.CharField(choices=[('global', '全局'), ('workteam', '工作团队'), ('user', '个人')], default='global', max_length=20, verbose_name='配置范围'),
        ),
        migrations.RunSQL(
            sql="UPDATE services_media_provider SET scope = 'workteam' WHERE scope = 'workspace';",
            reverse_sql="UPDATE services_media_provider SET scope = 'workspace' WHERE scope = 'workteam';",
        ),
    ]
