# Generated by Django 4.2.7 on 2026-04-01 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_generation', '0004_scope_workspace_to_workteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaprovider',
            name='name',
            field=models.CharField(choices=[('dashscope', '阿里云百炼 DashScope'), ('fal', 'fal.ai'), ('replicate', 'Replicate')], max_length=50, verbose_name='提供商名称'),
        ),
    ]
