# Generated by Django 4.2.7 on 2026-07-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_generation', '0006_rename_workteam_to_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaprovider',
            name='organization_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='mediaprovider',
            name='scope',
            field=models.CharField(choices=[('global', '全局'), ('organization', '组织'), ('user', '个人')], default='global', max_length=20, verbose_name='配置范围'),
        ),
        migrations.AlterField(
            model_name='mediatask',
            name='organization_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='组织ID'),
        ),
    ]
