# Generated by Django 4.2.7 on 2026-03-04 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracker', '0001_initial'),
        ('tabtinspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledjob',
            name='agent_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_jobs', to='tabtinspace.agentspace', verbose_name='所属智能体空间'),
        ),
    ]
