# Generated by Django 4.2.7 on 2026-03-04 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracker', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tabtinspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledjob',
            name='created_by',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scheduled_jobs', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='scheduledjob',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_scheduled_jobs', to=settings.AUTH_USER_MODEL, verbose_name='最后修改者'),
        ),
        migrations.AddField(
            model_name='scheduledjob',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_jobs', to='tabtinspace.workspace', verbose_name='所属工作空间'),
        ),
        migrations.AddField(
            model_name='goalstep',
            name='delegate_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tabtinspace.agentspace', verbose_name='委托执行空间'),
        ),
        migrations.AddField(
            model_name='goalstep',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='tracker.goal', verbose_name='所属目标'),
        ),
        migrations.AddField(
            model_name='goalstep',
            name='restart_from_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restart_targets', to='tracker.goalstep', verbose_name='回环目标步骤'),
        ),
        migrations.AddField(
            model_name='goalrun',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='tracker.goal', verbose_name='所属目标'),
        ),
        migrations.AddField(
            model_name='goal',
            name='agent_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='tabtinspace.agentspace', verbose_name='所属智能体空间'),
        ),
        migrations.AddField(
            model_name='goal',
            name='created_by',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_goals', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='goal',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='tabtinspace.workspace', verbose_name='所属工作空间'),
        ),
        migrations.AddIndex(
            model_name='steprun',
            index=models.Index(fields=['goal_run', 'status'], name='step_run_goal_ru_c69049_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledjobrun',
            index=models.Index(fields=['job', 'created_at'], name='scheduler_j_job_id_17405f_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledjobrun',
            index=models.Index(fields=['request_id'], name='scheduler_j_request_7ca324_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledjobrun',
            index=models.Index(fields=['status'], name='scheduler_j_status_60496b_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledjob',
            index=models.Index(fields=['workspace', 'is_active', 'is_paused'], name='scheduler_j_workspa_5a4dd5_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledjob',
            index=models.Index(fields=['status'], name='scheduler_j_status_69fd68_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledjob',
            index=models.Index(fields=['next_run_at'], name='scheduler_j_next_ru_084f74_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledjob',
            index=models.Index(fields=['job_type'], name='scheduler_j_job_typ_504884_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledjob',
            index=models.Index(fields=['resource_type', 'resource_id'], name='scheduler_j_resourc_344407_idx'),
        ),
        migrations.AddConstraint(
            model_name='scheduledjob',
            constraint=models.UniqueConstraint(fields=('resource_type', 'resource_id'), name='scheduler_job_resource_unique'),
        ),
        migrations.AddIndex(
            model_name='goalrun',
            index=models.Index(fields=['goal', 'created_at'], name='goal_run_goal_id_7a986f_idx'),
        ),
        migrations.AddIndex(
            model_name='goalrun',
            index=models.Index(fields=['status'], name='goal_run_status_cefcaf_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['workspace', 'status'], name='goal_workspa_65cf30_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['agent_space'], name='goal_agent_s_f55a97_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['next_run_at'], name='goal_next_ru_0f94a4_idx'),
        ),
    ]
