# Generated by Django 4.2.7 on 2026-03-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalstep',
            name='capability',
            field=models.CharField(choices=[('agent', '通用 Agent'), ('browser', 'Browser / 采集'), ('table', 'TabData'), ('docs', 'TabDoc'), ('slide', 'TabSlide'), ('code', 'TabCode'), ('notification', '通知'), ('group_chat', '多 Agent 讨论')], default='agent', max_length=32, verbose_name='能力类型'),
        ),
    ]
