# Generated by Django 4.2.7 on 2026-03-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_goalstep_capability'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='project_mode',
            field=models.BooleanField(default=False, help_text='启用后自动生成计划概览、步骤质量校验、完成后生成项目报告 TabDoc', verbose_name='制片人模式'),
        ),
    ]
