# Generated by Django 4.2.7 on 2026-03-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_add_project_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalstep',
            name='model_preference',
            field=models.CharField(blank=True, default='', help_text='步骤级模型策略：fast(快速低成本) / default(系统默认) / powerful(高质量)。为空时由 ExecutionProfile 决定。', max_length=16, verbose_name='模型偏好'),
        ),
        migrations.AddField(
            model_name='steprun',
            name='cost_usd',
            field=models.FloatField(default=0.0, help_text='本步骤的 LLM 调用成本估算（美元）', verbose_name='成本(USD)'),
        ),
        migrations.AddField(
            model_name='steprun',
            name='model_used',
            field=models.CharField(blank=True, default='', help_text='记录步骤实际使用的 LLM 模型标识', max_length=200, verbose_name='实际使用模型'),
        ),
        migrations.AddField(
            model_name='steprun',
            name='tokens_used',
            field=models.PositiveIntegerField(default=0, help_text='本步骤消耗的 token 总数（从 ChatSession 或外部 Agent 事件汇总）', verbose_name='Token 用量'),
        ),
    ]
