# Generated by Django 4.2.7 on 2026-03-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_goalstep_model_preference_steprun_cost_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalstep',
            name='model_preference',
            field=models.CharField(blank=True, choices=[('', '自动'), ('fast', '快速低成本'), ('default', '系统默认'), ('powerful', '高质量')], default='', help_text='步骤级模型策略：fast(快速低成本) / default(系统默认) / powerful(高质量)。为空时由 ExecutionProfile 决定。', max_length=16, verbose_name='模型偏好'),
        ),
    ]
