# Generated by Django 4.2.7 on 2026-03-08 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0007_alter_space_options_alter_spaceappsettings_options_and_more'),
        ('tracker', '0009_rename_agent_space_to_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='space',
            field=models.ForeignKey(db_column='agent_space_id', on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='tabtinspace.space', verbose_name='所属智能体空间'),
        ),
        migrations.AlterField(
            model_name='scheduledjob',
            name='space',
            field=models.ForeignKey(blank=True, db_column='agent_space_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_jobs', to='tabtinspace.space', verbose_name='所属智能体空间'),
        ),
    ]
