# Generated by Django 4.2.7 on 2026-03-08 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0008_alter_contextitem_space_and_more'),
        ('tracker', '0010_alter_goal_space_alter_scheduledjob_space'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='goal',
            new_name='goal_space_i_30c3d7_idx',
            old_name='goal_agent_s_f55a97_idx',
        ),
        migrations.AlterField(
            model_name='goal',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='tabtinspace.space', verbose_name='所属空间'),
        ),
        migrations.AlterField(
            model_name='scheduledjob',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_jobs', to='tabtinspace.space', verbose_name='所属空间'),
        ),
    ]
