# Generated by Django 4.2.7 on 2026-03-19 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0017_alter_workteam_options_and_more'),
        ('tracker', '0012_workspace_to_workteam_rename'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='goal',
            name='goal_workspa_65cf30_idx',
        ),
        migrations.RemoveIndex(
            model_name='scheduledjob',
            name='scheduler_j_workspa_5a4dd5_idx',
        ),
        migrations.AlterField(
            model_name='goal',
            name='workteam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='tabtinspace.workteam', verbose_name='所属工作团队'),
        ),
        migrations.AlterField(
            model_name='goalrun',
            name='status',
            field=models.CharField(choices=[('pending', '等待执行'), ('running', '执行中'), ('waiting_checkpoint', '等待检查点'), ('completed', '已完成'), ('partial_failed', '部分失败'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=24, verbose_name='执行状态'),
        ),
        migrations.AlterField(
            model_name='scheduledjob',
            name='job_type',
            field=models.CharField(choices=[('agent', 'Agent 任务'), ('skill_field', 'Skill 字段定时执行'), ('table_automation', '表格自动化')], max_length=32, verbose_name='任务类型'),
        ),
        migrations.AlterField(
            model_name='scheduledjob',
            name='workteam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_jobs', to='tabtinspace.workteam', verbose_name='所属工作团队'),
        ),
        migrations.AlterField(
            model_name='steprun',
            name='status',
            field=models.CharField(choices=[('waiting', '等待依赖'), ('ready', '就绪'), ('running', '执行中'), ('done', '已完成'), ('failed', '失败'), ('skipped', '已跳过'), ('cancelled', '已取消'), ('checkpoint', '检查点暂停')], default='waiting', max_length=24, verbose_name='执行状态'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['workteam', 'status'], name='goal_worktea_8f1179_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledjob',
            index=models.Index(fields=['workteam', 'is_active', 'is_paused'], name='scheduler_j_worktea_96e100_idx'),
        ),
    ]
