# Generated by Django 4.2.7 on 2026-03-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_remove_goal_goal_workspa_65cf30_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='skill_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='指向要执行的 Skill（skill_key）。空值表示旧版多步骤 Goal 或纯 Agent 触发。', max_length=128, verbose_name='关联 Skill'),
        ),
        migrations.AddField(
            model_name='goalrun',
            name='progress_message',
            field=models.CharField(blank=True, default='', help_text='SDK 上报的当前阶段描述，如「正在分析数据…」。', max_length=500, verbose_name='进度描述'),
        ),
        migrations.AddField(
            model_name='goalrun',
            name='progress_pct',
            field=models.PositiveSmallIntegerField(default=0, help_text='SDK 上报的执行进度（0-100）。V2 简化后替代 step 级别进度。', verbose_name='进度百分比'),
        ),
    ]
