# Generated by Django 4.2.7 on 2026-03-30 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0026_bot_space_requires_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0014_goal_v2_skill_key_and_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='event_type',
            field=models.CharField(choices=[('agent_task', 'Agent 自动化任务'), ('event', '日程事件')], default='agent_task', help_text='agent_task: 有执行链路的自动化任务；event: 纯日程时间标记。', max_length=20, verbose_name='事件类型'),
        ),
        migrations.CreateModel(
            name='GoalReminderDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurrence_key', models.CharField(help_text='goal_id + 实例开始时间 UTC ISO，用于重复事件去重。', max_length=100, verbose_name='实例标识')),
                ('reminder_offset_minutes', models.IntegerField(verbose_name='提醒偏移(分钟)')),
                ('channel', models.CharField(max_length=20, verbose_name='发送渠道')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_deliveries', to='tracker.goal', verbose_name='关联事件')),
                ('recipient_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_deliveries', to='tabtinspace.agent', verbose_name='接收 Agent')),
                ('recipient_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='接收用户')),
            ],
            options={
                'verbose_name': '提醒发送记录',
                'verbose_name_plural': '提醒发送记录',
                'db_table': 'scheduler_goal_reminder_delivery',
            },
        ),
        migrations.CreateModel(
            name='GoalAttendee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('organizer', '组织者'), ('attendee', '参与者')], default='attendee', max_length=16, verbose_name='角色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda_attendances', to='tabtinspace.agent', verbose_name='Agent 参与者')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='tracker.goal', verbose_name='关联事件')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda_attendances', to=settings.AUTH_USER_MODEL, verbose_name='用户参与者')),
            ],
            options={
                'verbose_name': '事件参与者',
                'verbose_name_plural': '事件参与者',
                'db_table': 'scheduler_goal_attendee',
            },
        ),
        migrations.CreateModel(
            name='GoalAgendaMeta',
            fields=[
                ('goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='agenda_meta', serialize=False, to='tracker.goal', verbose_name='关联事件')),
                ('start_at', models.DateTimeField(db_index=True, verbose_name='开始时间')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('all_day', models.BooleanField(default=False, verbose_name='全天事件')),
                ('timezone', models.CharField(blank=True, default='', max_length=50, verbose_name='展示时区')),
                ('recurrence_rule', models.TextField(blank=True, default='', help_text='RFC 5545 RRULE。MVP 仅支持 DAILY/WEEKLY + INTERVAL + BYDAY + UNTIL/COUNT。', verbose_name='重复规则')),
                ('recurrence_exceptions', models.JSONField(default=list, help_text='EXDATE 列表，ISO 格式字符串。', verbose_name='排除日期列表')),
                ('reminders', models.JSONField(default=list, help_text='[{"minutes": 15, "channel": "push"}]', verbose_name='提醒配置')),
            ],
            options={
                'verbose_name': '日程元数据',
                'verbose_name_plural': '日程元数据',
                'db_table': 'scheduler_goal_agenda_meta',
                'indexes': [models.Index(fields=['start_at'], name='scheduler_g_start_a_3d4fbe_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='goalreminderdelivery',
            constraint=models.UniqueConstraint(condition=models.Q(('recipient_user__isnull', False)), fields=('goal', 'occurrence_key', 'reminder_offset_minutes', 'channel', 'recipient_user'), name='reminder_delivery_unique_user'),
        ),
        migrations.AddConstraint(
            model_name='goalreminderdelivery',
            constraint=models.UniqueConstraint(condition=models.Q(('recipient_agent__isnull', False)), fields=('goal', 'occurrence_key', 'reminder_offset_minutes', 'channel', 'recipient_agent'), name='reminder_delivery_unique_agent'),
        ),
        migrations.AddConstraint(
            model_name='goalattendee',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('agent__isnull', True), ('user__isnull', False)), models.Q(('agent__isnull', False), ('user__isnull', True)), _connector='OR'), name='attendee_one_identity'),
        ),
        migrations.AddConstraint(
            model_name='goalattendee',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('goal', 'user'), name='attendee_unique_user'),
        ),
        migrations.AddConstraint(
            model_name='goalattendee',
            constraint=models.UniqueConstraint(condition=models.Q(('agent__isnull', False)), fields=('goal', 'agent'), name='attendee_unique_agent'),
        ),
    ]
