# Generated by Django 4.2.7 on 2026-03-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_tabagenda_models'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='goalagendameta',
            name='scheduler_g_start_a_3d4fbe_idx',
        ),
        migrations.AddConstraint(
            model_name='goalagendameta',
            constraint=models.CheckConstraint(check=models.Q(('end_at__isnull', True), ('end_at__gte', models.F('start_at')), _connector='OR'), name='agenda_meta_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='goalreminderdelivery',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('recipient_agent__isnull', True), ('recipient_user__isnull', False)), models.Q(('recipient_agent__isnull', False), ('recipient_user__isnull', True)), _connector='OR'), name='reminder_delivery_one_recipient'),
        ),
    ]
