# Generated by Django 4.2.7 on 2026-05-21 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tabtinspace", "0052_alter_spaceadminactionlog_action_type_and_more"),
        ("tracker", "0028_rename_goal_to_tracker"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trackerrun",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Tracker 执行记录",
                "verbose_name_plural": "Tracker 执行记录",
            },
        ),
        migrations.RenameIndex(
            model_name="tracker",
            new_name="tracker_worktea_367d8f_idx",
            old_name="goal_worktea_8f1179_idx",
        ),
        migrations.RenameIndex(
            model_name="tracker",
            new_name="tracker_space_i_21e1e4_idx",
            old_name="goal_space_i_30c3d7_idx",
        ),
        migrations.RenameIndex(
            model_name="tracker",
            new_name="tracker_next_ru_bd3d89_idx",
            old_name="goal_next_ru_0f94a4_idx",
        ),
        migrations.RenameIndex(
            model_name="trackerrun",
            new_name="tracker_run_tracker_c6a6a7_idx",
            old_name="goal_run_goal_id_7a986f_idx",
        ),
        migrations.RenameIndex(
            model_name="trackerrun",
            new_name="tracker_run_status_c93cc3_idx",
            old_name="goal_run_status_cefcaf_idx",
        ),
        migrations.AlterField(
            model_name="tracker",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                help_text="执行该 Tracker 的 Agent。本期 nullable，应用层校验「创建时必填」。",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trackers",
                to="tabtinspace.agent",
                verbose_name="执行 Agent",
            ),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_trackers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="description",
            field=models.TextField(blank=True, verbose_name="Tracker 描述"),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Tracker 名称"),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="skill_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text='指向要执行的 Skill（charter v1.8 §6.4 单 Skill 执行模型）。空值表示纯 Agent 触发模式。应用层 TrackerService.create_tracker 在创建时强制非空——历史 Tracker 行可能为空，为兼容存量数据保留 blank=True / default=""。',
                max_length=128,
                verbose_name="关联 Skill",
            ),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="space",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trackers",
                to="tabtinspace.space",
                verbose_name="所属空间",
            ),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "草案"),
                    ("active", "已激活"),
                    ("paused", "已暂停"),
                    ("disabled", "已禁用"),
                ],
                default="draft",
                max_length=16,
                verbose_name="Tracker 状态",
            ),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="workteam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trackers",
                to="tabtinspace.workteam",
                verbose_name="所属工作团队",
            ),
        ),
        migrations.AlterField(
            model_name="trackerrun",
            name="tracker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="runs",
                to="tracker.tracker",
                verbose_name="所属 Tracker",
            ),
        ),
    ]
