# Generated by Django 4.2.7 on 2026-07-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0035_remove_trackerrun_chat_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackerrun',
            name='status',
            field=models.CharField(choices=[('pending', '等待执行'), ('running', '执行中'), ('waiting_checkpoint', '等待检查点（已废弃）'), ('waiting_device', '等待设备上线'), ('completed', '已完成'), ('partial_failed', '部分失败'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=24, verbose_name='执行状态'),
        ),
    ]
