# Generated by Django 4.2.7 on 2026-07-07 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0090_alter_organization_options_and_more'),
        ('tracker', '0037_rename_workteam_to_organization'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tracker',
            new_name='tracker_organiz_6b1f4b_idx',
            old_name='tracker_worktea_367d8f_idx',
        ),
        migrations.AlterField(
            model_name='tracker',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackers', to='tabtinspace.organization', verbose_name='所属组织'),
        ),
    ]
