# Generated by Django 4.2.7 on 2026-04-18 07:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('namespace', models.CharField(db_index=True, max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('workteam_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('latest_version_seq', models.PositiveIntegerField(blank=True, null=True)),
                ('parent_package_id', models.UUIDField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'package_registry_package',
                'unique_together': {('namespace', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PackageVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_seq', models.PositiveIntegerField(blank=True, null=True)),
                ('version_label', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('bundle_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('file_count', models.PositiveIntegerField(default=0)),
                ('total_size', models.BigIntegerField(default=0)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('uploading', '上传中'), ('published', '已发布')], db_index=True, default='uploading', max_length=16)),
                ('is_yanked', models.BooleanField(db_index=True, default=False)),
                ('yanked_at', models.DateTimeField(blank=True, null=True)),
                ('yanked_by', models.UUIDField(blank=True, null=True)),
                ('yanked_reason', models.TextField(blank=True, default='')),
                ('created_by', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='package_registry.package')),
            ],
            options={
                'db_table': 'package_registry_version',
                'unique_together': {('package', 'version_seq')},
            },
        ),
        migrations.CreateModel(
            name='PackageFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=512)),
                ('file_record_id', models.UUIDField(db_index=True)),
                ('oss_object_key', models.CharField(blank=True, default='', max_length=512)),
                ('file_size', models.BigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='package_registry.packageversion')),
            ],
            options={
                'db_table': 'package_registry_file',
                'indexes': [models.Index(fields=['sha256'], name='package_reg_sha256_52b6c4_idx')],
                'unique_together': {('version', 'path')},
            },
        ),
    ]
