# Generated by Django 4.2.7 on 2026-04-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagefile',
            name='content_type',
            field=models.CharField(blank=True, default='application/octet-stream', max_length=128),
        ),
    ]
