# Generated by Django 4.2.7 on 2026-05-05 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package_registry', '0004_event_outbox'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='eventoutbox',
            new_name='package_reg_status_a36d8b_idx',
            old_name='pkg_outbox_status_retry_idx',
        ),
        migrations.RenameIndex(
            model_name='eventoutbox',
            new_name='package_reg_event_t_94b48f_idx',
            old_name='pkg_outbox_event_type_idx',
        ),
    ]
