// ════════════════════════════════════════════════════════════════════
// 自动生成 — DO NOT EDIT MANUALLY
// Generated by @tabtin/wire-codegen (Wave 1 协议层)
// Source: packages/agent-wire/src/stream-content-block.ts (zod SSoT)
// 重新生成: pnpm --filter @tabtin/wire-codegen codegen
// 文档: docs/agent-runtime/wire-protocol.md
// ════════════════════════════════════════════════════════════════════

@file:OptIn(ExperimentalSerializationApi::class)
@file:Suppress("PropertyName", "ConstructorParameterNaming")

package com.tabtin.mobile.data.wire

import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonElement

@Serializable
@JsonClassDiscriminator("type")
public sealed class ApprovalRequestedPayloadActionRequestsItemDecisionReason

@Serializable
@SerialName("plan_guard")
public data class ApprovalRequestedPayloadActionRequestsItemDecisionReasonPlanGuard(
    @SerialName("deny_code") val deny_code: String,
    val details: JsonElement? = null
) : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("hardline_block")
public data class ApprovalRequestedPayloadActionRequestsItemDecisionReasonHardlineBlock(
    @SerialName("pattern_name") val pattern_name: String,
    @SerialName("matched_text") val matched_text: String
) : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("hardline_confirm")
public data class ApprovalRequestedPayloadActionRequestsItemDecisionReasonHardlineConfirm(
    @SerialName("pattern_name") val pattern_name: String,
    @SerialName("matched_text") val matched_text: String
) : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("skill_not_approved")
public data class ApprovalRequestedPayloadActionRequestsItemDecisionReasonSkillNotApproved(
    @SerialName("skill_id") val skill_id: String
) : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("skill_trust_downgrade")
public data class ApprovalRequestedPayloadActionRequestsItemDecisionReasonSkillTrustDowngrade(
    @SerialName("skill_id") val skill_id: String,
    @SerialName("from_preset") val from_preset: String,
    @SerialName("to_preset") val to_preset: String
) : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("operation_switch")
public data class ApprovalRequestedPayloadActionRequestsItemDecisionReasonOperationSwitch(
    @SerialName("switch_key") val switch_key: String,
    @SerialName("switch_action") val switch_action: String
) : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("deny_read_path")
public data class ApprovalRequestedPayloadActionRequestsItemDecisionReasonDenyReadPath(
    val path: String,
    @SerialName("matched_pattern") val matched_pattern: String
) : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("deny_write_path")
public data class ApprovalRequestedPayloadActionRequestsItemDecisionReasonDenyWritePath(
    val path: String,
    @SerialName("matched_pattern") val matched_pattern: String
) : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("sandbox_readonly")
public data class ApprovalRequestedPayloadActionRequestsItemDecisionReasonSandboxReadonly(
    val path: String,
    @SerialName("grant_path") val grant_path: String
) : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("bash_too_complex")
public data class ApprovalRequestedPayloadActionRequestsItemDecisionReasonBashTooComplex(
    val node: String
) : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("bash_parse_unavailable")
public object ApprovalRequestedPayloadActionRequestsItemDecisionReasonBashParseUnavailable : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("memoized_always")
public data class ApprovalRequestedPayloadActionRequestsItemDecisionReasonMemoizedAlways(
    @SerialName("previous_reason") val previous_reason: JsonElement? = null
) : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("memoized_thread")
public data class ApprovalRequestedPayloadActionRequestsItemDecisionReasonMemoizedThread(
    @SerialName("previous_reason") val previous_reason: JsonElement? = null
) : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("classifier_low_confidence")
public data class ApprovalRequestedPayloadActionRequestsItemDecisionReasonClassifierLowConfidence(
    val confidence: Double
) : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("classifier_decided")
public data class ApprovalRequestedPayloadActionRequestsItemDecisionReasonClassifierDecided(
    val confidence: Double,
    @SerialName("llm_reason") val llm_reason: String
) : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("user_interactive")
public data class ApprovalRequestedPayloadActionRequestsItemDecisionReasonUserInteractive(
    val scope: String,
    @SerialName("rejection_message") val rejection_message: String? = null
) : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("unknown_tool")
public object ApprovalRequestedPayloadActionRequestsItemDecisionReasonUnknownTool : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("fallback_preset")
public data class ApprovalRequestedPayloadActionRequestsItemDecisionReasonFallbackPreset(
    val preset: String
) : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("rule_high_risk_allowlist_miss")
public data class ApprovalRequestedPayloadActionRequestsItemDecisionReasonRuleHighRiskAllowlistMiss(
    @SerialName("preset_name") val preset_name: String,
    @SerialName("risk_signal") val risk_signal: String,
    @SerialName("matched_text") val matched_text: String? = null
) : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("hardline_command")
public data class ApprovalRequestedPayloadActionRequestsItemDecisionReasonHardlineCommand(
    val pattern: String
) : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("hardline_path")
public data class ApprovalRequestedPayloadActionRequestsItemDecisionReasonHardlinePath(
    val pattern: String
) : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("sensitive_out_deny")
public data class ApprovalRequestedPayloadActionRequestsItemDecisionReasonSensitiveOutDeny(
    val path: String,
    val category: String
) : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("sensitive_in_ask")
public data class ApprovalRequestedPayloadActionRequestsItemDecisionReasonSensitiveInAsk(
    val path: String,
    val category: String
) : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("memo_allow")
public data class ApprovalRequestedPayloadActionRequestsItemDecisionReasonMemoAllow(
    val key: String,
    val createdAt: String,
    val specificity: String,
    @SerialName("scope_description") val scope_description: String? = null
) : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

public typealias Specificity = String
@Serializable
@SerialName("memo_deny")
public data class ApprovalRequestedPayloadActionRequestsItemDecisionReasonMemoDeny(
    val key: String,
    val createdAt: String,
    val specificity: Specificity,
    @SerialName("scope_description") val scope_description: String? = null
) : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("yolo_allow")
public object ApprovalRequestedPayloadActionRequestsItemDecisionReasonYoloAllow : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("auto_allow")
public object ApprovalRequestedPayloadActionRequestsItemDecisionReasonAutoAllow : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("full_access_allow")
public object ApprovalRequestedPayloadActionRequestsItemDecisionReasonFullAccessAllow : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("policy_risk_ask")
public data class ApprovalRequestedPayloadActionRequestsItemDecisionReasonPolicyRiskAsk(
    val pattern: String? = null,
    val category: String? = null
) : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("workspace_in")
public data class ApprovalRequestedPayloadActionRequestsItemDecisionReasonWorkspaceIn(
    val path: String,
    val kind: String
) : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("workspace_out")
public data class ApprovalRequestedPayloadActionRequestsItemDecisionReasonWorkspaceOut(
    val path: String,
    val kind: String
) : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("platform_artifact_allow")
public data class ApprovalRequestedPayloadActionRequestsItemDecisionReasonPlatformArtifactAllow(
    val path: String
) : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("platform_gate_deferred")
public data class ApprovalRequestedPayloadActionRequestsItemDecisionReasonPlatformGateDeferred(
    val surface: String
) : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("destructive_in_workspace_ask")
public data class ApprovalRequestedPayloadActionRequestsItemDecisionReasonDestructiveInWorkspaceAsk(
    val path: String
) : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("object_default_allow")
public object ApprovalRequestedPayloadActionRequestsItemDecisionReasonObjectDefaultAllow : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("object_write_ask")
public object ApprovalRequestedPayloadActionRequestsItemDecisionReasonObjectWriteAsk : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("mcp_default_ask")
public data class ApprovalRequestedPayloadActionRequestsItemDecisionReasonMcpDefaultAsk(
    val server: String? = null
) : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("device_default_ask")
public data class ApprovalRequestedPayloadActionRequestsItemDecisionReasonDeviceDefaultAsk(
    @SerialName("device_action") val device_action: String? = null
) : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("device_observe_allow")
public object ApprovalRequestedPayloadActionRequestsItemDecisionReasonDeviceObserveAllow : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("plan_blocked")
public data class ApprovalRequestedPayloadActionRequestsItemDecisionReasonPlanBlocked(
    val mode: String
) : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

@Serializable
@SerialName("fallback_ask")
public object ApprovalRequestedPayloadActionRequestsItemDecisionReasonFallbackAsk : ApprovalRequestedPayloadActionRequestsItemDecisionReason()

public typealias Scope = String
@Serializable
public data class ApprovalRequestedPayloadActionRequestsItemAskHint(
    val summary: String,
    @SerialName("suggested_scope") val suggested_scope: Scope
)

@Serializable
public data class ApprovalRequestedPayloadActionRequestsItemSkillContext(
    @SerialName("skill_id") val skill_id: String,
    val source: String,
    @SerialName("permissions_approved") val permissions_approved: Boolean
)

@Serializable
public data class ApprovalRequestedPayloadActionRequestsItemBatchContext(
    @SerialName("batch_id") val batch_id: String,
    @SerialName("current_row_index") val current_row_index: Long? = null,
    @SerialName("total_count") val total_count: Long? = null,
    @SerialName("origin_column_id") val origin_column_id: String? = null,
    @SerialName("memoization_hint") val memoization_hint: String? = null
)

@Serializable
public data class ApprovalRequestedPayloadActionRequestsItemSubagentContext(
    @SerialName("parent_tool_call_id") val parent_tool_call_id: String,
    @SerialName("subagent_run_id") val subagent_run_id: String? = null,
    val label: String? = null
)

@Serializable
public data class ApprovalRequestedPayloadActionRequestsItem(
    @SerialName("request_id") val request_id: String,
    @SerialName("tool_call_id") val tool_call_id: String,
    @SerialName("tool_name") val tool_name: String,
    @SerialName("tool_namespace") val tool_namespace: String? = null,
    @SerialName("tool_input") val tool_input: JsonElement? = null,
    @SerialName("decision_reason") val decision_reason: ApprovalRequestedPayloadActionRequestsItemDecisionReason,
    @SerialName("user_visible_reason") val user_visible_reason: String? = null,
    @SerialName("ask_hint") val ask_hint: ApprovalRequestedPayloadActionRequestsItemAskHint? = null,
    @SerialName("allowed_scopes") val allowed_scopes: List<Scope>,
    @SerialName("allowed_outcomes") val allowed_outcomes: List<String>,
    @SerialName("risk_level") val risk_level: String? = null,
    @SerialName("skill_context") val skill_context: ApprovalRequestedPayloadActionRequestsItemSkillContext? = null,
    @SerialName("batch_context") val batch_context: ApprovalRequestedPayloadActionRequestsItemBatchContext? = null,
    @SerialName("subagent_context") val subagent_context: ApprovalRequestedPayloadActionRequestsItemSubagentContext? = null
)

@Serializable
public data class ApprovalRequestedPayload(
    @SerialName("batch_id") val batch_id: String,
    @SerialName("approval_type") val approval_type: String,
    @SerialName("action_requests") val action_requests: List<ApprovalRequestedPayloadActionRequestsItem>,
    @SerialName("runtime_mode") val runtime_mode: String,
    @SerialName("expires_at") val expires_at: Double,
    @SerialName("schema_version") val schema_version: String,
    @SerialName("message_id") val message_id: String? = null
)

public typealias ApprovalRequested = ApprovalRequestedPayload