// ════════════════════════════════════════════════════════════════════
// 自动生成 — DO NOT EDIT MANUALLY
// Generated by @tabtin/wire-codegen (Wave 1 协议层)
// Source: packages/agent-wire/src/stream-content-block.ts (zod SSoT)
// 重新生成: pnpm --filter @tabtin/wire-codegen codegen
// 文档: docs/agent-runtime/wire-protocol.md
// ════════════════════════════════════════════════════════════════════

@file:OptIn(ExperimentalSerializationApi::class)
@file:Suppress("PropertyName", "ConstructorParameterNaming")

package com.tabtin.mobile.data.wire

import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonElement

@Serializable
public data class MessageStop(
    @SerialName("protocol_version") val protocol_version: ProtocolVersion,
    @SerialName("min_compatible_version") val min_compatible_version: MinCompatibleVersion,
    @SerialName("trace_id") val trace_id: TraceId,
    @SerialName("_seq") val _seq: Seq,
    @SerialName("thread_id") val thread_id: ThreadId,
    @SerialName("arrival_seq") val arrival_seq: ArrivalSeq? = null,
    @SerialName("event_id") val event_id: EventId? = null,
    @SerialName("subagent_run_id") val subagent_run_id: SubagentRunId? = null,
    @SerialName("event_type") val event_type: String,
    @SerialName("message_id") val message_id: String,
    @SerialName("persisted_id") val persisted_id: String? = null,
    @SerialName("block_id_overrides") val block_id_overrides: JsonObject? = null,
    @SerialName("error_info") val error_info: ErrorInfo? = null
)
