// ════════════════════════════════════════════════════════════════════
// 自动生成 — DO NOT EDIT MANUALLY
// Generated by @tabtin/wire-codegen (Wave 1 协议层)
// Source: packages/agent-wire/src/stream-content-block.ts (zod SSoT)
// 重新生成: pnpm --filter @tabtin/wire-codegen codegen
// 文档: docs/agent-runtime/wire-protocol.md
// ════════════════════════════════════════════════════════════════════

@file:OptIn(ExperimentalSerializationApi::class)
@file:Suppress("PropertyName", "ConstructorParameterNaming")

package com.tabtin.mobile.data.wire

import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonElement

@Serializable
public data class StreamStep(
    @SerialName("step_type") val step_type: String,
    val title: String,
    val status: String,
    @SerialName("step_id") val step_id: String? = null,
    @SerialName("run_id") val run_id: String? = null,
    val detail: JsonElement? = null,
    val source: Source? = null,
    @SerialName("backend_type") val backend_type: BackendType? = null,
    @SerialName("task_id") val task_id: TaskId? = null
)
