# Generated by Django 4.2.7 on 2026-03-04 20:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelRuntimeStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=50, verbose_name='渠道')),
                ('account_id', models.CharField(default='default', max_length=100, verbose_name='账号ID')),
                ('workspace_id', models.CharField(max_length=100, verbose_name='工作空间ID')),
                ('status', models.CharField(max_length=32, verbose_name='运行状态')),
                ('last_error', models.TextField(blank=True, null=True, verbose_name='最后错误')),
                ('qr', models.TextField(blank=True, null=True, verbose_name='登录二维码')),
                ('details', models.JSONField(default=dict, verbose_name='状态详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '渠道运行状态',
                'verbose_name_plural': '渠道运行状态',
                'db_table': 'channel_gateway_runtime_status',
                'indexes': [models.Index(fields=['workspace_id'], name='cg_runtime_workspace_idx'), models.Index(fields=['channel', 'account_id'], name='cg_runtime_channel_idx'), models.Index(fields=['status'], name='cg_runtime_status_idx')],
                'unique_together': {('channel', 'account_id', 'workspace_id')},
            },
        ),
        migrations.CreateModel(
            name='ChannelPairingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=50, verbose_name='渠道')),
                ('account_id', models.CharField(default='default', max_length=100, verbose_name='账号ID')),
                ('peer_kind', models.CharField(max_length=20, verbose_name='会话类型')),
                ('peer_id', models.CharField(max_length=255, verbose_name='会话ID')),
                ('workspace_id', models.CharField(max_length=100, verbose_name='工作空间ID')),
                ('code', models.CharField(max_length=20, verbose_name='配对码')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('approved', '已通过'), ('rejected', '已拒绝'), ('expired', '已过期')], default='pending', max_length=20, verbose_name='状态')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('resolved_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='处理人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '渠道配对请求',
                'verbose_name_plural': '渠道配对请求',
                'db_table': 'channel_gateway_pairing',
                'indexes': [models.Index(fields=['workspace_id', 'status'], name='cg_pair_workspace_status_idx'), models.Index(fields=['channel', 'account_id', 'peer_id'], name='cg_pair_channel_peer_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChannelOutboundMessageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=50, verbose_name='渠道')),
                ('account_id', models.CharField(default='default', max_length=100, verbose_name='账号ID')),
                ('workspace_id', models.CharField(max_length=100, verbose_name='工作空间ID')),
                ('peer_id', models.CharField(max_length=255, verbose_name='会话ID')),
                ('payload', models.JSONField(default=dict, verbose_name='消息内容')),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='幂等Key')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('dispatched', '已分发待确认'), ('sent', '已发送'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='尝试次数')),
                ('next_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='下次重试时间')),
                ('last_error', models.TextField(blank=True, null=True, verbose_name='最后错误')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '渠道出站消息',
                'verbose_name_plural': '渠道出站消息',
                'db_table': 'channel_gateway_outbox',
                'indexes': [models.Index(fields=['workspace_id'], name='cg_outbox_workspace_idx'), models.Index(fields=['status', 'next_retry_at'], name='cg_outbox_status_retry_idx'), models.Index(fields=['channel', 'account_id'], name='cg_outbox_channel_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChannelInboundMessageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=50, verbose_name='渠道')),
                ('account_id', models.CharField(default='default', max_length=100, verbose_name='账号ID')),
                ('workspace_id', models.CharField(max_length=100, verbose_name='工作空间ID')),
                ('peer_id', models.CharField(max_length=255, verbose_name='会话ID')),
                ('message_id', models.CharField(max_length=255, verbose_name='消息ID')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='接收时间')),
            ],
            options={
                'verbose_name': '渠道入站消息记录',
                'verbose_name_plural': '渠道入站消息记录',
                'db_table': 'channel_gateway_inbound_log',
                'indexes': [models.Index(fields=['workspace_id'], name='cg_inbound_workspace_idx'), models.Index(fields=['channel', 'account_id'], name='cg_inbound_channel_idx')],
                'unique_together': {('channel', 'account_id', 'workspace_id', 'peer_id', 'message_id')},
            },
        ),
        migrations.CreateModel(
            name='ChannelBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=50, verbose_name='渠道')),
                ('account_id', models.CharField(default='default', max_length=100, verbose_name='账号ID')),
                ('peer_kind', models.CharField(max_length=20, verbose_name='会话类型')),
                ('peer_id', models.CharField(max_length=255, verbose_name='会话ID')),
                ('workspace_id', models.CharField(max_length=100, verbose_name='工作空间ID')),
                ('agent_space_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='智能体空间ID')),
                ('session_id', models.UUIDField(blank=True, null=True, verbose_name='ChatSession ID')),
                ('thread_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Thread ID')),
                ('agent_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Agent ID')),
                ('status', models.CharField(choices=[('active', '启用'), ('paused', '暂停'), ('blocked', '禁用')], default='active', max_length=20, verbose_name='状态')),
                ('last_message_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='最后消息ID')),
                ('metadata', models.JSONField(default=dict, verbose_name='扩展信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '渠道绑定',
                'verbose_name_plural': '渠道绑定',
                'db_table': 'channel_gateway_binding',
                'indexes': [models.Index(fields=['channel', 'account_id', 'peer_id'], name='cg_bind_channel_peer_idx'), models.Index(fields=['workspace_id'], name='cg_bind_workspace_idx')],
                'unique_together': {('channel', 'account_id', 'peer_id', 'workspace_id')},
            },
        ),
        migrations.CreateModel(
            name='ChannelAllowlistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=50, verbose_name='渠道')),
                ('account_id', models.CharField(default='default', max_length=100, verbose_name='账号ID')),
                ('peer_kind', models.CharField(max_length=20, verbose_name='会话类型')),
                ('peer_id', models.CharField(max_length=255, verbose_name='会话ID')),
                ('workspace_id', models.CharField(max_length=100, verbose_name='工作空间ID')),
                ('allow', models.BooleanField(default=True, verbose_name='是否允许')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '渠道 Allowlist',
                'verbose_name_plural': '渠道 Allowlist',
                'db_table': 'channel_gateway_allowlist',
                'indexes': [models.Index(fields=['workspace_id'], name='cg_allow_workspace_idx'), models.Index(fields=['channel', 'account_id', 'peer_kind'], name='cg_allow_channel_kind_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChannelAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=50, verbose_name='渠道')),
                ('account_id', models.CharField(default='default', max_length=100, verbose_name='账号ID')),
                ('workspace_id', models.CharField(max_length=100, verbose_name='工作空间ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='账号名称')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('config', models.JSONField(default=dict, verbose_name='账号配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '渠道账号',
                'verbose_name_plural': '渠道账号',
                'db_table': 'channel_gateway_account',
                'indexes': [models.Index(fields=['workspace_id'], name='cg_account_workspace_idx'), models.Index(fields=['channel', 'account_id'], name='cg_account_channel_idx')],
                'unique_together': {('channel', 'account_id', 'workspace_id')},
            },
        ),
    ]
