# Generated by Django 4.2.7 on 2026-03-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelbinding',
            name='agent_space_id',
            field=models.CharField(blank=True, db_column='agent_space_id', max_length=100, null=True, verbose_name='智能体空间ID'),
        ),
        migrations.RenameField(
            model_name='channelbinding',
            old_name='agent_space_id',
            new_name='space_id',
        ),
    ]
