# Generated by Django 4.2.7 on 2026-03-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_gateway', '0002_alter_channelbinding_agent_space_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelbinding',
            name='space_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='智能体空间ID'),
        ),
    ]
