# Generated by Django 4.2.7 on 2026-03-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_gateway', '0005_workspace_to_workteam_rename'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='channelaccount',
            name='cg_account_workteam_idx',
        ),
        migrations.RemoveIndex(
            model_name='channelallowlistentry',
            name='cg_allow_workteam_idx',
        ),
        migrations.RemoveIndex(
            model_name='channelbinding',
            name='cg_bind_workteam_idx',
        ),
        migrations.RemoveIndex(
            model_name='channelinboundmessagelog',
            name='cg_inbound_workteam_idx',
        ),
        migrations.RemoveIndex(
            model_name='channeloutboundmessagerecord',
            name='cg_outbox_workteam_idx',
        ),
        migrations.RemoveIndex(
            model_name='channelpairingrequest',
            name='cg_pair_workteam_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='channelruntimestatus',
            name='cg_runtime_workteam_idx',
        ),
        migrations.AlterField(
            model_name='channelaccount',
            name='workteam_id',
            field=models.CharField(max_length=100, verbose_name='工作团队ID'),
        ),
        migrations.AlterField(
            model_name='channelallowlistentry',
            name='workteam_id',
            field=models.CharField(max_length=100, verbose_name='工作团队ID'),
        ),
        migrations.AlterField(
            model_name='channelbinding',
            name='workteam_id',
            field=models.CharField(max_length=100, verbose_name='工作团队ID'),
        ),
        migrations.AlterField(
            model_name='channelinboundmessagelog',
            name='workteam_id',
            field=models.CharField(max_length=100, verbose_name='工作团队ID'),
        ),
        migrations.AlterField(
            model_name='channeloutboundmessagerecord',
            name='workteam_id',
            field=models.CharField(max_length=100, verbose_name='工作团队ID'),
        ),
        migrations.AlterField(
            model_name='channelpairingrequest',
            name='workteam_id',
            field=models.CharField(max_length=100, verbose_name='工作团队ID'),
        ),
        migrations.AlterField(
            model_name='channelruntimestatus',
            name='workteam_id',
            field=models.CharField(max_length=100, verbose_name='工作团队ID'),
        ),
        migrations.AddIndex(
            model_name='channelaccount',
            index=models.Index(fields=['workteam_id'], name='cg_account_workteam_idx'),
        ),
        migrations.AddIndex(
            model_name='channelallowlistentry',
            index=models.Index(fields=['workteam_id'], name='cg_allow_workteam_idx'),
        ),
        migrations.AddIndex(
            model_name='channelbinding',
            index=models.Index(fields=['workteam_id'], name='cg_bind_workteam_idx'),
        ),
        migrations.AddIndex(
            model_name='channelinboundmessagelog',
            index=models.Index(fields=['workteam_id'], name='cg_inbound_workteam_idx'),
        ),
        migrations.AddIndex(
            model_name='channeloutboundmessagerecord',
            index=models.Index(fields=['workteam_id'], name='cg_outbox_workteam_idx'),
        ),
        migrations.AddIndex(
            model_name='channelpairingrequest',
            index=models.Index(fields=['workteam_id', 'status'], name='cg_pair_workteam_status_idx'),
        ),
        migrations.AddIndex(
            model_name='channelruntimestatus',
            index=models.Index(fields=['workteam_id'], name='cg_runtime_workteam_idx'),
        ),
    ]
