# Generated by Django 4.2.7 on 2026-07-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_gateway', '0009_rename_workteam_to_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelaccount',
            name='organization_id',
            field=models.CharField(max_length=100, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='channelallowlistentry',
            name='organization_id',
            field=models.CharField(max_length=100, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='channelbinding',
            name='organization_id',
            field=models.CharField(max_length=100, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='channelinboundmessagelog',
            name='organization_id',
            field=models.CharField(max_length=100, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='channeloutboundmessagerecord',
            name='organization_id',
            field=models.CharField(max_length=100, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='channelpairingrequest',
            name='organization_id',
            field=models.CharField(max_length=100, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='channelruntimestatus',
            name='organization_id',
            field=models.CharField(max_length=100, verbose_name='组织ID'),
        ),
    ]
