# Generated by Django 4.2.7 on 2026-07-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_gateway', '0011_binding_execution_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelbinding',
            name='space_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Agent 空间ID'),
        ),
    ]
