# Generated by Django 4.2.7 on 2026-03-04 20:27

import apps.extensions.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(db_index=True, max_length=100, verbose_name='工作空间ID')),
                ('agent_space_id', models.CharField(blank=True, help_text='null 表示 workspace 级规则', max_length=100, null=True, verbose_name='智能体空间ID')),
                ('event_pattern', models.CharField(help_text='fnmatch 语法，如 "email.*"、"*.failed"', max_length=200, verbose_name='事件匹配模式')),
                ('source_extension_id', models.CharField(blank=True, default='', help_text='空=匹配所有来源', max_length=64, verbose_name='来源 Extension')),
                ('channels', models.JSONField(default=list, help_text='如 ["in_app", "desktop"]', verbose_name='投递渠道')),
                ('priority', models.CharField(choices=[('low', '低'), ('normal', '普通'), ('high', '高'), ('urgent', '紧急')], default='normal', max_length=16, verbose_name='优先级')),
                ('category', models.CharField(default='general', max_length=64, verbose_name='分类标签')),
                ('title_template', models.CharField(blank=True, default='', help_text='支持 {event_type}, {source} 等变量', max_length=500, verbose_name='标题模板')),
                ('body_template', models.TextField(blank=True, default='', verbose_name='正文模板')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_system', models.BooleanField(default=False, help_text='系统内置规则不可删除', verbose_name='系统内置')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '通知规则',
                'verbose_name_plural': '通知规则',
                'db_table': 'ext_notification_rule',
                'ordering': ['sort_order', '-created_at'],
                'indexes': [models.Index(fields=['workspace_id', 'enabled'], name='ext_nrule_ws_enabled_idx'), models.Index(fields=['workspace_id', 'agent_space_id'], name='ext_nrule_ws_as_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExtensionWebhookSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=100, verbose_name='工作空间ID')),
                ('agent_space_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='智能体空间ID')),
                ('url', models.URLField(max_length=2048, verbose_name='Webhook URL')),
                ('secret', apps.extensions.fields.EncryptedCharField(verbose_name='签名密钥')),
                ('event_types', models.JSONField(default=list, help_text='如 ["email.received", "telegram.message_received"]', verbose_name='订阅事件列表')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('max_retries', models.PositiveSmallIntegerField(default=3, verbose_name='最大重试次数')),
                ('total_deliveries', models.PositiveIntegerField(default=0, verbose_name='总投递次数')),
                ('failed_deliveries', models.PositiveIntegerField(default=0, verbose_name='失败次数')),
                ('consecutive_failures', models.PositiveIntegerField(default=0, verbose_name='连续失败次数')),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='上次触发时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Extension Webhook 订阅',
                'verbose_name_plural': 'Extension Webhook 订阅',
                'db_table': 'ext_webhook_subscription',
                'indexes': [models.Index(fields=['workspace_id', 'is_active'], name='ext_wh_ws_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExtensionEventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extension_id', models.CharField(max_length=64, verbose_name='Extension 标识')),
                ('connection_id', models.UUIDField(blank=True, null=True, verbose_name='连接ID')),
                ('workspace_id', models.CharField(max_length=100, verbose_name='工作空间ID')),
                ('agent_space_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='智能体空间ID')),
                ('event_type', models.CharField(help_text='如 email.received, telegram.message_received', max_length=128, verbose_name='事件类型')),
                ('event_data', models.JSONField(default=dict, verbose_name='事件数据')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('dispatched', '已分发'), ('consumed', '已消费'), ('failed', '失败'), ('skipped', '跳过')], default='pending', max_length=20)),
                ('consumer_results', models.JSONField(default=dict, help_text='各消费者的处理结果', verbose_name='消费结果')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
            ],
            options={
                'verbose_name': 'Extension 事件日志',
                'verbose_name_plural': 'Extension 事件日志',
                'db_table': 'ext_event_log',
                'indexes': [models.Index(fields=['workspace_id', 'extension_id'], name='ext_evt_ws_ext_idx'), models.Index(fields=['event_type', 'status'], name='ext_evt_type_status_idx'), models.Index(fields=['created_at'], name='ext_evt_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExtensionConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extension_id', models.CharField(help_text='对应 BaseExtension.id，如 tabmail / telegram / 等', max_length=64, verbose_name='Extension 标识')),
                ('workspace_id', models.CharField(max_length=100, verbose_name='工作空间ID')),
                ('agent_space_id', models.CharField(blank=True, help_text='null 表示 workspace 级连接', max_length=100, null=True, verbose_name='智能体空间ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='连接名称')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('auth_type', models.CharField(choices=[('none', '无认证'), ('api_key', 'API Key'), ('oauth2', 'OAuth2'), ('app_password', '应用密码'), ('bot_token', 'Bot Token')], default='none', max_length=32, verbose_name='认证方式')),
                ('config', apps.extensions.fields.EncryptedJSONField(default=dict, help_text='存储 API Key、OAuth token 等凭证和配置项（加密存储）', verbose_name='连接配置')),
                ('status', models.CharField(choices=[('disconnected', '未连接'), ('connecting', '连接中'), ('connected', '已连接'), ('error', '错误')], default='disconnected', max_length=32, verbose_name='连接状态')),
                ('last_error', models.TextField(blank=True, null=True, verbose_name='最后错误')),
                ('last_probe_at', models.DateTimeField(blank=True, null=True, verbose_name='上次探测时间')),
                ('metadata', models.JSONField(default=dict, verbose_name='扩展元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Extension 连接',
                'verbose_name_plural': 'Extension 连接',
                'db_table': 'ext_connection',
                'indexes': [models.Index(fields=['workspace_id', 'extension_id'], name='ext_conn_ws_ext_idx'), models.Index(fields=['agent_space_id'], name='ext_conn_as_idx'), models.Index(fields=['status'], name='ext_conn_status_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='extensionconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('agent_space_id__isnull', False)), fields=('extension_id', 'workspace_id', 'agent_space_id'), name='ext_conn_unique_with_as'),
        ),
        migrations.AddConstraint(
            model_name='extensionconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('agent_space_id__isnull', True)), fields=('extension_id', 'workspace_id'), name='ext_conn_unique_ws_level'),
        ),
    ]
