# Generated by Django 4.2.7 on 2026-03-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='extensionconnection',
            name='ext_conn_unique_with_as',
        ),
        migrations.RemoveConstraint(
            model_name='extensionconnection',
            name='ext_conn_unique_ws_level',
        ),
        migrations.RemoveIndex(
            model_name='extensionconnection',
            name='ext_conn_as_idx',
        ),
        migrations.RemoveIndex(
            model_name='notificationrule',
            name='ext_nrule_ws_as_idx',
        ),
        migrations.AlterField(
            model_name='extensionconnection',
            name='agent_space_id',
            field=models.CharField(blank=True, db_column='agent_space_id', help_text='null 表示 workspace 级连接', max_length=100, null=True, verbose_name='智能体空间ID'),
        ),
        migrations.RenameField(
            model_name='extensionconnection',
            old_name='agent_space_id',
            new_name='space_id',
        ),
        migrations.AlterField(
            model_name='extensioneventlog',
            name='agent_space_id',
            field=models.CharField(blank=True, db_column='agent_space_id', max_length=100, null=True, verbose_name='智能体空间ID'),
        ),
        migrations.RenameField(
            model_name='extensioneventlog',
            old_name='agent_space_id',
            new_name='space_id',
        ),
        migrations.AlterField(
            model_name='extensionwebhooksubscription',
            name='agent_space_id',
            field=models.CharField(blank=True, db_column='agent_space_id', max_length=100, null=True, verbose_name='智能体空间ID'),
        ),
        migrations.RenameField(
            model_name='extensionwebhooksubscription',
            old_name='agent_space_id',
            new_name='space_id',
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='agent_space_id',
            field=models.CharField(blank=True, db_column='agent_space_id', help_text='null 表示 workspace 级规则', max_length=100, null=True, verbose_name='智能体空间ID'),
        ),
        migrations.RenameField(
            model_name='notificationrule',
            old_name='agent_space_id',
            new_name='space_id',
        ),
        migrations.AddIndex(
            model_name='extensionconnection',
            index=models.Index(fields=['space_id'], name='ext_conn_as_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrule',
            index=models.Index(fields=['workspace_id', 'space_id'], name='ext_nrule_ws_as_idx'),
        ),
        migrations.AddConstraint(
            model_name='extensionconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('space_id__isnull', False)), fields=('extension_id', 'workspace_id', 'space_id'), name='ext_conn_unique_with_as'),
        ),
        migrations.AddConstraint(
            model_name='extensionconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('space_id__isnull', True)), fields=('extension_id', 'workspace_id'), name='ext_conn_unique_ws_level'),
        ),
    ]
