# Generated by Django 4.2.7 on 2026-03-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0002_remove_extensionconnection_ext_conn_unique_with_as_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extensionconnection',
            name='space_id',
            field=models.CharField(blank=True, help_text='null 表示 workspace 级连接', max_length=100, null=True, verbose_name='智能体空间ID'),
        ),
        migrations.AlterField(
            model_name='extensioneventlog',
            name='space_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='智能体空间ID'),
        ),
        migrations.AlterField(
            model_name='extensionwebhooksubscription',
            name='space_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='智能体空间ID'),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='space_id',
            field=models.CharField(blank=True, help_text='null 表示 workspace 级规则', max_length=100, null=True, verbose_name='智能体空间ID'),
        ),
    ]
