# Generated by Django 4.2.7 on 2026-03-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0004_workspace_to_workteam_rename'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='extensionconnection',
            name='ext_conn_unique_with_as',
        ),
        migrations.RemoveConstraint(
            model_name='extensionconnection',
            name='ext_conn_unique_ws_level',
        ),
        migrations.RemoveIndex(
            model_name='extensionconnection',
            name='ext_conn_ws_ext_idx',
        ),
        migrations.RemoveIndex(
            model_name='extensioneventlog',
            name='ext_evt_ws_ext_idx',
        ),
        migrations.RemoveIndex(
            model_name='extensionwebhooksubscription',
            name='ext_wh_ws_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='notificationrule',
            name='ext_nrule_ws_enabled_idx',
        ),
        migrations.RemoveIndex(
            model_name='notificationrule',
            name='ext_nrule_ws_as_idx',
        ),
        migrations.AlterField(
            model_name='extensionconnection',
            name='space_id',
            field=models.CharField(blank=True, help_text='null 表示 workteam 级连接', max_length=100, null=True, verbose_name='智能体空间ID'),
        ),
        migrations.AlterField(
            model_name='extensionconnection',
            name='workteam_id',
            field=models.CharField(max_length=100, verbose_name='工作团队ID'),
        ),
        migrations.AlterField(
            model_name='extensioneventlog',
            name='workteam_id',
            field=models.CharField(max_length=100, verbose_name='工作团队ID'),
        ),
        migrations.AlterField(
            model_name='extensionwebhooksubscription',
            name='workteam_id',
            field=models.CharField(max_length=100, verbose_name='工作团队ID'),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='space_id',
            field=models.CharField(blank=True, help_text='null 表示 workteam 级规则', max_length=100, null=True, verbose_name='智能体空间ID'),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='workteam_id',
            field=models.CharField(db_index=True, max_length=100, verbose_name='工作团队ID'),
        ),
        migrations.AddIndex(
            model_name='extensionconnection',
            index=models.Index(fields=['workteam_id', 'extension_id'], name='ext_conn_ws_ext_idx'),
        ),
        migrations.AddIndex(
            model_name='extensioneventlog',
            index=models.Index(fields=['workteam_id', 'extension_id'], name='ext_evt_ws_ext_idx'),
        ),
        migrations.AddIndex(
            model_name='extensionwebhooksubscription',
            index=models.Index(fields=['workteam_id', 'is_active'], name='ext_wh_ws_active_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrule',
            index=models.Index(fields=['workteam_id', 'enabled'], name='ext_nrule_ws_enabled_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrule',
            index=models.Index(fields=['workteam_id', 'space_id'], name='ext_nrule_ws_as_idx'),
        ),
        migrations.AddConstraint(
            model_name='extensionconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('space_id__isnull', False)), fields=('extension_id', 'workteam_id', 'space_id'), name='ext_conn_unique_with_as'),
        ),
        migrations.AddConstraint(
            model_name='extensionconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('space_id__isnull', True)), fields=('extension_id', 'workteam_id'), name='ext_conn_unique_ws_level'),
        ),
    ]
