# Generated by Django 4.2.7 on 2026-07-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0006_rename_workteam_to_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extensionconnection',
            name='organization_id',
            field=models.CharField(max_length=100, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='extensionconnection',
            name='space_id',
            field=models.CharField(blank=True, help_text='null 表示 organization 级连接', max_length=100, null=True, verbose_name='智能体空间ID'),
        ),
        migrations.AlterField(
            model_name='extensioneventlog',
            name='organization_id',
            field=models.CharField(max_length=100, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='extensionwebhooksubscription',
            name='organization_id',
            field=models.CharField(max_length=100, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='organization_id',
            field=models.CharField(db_index=True, max_length=100, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='space_id',
            field=models.CharField(blank=True, help_text='null 表示 organization 级规则', max_length=100, null=True, verbose_name='智能体空间ID'),
        ),
    ]
