# Generated by Django 4.2.7 on 2026-04-16 17:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('messages_json', models.JSONField(default=list, help_text='OpenAI 格式消息列表')),
                ('state_json', models.JSONField(default=dict, help_text='非消息状态字段')),
                ('interrupt_state', models.JSONField(blank=True, help_text='HITL 中断时保存的完整状态快照', null=True)),
                ('version', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_engine_conversation_states',
            },
        ),
        migrations.CreateModel(
            name='ExecutionRun',
            fields=[
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thread_id', models.CharField(db_index=True, max_length=128)),
                ('graph_type', models.CharField(db_index=True, max_length=64)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('instance_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('workteam_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('trace_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(db_index=True, default='running', max_length=32)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('max_alive_seconds', models.IntegerField(default=1800, help_text='Run 最大存活时间（秒），超时后 Celery beat 自动取消')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_engine_runs',
            },
        ),
        migrations.CreateModel(
            name='ExecutionTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('thread_id', models.CharField(db_index=True, max_length=128)),
                ('graph_type', models.CharField(db_index=True, max_length=64)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('instance_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('workteam_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('status', models.CharField(default='running', max_length=32)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_event_seq', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'agent_engine_traces',
            },
        ),
        migrations.CreateModel(
            name='MonitorTask',
            fields=[
                ('monitor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thread_id', models.CharField(db_index=True, max_length=128)),
                ('command', models.TextField()),
                ('description', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('stream_ended', 'Stream Ended'), ('failed', 'Failed')], default='running', max_length=20)),
                ('fail_reason', models.CharField(blank=True, max_length=64, null=True)),
                ('notify_on', models.CharField(choices=[('every_line', 'Every Line'), ('on_error', 'On Error'), ('on_pattern', 'On Pattern'), ('on_build', 'On Build')], default='every_line', max_length=20)),
                ('pattern', models.CharField(blank=True, max_length=500, null=True)),
                ('device_fingerprint', models.CharField(max_length=128)),
                ('session_id', models.CharField(blank=True, max_length=128, null=True)),
                ('parent_subagent_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('working_directory', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_engine_monitor_tasks',
            },
        ),
        migrations.CreateModel(
            name='TraceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('seq', models.BigIntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('input', models.JSONField(blank=True, null=True)),
                ('output', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('usage', models.JSONField(blank=True, null=True)),
                ('parent_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='agent_engine.traceevent')),
                ('trace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='agent_engine.executiontrace')),
            ],
            options={
                'db_table': 'agent_engine_trace_events',
            },
        ),
        migrations.CreateModel(
            name='SubtaskRun',
            fields=[
                ('subagent_run_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent_thread_id', models.CharField(db_index=True, max_length=128)),
                ('child_thread_id', models.CharField(db_index=True, max_length=128)),
                ('parent_agent_name', models.CharField(blank=True, max_length=64, null=True)),
                ('parent_agent_type', models.CharField(blank=True, max_length=32, null=True)),
                ('agent_name', models.CharField(blank=True, max_length=64, null=True)),
                ('agent_type', models.CharField(default='react', max_length=32)),
                ('subagent_type', models.CharField(blank=True, help_text='子 Agent 类型预设：explore/plan/execute', max_length=32, null=True)),
                ('app_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('mode', models.CharField(default='background', max_length=32)),
                ('cleanup', models.CharField(default='keep', max_length=16)),
                ('status', models.CharField(db_index=True, default='pending', max_length=32)),
                ('task', models.TextField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=128, null=True)),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('workteam_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('current_space_id', models.CharField(blank=True, max_length=64, null=True)),
                ('current_table_id', models.CharField(blank=True, max_length=64, null=True)),
                ('model_id', models.CharField(blank=True, max_length=64, null=True)),
                ('thinking_level', models.CharField(blank=True, max_length=32, null=True)),
                ('run_timeout_seconds', models.IntegerField(blank=True, null=True)),
                ('tool_domains', models.JSONField(blank=True, default=list)),
                ('action_app_ids', models.JSONField(blank=True, default=list)),
                ('allowed_tools', models.JSONField(blank=True, default=list)),
                ('input_state', models.JSONField(blank=True, default=dict)),
                ('system_prompt', models.TextField(blank=True, null=True)),
                ('result_summary', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('stats_json', models.JSONField(blank=True, default=dict)),
                ('requester_origin_json', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('archive_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_engine_subtask_runs',
                'indexes': [models.Index(fields=['parent_thread_id', 'status'], name='idx_subagent_parent_status'), models.Index(fields=['child_thread_id'], name='idx_subagent_child'), models.Index(fields=['app_id', 'status'], name='idx_subagent_app_status'), models.Index(fields=['archive_at'], name='idx_subagent_archive'), models.Index(fields=['parent_thread_id', 'created_at'], name='idx_subagent_parent_created')],
            },
        ),
        migrations.CreateModel(
            name='SubAgentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('space_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(help_text='子 Agent 名称（当前 Agent 通过此名称引用）', max_length=64)),
                ('description', models.TextField(blank=True, default='', help_text='子 Agent 用途描述')),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('system_prompt', models.TextField(blank=True, default='', help_text='角色设定 / 系统提示')),
                ('subagent_type', models.CharField(default='execute', help_text='任务角色：explore（只读探索）/ plan（只读规划）/ execute（可写执行）', max_length=32)),
                ('allowed_tools', models.JSONField(blank=True, default=list, help_text='工具白名单（空=不限制）')),
                ('denied_tools', models.JSONField(blank=True, default=list, help_text='工具黑名单')),
                ('model_id', models.CharField(blank=True, default='', help_text='首选模型 ID', max_length=64)),
                ('thinking_level', models.CharField(blank=True, default='', help_text='思维级别', max_length=32)),
                ('default_mode', models.CharField(default='wait', help_text='默认执行模式：wait（同步）/ background（异步）', max_length=32)),
                ('app_id', models.CharField(blank=True, default='', help_text='工具域来源 APP（决定子 Agent 可用的工具集，空=通用）', max_length=64)),
                ('reply_mode', models.CharField(blank=True, default='', help_text='回复模式（来自 agents/*.md 的 reply_mode 字段，空=由编排器决定）', max_length=32)),
                ('tool_domains', models.JSONField(blank=True, default=list, help_text='工具域标签列表（如 ["rag","browser","tabdata"]），来自 agents/*.md')),
                ('skill_key', models.CharField(blank=True, default='', help_text='来源 Skill 标识（从文件系统 agents/*.md 注册时回填）', max_length=128)),
                ('is_enabled', models.BooleanField(default=True, help_text='是否启用')),
                ('order', models.IntegerField(default=0, help_text='排序权重')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_engine_subagent_templates',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['space_id', 'is_enabled'], name='idx_tpl_space_enabled')],
            },
        ),
        migrations.AddConstraint(
            model_name='subagenttemplate',
            constraint=models.UniqueConstraint(fields=('space_id', 'name'), name='uq_tpl_space_name'),
        ),
        migrations.AddIndex(
            model_name='monitortask',
            index=models.Index(fields=['thread_id', 'status'], name='idx_monitor_thread_status'),
        ),
        migrations.AddIndex(
            model_name='monitortask',
            index=models.Index(fields=['parent_subagent_id'], name='idx_monitor_parent_subagent'),
        ),
        migrations.AddIndex(
            model_name='executiontrace',
            index=models.Index(fields=['thread_id', 'graph_type'], name='idx_thread_graph'),
        ),
        migrations.AddIndex(
            model_name='executiontrace',
            index=models.Index(fields=['user_id', 'started_at'], name='idx_user_started'),
        ),
        migrations.AddIndex(
            model_name='executiontrace',
            index=models.Index(fields=['session_id'], name='idx_session'),
        ),
        migrations.AddIndex(
            model_name='executionrun',
            index=models.Index(fields=['thread_id', 'status'], name='idx_run_thread_status'),
        ),
        migrations.AddIndex(
            model_name='executionrun',
            index=models.Index(fields=['graph_type', 'started_at'], name='idx_run_graph_started'),
        ),
        migrations.AddIndex(
            model_name='executionrun',
            index=models.Index(fields=['trace_id'], name='idx_run_trace'),
        ),
        migrations.AddIndex(
            model_name='executionrun',
            index=models.Index(fields=['session_id'], name='idx_run_session'),
        ),
        migrations.AddIndex(
            model_name='conversationstate',
            index=models.Index(fields=['updated_at'], name='idx_convstate_updated'),
        ),
        migrations.AddIndex(
            model_name='traceevent',
            index=models.Index(fields=['trace', 'seq'], name='idx_trace_seq'),
        ),
        migrations.AddIndex(
            model_name='traceevent',
            index=models.Index(fields=['event_type'], name='idx_event_type'),
        ),
    ]
