# Generated by Django 4.2.7 on 2026-04-21 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent_engine', '0004_drop_orphan_runs_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='subagenttemplate',
            name='display_color',
            field=models.CharField(blank=True, default='', help_text='显示颜色 hex 值', max_length=16),
        ),
        migrations.AddField(
            model_name='subagenttemplate',
            name='inherit_mode_default',
            field=models.CharField(default='filtered', help_text='子 Agent 默认继承模式：full / filtered / summary / none', max_length=16),
        ),
        migrations.AddField(
            model_name='subagenttemplate',
            name='max_active',
            field=models.IntegerField(default=5, help_text='该模板并发上限'),
        ),
        migrations.AddField(
            model_name='subagenttemplate',
            name='max_turns',
            field=models.IntegerField(default=50, help_text='子 Agent 最大迭代轮数'),
        ),
        migrations.AddField(
            model_name='subagenttemplate',
            name='version',
            field=models.IntegerField(default=1, help_text='当前版本号，每次编辑自增'),
        ),
        migrations.AlterField(
            model_name='cliauditevent',
            name='agent_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='发起调用的 Agent ID（跨库软引用 agent_engine.Agent.id）', null=True),
        ),
        migrations.AlterField(
            model_name='cliauditevent',
            name='risk_level',
            field=models.CharField(db_index=True, help_text='safe / review / strict，与 RegisteredTool.risk_level 词表对齐（K8 决策）', max_length=16),
        ),
        migrations.AlterField(
            model_name='cliauditevent',
            name='spec_json',
            field=models.JSONField(default=dict, help_text='CliInvocationSpec.to_dict() 完整序列化（含 matched_rule_pattern / matched_rule_reason 便于审计反查）；写入前按 risk_level 二次脱敏 raw_args'),
        ),
        migrations.AlterField(
            model_name='cliauditevent',
            name='thread_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='对话线程 ID（跨库软引用 conversation.Thread.id）', null=True),
        ),
        migrations.AlterField(
            model_name='cliauditevent',
            name='user_id',
            field=models.UUIDField(blank=True, help_text='实际用户 ID（跨库软引用 users_auth.User.id）', null=True),
        ),
        migrations.CreateModel(
            name='SubAgentTemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('snapshot_json', models.JSONField(help_text='改动时刻的模板完整快照')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='agent_engine.subagenttemplate')),
            ],
            options={
                'db_table': 'agent_engine_subagent_template_versions',
            },
        ),
        migrations.AddConstraint(
            model_name='subagenttemplateversion',
            constraint=models.UniqueConstraint(fields=('template', 'version'), name='uq_tpl_version'),
        ),
    ]
