# Generated by Django 4.2.7 on 2026-04-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_engine', '0005_prd06_subagent_template_versioning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subagenttemplate',
            name='inherit_mode_default',
            field=models.CharField(choices=[('full', 'Full'), ('filtered', 'Filtered'), ('summary', 'Summary'), ('none', 'None')], default='filtered', help_text='子 Agent 默认继承模式', max_length=16),
        ),
        migrations.AlterField(
            model_name='subagenttemplate',
            name='max_active',
            field=models.PositiveIntegerField(default=5, help_text='该模板并发上限'),
        ),
        migrations.AlterField(
            model_name='subagenttemplate',
            name='max_turns',
            field=models.PositiveIntegerField(default=50, help_text='子 Agent 最大迭代轮数'),
        ),
        migrations.AlterField(
            model_name='subagenttemplate',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='当前版本号，每次编辑自增'),
        ),
    ]
