# Generated by Django 4.2.7 on 2026-05-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_engine', '0009_permission_audit_unique_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliauditevent',
            name='inner_binary',
            field=models.CharField(blank=True, db_index=True, help_text='fork 子进程实际 binary（顶层入口与子进程 binary 不同的场景，如 wrapper fork 第三方 CLI）；非 fork 场景为 NULL；K7 决策', max_length=64, null=True),
        ),
    ]
