# Generated by Django 4.2.7 on 2026-07-04 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent_engine', '0015_permission_audit_team_space_identity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subagenttemplate',
            name='inherit_mode_default',
        ),
    ]
