# Generated by Django 4.2.7 on 2026-07-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_engine', '0017_rename_workteam_to_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliauditevent',
            name='organization_id',
            field=models.UUIDField(blank=True, help_text='租户 ID（跨库软引用 tabtinspace.Organization.id）。PRD §5.5 「授权数据 PII 隔离」硬性要求：所有 admin 查询 API 必须按 request.user.organization_id == row.organization_id 过滤，因此审计行必须含 organization_id 一等字段，避免 admin 通过 thread/user 反查跨库', null=True),
        ),
        migrations.AlterField(
            model_name='permissionaudit',
            name='organization_id',
            field=models.UUIDField(db_index=True, help_text='所属 Organization'),
        ),
    ]
