/* eslint-disable */
// ════════════════════════════════════════════════════════════════════
// 自动生成 — DO NOT EDIT MANUALLY
// Generated by @tabtin/wire-codegen (Wave 1 协议层)
// Source: packages/agent-wire/src/stream-content-block.ts (zod SSoT)
// 重新生成: pnpm --filter @tabtin/wire-codegen codegen
// 文档: docs/agent-runtime/wire-protocol.md
// ════════════════════════════════════════════════════════════════════
// 类型定义文件——consumer 不依赖 zod 时可仅用 .d.ts
/* eslint-disable */
// ════════════════════════════════════════════════════════════════════
// 自动生成 — DO NOT EDIT MANUALLY
// Generated by @tabtin/wire-codegen (Wave 1 协议层)
// Source: packages/agent-wire/src/stream-content-block.ts (zod SSoT)
// 重新生成: pnpm --filter @tabtin/wire-codegen codegen
// 文档: docs/agent-runtime/wire-protocol.md
// ════════════════════════════════════════════════════════════════════

/**
 * TabTin wire-protocol generated types (Anthropic Messages API alignment).
 *
 * 在 monorepo 内（推荐路径）：
 *   import type { ContentBlock, MessageStart } from '@tabtin/agent-wire';
 *
 * 在 monorepo 外（本文件就是为这种场景准备的）：
 *   import type { ContentBlock, MessageStart } from './wire-generated/wire-types';
 *
 * 两条路径功能完全等价，类型从同一份 zod schema 推导。
 */

export type {
  // Block 22 case 完整 union
  ContentBlock,
  // 单 case type 导出
  TextBlock,
  ToolUseBlock,
  ToolResultBlock,
  ThinkingBlock,
  RedactedThinkingBlock,
  ImageBlock,
  DocumentBlock,
  TabTinSourceRefBlock,
  TabTinSkillInvocationBlock,
  TabTinApprovalRequestBlock,
  TabTinRichContentBlock,
  TabTinSnapshot,
  // 公共子结构
  Citation,
  ImageSource,
  DocumentSource,
  ToolExecutionMetadata,
  CodeExecutionResultContent,
  ToolResultInlineBlock,
  // 6 envelope
  StreamEnvelopeBase,
  MessageStart,
  // 协议层 message_kind 三档语义分类
  MessageKind,
  MessageDelta,
  MessageStop,
  MessageUsage,
  MessageStopReason,
  ContentBlockStart,
  ContentBlockDelta,
  ContentBlockDeltaPayload,
  ContentBlockStop,
  // 顶层 union
  AnyContentBlockStreamEvent,
  // W4c-L5 · W4.5 第二波 B1：MessageStop.error_info 协议字段
  ErrorInfo,
  PartialReason,
} from '@tabtin/agent-wire';

export {
  // Schema (runtime validation)
  ContentBlockSchema,
  CitationSchema,
  ImageSourceSchema,
  DocumentSourceSchema,
  ToolResultInlineBlockSchema,
  StreamEnvelopeBaseSchema,
  MessageStartSchema,
  MessageKindSchema,
  MessageDeltaSchema,
  MessageStopSchema,
  ContentBlockStartSchema,
  ContentBlockDeltaSchema,
  ContentBlockDeltaPayloadSchema,
  ContentBlockStopSchema,
  AnyContentBlockStreamEventSchema,
  PROTOCOL_VERSION_V2,
  // W4c-L5 · W4.5 第二波 B1
  ErrorInfoSchema,
  PartialReasonSchema,
} from '@tabtin/agent-wire';

export {
  ContentBlockEvents,
  isContentBlockEvent,
} from '@tabtin/agent-wire';
export type { ContentBlockEventType } from '@tabtin/agent-wire';

