# Generated by Django 4.2.7 on 2026-03-04 20:27

import apps.services.common.base_models
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import uuid
from tabtin.migration_utils import PostgresOnlyOperation


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField(verbose_name='分块序号（从 0 开始）')),
                ('chunk_key', models.CharField(blank=True, default='', max_length=128, verbose_name='分块标识（如 heading Block ID）')),
                ('blob', models.BinaryField(verbose_name='zlib 压缩的 Y.js subdocument binary')),
                ('blob_size', models.PositiveIntegerField(default=0, verbose_name='blob 字节数')),
                ('block_count', models.PositiveIntegerField(default=0, verbose_name='该 chunk 包含的 Block 数量')),
                ('plaintext_preview', models.TextField(blank=True, default='', verbose_name='纯文本预览（用于目录/大纲，<200 字）')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tabdoc_chunk',
                'ordering': ['chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='DocHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(verbose_name='Workspace ID')),
                ('blob', models.BinaryField(verbose_name='Y.js binary（全量快照或增量 diff）')),
                ('is_snapshot', models.BooleanField(default=True, verbose_name='是否全量快照（False=增量 diff）')),
                ('editor_type', models.CharField(blank=True, default='', max_length=16, verbose_name='触发者类型 (human/agent)')),
                ('editor_id', models.CharField(blank=True, default='', max_length=64, verbose_name='触发者 ID')),
                ('expired_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='过期时间（TTL，命名版本为 NULL）')),
                ('is_named', models.BooleanField(default=False, verbose_name='是否用户手动保存的命名版本')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='版本名称')),
                ('pinned', models.BooleanField(default=False, verbose_name='是否置顶（不受 TTL/降采样影响）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tabdoc_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('agent_space_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(default='未命名文档', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('latest_version', models.PositiveIntegerField(default=0)),
                ('description_binary', models.BinaryField(blank=True, null=True, verbose_name='Y.js CRDT 二进制（source of truth）')),
                ('description_markdown', models.TextField(blank=True, default='<p></p>', verbose_name='Markdown/HTML 文本副本')),
                ('description_json', models.JSONField(blank=True, default=dict, verbose_name='ProseMirror JSON')),
                ('description_plaintext', models.TextField(blank=True, default='', verbose_name='纯文本（搜索用）')),
                ('last_editor_type', models.CharField(blank=True, choices=[('human', 'Human'), ('agent', 'Agent')], default='', max_length=16, verbose_name='最后编辑者类型')),
                ('last_editor_id', models.CharField(blank=True, default='', max_length=64, verbose_name='最后编辑者 ID')),
                ('icon', models.CharField(blank=True, default='', max_length=64, verbose_name='图标/Emoji')),
                ('cover_image', models.URLField(blank=True, default='', max_length=1024, verbose_name='封面图片 URL')),
                ('cover_position', models.FloatField(default=0.5, verbose_name='封面裁剪位置 (0-1)')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签列表')),
                ('properties', models.JSONField(blank=True, default=dict, verbose_name='自定义属性')),
                ('is_full_width', models.BooleanField(default=False, verbose_name='是否全宽展示')),
                ('font_style', models.CharField(choices=[('default', 'Default'), ('serif', 'Serif'), ('mono', 'Mono')], default='default', max_length=32, verbose_name='字体风格')),
            ],
            options={
                'db_table': 'tabdoc_document',
                'ordering': ['-updated_at'],
            },
            bases=(models.Model, apps.services.common.base_models.ContextSyncMixin),
        ),
        PostgresOnlyOperation(
            migrations.AddField(
                model_name='document',
                name='search_vector',
                field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True, verbose_name='搜索向量'),
            ),
        ),
        migrations.CreateModel(
            name='DocumentAdminActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('batch_archive', '批量归档'), ('batch_restore', '批量恢复'), ('single_archive', '单文档归档'), ('single_restore', '单文档恢复'), ('restore_version', '版本恢复'), ('update_permissions', '权限覆盖更新'), ('audit_export', '审计导出')], db_index=True, max_length=64, verbose_name='动作类型')),
                ('operator_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='操作人 ID')),
                ('operator_name', models.CharField(blank=True, default='', max_length=255, verbose_name='操作人展示名')),
                ('target_document_ids', models.JSONField(default=list, help_text='治理动作影响的文档 ID 列表', verbose_name='目标文档 ID 列表')),
                ('target_document_ids_text', models.TextField(blank=True, default='', help_text='格式: |doc_id_1|doc_id_2|，用于模糊检索', verbose_name='目标文档检索文本')),
                ('requested_count', models.PositiveIntegerField(default=0, verbose_name='请求总数')),
                ('updated_count', models.PositiveIntegerField(default=0, verbose_name='成功处理数')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='跳过数')),
                ('dry_run', models.BooleanField(default=False, verbose_name='是否 dry-run')),
                ('success', models.BooleanField(db_index=True, default=True, verbose_name='是否成功')),
                ('result_message', models.TextField(blank=True, default='', verbose_name='结果信息')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('request_payload', models.JSONField(default=dict, verbose_name='请求快照')),
                ('result_payload', models.JSONField(default=dict, verbose_name='结果快照')),
                ('trace_id', models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='链路追踪 ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '文档后台治理动作日志',
                'verbose_name_plural': '文档后台治理动作日志',
                'db_table': 'tabdoc_admin_action_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(choices=[('user', 'User'), ('role', 'Role'), ('agent', 'Agent')], max_length=20, verbose_name='权限主体类型')),
                ('subject_id', models.CharField(max_length=64, verbose_name='权限主体 ID')),
                ('permission', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('admin', 'Admin')], default='viewer', max_length=20, verbose_name='权限级别')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否生效')),
                ('granted_by', models.CharField(blank=True, default='', max_length=64, verbose_name='授权人 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tabdoc_permission',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('content_pm_json', models.JSONField(default=dict)),
                ('content_markdown', models.TextField(blank=True, default='')),
                ('content_plaintext', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tabdoc_revision',
                'ordering': ['-version', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(verbose_name='Workspace ID')),
                ('description_binary', models.BinaryField(blank=True, null=True)),
                ('description_markdown', models.TextField(blank=True, default='<p></p>')),
                ('description_json', models.JSONField(blank=True, default=dict)),
                ('description_plaintext', models.TextField(blank=True, default='')),
                ('version', models.PositiveIntegerField(blank=True, null=True)),
                ('last_saved_at', models.DateTimeField(verbose_name='原始保存时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tabdoc_version',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blob', models.BinaryField(verbose_name='Y.js update binary')),
                ('editor_type', models.CharField(blank=True, default='', max_length=16, verbose_name='编辑者类型 (human/agent)')),
                ('editor_id', models.CharField(blank=True, default='', max_length=64, verbose_name='编辑者 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='tabdoc.document')),
            ],
            options={
                'db_table': 'tabdoc_update',
                'ordering': ['created_at'],
            },
        ),
    ]
