# Generated by Django 4.2.7 on 2026-03-04 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tabdoc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabdoc_versions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='tabdoc.document'),
        ),
        migrations.AddField(
            model_name='documentrevision',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='tabdoc.document'),
        ),
        migrations.AddField(
            model_name='documentrevision',
            name='editor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabdoc_revisions_edited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentpermission',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabdoc_permissions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentpermission',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='tabdoc.document'),
        ),
        migrations.AddIndex(
            model_name='documentadminactionlog',
            index=models.Index(fields=['action_type', 'created_at'], name='docadm_action_created_idx'),
        ),
        migrations.AddIndex(
            model_name='documentadminactionlog',
            index=models.Index(fields=['operator_id', 'created_at'], name='docadm_operator_created_idx'),
        ),
        migrations.AddIndex(
            model_name='documentadminactionlog',
            index=models.Index(fields=['success', 'created_at'], name='docadm_success_created_idx'),
        ),
        migrations.AddIndex(
            model_name='documentadminactionlog',
            index=models.Index(fields=['dry_run', 'created_at'], name='docadm_dryrun_created_idx'),
        ),
        migrations.AddField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabdoc_documents_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='tabdoc.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabdoc_documents_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dochistory',
            name='base_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diffs', to='tabdoc.dochistory', verbose_name='增量 diff 基于的全量快照'),
        ),
        migrations.AddField(
            model_name='dochistory',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='tabdoc.document'),
        ),
        migrations.AddField(
            model_name='docchunk',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='tabdoc.document'),
        ),
        migrations.AddIndex(
            model_name='docupdate',
            index=models.Index(fields=['document', 'created_at'], name='docupd_doc_created_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['document', 'created_at'], name='docver_doc_created_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['document', 'version'], name='docver_doc_ver_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrevision',
            index=models.Index(fields=['document', 'version'], name='doc_revision_doc_ver_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentrevision',
            constraint=models.UniqueConstraint(fields=('document', 'version'), name='doc_revision_unique_version'),
        ),
        migrations.AddIndex(
            model_name='documentpermission',
            index=models.Index(fields=['document', 'is_active'], name='doc_perm_doc_active_idx'),
        ),
        migrations.AddIndex(
            model_name='documentpermission',
            index=models.Index(fields=['subject_type', 'subject_id'], name='doc_perm_subject_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentpermission',
            constraint=models.UniqueConstraint(fields=('document', 'subject_type', 'subject_id'), name='doc_permission_unique_subject'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['workspace_id', 'agent_space_id'], name='doc_ws_proj_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['agent_space_id', 'status'], name='doc_proj_status_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['parent', 'updated_at'], name='doc_parent_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['search_vector'], name='doc_search_vector_idx'),
        ),
        migrations.AddIndex(
            model_name='dochistory',
            index=models.Index(fields=['document', 'created_at'], name='dochist_doc_created_idx'),
        ),
        migrations.AddIndex(
            model_name='dochistory',
            index=models.Index(fields=['document', 'is_snapshot'], name='dochist_doc_snap_idx'),
        ),
        migrations.AddIndex(
            model_name='dochistory',
            index=models.Index(fields=['document', 'is_named'], name='dochist_doc_named_idx'),
        ),
        migrations.AddIndex(
            model_name='docchunk',
            index=models.Index(fields=['document', 'chunk_index'], name='docchunk_doc_idx_idx'),
        ),
        migrations.AddConstraint(
            model_name='docchunk',
            constraint=models.UniqueConstraint(fields=('document', 'chunk_index'), name='doc_chunk_doc_index_unique'),
        ),
    ]
