# Generated by Django 4.2.7 on 2026-03-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabdoc', '0004_fix_search_vector_gin_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='document',
            name='doc_ws_proj_idx',
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='doc_proj_status_idx',
        ),
        migrations.AlterField(
            model_name='document',
            name='agent_space_id',
            field=models.UUIDField(db_column='agent_space_id', db_index=True),
        ),
        migrations.RenameField(
            model_name='document',
            old_name='agent_space_id',
            new_name='space_id',
        ),
        migrations.AddField(
            model_name='document',
            name='owner_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['workspace_id', 'space_id'], name='doc_ws_proj_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['space_id', 'status'], name='doc_proj_status_idx'),
        ),
    ]
