# Generated by Django 4.2.7 on 2026-03-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabdoc', '0006_alter_document_space_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_private',
            field=models.BooleanField(default=False, help_text='私密文档不回退空间权限，必须有直接权限记录才能访问', verbose_name='是否私密文档'),
        ),
    ]
