# Generated by Django 4.2.7 on 2026-03-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabdoc', '0008_workspace_to_workteam_rename'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documentpermission',
            name='doc_permission_unique_subject',
        ),
        migrations.RemoveIndex(
            model_name='docchunk',
            name='docchunk_doc_idx_idx',
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='doc_ws_proj_idx',
        ),
        migrations.AlterField(
            model_name='dochistory',
            name='workteam_id',
            field=models.UUIDField(verbose_name='Workteam ID'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='workteam_id',
            field=models.UUIDField(verbose_name='Workteam ID'),
        ),
        migrations.AddIndex(
            model_name='dochistory',
            index=models.Index(fields=['document', 'expired_at'], name='dochist_doc_expired_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['workteam_id', 'space_id'], name='doc_ws_proj_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentpermission',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('document', 'subject_type', 'subject_id'), name='doc_perm_unique_active_subject'),
        ),
    ]
