# Generated by Django 4.2.7 on 2026-03-29 12:03

import apps.tabdoc.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tabdoc', '0009_remove_documentpermission_doc_permission_unique_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dochistory',
            name='editor_type',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='触发者类型 (user/agent/system)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='last_editor_type',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('agent', 'Agent'), ('system', 'System')], default='', max_length=16, verbose_name='最后编辑者类型'),
        ),
        migrations.AlterField(
            model_name='docupdate',
            name='editor_type',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='编辑者类型 (user/agent/system)'),
        ),
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_type', models.CharField(choices=[('public', '公开链接'), ('workteam', '团队限定')], default='public', max_length=20, verbose_name='分享类型')),
                ('share_id', models.CharField(default=apps.tabdoc.models._generate_share_id, max_length=20, unique=True, verbose_name='分享 ID（短链接）')),
                ('password_hash', models.CharField(blank=True, max_length=255, verbose_name='访问密码哈希')),
                ('permission', models.CharField(choices=[('view', '只读'), ('comment', '可评论'), ('edit', '可编辑')], default='view', max_length=20, verbose_name='权限')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('max_visits', models.IntegerField(blank=True, null=True, verbose_name='最大访问次数')),
                ('visit_count', models.IntegerField(default=0, verbose_name='访问计数')),
                ('workteam_id', models.CharField(blank=True, help_text='share_type=workteam 时必填', max_length=36, verbose_name='限定 Workteam ID')),
                ('allow_download', models.BooleanField(default=True, verbose_name='允许下载')),
                ('allow_copy', models.BooleanField(default=True, verbose_name='允许复制内容')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否生效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabdoc_shares_created', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='tabdoc.document', verbose_name='所属文档')),
            ],
            options={
                'verbose_name': '文档分享',
                'verbose_name_plural': '文档分享',
                'db_table': 'tabdoc_share',
                'indexes': [models.Index(fields=['document', 'is_active'], name='docshare_doc_active_idx'), models.Index(fields=['share_type', 'workteam_id'], name='docshare_type_wt_idx'), models.Index(fields=['created_at'], name='docshare_created_idx')],
            },
        ),
    ]
