# Generated by Django 4.2.7 on 2026-06-05 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tabdoc', '0011_alter_documentpermission_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabdoc_documents_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabdoc_documents_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentpermission',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabdoc_permissions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentrevision',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabdoc_revisions_edited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentshare',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabdoc_shares_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabdoc_versions_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
