# Generated by Django 4.2.7 on 2026-06-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabdoc', '0016_merge_document_cover_image_and_share_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='space_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
