# Generated by Django 4.2.7 on 2026-07-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabdoc', '0018_documentsharecomment_mentions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentadminactionlog',
            name='action_type',
            field=models.CharField(choices=[('batch_archive', '批量归档'), ('batch_restore', '批量恢复'), ('batch_trash', '批量逻辑删除'), ('batch_untrash', '批量回收站恢复'), ('single_archive', '单文档归档'), ('single_restore', '单文档恢复'), ('single_trash', '单文档逻辑删除'), ('single_untrash', '单文档回收站恢复'), ('restore_version', '版本恢复'), ('update_permissions', '权限覆盖更新'), ('audit_export', '审计导出')], db_index=True, max_length=64, verbose_name='动作类型'),
        ),
    ]
