# Generated by Django 4.2.7 on 2026-07-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabdoc', '0020_rename_workteam_to_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dochistory',
            name='organization_id',
            field=models.UUIDField(verbose_name='Organization ID'),
        ),
        migrations.AlterField(
            model_name='documentshare',
            name='organization_id',
            field=models.CharField(blank=True, help_text='share_type=organization 时必填', max_length=36, verbose_name='限定 Organization ID'),
        ),
        migrations.AlterField(
            model_name='documentshare',
            name='share_type',
            field=models.CharField(choices=[('public', '公开链接'), ('organization', '组织限定')], default='public', max_length=20, verbose_name='分享类型'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='organization_id',
            field=models.UUIDField(verbose_name='Organization ID'),
        ),
    ]
