# Generated by Django 4.2.7 on 2026-07-26 08:52

import apps.tabdoc.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oss', '0014_widen_filerecord_url_fields'),
        ('tabdoc', '0023_documentshare_one_active_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='HtmlArtifactShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_id', models.CharField(default=apps.tabdoc.models._generate_share_id, max_length=20, unique=True, verbose_name='分享 ID')),
                ('visibility', models.CharField(choices=[('organization', '组织内可见'), ('public', '所有人可见')], default='organization', max_length=20, verbose_name='可见范围')),
                ('organization_id', models.CharField(blank=True, help_text='visibility=organization 时必填；与 Document.organization_id 对齐', max_length=36, verbose_name='Organization ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否生效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='html_artifact_shares_created', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='html_artifact_shares', to='tabdoc.document', verbose_name='所属文档')),
                ('file_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='html_artifact_shares', to='oss.filerecord', verbose_name='HTML 文件')),
            ],
            options={
                'verbose_name': 'HTML 块独立分享',
                'verbose_name_plural': 'HTML 块独立分享',
                'db_table': 'tabdoc_html_artifact_share',
                'indexes': [models.Index(fields=['document', 'file_record', 'is_active'], name='htmlashare_doc_file_active_idx'), models.Index(fields=['visibility', 'organization_id'], name='htmlashare_vis_org_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='htmlartifactshare',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('document', 'file_record'), name='htmlashare_one_active_per_artifact'),
        ),
    ]
