# Generated by Django 4.2.7 on 2026-03-04 20:27

import apps.tabchat.constants
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import uuid
from tabtin.migration_utils import PostgresOnlyOperation


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(db_index=True, max_length=100)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'DM'), (2, 'GROUP')], default=apps.tabchat.constants.ConversationType['GROUP'])),
                ('dm_hash', models.CharField(blank=True, db_index=True, help_text='DM 成员哈希 sha256(sorted user_ids)，保证去重', max_length=64, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('created_by', models.CharField(max_length=100)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_preview', models.CharField(blank=True, default='', max_length=200)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tabchat_conversation',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sender_id', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('message_type', models.PositiveSmallIntegerField(choices=[(1, 'TEXT'), (2, 'SYSTEM'), (3, 'FILE'), (4, 'IMAGE')], default=apps.tabchat.constants.MessageType['TEXT'])),
                ('has_attachment', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tabchat.conversation')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='tabchat.message')),
            ],
            options={
                'db_table': 'tabchat_message',
            },
        ),
        PostgresOnlyOperation(
            migrations.AddField(
                model_name='message',
                name='search_tsvector',
                field=django.contrib.postgres.search.SearchVectorField(null=True),
            ),
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('flags', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to='tabchat.conversation')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to='tabchat.message')),
            ],
            options={
                'db_table': 'tabchat_user_message',
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('emoji', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='tabchat.message')),
            ],
            options={
                'db_table': 'tabchat_message_reaction',
            },
        ),
        migrations.CreateModel(
            name='ConversationMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('role', models.PositiveSmallIntegerField(choices=[(3, 'OWNER'), (2, 'ADMIN'), (1, 'MEMBER')], default=apps.tabchat.constants.MemberRole['MEMBER'])),
                ('is_muted', models.BooleanField(default=False)),
                ('pinned', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tabchat.conversation')),
            ],
            options={
                'db_table': 'tabchat_conversation_member',
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['workspace_id', '-last_message_at'], name='tabchat_conv_ws_last_msg_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('dm_hash__isnull', False)), fields=('workspace_id', 'dm_hash'), name='tabchat_conv_ws_dmhash_uniq'),
        ),
        migrations.AddIndex(
            model_name='usermessage',
            index=models.Index(fields=['user_id', 'conversation', '-message_id'], name='tabchat_um_user_conv_msg_idx'),
        ),
        migrations.AddConstraint(
            model_name='usermessage',
            constraint=models.UniqueConstraint(fields=('user_id', 'message'), name='tabchat_um_user_msg_uniq'),
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['message'], name='tabchat_reaction_msg_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagereaction',
            constraint=models.UniqueConstraint(fields=('message', 'user_id', 'emoji'), name='tabchat_reaction_msg_user_emoji_uniq'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', '-created_at'], name='tabchat_msg_conv_created_idx'),
        ),
        PostgresOnlyOperation(
            migrations.AddIndex(
                model_name='message',
                index=django.contrib.postgres.indexes.GinIndex(fields=['search_tsvector'], name='tabchat_msg_search_gin_idx'),
            ),
        ),
        migrations.AddIndex(
            model_name='conversationmember',
            index=models.Index(fields=['user_id', 'conversation'], name='tabchat_member_user_conv_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationmember',
            constraint=models.UniqueConstraint(fields=('conversation', 'user_id'), name='tabchat_member_conv_user_uniq'),
        ),
    ]
