# Generated by Django 4.2.7 on 2026-03-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabchat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='space_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='关联的 Space UUID（Phase 2A：dm 类型 Space）', null=True),
        ),
    ]
