# Generated by Django 4.2.7 on 2026-03-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabchat', '0003_workspace_to_workteam_rename'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conversation',
            name='tabchat_conv_ws_dmhash_uniq',
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='tabchat_conv_ws_last_msg_idx',
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['workteam_id', '-last_message_at'], name='tabchat_conv_ws_last_msg_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('dm_hash__isnull', False)), fields=('workteam_id', 'dm_hash'), name='tabchat_conv_ws_dmhash_uniq'),
        ),
    ]
