# Generated by Django 4.2.7 on 2026-06-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabchat', '0004_remove_conversation_tabchat_conv_ws_dmhash_uniq_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conversationmember',
            name='tabchat_member_conv_user_uniq',
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='agent_id',
            field=models.CharField(blank=True, help_text='AI Agent 成员（与 user_id 互斥，二选一）', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_type',
            field=models.CharField(default='user', help_text='发送者身份类型：user（人）/ agent（AI）。TC-8', max_length=10),
        ),
        migrations.AlterField(
            model_name='conversationmember',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='conversationmember',
            index=models.Index(fields=['agent_id', 'conversation'], name='tabchat_member_agent_conv_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationmember',
            constraint=models.UniqueConstraint(condition=models.Q(('user_id__isnull', False)), fields=('conversation', 'user_id'), name='tabchat_member_conv_user_uniq'),
        ),
        migrations.AddConstraint(
            model_name='conversationmember',
            constraint=models.UniqueConstraint(condition=models.Q(('agent_id__isnull', False)), fields=('conversation', 'agent_id'), name='tabchat_member_conv_agent_uniq'),
        ),
        migrations.AddConstraint(
            model_name='conversationmember',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('agent_id__isnull', True), ('user_id__isnull', False)), models.Q(('agent_id__isnull', False), ('user_id__isnull', True)), _connector='OR'), name='tabchat_member_user_xor_agent'),
        ),
    ]
