# Generated by Django 4.2.7 on 2026-06-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabchat', '0006_conversationmember_history_cleared_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='pinned_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(condition=models.Q(('is_pinned', True)), fields=['conversation', '-pinned_at'], name='tabchat_msg_pinned_idx'),
        ),
    ]
