# Generated by Django 4.2.7 on 2026-06-27 03:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tabchat', '0010_message_search_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='space_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='历史 shadow Space 软引用（deprecated）。新建 DM/GROUP 会话不再写入。', null=True),
        ),
        migrations.AlterField(
            model_name='conversationlabel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
