# Generated by Django 4.2.7 on 2026-07-12 02:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


def clear_legacy_message_data(apps, schema_editor):
    Message = apps.get_model("tabchat", "Message")
    Conversation = apps.get_model("tabchat", "Conversation")
    db_alias = schema_editor.connection.alias

    Message.objects.using(db_alias).all().delete()
    Conversation.objects.using(db_alias).update(
        last_message_at=None,
        last_message_preview="",
        latest_message_seq=0,
    )


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('tabchat', '0014_rename_workteam_to_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMentionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_id', models.CharField(max_length=100)),
                ('organization_id', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('claim_token', models.UUIDField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('session_id', models.UUIDField(blank=True, null=True)),
                ('billing_idempotency_key', models.CharField(max_length=200, unique=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tabchat_agent_mention_job',
            },
        ),
        migrations.CreateModel(
            name='ConversationUserState',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('last_read_seq', models.BigIntegerField(default=0)),
                ('history_cleared_seq', models.BigIntegerField(default=0)),
                ('muted', models.BooleanField(default=False)),
                ('pinned', models.BooleanField(default=False)),
                ('notification_level', models.CharField(default='all', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tabchat_conversation_user_state',
            },
        ),
        migrations.CreateModel(
            name='IMEventOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain_event_id', models.UUIDField()),
                ('event_id', models.UUIDField(unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('organization_id', models.CharField(db_index=True, max_length=100)),
                ('target_channels', models.JSONField(default=list)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('publishing', 'Publishing'), ('retry', 'Retry'), ('delivered', 'Delivered'), ('dead', 'Dead')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('claim_token', models.UUIDField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tabchat_im_event_outbox',
            },
        ),
        migrations.CreateModel(
            name='MessageMention',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('agent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mention_type', models.CharField(choices=[('user', 'User'), ('agent', 'Agent')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tabchat_message_mention',
            },
        ),
        migrations.CreateModel(
            name='MessageUserState',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('starred', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tabchat_message_user_state',
            },
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='message',
        ),
        migrations.RemoveField(
            model_name='conversationmember',
            name='history_cleared_at',
        ),
        migrations.RemoveField(
            model_name='conversationmember',
            name='is_muted',
        ),
        migrations.RemoveField(
            model_name='conversationmember',
            name='pinned',
        ),
        migrations.AddField(
            model_name='conversation',
            name='latest_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tabchat.message'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='latest_message_seq',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(check=models.Q(('latest_message_seq__gte', 0)), name='tabchat_conv_latest_seq_nonneg'),
        ),
        migrations.RunPython(
            clear_legacy_message_data,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='message',
            name='client_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='counts_as_unread',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='message',
            name='mention_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='seq',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('conversation', 'seq'), name='tabchat_msg_conv_seq_uniq'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id__isnull', False)), fields=('conversation', 'sender_type', 'sender_id', 'client_request_id'), name='tabchat_msg_sender_request_uniq'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(check=models.Q(('seq__gt', 0)), name='tabchat_msg_seq_positive'),
        ),
        migrations.DeleteModel(
            name='UserMessage',
        ),
        migrations.AddField(
            model_name='messageuserstate',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='tabchat.message'),
        ),
        migrations.AddField(
            model_name='messagemention',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_mentions', to='tabchat.conversation'),
        ),
        migrations.AddField(
            model_name='messagemention',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='tabchat.message'),
        ),
        migrations.AddField(
            model_name='imeventoutbox',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbox_events', to='tabchat.conversation'),
        ),
        migrations.AddField(
            model_name='imeventoutbox',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbox_events', to='tabchat.message'),
        ),
        migrations.AddField(
            model_name='conversationuserstate',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='tabchat.conversation'),
        ),
        migrations.AddField(
            model_name='agentmentionjob',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_mention_jobs', to='tabchat.conversation'),
        ),
        migrations.AddField(
            model_name='agentmentionjob',
            name='final_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tabchat.message'),
        ),
        migrations.AddField(
            model_name='agentmentionjob',
            name='source_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_mention_jobs', to='tabchat.message'),
        ),
        migrations.AddIndex(
            model_name='messageuserstate',
            index=models.Index(fields=['user_id', 'starred', 'message'], name='tabchat_msg_state_star_idx'),
        ),
        migrations.AddIndex(
            model_name='messageuserstate',
            index=models.Index(fields=['user_id', 'hidden', 'message'], name='tabchat_msg_state_hide_idx'),
        ),
        migrations.AddConstraint(
            model_name='messageuserstate',
            constraint=models.UniqueConstraint(fields=('message', 'user_id'), name='tabchat_msg_state_user_uniq'),
        ),
        migrations.AddIndex(
            model_name='messagemention',
            index=models.Index(fields=['user_id', 'conversation', 'message'], name='tabchat_mention_user_conv_idx'),
        ),
        migrations.AddIndex(
            model_name='messagemention',
            index=models.Index(fields=['agent_id', 'message'], name='tabchat_mention_agent_msg_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagemention',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('agent_id__isnull', True), ('user_id__isnull', False)), models.Q(('agent_id__isnull', False), ('user_id__isnull', True)), _connector='OR'), name='tabchat_mention_user_xor_agent'),
        ),
        migrations.AddConstraint(
            model_name='messagemention',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('agent_id__isnull', True), ('mention_type', 'user'), ('user_id__isnull', False)), models.Q(('agent_id__isnull', False), ('mention_type', 'agent'), ('user_id__isnull', True)), _connector='OR'), name='tabchat_mention_subject_type_match'),
        ),
        migrations.AddConstraint(
            model_name='messagemention',
            constraint=models.UniqueConstraint(condition=models.Q(('user_id__isnull', False)), fields=('message', 'user_id'), name='tabchat_mention_msg_user_uniq'),
        ),
        migrations.AddConstraint(
            model_name='messagemention',
            constraint=models.UniqueConstraint(condition=models.Q(('agent_id__isnull', False)), fields=('message', 'agent_id'), name='tabchat_mention_msg_agent_uniq'),
        ),
        migrations.AddIndex(
            model_name='imeventoutbox',
            index=models.Index(fields=['status', 'next_retry_at', 'created_at'], name='tabchat_outbox_ready_idx'),
        ),
        migrations.AddIndex(
            model_name='imeventoutbox',
            index=models.Index(fields=['status', 'lease_expires_at'], name='tabchat_outbox_lease_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationuserstate',
            index=models.Index(fields=['user_id', 'conversation'], name='tabchat_state_user_conv_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationuserstate',
            constraint=models.UniqueConstraint(fields=('conversation', 'user_id'), name='tabchat_conv_state_user_uniq'),
        ),
        migrations.AddConstraint(
            model_name='conversationuserstate',
            constraint=models.CheckConstraint(check=models.Q(('last_read_seq__gte', 0)), name='tabchat_conv_state_read_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='conversationuserstate',
            constraint=models.CheckConstraint(check=models.Q(('history_cleared_seq__gte', 0)), name='tabchat_conv_state_clear_nonneg'),
        ),
        migrations.AddIndex(
            model_name='agentmentionjob',
            index=models.Index(fields=['status', 'lease_expires_at', 'created_at'], name='tabchat_agent_job_ready_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentmentionjob',
            constraint=models.UniqueConstraint(fields=('source_message', 'agent_id'), name='tabchat_agent_job_msg_agent_uniq'),
        ),
    ]
