# Generated by Django 4.2.7 on 2026-07-20 10:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "tabchat",
            "0015_agentmentionjob_conversationuserstate_imeventoutbox_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="HandoffPackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("organization_id", models.CharField(db_index=True, max_length=100)),
                (
                    "initiator_user_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "initiator_agent_id",
                    models.CharField(
                        blank=True,
                        help_text="Agent 发起的交接包（与 initiator_user_id 互斥，二选一）",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        help_text="工作目标（必填，短文本）", max_length=500
                    ),
                ),
                (
                    "progress_json",
                    models.JSONField(
                        default=list, help_text="当前进展要点数组：[{text}]"
                    ),
                ),
                (
                    "next_steps_json",
                    models.JSONField(
                        default=list,
                        help_text="下一步 checklist 数组：[{text, checked}]",
                    ),
                ),
                (
                    "risks_json",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="待确认/风险数组：[{text, high_risk}]",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("view_only", "仅查看"), ("continuable", "可继续")],
                        default="continuable",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("sent", "已发送"),
                            ("superseded", "已被新版本取代"),
                            ("revoked", "已撤销"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="补充版本号，Phase 3 起使用"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "card_message",
                    models.ForeignKey(
                        blank=True,
                        help_text="发送后承载卡片的 IM 消息",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tabchat.message",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handoff_packages",
                        to="tabchat.conversation",
                    ),
                ),
            ],
            options={
                "db_table": "tabchat_handoff_package",
            },
        ),
        migrations.CreateModel(
            name="HandoffEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "actor_user_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "actor_agent_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "创建"),
                            ("sent", "发送"),
                            ("viewed", "查看"),
                            ("acknowledged", "已了解"),
                            ("taken_over", "由我继续"),
                            ("delegated", "交给 Agent"),
                            ("supplemented", "补充"),
                            ("revoked", "撤销"),
                            ("rejected", "拒绝"),
                        ],
                        max_length=20,
                    ),
                ),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="tabchat.handoffpackage",
                    ),
                ),
            ],
            options={
                "db_table": "tabchat_handoff_event",
            },
        ),
        migrations.CreateModel(
            name="HandoffReference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, help_text="归属的包版本"),
                ),
                (
                    "ref_type",
                    models.CharField(
                        choices=[
                            ("im_message", "IM 消息"),
                            ("document", "文档"),
                            ("table", "表格"),
                            ("attachment", "附件"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(
                        help_text="目标资源 id（软引用，跨 App；im_message 为 Message.id）",
                        max_length=100,
                    ),
                ),
                (
                    "title_snapshot",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "summary_snapshot",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "source_link",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="回链信息：im_message 存 {conversation_id, message_id, seq}；doc/table 存 {space_id, organization_id}",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="tabchat.handoffpackage",
                    ),
                ),
            ],
            options={
                "db_table": "tabchat_handoff_reference",
                "indexes": [
                    models.Index(
                        fields=["package", "version"],
                        name="tabchat_handoff_ref_pkg_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HandoffRecipient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "agent_id",
                    models.CharField(
                        blank=True,
                        help_text="Agent 接收者（Phase 2 起；与 user_id 互斥）",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("sent", "已发送"),
                            ("viewed", "已查看"),
                            ("acknowledged", "已了解"),
                            ("taking_over", "由我继续"),
                            ("delegated_to_agent", "已交给 Agent"),
                            ("rejected", "已拒绝"),
                        ],
                        default="sent",
                        max_length=32,
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="接手备注 / 拒绝原因",
                        max_length=500,
                    ),
                ),
                (
                    "linked_session_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Phase 2：接手后创建的 Agent 任务会话",
                        max_length=100,
                    ),
                ),
                (
                    "linked_tracker_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Phase 3：关联的 Tracker 任务引用",
                        max_length=200,
                    ),
                ),
                ("state_changed_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="tabchat.handoffpackage",
                    ),
                ),
            ],
            options={
                "db_table": "tabchat_handoff_recipient",
                "indexes": [
                    models.Index(
                        fields=["user_id", "-created_at"],
                        name="tabchat_handoff_rcpt_user_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="handoffrecipient",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("agent_id__isnull", True), ("user_id__isnull", False)),
                    models.Q(("agent_id__isnull", False), ("user_id__isnull", True)),
                    _connector="OR",
                ),
                name="tabchat_handoff_rcpt_xor",
            ),
        ),
        migrations.AddConstraint(
            model_name="handoffrecipient",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user_id__isnull", False)),
                fields=("package", "user_id"),
                name="tabchat_handoff_rcpt_user_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="handoffrecipient",
            constraint=models.UniqueConstraint(
                condition=models.Q(("agent_id__isnull", False)),
                fields=("package", "agent_id"),
                name="tabchat_handoff_rcpt_agent_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="handoffpackage",
            index=models.Index(
                fields=["conversation", "-created_at"], name="tabchat_handoff_conv_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="handoffpackage",
            index=models.Index(
                fields=["initiator_user_id", "-created_at"],
                name="tabchat_handoff_init_user_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="handoffpackage",
            index=models.Index(
                fields=["initiator_agent_id", "-created_at"],
                name="tabchat_handoff_init_agent_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="handoffpackage",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("initiator_agent_id__isnull", True),
                        ("initiator_user_id__isnull", False),
                    ),
                    models.Q(
                        ("initiator_agent_id__isnull", False),
                        ("initiator_user_id__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="tabchat_handoff_initiator_xor",
            ),
        ),
        migrations.AddConstraint(
            model_name="handoffpackage",
            constraint=models.CheckConstraint(
                check=models.Q(("version__gte", 1)),
                name="tabchat_handoff_version_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="handoffevent",
            index=models.Index(
                fields=["package", "-created_at"], name="tabchat_handoff_evt_pkg_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="handoffevent",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("actor_agent_id__isnull", True),
                        ("actor_user_id__isnull", False),
                    ),
                    models.Q(
                        ("actor_agent_id__isnull", False),
                        ("actor_user_id__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="tabchat_handoff_evt_actor_xor",
            ),
        ),
    ]
