# Generated by Django 4.2.7 on 2026-07-21 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabchat", "0016_handoffpackage_handoffevent_handoffreference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="handoffreference",
            name="frozen_snapshot_json",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="仅快照型材料（chat_session）使用：冻结的清洗版会话历史 {title, message_count, turns:[...]}；回源型材料此字段为空 {}",
            ),
        ),
        migrations.AlterField(
            model_name="handoffreference",
            name="ref_type",
            field=models.CharField(
                choices=[
                    ("im_message", "IM 消息"),
                    ("document", "文档"),
                    ("table", "表格"),
                    ("attachment", "附件"),
                    ("chat_session", "Agent 会话"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="handoffreference",
            name="source_link",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="回链信息：im_message 存 {conversation_id, message_id, seq}；doc/table 存 {space_id, organization_id}；chat_session 存 {session_id}",
            ),
        ),
    ]
