# Generated by Django 4.2.7 on 2026-07-28 07:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tabchat', '0017_handoffreference_frozen_snapshot_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceAccessRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('table', '表格'), ('document', '文档')], max_length=20)),
                ('resource_id', models.UUIDField(db_index=True)),
                ('requester_id', models.CharField(max_length=100)),
                ('owner_id', models.CharField(db_index=True, max_length=100)),
                ('role', models.CharField(choices=[('viewer', '查看者')], default='viewer', max_length=20)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('approved', '已批准'), ('superseded', '已失效')], db_index=True, default='pending', max_length=20)),
                ('resolved_by', models.CharField(blank=True, default='', max_length=100)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_access_requests', to='tabchat.conversation')),
                ('source_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_access_requests', to='tabchat.message')),
            ],
            options={
                'db_table': 'tabchat_resource_access_request',
                'indexes': [models.Index(fields=['owner_id', 'status', '-created_at'], name='tabchat_rar_owner_st_idx'), models.Index(fields=['requester_id', 'status', '-created_at'], name='tabchat_rar_req_st_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='resourceaccessrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('resource_type', 'resource_id', 'requester_id'), name='tabchat_rar_pend_res_req_uq'),
        ),
        migrations.AddConstraint(
            model_name='resourceaccessrequest',
            constraint=models.CheckConstraint(check=models.Q(('role', 'viewer')), name='tabchat_rar_role_viewer_only'),
        ),
    ]
