# Generated by Django 4.2.7 on 2026-08-19.

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tabtinspace", "0145_shared_resource_placement_dismissed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tabchat", "0031_agentmentionjob_session_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationMembershipWindow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("visible_from_seq", models.PositiveBigIntegerField(default=1)),
                ("visible_until_seq", models.PositiveBigIntegerField(blank=True, null=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"db_table": "tabchat_conversation_membership_window"},
        ),
        migrations.CreateModel(
            name="ExternalContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("friend", "Friend"),
                            ("blocked", "Blocked"),
                            ("suspended", "Suspended"),
                            ("removed", "Removed"),
                        ],
                        default="friend",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "tabchat_external_contact"},
        ),
        migrations.AddField(
            model_name="conversation",
            name="creation_request_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="conversation",
            name="is_external",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="一旦外部联系人加入即永久为 true",
            ),
        ),
        migrations.AddField(
            model_name="conversationmember",
            name="left_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conversationmember",
            name="participant_organization_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="成员加入会话时的组织展示上下文；不作为联系人关系主键",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="conversationmember",
            name="removed_by",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="conversationmember",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("left", "Left"),
                    ("removed", "Removed"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="conversationmember",
            index=models.Index(
                fields=["conversation", "status"],
                name="tabchat_member_conv_status_idx",
            ),
        ),
        migrations.AddField(
            model_name="externalcontact",
            name="owner_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_external_contacts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="externalcontact",
            name="peer_organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="external_contact_profiles",
                to="tabtinspace.organization",
            ),
        ),
        migrations.AddField(
            model_name="externalcontact",
            name="peer_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="external_contact_peers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="conversationmembershipwindow",
            name="conversation_member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visibility_windows",
                to="tabchat.conversationmember",
            ),
        ),
        migrations.AddIndex(
            model_name="externalcontact",
            index=models.Index(
                fields=["owner_user", "relationship", "updated_at"],
                name="tabchat_external_owner_rel_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                condition=~models.Q(creation_request_id=""),
                fields=("organization_id", "created_by", "creation_request_id"),
                name="tabchat_group_creation_request_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalcontact",
            constraint=models.UniqueConstraint(
                fields=("owner_user", "peer_user"),
                name="tabchat_external_contact_owner_peer_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalcontact",
            constraint=models.CheckConstraint(
                check=~models.Q(owner_user=models.F("peer_user")),
                name="tabchat_external_contact_not_self",
            ),
        ),
        migrations.AddIndex(
            model_name="conversationmembershipwindow",
            index=models.Index(
                fields=[
                    "conversation_member",
                    "visible_from_seq",
                    "visible_until_seq",
                ],
                name="tabchat_member_window_seq_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="conversationmembershipwindow",
            constraint=models.UniqueConstraint(
                condition=models.Q(visible_until_seq__isnull=True),
                fields=("conversation_member",),
                name="tabchat_member_one_open_window",
            ),
        ),
        migrations.AddConstraint(
            model_name="conversationmembershipwindow",
            constraint=models.CheckConstraint(
                check=(
                    models.Q(visible_until_seq__isnull=True)
                    | models.Q(visible_until_seq__gte=models.F("visible_from_seq"))
                ),
                name="tabchat_member_window_order",
            ),
        ),
    ]
