"""tabchat.0021 遗留 MessageReaction 结构的 PostgreSQL 场景测试。"""

from apps.services.migration_guard.scenario import PostgresMigrationScenarioTestCase


class ReconcileMessageReactionSchemaScenario(PostgresMigrationScenarioTestCase):
    app_label = "tabchat"
    migrate_from = "0020_resource_access_request_message_ref"
    migrate_to = "0021_reconcile_orphaned_message_reaction_schema"

    def test_empty_legacy_table_is_reconciled(self) -> None:
        self.run_migration_scenario()

    def seed_before_migration(self, connection) -> None:
        self.execute("DROP TABLE tabchat_message_reaction")
        self.execute(
            """
            CREATE TABLE tabchat_message_reaction (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                message_ref uuid NOT NULL,
                user_id varchar(100) NOT NULL,
                emoji varchar(10) NOT NULL,
                created_at timestamptz NOT NULL,
                conversation_id uuid NOT NULL
                    REFERENCES tabchat_conversation(id) DEFERRABLE INITIALLY DEFERRED,
                CONSTRAINT tabchat_reaction_conv_ref_user_emoji_uniq
                    UNIQUE (conversation_id, message_ref, user_id, emoji)
            )
            """
        )

    def assert_after_migration(self, connection) -> None:
        rows = self.fetchall(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = 'tabchat_message_reaction'
            ORDER BY ordinal_position
            """
        )
        columns = {row[0] for row in rows}
        self.assertIn("message_id", columns)
        self.assertNotIn("message_ref", columns)
        self.assertNotIn("conversation_id", columns)

        constraint = self.fetchone(
            """
            SELECT COUNT(*)
            FROM pg_constraint
            WHERE conname = 'tabchat_reaction_msg_user_emoji_uniq'
            """
        )
        self.assertEqual(constraint[0], 1)


class NonEmptyMessageReactionSchemaScenario(PostgresMigrationScenarioTestCase):
    app_label = "tabchat"
    migrate_from = "0020_resource_access_request_message_ref"
    migrate_to = "0021_reconcile_orphaned_message_reaction_schema"

    def test_non_empty_legacy_table_fails_closed(self) -> None:
        with self.assertRaisesRegex(
            AssertionError,
            "必须先制定显式数据映射方案",
        ):
            self.run_migration_scenario()

    def seed_before_migration(self, connection) -> None:
        self.execute("DROP TABLE tabchat_message_reaction")
        self.execute(
            """
            CREATE TABLE tabchat_message_reaction (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                message_ref uuid NOT NULL,
                user_id varchar(100) NOT NULL,
                emoji varchar(10) NOT NULL,
                created_at timestamptz NOT NULL,
                conversation_id uuid NOT NULL
            )
            """
        )
        self.execute(
            """
            INSERT INTO tabchat_message_reaction (
                message_ref, user_id, emoji, created_at, conversation_id
            ) VALUES (
                '11111111-1111-1111-1111-111111111111',
                'migration-test-user',
                'ok',
                NOW(),
                '22222222-2222-2222-2222-222222222222'
            )
            """
        )

    def assert_after_migration(self, connection) -> None:
        self.fail("非空遗留表不应完成自动迁移")
