# Generated by Django 4.2.7 on 2026-03-04 20:27

import apps.services.payment.models
from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCallback',
            fields=[
                ('id', models.CharField(default=apps.services.payment.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(db_index=True, max_length=20, verbose_name='支付方式')),
                ('callback_data', models.JSONField(verbose_name='回调数据')),
                ('is_verified', models.BooleanField(default=False, verbose_name='是否验证通过')),
                ('is_processed', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '支付回调',
                'verbose_name_plural': '支付回调',
                'db_table': 'services_payment_callback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.CharField(default=apps.services.payment.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('order_no', models.CharField(db_index=True, default=apps.services.payment.models.generate_order_no, max_length=32, unique=True, verbose_name='订单号')),
                ('workspace_id', models.CharField(blank=True, db_index=True, default='', help_text='该订单归属的工作空间，为空时兼容旧用户级订单', max_length=100, verbose_name='工作空间ID')),
                ('order_type', models.CharField(choices=[('membership', '会员购买'), ('credits', '点券充值')], db_index=True, max_length=20, verbose_name='订单类型')),
                ('subject', models.CharField(max_length=200, verbose_name='订单标题')),
                ('description', models.TextField(blank=True, verbose_name='订单描述')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='订单金额（元）')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='实付金额（元）')),
                ('payment_method', models.CharField(choices=[('alipay', '支付宝'), ('wechat', '微信支付')], db_index=True, max_length=20, verbose_name='支付方式')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paying', '支付中'), ('paid', '已支付'), ('cancelled', '已取消'), ('failed', '支付失败'), ('completed', '已完成')], db_index=True, default='pending', max_length=20, verbose_name='订单状态')),
                ('third_party_order_no', models.CharField(blank=True, max_length=100, verbose_name='第三方订单号')),
                ('third_party_trade_no', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='第三方交易号')),
                ('business_data', models.JSONField(default=dict, help_text='存储会员等级、点券套餐等业务信息', verbose_name='业务数据')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('expired_at', models.DateTimeField(verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '支付订单',
                'verbose_name_plural': '支付订单',
                'db_table': 'services_payment_order',
                'ordering': ['-created_at'],
            },
        ),
    ]
