# Generated by Django 4.2.7 on 2026-03-04 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='paymentcallback',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='callbacks', to='payment.paymentorder', verbose_name='订单'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['user', 'status'], name='services_pa_user_id_252b91_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['order_no'], name='services_pa_order_n_0f04b0_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['third_party_trade_no'], name='services_pa_third_p_44160e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['status', 'created_at'], name='services_pa_status_ef29d9_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['payment_method', 'status'], name='services_pa_payment_88ff1c_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcallback',
            index=models.Index(fields=['order', 'created_at'], name='services_pa_order_i_5daf1a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcallback',
            index=models.Index(fields=['payment_method', 'created_at'], name='services_pa_payment_e37730_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcallback',
            index=models.Index(fields=['is_processed', 'created_at'], name='services_pa_is_proc_f6e5a7_idx'),
        ),
    ]
