# Generated by Django 4.2.7 on 2026-03-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentorder",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("membership", "会员购买"),
                    ("credits", "点券充值"),
                    ("storage_package", "存储套餐"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="订单类型",
            ),
        ),
    ]
