# Generated by Django 4.2.7 on 2026-03-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_add_storage_package_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='status',
            field=models.CharField(choices=[('pending', '待支付'), ('paying', '支付中'), ('paid', '已支付'), ('cancelled', '已取消'), ('failed', '支付失败'), ('completed', '已完成'), ('refunded', '已退款'), ('partially_refunded', '部分退款')], db_index=True, default='pending', max_length=20, verbose_name='订单状态'),
        ),
    ]
