# Generated by Django 4.2.7 on 2026-03-19 02:11

import apps.services.payment.models
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_workspace_to_workteam_rename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='workteam_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='该订单归属的工作团队，为空时兼容旧用户级订单', max_length=100, verbose_name='工作团队ID'),
        ),
        migrations.CreateModel(
            name='RefundRecord',
            fields=[
                ('id', models.CharField(default=apps.services.payment.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('invoice_id', models.CharField(db_index=True, help_text='BillingInvoice ID（跨数据库引用，不建外键）', max_length=36, verbose_name='关联账单ID')),
                ('refund_no', models.CharField(db_index=True, default=apps.services.payment.models.generate_refund_no, max_length=32, unique=True, verbose_name='退款单号')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='退款金额（元）')),
                ('refund_status', models.CharField(choices=[('pending', '待退款'), ('refunding', '退款中'), ('refunded', '已退款'), ('refund_failed', '退款失败')], db_index=True, default='pending', max_length=20, verbose_name='退款状态')),
                ('payment_method', models.CharField(choices=[('alipay', '支付宝'), ('wechat', '微信支付')], max_length=20, verbose_name='支付方式')),
                ('third_party_refund_no', models.CharField(blank=True, max_length=100, verbose_name='第三方退款单号')),
                ('failure_reason', models.TextField(blank=True, verbose_name='失败原因')),
                ('operator_user_id', models.CharField(blank=True, max_length=36, verbose_name='操作人')),
                ('reason', models.TextField(blank=True, verbose_name='退款原因')),
                ('metadata', models.JSONField(default=dict, verbose_name='附加数据')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='退款完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('payment_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_records', to='payment.paymentorder', verbose_name='原支付订单')),
            ],
            options={
                'verbose_name': '退款记录',
                'verbose_name_plural': '退款记录',
                'db_table': 'services_payment_refund_record',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payment_order', 'refund_status'], name='services_pa_payment_a0b2e2_idx'), models.Index(fields=['invoice_id'], name='services_pa_invoice_5806af_idx'), models.Index(fields=['refund_status', 'created_at'], name='services_pa_refund__fc3aa2_idx')],
            },
        ),
    ]
