# Generated by Django 4.2.7 on 2026-06-05 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0008_add_refund_record_payment_order_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
