# Generated by Django 4.2.7 on 2026-07-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_rename_workteam_to_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='organization_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='该订单归属的组织，为空时兼容旧用户级订单', max_length=100, verbose_name='组织ID'),
        ),
    ]
