# Generated by Django 4.2.7 on 2026-08-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_reconcile_unpublished_payment_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundrecord',
            name='payment_method',
            field=models.CharField(choices=[('alipay', '支付宝'), ('wechat', '微信支付'), ('organization_wallet', '组织现金钱包')], max_length=20, verbose_name='支付方式'),
        ),
    ]
