# Generated by Django 4.2.7 on 2026-03-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='语义化版本号，如 1.2.3', max_length=20)),
                ('platform', models.CharField(choices=[('mac', 'macOS'), ('win', 'Windows'), ('linux', 'Linux')], max_length=10)),
                ('arch', models.CharField(choices=[('x64', 'x64'), ('arm64', 'ARM64')], default='x64', max_length=10)),
                ('channel', models.CharField(choices=[('stable', 'Stable'), ('beta', 'Beta'), ('alpha', 'Alpha')], default='stable', max_length=20)),
                ('file_url', models.URLField(help_text='安装包下载地址 (CDN)')),
                ('file_size', models.BigIntegerField(help_text='文件大小（字节）')),
                ('checksum_sha256', models.CharField(help_text='SHA256 校验和', max_length=64)),
                ('is_draft', models.BooleanField(default=True, help_text='草稿状态，不会推送给用户')),
                ('published_at', models.DateTimeField(blank=True, help_text='发布时间', null=True)),
                ('deprecated_at', models.DateTimeField(blank=True, help_text='废弃时间', null=True)),
                ('is_mandatory', models.BooleanField(default=False, help_text='是否强制更新')),
                ('min_compatible_version', models.CharField(blank=True, help_text='最低兼容版本，低于此版本必须更新', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', help_text='更新优先级', max_length=20)),
                ('release_notes', models.TextField(help_text='更新日志（中文）')),
                ('release_notes_en', models.TextField(blank=True, help_text='更新日志（英文）')),
                ('rollout_percentage', models.IntegerField(default=0, help_text='灰度发布百分比 (0-100)，0表示未推送')),
                ('rollout_target_users', models.JSONField(blank=True, default=list, help_text='白名单用户 ID 列表（用于内测）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '应用版本',
                'verbose_name_plural': '应用版本',
                'db_table': 'updater_app_release',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('device_id', models.CharField(db_index=True, max_length=100)),
                ('workspace_id', models.CharField(blank=True, max_length=100)),
                ('from_version', models.CharField(max_length=20)),
                ('to_version', models.CharField(db_index=True, max_length=20)),
                ('platform', models.CharField(max_length=10)),
                ('arch', models.CharField(max_length=10)),
                ('channel', models.CharField(default='stable', max_length=20)),
                ('trigger_source', models.CharField(choices=[('ws_push', 'WebSocket Push'), ('http_poll', 'HTTP Poll'), ('manual', 'Manual Check')], help_text='触发来源', max_length=20)),
                ('status', models.CharField(choices=[('checking', 'Checking'), ('available', 'Available'), ('downloading', 'Downloading'), ('downloaded', 'Downloaded'), ('installing', 'Installing'), ('installed', 'Installed'), ('failed', 'Failed'), ('skipped', 'Skipped')], help_text='当前状态', max_length=20)),
                ('progress', models.FloatField(default=0, help_text='下载进度 0-100')),
                ('success', models.BooleanField(help_text='是否成功', null=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('download_duration_ms', models.IntegerField(help_text='下载耗时（毫秒）', null=True)),
                ('client_metadata', models.JSONField(blank=True, default=dict, help_text='客户端元数据')),
            ],
            options={
                'verbose_name': '更新日志',
                'verbose_name_plural': '更新日志',
                'db_table': 'updater_log',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UpdatePushRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_group', models.CharField(help_text='目标 WebSocket 分组名，如 app.update.mac.x64.stable', max_length=100)),
                ('rollout_percentage', models.IntegerField(help_text='本次推送的灰度比例')),
                ('silent', models.BooleanField(default=False, help_text='是否静默下载')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('pushed_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='推送备注')),
            ],
            options={
                'verbose_name': '推送记录',
                'verbose_name_plural': '推送记录',
                'db_table': 'updater_push_record',
                'ordering': ['-pushed_at'],
            },
        ),
    ]
