# Generated by Django 4.2.7 on 2026-03-04 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('updater', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='updatepushrecord',
            name='pushed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pushed_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='updatepushrecord',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_records', to='updater.apprelease'),
        ),
        migrations.AddIndex(
            model_name='updatelog',
            index=models.Index(fields=['to_version', 'status'], name='updater_log_to_vers_d49412_idx'),
        ),
        migrations.AddIndex(
            model_name='updatelog',
            index=models.Index(fields=['user_id', 'started_at'], name='updater_log_user_id_b4c36b_idx'),
        ),
        migrations.AddIndex(
            model_name='updatelog',
            index=models.Index(fields=['device_id', 'started_at'], name='updater_log_device__b48568_idx'),
        ),
        migrations.AddIndex(
            model_name='updatelog',
            index=models.Index(fields=['trigger_source', 'success'], name='updater_log_trigger_8a9ac3_idx'),
        ),
        migrations.AddField(
            model_name='apprelease',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_releases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='updatepushrecord',
            index=models.Index(fields=['release', 'status'], name='updater_pus_release_f54cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='updatepushrecord',
            index=models.Index(fields=['pushed_at'], name='updater_pus_pushed__b4d417_idx'),
        ),
        migrations.AddIndex(
            model_name='apprelease',
            index=models.Index(fields=['platform', 'arch', 'channel', 'is_draft'], name='updater_app_platfor_ed7093_idx'),
        ),
        migrations.AddIndex(
            model_name='apprelease',
            index=models.Index(fields=['published_at'], name='updater_app_publish_8ee9c4_idx'),
        ),
        migrations.AddIndex(
            model_name='apprelease',
            index=models.Index(fields=['version'], name='updater_app_version_8714b4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='apprelease',
            unique_together={('version', 'platform', 'arch', 'channel')},
        ),
    ]
