# Generated by Django 4.2.7 on 2026-07-19 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('updater', '0006_rename_workteam_to_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientVersionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], help_text='平台，每个平台仅一条策略', max_length=16, unique=True)),
                ('enabled', models.BooleanField(default=True, help_text='总开关；关闭时门禁对该平台恒返回 none（出问题可一键停用）')),
                ('min_supported_build', models.PositiveIntegerField(default=0, help_text='最低支持 build 号；当前 build 低于此值 → 强制更新（force）')),
                ('latest_build', models.PositiveIntegerField(default=0, help_text='最新 build 号；最低支持 ≤ 当前 < 最新 → 推荐更新（soft）；0 表示不做软提示')),
                ('min_supported_version', models.CharField(blank=True, default='', help_text='最低支持语义版本，仅展示', max_length=32)),
                ('latest_version', models.CharField(blank=True, default='', help_text='最新语义版本，仅展示', max_length=32)),
                ('store_url', models.URLField(blank=True, default='', help_text='去更新跳转地址；Android 建议填官网落地页（国内多商店）')),
                ('force_title', models.CharField(blank=True, default='', help_text='强制更新弹窗标题；留空用默认文案', max_length=128)),
                ('force_message', models.TextField(blank=True, default='', help_text='强制更新弹窗正文；留空用默认文案')),
                ('soft_title', models.CharField(blank=True, default='', help_text='推荐更新弹窗标题；留空用默认文案', max_length=128)),
                ('soft_message', models.TextField(blank=True, default='', help_text='推荐更新弹窗正文；留空用默认文案')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_version_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '移动端版本门禁',
                'verbose_name_plural': '移动端版本门禁',
                'db_table': 'updater_client_version_policy',
            },
        ),
    ]
