# Generated by Django 4.2.7 on 2026-07-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updater', '0007_clientversionpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientversionpolicy',
            name='soft_prompt_enabled',
            field=models.BooleanField(default=False, help_text='软提示（推荐更新）开关，默认关；关闭时只保留强更，不因有新版本就打扰用户'),
        ),
    ]
