# Generated by Django 4.2.7 on 2026-08-07 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tabtinspace', '0140_backfill_mcpconnection_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticBundle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_install_id', models.CharField(db_index=True, max_length=128)),
                ('sentry_event_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('object_key', models.CharField(max_length=512, unique=True)),
                ('upload_object_key', models.CharField(max_length=512, unique=True)),
                ('expected_size', models.PositiveBigIntegerField()),
                ('expected_sha256', models.CharField(max_length=64)),
                ('content_type', models.CharField(default='application/zip', max_length=128)),
                ('status', models.CharField(choices=[('pending_upload', '待上传'), ('uploaded', '已上传'), ('scanning', '扫描中'), ('available', '可下载'), ('quarantined', '已隔离'), ('expired', '已过期'), ('deleted', '已删除')], db_index=True, default='pending_upload', max_length=24)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('available_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('scan_result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabtinspace.organization')),
            ],
            options={
                'db_table': 'diagnostic_bundle',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticDownloadAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('request_id', models.CharField(blank=True, default='', max_length=128)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_audits', to='diagnostics.diagnosticbundle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'diagnostic_download_audit',
            },
        ),
        migrations.AddIndex(
            model_name='diagnosticbundle',
            index=models.Index(fields=['organization', 'status', '-created_at'], name='diag_org_status_created_idx'),
        ),
    ]
