# Generated by Django 4.2.7 on 2026-08-16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("diagnostics", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="diagnosticbundle",
            name="source",
            field=models.CharField(
                choices=[("incident", "自动故障采集"), ("support_upload", "用户主动上传")],
                db_index=True,
                default="incident",
                max_length=32,
            ),
        ),
    ]
