#!/usr/bin/env node
/**
 * 从 prompts/*.md 生成 src/generated-content.ts。
 *
 * SSoT 是 .md 文件——修改 prompt 只需编辑 .md，然后 build 自动重新生成 TS 常量。
 * 与 @tabtin/agent-modes 的 gen-prompt-sections.mjs 同一模式。
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROMPTS_DIR = resolve(__dirname, '../prompts');
const OUTPUT = resolve(__dirname, '../src/generated-content.ts');

// W4.5（2026-05-10）: `tracker_intent` 已下线 — Tracker CLI 未接通时
// builder 不会注入此段，留死代码反而误导后续维护者。需要恢复时同步加回
// `prompts/tracker_intent.md` + builder.ts 注入点。
//
// 阶段 6.7 议题 1 治理（2026-05-21）：
// - 删 `ask_user_tools` —— 原段（1693 字）拆到 ask_user / ask_form / request_approval
//   三个工具说明书 + Agent 节奏约束搬 execution。消除"工具说明书 + 段 + tools_reference
//   guide" 3 处出入造成的 Agent 决策混淆。
// - 删 `skills_usage` —— 原段（3110 字）拆到 4 个 skills 工具说明书。
// - 删 `skills_user_voice`—— 用户措辞 / description 边界 / relevant_skills
//   说明并入静态 `<skills>` index header（agent-runtime skill-renderer）。
//   Skill 入口决策（read/invoke/CLI）不再写入 execution。
// execution：主 / 子 Agent 共用同一份（不含「用子 Agent 卸载上下文」编排指引）。
// 编排指引已抽成独立段 subagent_orchestration，只对非 worker（编排者）在静态段
// 最末尾注入（见 builder.ts），以最大化主 Agent 与 worker 子 Agent 的共享缓存前缀。
const SECTIONS = ['operating_loop', 'execution', 'safety', 'planning', 'subagent_orchestration'];

function escapeForTemplateLiteral(s) {
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

const lines = [
  '/* eslint-disable */',
  '// AUTO-GENERATED by scripts/generate-content.mjs — DO NOT EDIT',
  '// SSoT: prompts/*.md',
  '',
];

for (const section of SECTIONS) {
  const path = resolve(PROMPTS_DIR, `${section}.md`);
  const raw = readFileSync(path, 'utf-8').trim();
  const constName = `SECTION_${section.toUpperCase()}`;
  lines.push(`export const ${constName} = \`${escapeForTemplateLiteral(raw)}\`;`);
  lines.push('');
}

writeFileSync(OUTPUT, lines.join('\n'), 'utf-8');
console.log(`✓ Generated ${OUTPUT}`);
