from apps.services.llm.registry import ProviderRegistry
from apps.services.llm.interface import ProviderMetadata, ProviderModelDeclaration

ProviderRegistry.register(ProviderMetadata(
    name="volcengine",
    display_name="豆包",
    service_class_path="apps.services.llm.providers.volcengine.service.VolcengineService",
    sdk_type="openai",
    default_base_url="https://ark.cn-beijing.volces.com/api/v3",
    icon_emoji="🔥",
    color_class="text-muted-foreground",
    supports_openai_compat=True,
    default_max_output_tokens=32768,
    fallback_api_key_envs=("ARK_API_KEY", "VOLCENGINE_API_KEY"),
    fallback_base_url_envs=("ARK_BASE_URL", "VOLCENGINE_BASE_URL"),
    fallback_model_envs=("ARK_MODEL", "VOLCENGINE_MODEL", "DOUBAO_MODEL"),
    fallback_settings_prefixes=("ARK", "VOLCENGINE"),
    default_model_name="doubao-seed-2-0-lite-260428",
    # Registry 仍用旧标识 "llm"；DB / capability_guard 会把它等价成 chat 域。
    capability_domains=frozenset({"llm", "image_gen"}),
    static_models=(
        ProviderModelDeclaration(
            model_name="doubao-seed-2-0-lite-260428",
            display_name="Doubao Seed 2.0 Lite",
            context_window_tokens=262144,
            max_output_tokens=32768,
            supports_vision=True,
            input_price_per_1k=0.00009,
            output_price_per_1k=0.00051,
        ),
        ProviderModelDeclaration(
            model_name="doubao-seed-2-0-pro-260428",
            display_name="Doubao Seed 2.0 Pro",
            context_window_tokens=262144,
            max_output_tokens=32768,
            supports_vision=True,
            input_price_per_1k=0.00045,
            output_price_per_1k=0.00224,
        ),
        ProviderModelDeclaration(
            model_name="doubao-seed-evolving",
            display_name="Doubao Seed Evolving",
            context_window_tokens=1048576,
            max_output_tokens=262144,
            supports_vision=True,
            input_price_per_1k=0.006,
            output_price_per_1k=0.03,
        ),
        ProviderModelDeclaration(
            model_name="doubao-seedream-4-0-250828",
            display_name="Doubao Seedream 4.0",
            mode="image_generation",
            context_window_tokens=0,
            max_output_tokens=0,
            supports_function_calling=False,
        ),
        ProviderModelDeclaration(
            model_name="doubao-seedream-4-5-251128",
            display_name="Doubao Seedream 4.5",
            mode="image_generation",
            context_window_tokens=0,
            max_output_tokens=0,
            supports_function_calling=False,
        ),
        ProviderModelDeclaration(
            model_name="doubao-seedream-5-0-260128",
            display_name="Doubao Seedream 5.0",
            mode="image_generation",
            context_window_tokens=0,
            max_output_tokens=0,
            supports_function_calling=False,
        ),
        ProviderModelDeclaration(
            model_name="doubao-seedream-5-0-pro-260628",
            display_name="Doubao Seedream 5.0 Pro",
            mode="image_generation",
            context_window_tokens=0,
            max_output_tokens=0,
            supports_function_calling=False,
        ),
    ),
))
