/**
 * 自家 Kotlin codegen——从 JSON Schema (Draft 7) 直接生成 type-safe Kotlin
 * (kotlinx-serialization sealed class)。
 *
 * 设计：
 *   - oneOf+discriminator → `@Serializable @JsonClassDiscriminator("type") sealed class X`
 *     + `@SerialName("text") @Serializable data class Text(...) : X()`
 *   - object → `@Serializable data class X(...)`
 *   - tool_use.input 等任意 object → `JsonObject`
 *   - List<X> → `List<X>`
 *   - 字段 default = null 让 Json 默认 ignoreUnknownKeys + encodeDefaults=false
 *
 * 不依赖 Klaxon——Klaxon 默认输出 null 字段、把 int 解析为 double（W0 PoC §3.2 K9-K11）。
 */

type JsonSchema = Record<string, unknown>;

const HEADER = (packageName: string) => `// ════════════════════════════════════════════════════════════════════
// 自动生成 — DO NOT EDIT MANUALLY
// Generated by @tabtin/wire-codegen (Wave 1 协议层)
// Source: packages/agent-wire/src/stream-content-block.ts (zod SSoT)
// 重新生成: pnpm --filter @tabtin/wire-codegen codegen
// 文档: docs/agent-runtime/wire-protocol.md
// ════════════════════════════════════════════════════════════════════

@file:OptIn(ExperimentalSerializationApi::class)
@file:Suppress("PropertyName", "ConstructorParameterNaming")

package ${packageName}

import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonElement
`;

const isObj = (x: unknown): x is JsonSchema =>
  typeof x === 'object' && x !== null && !Array.isArray(x);

interface CodegenContext {
  emittedTypes: Set<string>;
  inProgress: Set<string>;
  output: string[];
  baseName: string;
  packageName: string;
}

function snakeToPascal(s: string): string {
  // 把 _ / - / 空格 / . 都当分隔符（dotted 来自 event_type='agent.stream.message_start'）
  return s
    .split(/[_\-\s.]/)
    .filter(Boolean)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join('');
}

// Note: refToTypeName 见下方，处理 anyOf/数字 末段 ref。

function literalToCaseName(lit: string): string {
  // text → Text, tool_use → ToolUse, tabtin_source_ref → TabtinSourceRef
  return snakeToPascal(lit);
}

function safeIdent(name: string): string {
  const KOTLIN_KEYWORDS = new Set([
    'as', 'break', 'class', 'continue', 'do', 'else', 'false', 'for', 'fun', 'if',
    'in', 'interface', 'is', 'null', 'object', 'package', 'return', 'super', 'this',
    'throw', 'true', 'try', 'typealias', 'typeof', 'val', 'var', 'when', 'while',
  ]);
  if (KOTLIN_KEYWORDS.has(name)) return `\`${name}\``;
  // Identifiers starting with _ are valid in Kotlin; no transform needed.
  return name;
}

/** 处理 $ref → Kotlin 类型名（与 swift_codegen 对应：纯数字段回溯到上一段）。 */
function refToTypeName(ref: string): string {
  const parts = ref.split('/');
  const last = parts[parts.length - 1]!;
  if (/^\d+$/.test(last)) {
    let i = parts.length - 2;
    while (i >= 0 && /^\d+$/.test(parts[i]!)) i--;
    if (i >= 0) {
      const stem = snakeToPascal(parts[i]!);
      return `${stem}_${last}`;
    }
    return `_${last}`;
  }
  return snakeToPascal(last);
}

/** 解析 schema 引用——兼容 anyOf ↔ oneOf 路径段切换。
 *
 * 详见 swift_codegen.ts 同名函数说明（inject_discriminator 转换后 ref 路径
 * 仍指向旧的 anyOf 段；本函数自动 fallback 到对应 oneOf 段）。 */
function resolveRef(ref: string, root: JsonSchema): JsonSchema {
  const parts = ref.replace(/^#\//, '').split('/');
  let cur: unknown = root;
  for (const part of parts) {
    if (Array.isArray(cur)) {
      const idx = Number(part);
      if (Number.isNaN(idx) || idx < 0 || idx >= cur.length) {
        throw new Error(`Cannot resolve ref ${ref} at array index '${part}'`);
      }
      cur = cur[idx];
      continue;
    }
    if (!isObj(cur)) throw new Error(`Cannot resolve ref ${ref}`);
    let next: unknown = (cur as JsonSchema)[part];
    if (typeof next === 'undefined') {
      if (part === 'anyOf' && Array.isArray((cur as JsonSchema)['oneOf'])) {
        next = (cur as JsonSchema)['oneOf'];
      } else if (part === 'oneOf' && Array.isArray((cur as JsonSchema)['anyOf'])) {
        next = (cur as JsonSchema)['anyOf'];
      }
    }
    cur = next;
  }
  if (!isObj(cur)) throw new Error(`Ref ${ref} did not resolve`);
  return cur;
}

function resolveIfRef(schema: JsonSchema, root: JsonSchema): {
  schema: JsonSchema;
  refTypeName: string | null;
} {
  if (typeof schema['$ref'] === 'string') {
    return {
      schema: resolveRef(schema['$ref'], root),
      refTypeName: refToTypeName(schema['$ref']),
    };
  }
  return { schema, refTypeName: null };
}

function schemaToKotlinType(
  schema: JsonSchema,
  root: JsonSchema,
  ctx: CodegenContext,
  hintName?: string,
): string {
  if (typeof schema['$ref'] === 'string') {
    const refName = refToTypeName(schema['$ref']);
    const resolved = resolveRef(schema['$ref'], root);
    ensureTypeEmitted(refName, resolved, root, ctx);
    return refName;
  }

  if (typeof schema['const'] !== 'undefined') return 'String';
  if (Array.isArray(schema['enum'])) return 'String';

  if (Array.isArray(schema['anyOf'])) {
    const variants = schema['anyOf'] as JsonSchema[];
    const nullVariants = variants.filter((v) => v['type'] === 'null');
    const nonNull = variants.filter((v) => v['type'] !== 'null');
    if (nullVariants.length > 0 && nonNull.length === 1) {
      return `${schemaToKotlinType(nonNull[0]!, root, ctx, hintName)}?`;
    }
    return 'JsonElement';
  }

  if (Array.isArray(schema['oneOf'])) {
    if (isObj(schema['discriminator'])) {
      if (!hintName) {
        throw new Error('Inline oneOf+discriminator without hintName not supported');
      }
      ensureUnionTypeEmitted(hintName, schema, root, ctx);
      return hintName;
    }
    return 'JsonElement';
  }

  const t = schema['type'];
  if (t === 'string') return 'String';
  if (t === 'integer') return 'Long';
  if (t === 'number') return 'Double';
  if (t === 'boolean') return 'Boolean';
  if (t === 'array') {
    if (isObj(schema['items'])) {
      const items = schema['items'] as JsonSchema;
      return `List<${schemaToKotlinType(items, root, ctx, hintName ? `${hintName}Item` : undefined)}>`;
    }
    // tuple-form array（z.tuple）：items 是 schema 数组
    if (Array.isArray(schema['items'])) {
      const itemArr = schema['items'] as JsonSchema[];
      if (itemArr.length === 0) return 'List<JsonElement>';
      const types = itemArr
        .filter((i) => isObj(i))
        .map((i) => schemaToKotlinType(i, root, ctx, hintName ? `${hintName}Item` : undefined));
      const allSame = types.every((tp) => tp === types[0]);
      return allSame ? `List<${types[0]}>` : 'List<JsonElement>';
    }
    return 'List<JsonElement>';
  }
  if (t === 'object' || (typeof t === 'undefined' && isObj(schema['properties']))) {
    // **关键修复（W1-Review P0-1）**：
    // zod 的 `z.record(z.unknown())` 输出 `{type: "object", additionalProperties: {}}`
    // 没有 `properties`。如果直接 emit `@Serializable public object XxxInput`，
    // kotlinx-serialization 把它当成单例（永远是 `{}`），decode 时**静默丢掉所有字段**。
    //
    // 修复：纯 additionalProperties only → 返回 `JsonObject` 字典类型。
    const hasProperties = isObj(schema['properties']) && Object.keys(schema['properties'] as object).length > 0;
    if (!hasProperties) {
      return 'JsonObject';
    }
    if (!hintName) {
      return 'JsonObject';
    }
    ensureObjectTypeEmitted(hintName, schema, root, ctx);
    return hintName;
  }

  if (Array.isArray(t)) {
    const types = t as string[];
    const nullable = types.includes('null');
    const nonNull = types.filter((x) => x !== 'null');
    if (nonNull.length === 1) {
      const baseSchema: JsonSchema = { ...schema, type: nonNull[0]! };
      return `${schemaToKotlinType(baseSchema, root, ctx, hintName)}${nullable ? '?' : ''}`;
    }
    return 'JsonElement';
  }

  return 'JsonElement';
}

function ensureTypeEmitted(
  name: string,
  schema: JsonSchema,
  root: JsonSchema,
  ctx: CodegenContext,
): void {
  if (ctx.emittedTypes.has(name) || ctx.inProgress.has(name)) return;
  ctx.inProgress.add(name);

  if (Array.isArray(schema['oneOf']) && isObj(schema['discriminator'])) {
    ensureUnionTypeEmitted(name, schema, root, ctx);
  } else if (
    schema['type'] === 'object' ||
    (typeof schema['type'] === 'undefined' && isObj(schema['properties']))
  ) {
    ensureObjectTypeEmitted(name, schema, root, ctx);
  } else {
    const kt = schemaToKotlinType(schema, root, ctx, name);
    ctx.output.push(`public typealias ${name} = ${kt}`);
  }

  ctx.inProgress.delete(name);
  ctx.emittedTypes.add(name);
}

interface FieldInfo {
  jsonName: string;
  ktName: string;
  ktType: string;
  isOptional: boolean;
  isDiscriminator: boolean;
  doc: string | null;
}

function getFieldsForObject(
  schema: JsonSchema,
  root: JsonSchema,
  ctx: CodegenContext,
  parentName: string,
  discriminatorProp?: string,
): FieldInfo[] {
  const props = isObj(schema['properties']) ? schema['properties'] : {};
  const required = new Set(Array.isArray(schema['required']) ? (schema['required'] as string[]) : []);
  const fields: FieldInfo[] = [];

  for (const [propName, propSchema] of Object.entries(props)) {
    if (!isObj(propSchema)) continue;
    // 跳过 discriminator 字段（kotlinx-serialization 通过 @SerialName 自动处理）
    if (discriminatorProp && propName === discriminatorProp) continue;

    const isOptional = !required.has(propName);
    const hintName = `${parentName}${snakeToPascal(propName)}`;

    let ktType: string;
    try {
      ktType = schemaToKotlinType(propSchema, root, ctx, hintName);
    } catch (e) {
      throw new Error(`Failed to resolve ${parentName}.${propName}: ${(e as Error).message}`);
    }

    if (isOptional && !ktType.endsWith('?')) {
      ktType = `${ktType}?`;
    }

    fields.push({
      jsonName: propName,
      ktName: safeIdent(propName), // Kotlin 用 snake_case 也行，加 @SerialName 兜底
      ktType,
      isOptional,
      isDiscriminator: false,
      doc: typeof propSchema['description'] === 'string' ? propSchema['description'] : null,
    });
  }

  return fields;
}

function ensureObjectTypeEmitted(
  name: string,
  schema: JsonSchema,
  root: JsonSchema,
  ctx: CodegenContext,
  options?: { discriminatorProp?: string; sealedParent?: string; serialName?: string },
): void {
  if (ctx.emittedTypes.has(name)) return;

  const fields = getFieldsForObject(schema, root, ctx, name, options?.discriminatorProp);
  const lines: string[] = [];

  if (options?.serialName) {
    lines.push(`@Serializable`);
    lines.push(`@SerialName("${options.serialName}")`);
  } else {
    lines.push(`@Serializable`);
  }

  if (fields.length === 0) {
    lines.push(`public object ${name}${options?.sealedParent ? ` : ${options.sealedParent}()` : ''}`);
    lines.push('');
    ctx.output.push(lines.join('\n'));
    ctx.emittedTypes.add(name);
    return;
  }

  const params = fields.map((f) => {
    const serialAnnot =
      f.ktName !== f.jsonName || f.jsonName.includes('_') || f.jsonName.startsWith('_')
        ? `@SerialName("${f.jsonName}") `
        : '';
    const def = f.isOptional ? ' = null' : '';
    const docComment = f.doc ? `    /** ${f.doc.replace(/\n/g, ' ')} */\n    ` : '    ';
    return `${docComment}${serialAnnot}val ${f.ktName}: ${f.ktType}${def}`;
  });

  lines.push(`public data class ${name}(`);
  lines.push(params.join(',\n'));
  lines.push(`)${options?.sealedParent ? ` : ${options.sealedParent}()` : ''}`);
  lines.push('');

  ctx.output.push(lines.join('\n'));
  ctx.emittedTypes.add(name);
}

interface UnionVariant {
  literal: string;
  className: string;
  payloadSchema: JsonSchema;
  refTypeName: string | null;
}

function ensureUnionTypeEmitted(
  name: string,
  schema: JsonSchema,
  root: JsonSchema,
  ctx: CodegenContext,
): void {
  if (ctx.emittedTypes.has(name)) return;

  const oneOf = schema['oneOf'] as JsonSchema[];
  const discProp =
    isObj(schema['discriminator']) && typeof schema['discriminator']['propertyName'] === 'string'
      ? (schema['discriminator']['propertyName'] as string)
      : 'type';

  const variants: UnionVariant[] = [];
  for (const variant of oneOf) {
    const resolved = resolveIfRef(variant, root);
    const variantSchema = resolved.schema;
    const props = isObj(variantSchema['properties']) ? variantSchema['properties'] : {};
    const discField = isObj(props[discProp]) ? props[discProp] : null;
    if (!discField || typeof discField['const'] !== 'string') {
      throw new Error(`Variant in ${name} oneOf has no const literal for ${discProp}`);
    }
    const literal = discField['const'];
    variants.push({
      literal,
      className: literalToCaseName(literal),
      payloadSchema: variantSchema,
      refTypeName: resolved.refTypeName,
    });
  }

  // 顶层 sealed class 头
  // 注：kotlinx-serialization 不允许 subclass 暴露 discriminator 同名属性
  // （会跟 @JsonClassDiscriminator 冲突）。所以 sealed class 不声明
  // abstract val ${discProp}——消费方用 `when (block) is XxxBlock -> ...`
  // 来做 type narrowing；或者 `block::class.java.getAnnotation(SerialName::class.java).value`
  // 取出 SerialName 字符串。
  const sealedLines: string[] = [];
  sealedLines.push(`@Serializable`);
  sealedLines.push(`@JsonClassDiscriminator("${discProp}")`);
  sealedLines.push(`public sealed class ${name}`);
  sealedLines.push('');

  ctx.output.push(sealedLines.join('\n'));
  ctx.emittedTypes.add(name);

  // 每个 variant 生成嵌套子类
  for (const v of variants) {
    const subclassName = `${name}${v.className}`;

    if (v.refTypeName) {
      // 已有 ref type → 生成一个 wrapper data class 继承 sealed parent
      // 注：kotlinx-serialization 要求 sealed class subclass 必须直接继承
      // 不能用 typealias。这里生成 wrapper 把 ref 类型嵌入。
      const wrapperLines: string[] = [];
      wrapperLines.push(`@Serializable`);
      wrapperLines.push(`@SerialName("${v.literal}")`);
      // 在这里我们需要把 ref type 的所有字段拷过来 + 加 type 字段
      // 简化做法：让 subclass = ref 的同名 data class 继承 sealed parent
      // 但这样要求 ref 本身是 sealed parent 的 child——对一个 type 不能多个父
      //
      // 改方案：subclass 直接用 ref type 的字段拷贝 + 自带 type 字段
      ensureTypeEmitted(v.refTypeName, v.payloadSchema, root, ctx);
      const refFields = getFieldsForObject(v.payloadSchema, root, ctx, subclassName, discProp);
      const params = refFields.map((f) => {
        const serialAnnot =
          f.ktName !== f.jsonName || f.jsonName.includes('_') || f.jsonName.startsWith('_')
            ? `@SerialName("${f.jsonName}") `
            : '';
        const def = f.isOptional ? ' = null' : '';
        const docComment = f.doc ? `    /** ${f.doc.replace(/\n/g, ' ')} */\n    ` : '    ';
        return `${docComment}${serialAnnot}val ${f.ktName}: ${f.ktType}${def}`;
      });

      wrapperLines.push(`public data class ${subclassName}(`);
      wrapperLines.push(params.join(',\n'));
      wrapperLines.push(`) : ${name}()`);
      wrapperLines.push('');

      ctx.output.push(wrapperLines.join('\n'));
      ctx.emittedTypes.add(subclassName);
    } else {
      // Inline variant → 生成 subclass with fields
      const subFields = getFieldsForObject(v.payloadSchema, root, ctx, subclassName, discProp);

      const lines: string[] = [];
      lines.push(`@Serializable`);
      lines.push(`@SerialName("${v.literal}")`);

      if (subFields.length === 0) {
        // 空对象 → 用 object 单例（kotlinx-serialization 支持 @Serializable object）
        lines.push(`public object ${subclassName} : ${name}()`);
      } else {
        const params = subFields.map((f) => {
          const serialAnnot =
            f.ktName !== f.jsonName || f.jsonName.includes('_') || f.jsonName.startsWith('_')
              ? `@SerialName("${f.jsonName}") `
              : '';
          const def = f.isOptional ? ' = null' : '';
          const docComment = f.doc ? `    /** ${f.doc.replace(/\n/g, ' ')} */\n    ` : '    ';
          return `${docComment}${serialAnnot}val ${f.ktName}: ${f.ktType}${def}`;
        });
        lines.push(`public data class ${subclassName}(`);
        lines.push(params.join(',\n'));
        lines.push(`) : ${name}()`);
      }
      lines.push('');

      ctx.output.push(lines.join('\n'));
      ctx.emittedTypes.add(subclassName);
    }
  }
}

export function generateKotlinFile(
  schema: JsonSchema,
  baseName: string,
  emittedTypes: Set<string>,
): string {
  // **W1-Review P0-D 修复**：package name 必须跟 vendor 目录路径一致
  // （`apps/tabtin-android/app/src/main/java/com/tabtin/mobile/data/wire/`），
  // 否则 Android Studio 会高亮 "package name doesn't match file path"，
  // 自动 import 走两套路径 → 改一处所有 .kt 都要跟着改。
  const packageName = 'com.tabtin.mobile.data.wire';
  const ctx: CodegenContext = {
    emittedTypes,
    inProgress: new Set(),
    output: [],
    baseName,
    packageName,
  };

  for (const defKey of ['definitions', '$defs'] as const) {
    const defs = schema[defKey];
    if (isObj(defs)) {
      for (const [defName, defSchema] of Object.entries(defs)) {
        if (isObj(defSchema)) {
          const typeName = snakeToPascal(defName);
          ensureTypeEmitted(typeName, defSchema, schema, ctx);
        }
      }
    }
  }

  const rootName = snakeToPascal(baseName);
  if (typeof schema['$ref'] === 'string') {
    const refStr = schema['$ref'];
    const refLast = refStr.split('/').pop() || '';
    if (/^\d+$/.test(refLast)) {
      // root ref 末段是数字（如 #/definitions/ContentBlock/anyOf/20）——
      // 直接解析 ref 取出 variant，用 baseName 作为根类型名生成。
      const resolved = resolveRef(refStr, schema);
      ensureTypeEmitted(rootName, resolved, schema, ctx);
    } else {
      const refName = refToTypeName(refStr);
      if (refName !== rootName) {
        ctx.output.push(`public typealias ${rootName} = ${refName}`);
      }
    }
  } else {
    ensureTypeEmitted(rootName, schema, schema, ctx);
  }

  return HEADER(packageName) + '\n' + ctx.output.join('\n');
}
