/**
 * Pydantic v2 .py 后处理脚本（W0 PoC §4 P0 修复）。
 *
 * 修复项：
 *   1. extra="forbid" → extra="ignore"（forward-compat 红线，v2 §2.6 协议向前兼容硬约束）
 *   2. Field(discriminator='X') → Annotated[..., Discriminator('X')] 新语法
 *      （嵌套 union 错误信息从 303 行降到 1 行）
 *   3. **W0-L4 修复**：datamodel-codegen 0.57.0 给 anonymous nested object
 *      用数字后缀（ContentBlock1 / ContentBlock2 / ImageSource1 / ImageSource2 ...）。
 *      本步骤扫描每个 numbered class 的 `type: Literal["XYZ"]` 或
 *      `kind: Literal["XYZ"]` discriminator，自动重命名为业务语义类名
 *      （TextContentBlock / ToolUseContentBlock / Base64ImageSource / ...）。
 *   4. 顶部加生成 marker + DO NOT EDIT 警示
 */

const HEADER = `# ════════════════════════════════════════════════════════════════════
# 自动生成 — DO NOT EDIT MANUALLY
# Generated by @tabtin/wire-codegen (Wave 1 协议层)
# Source: packages/agent-wire/src/stream-content-block.ts (zod SSoT)
# 重新生成: pnpm --filter @tabtin/wire-codegen codegen
# 文档: docs/agent-runtime/wire-protocol.md
# ════════════════════════════════════════════════════════════════════
`;

/** snake_case / kebab-case / dotted.namespace → PascalCase
 *
 * 把 `_` / `-` / 空格 / `.` 都当分隔符（dotted 来自 event_type='agent.stream.message_start'）。
 * 数字开头自动加 `_` 前缀避开非法标识符。 */
function snakeToPascal(s: string): string {
  const pascal = s
    .split(/[_\-\s.]/)
    .filter(Boolean)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join('');
  return /^[0-9]/.test(pascal) ? `_${pascal}` : pascal;
}

/**
 * 自动重命名 numbered class（如 ContentBlock1 / ImageSource2）为业务语义名。
 *
 * 算法：
 *   1. 找所有 `class XYZ\d+\(BaseModel\):` 形态的类
 *   2. 在该类 body 中找 `(type|kind|event_type): Literal["VAL"]`
 *   3. 重命名 `XYZ_NUM` → `${PascalCase(VAL)}${XYZ_BASE}`
 *      （如 ContentBlock1 含 type='text' → TextContentBlock；ImageSource2 含 type='url' → UrlImageSource）
 *   4. 全文替换所有引用
 *
 * 不重命名：
 *   - 没有 type/kind/event_type Literal 的（无法推导业务语义）
 *   - 重命名后名字已被占用（保留原名避免冲突）
 */
function renameNumberedClasses(src: string): string {
  const classRe = /^class ([A-Z][A-Za-z]*?)(\d+)\(([^)]+)\):/gm;
  const renameMap = new Map<string, string>();
  const usedNames = new Set<string>();

  // Pre-collect all existing class names (含没编号的)
  for (const m of src.matchAll(/^class ([A-Z][A-Za-z0-9_]*)\(/gm)) {
    usedNames.add(m[1]!);
  }

  for (const m of src.matchAll(classRe)) {
    const fullMatch = m[0];
    const baseName = m[1]!;
    const num = m[2]!;
    const oldName = `${baseName}${num}`;

    // 找到该类 body 中的 type/kind literal
    const classStart = src.indexOf(fullMatch);
    if (classStart === -1) continue;
    // body 范围：从 fullMatch 末尾到下一个 `^class ` 或 EOF
    const bodyStart = classStart + fullMatch.length;
    const nextClassMatch = src.slice(bodyStart).match(/^class /m);
    const bodyEnd = nextClassMatch?.index !== undefined ? bodyStart + nextClassMatch.index : src.length;
    const body = src.slice(bodyStart, bodyEnd);

    // 优先级：type > event_type > kind
    let literal: string | null = null;
    for (const propName of ['type', 'event_type', 'kind']) {
      const litMatch = body.match(new RegExp(`\\b${propName}:\\s*Literal\\[(?:"|')([^"']+)(?:"|')\\]`));
      if (litMatch) {
        literal = litMatch[1]!;
        break;
      }
    }

    if (!literal) continue;
    const semanticPrefix = snakeToPascal(literal);
    const newName = `${semanticPrefix}${baseName}`;

    if (usedNames.has(newName) || renameMap.has(oldName)) continue;
    renameMap.set(oldName, newName);
    usedNames.add(newName);
  }

  // 应用重命名（按名字长度倒序，避免前缀冲突——如 ContentBlock10 vs ContentBlock1）
  const sortedRenames = [...renameMap.entries()].sort((a, b) => b[0].length - a[0].length);
  let out = src;
  for (const [oldName, newName] of sortedRenames) {
    // 用 \b 词边界严格匹配（防止误伤 ContentBlock10 / 11 等重叠 prefix）
    const re = new RegExp(`\\b${oldName}\\b`, 'g');
    out = out.replace(re, newName);
  }

  return out;
}

export function postProcessPydantic(raw: string, schemaFileName: string): string {
  let out = raw;

  // (1) extra="forbid" → extra="ignore"
  out = out.replace(/extra\s*=\s*"forbid"/g, 'extra="ignore"');

  // (2) Field(discriminator='X') → Annotated[..., Discriminator('X')]
  out = out.replace(/Field\(discriminator='([^']+)'\)/g, "Discriminator('$1')");
  out = out.replace(/Field\(discriminator="([^"]+)"\)/g, 'Discriminator("$1")');

  // 添加 Discriminator import（如果 .py 用了 Discriminator 但没 import）
  if (out.includes('Discriminator(')) {
    out = out.replace(
      /from pydantic import ([^\n]+)/,
      (match: string, imports: string) => {
        if (imports.includes('Discriminator')) return match;
        return `from pydantic import ${imports.replace('BaseModel', 'BaseModel, Discriminator')}`;
      },
    );
    if (!out.includes('Discriminator,') && !out.includes(', Discriminator')) {
      out = out.replace(
        /from pydantic import/,
        'from pydantic import Discriminator,\nfrom pydantic import',
      );
    }
  }

  // (3) W0-L4 修复：自动语义化重命名 numbered class
  out = renameNumberedClasses(out);

  // (4) 顶部加 header
  void schemaFileName;
  if (!out.includes('@tabtin/wire-codegen')) {
    out = HEADER + '\n' + out;
  }

  return out;
}
