/**
 * 自家 Swift codegen——从 JSON Schema (Draft 7) 直接生成 type-safe Swift 代码。
 *
 * 设计原则：
 *   - 每个 oneOf+discriminator → `enum X: Codable` + `init(from:)`/`encode(to:)`
 *   - 每个 anyOf 三 union（含 null）→ Swift `Optional`
 *   - 每个 object → `struct X: Codable`
 *   - 嵌套 ref → 用 ref name pascalCase
 *
 * 不依赖 quicktype——quicktype default 失类型安全（PoC §3.3 实测）。
 *
 * 优势：
 *   - 编译期保证 `case .text(let block)` 能 type narrow 到 TextBlock
 *   - 未知 type 字面量 decode 时抛 DecodingError（不静默通过）
 *   - 支持 nested oneOf+discriminator（snapshot 二级 discriminator）
 *
 * 限制：
 *   - 当前不处理 array of refs 的循环引用（schema 设计避免——叶子约束在 zod 端）
 *   - 不处理 OpenAPI 风的 nullable: true（zod-to-json-schema 不输出该形态）
 */

type JsonSchema = Record<string, unknown>;

const HEADER = `// ════════════════════════════════════════════════════════════════════
// 自动生成 — DO NOT EDIT MANUALLY
// Generated by @tabtin/wire-codegen (Wave 1 协议层)
// Source: packages/agent-wire/src/stream-content-block.ts (zod SSoT)
// 重新生成: pnpm --filter @tabtin/wire-codegen codegen
// 文档: docs/agent-runtime/wire-protocol.md
// ════════════════════════════════════════════════════════════════════

import Foundation
`;

const isObj = (x: unknown): x is JsonSchema =>
  typeof x === 'object' && x !== null && !Array.isArray(x);

interface CodegenContext {
  /** 跨 schema 去重（避免 ContentBlock 在多个 envelope schema 中重复定义） */
  emittedTypes: Set<string>;
  /** 本文件内本次新增的 type（避免循环引用时无限递归） */
  inProgress: Set<string>;
  /** 本文件内积累的输出 */
  output: string[];
  /** schema 文件名（用于命名 root） */
  baseName: string;
}

function snakeToPascal(s: string): string {
  // 把 _ / - / 空格 / . 都当分隔符（dotted 来自 event_type='agent.stream.message_start'）
  return s
    .split(/[_\-\s.]/)
    .filter(Boolean)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join('');
}

function snakeToCamel(s: string): string {
  const pascal = snakeToPascal(s);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

/** 把 enum literal type 字符串转成合法 Swift case 名 */
function literalToCaseName(lit: string): string {
  // text → text, tool_use → toolUse, tabtin_source_ref → tabtinSourceRef
  return snakeToCamel(lit);
}

/** 转 Swift 标识符 (避免关键字) */
function safeIdent(name: string): string {
  const SWIFT_KEYWORDS = new Set([
    'class', 'struct', 'enum', 'protocol', 'extension', 'func', 'var', 'let', 'init',
    'self', 'Self', 'true', 'false', 'nil', 'public', 'private', 'internal', 'fileprivate',
    'open', 'static', 'final', 'override', 'mutating', 'inout', 'in', 'out', 'where',
    'if', 'else', 'switch', 'case', 'default', 'for', 'while', 'do', 'return', 'break',
    'continue', 'throw', 'throws', 'rethrows', 'try', 'catch', 'guard', 'defer',
    'as', 'is', 'import', 'typealias', 'associatedtype',
    'String', 'Int', 'Double', 'Bool', 'Array', 'Dictionary', 'Optional',
  ]);
  if (SWIFT_KEYWORDS.has(name)) return `\`${name}\``;
  return name;
}

/** 处理 $ref → 对应 Swift 类型名
 *
 * **数字段处理**：zod-to-json-schema 在嵌套 union 里会输出
 * `#/definitions/X/anyOf/20` 这种带数字索引的 ref。直接 PascalCase("20") = "20"
 * 是非法 Swift 标识符。本函数遇到纯数字段时回溯到上一个非数字段，
 * 并把数字作为后缀拼出语义化名（如 `ContentBlockAnyOf20`）。
 *
 * 调用方如果有更好的 hintName（如 baseName），应该走 generateSwiftFile
 * 的 root-ref 特判路径，不依赖此函数。 */
function refToTypeName(ref: string): string {
  const parts = ref.split('/');
  const last = parts[parts.length - 1]!;
  if (/^\d+$/.test(last)) {
    // 找上一个非数字段，拼成 `${prev}AnyOf${num}` / `${prev}OneOf${num}`
    let i = parts.length - 2;
    while (i >= 0 && /^\d+$/.test(parts[i]!)) i--;
    if (i >= 0) {
      const prev = parts[i]!;
      const stem = snakeToPascal(prev);
      // 数字开头加 _ 前缀避开非法标识符；用 PascalCase 风格的 stem
      return `${stem}_${last}`;
    }
    return `_${last}`;
  }
  return snakeToPascal(last);
}

/** 解析 schema 引用（在 root.definitions / root.$defs 中查找）。
 *
 * **anyOf ↔ oneOf 兼容**：zod-to-json-schema 输出 `anyOf` 数组并在嵌套
 * `$ref` 中固定使用 `anyOf/N` 路径；本 codegen 的 inject_discriminator
 * 会把 anyOf 改成 oneOf（用于 datamodel-codegen 识别 discriminator），但
 * 内部 ref 路径已不可改回。所以遍历路径时若 `anyOf` 段不存在，自动回退
 * 到 `oneOf` 段（反之亦然）。 */
function resolveRef(ref: string, root: JsonSchema): JsonSchema {
  const parts = ref.replace(/^#\//, '').split('/');
  let cur: unknown = root;
  for (const part of parts) {
    if (Array.isArray(cur)) {
      const idx = Number(part);
      if (Number.isNaN(idx) || idx < 0 || idx >= cur.length) {
        throw new Error(`Cannot resolve ref ${ref} at array index '${part}'`);
      }
      cur = cur[idx];
      continue;
    }
    if (!isObj(cur)) throw new Error(`Cannot resolve ref ${ref}`);
    let next: unknown = (cur as JsonSchema)[part];
    if (typeof next === 'undefined') {
      // 兼容 anyOf ↔ oneOf 切换（inject_discriminator 转换后 ref 路径仍指 anyOf）
      if (part === 'anyOf' && Array.isArray((cur as JsonSchema)['oneOf'])) {
        next = (cur as JsonSchema)['oneOf'];
      } else if (part === 'oneOf' && Array.isArray((cur as JsonSchema)['anyOf'])) {
        next = (cur as JsonSchema)['anyOf'];
      }
    }
    cur = next;
  }
  if (!isObj(cur)) throw new Error(`Ref ${ref} did not resolve to an object`);
  return cur;
}

interface ResolvedSchema {
  schema: JsonSchema;
  /** 如果 schema 来自 ref，这是该 ref 解析出来的类型名 */
  refTypeName: string | null;
}

function resolveIfRef(schema: JsonSchema, root: JsonSchema): ResolvedSchema {
  if (typeof schema['$ref'] === 'string') {
    const ref = schema['$ref'];
    const resolved = resolveRef(ref, root);
    // zod merge(SourceMeta.partial()) 会产出 #/definitions/X/properties/field
    // 这类 ref 应 inline 成字段真实类型，而不是用末段 property 名作 struct 名。
    if (ref.includes('/properties/')) {
      return { schema: resolved, refTypeName: null };
    }
    const refName = refToTypeName(ref);
    return { schema: resolved, refTypeName: refName };
  }
  return { schema, refTypeName: null };
}

function isStringEnumSchema(schema: JsonSchema): schema is JsonSchema & { enum: string[] } {
  const values = schema['enum'];
  return Array.isArray(values) && values.length > 0 && values.every((v) => typeof v === 'string');
}

/** 把 enum literal 字符串转成合法 Swift case 名（支持 `/`、`-` 等分隔符） */
function enumValueToCaseName(value: string): string {
  const parts = value.split(/[^a-zA-Z0-9]+/).filter(Boolean);
  if (parts.length === 0) return 'value';
  const camel = parts
    .map((p, i) =>
      i === 0
        ? p.charAt(0).toLowerCase() + p.slice(1)
        : p.charAt(0).toUpperCase() + p.slice(1),
    )
    .join('');
  return safeIdent(camel);
}

function ensureStringEnumEmitted(name: string, values: string[], ctx: CodegenContext): void {
  if (ctx.emittedTypes.has(name)) return;

  const lines: string[] = [];
  lines.push(`public enum ${name}: String, Codable, Hashable, Sendable {`);
  for (const value of values) {
    const caseName = enumValueToCaseName(value);
    lines.push(`    case ${caseName} = "${value}"`);
  }
  lines.push('}');
  lines.push('');

  ctx.output.push(lines.join('\n'));
  ctx.emittedTypes.add(name);
}

/** 把 JSON Schema 类型映射到 Swift 类型 */
function schemaToSwiftType(
  schema: JsonSchema,
  root: JsonSchema,
  ctx: CodegenContext,
  hintName?: string,
): string {
  // $ref
  if (typeof schema['$ref'] === 'string') {
    const ref = schema['$ref'];
    const resolved = resolveRef(ref, root);
    if (ref.includes('/properties/')) {
      return schemaToSwiftType(resolved, root, ctx, hintName);
    }
    const refName = refToTypeName(ref);
    // 确保 ref 目标已生成
    ensureTypeEmitted(refName, resolved, root, ctx);
    return refName;
  }

  // const literal (单值 enum)
  if (typeof schema['const'] !== 'undefined') {
    const c = schema['const'];
    if (typeof c === 'number') return Number.isInteger(c) ? 'Int' : 'Double';
    if (typeof c === 'boolean') return 'Bool';
    return 'String';
  }

  // enum (string literals → 具名 Swift enum)
  if (isStringEnumSchema(schema)) {
    const enumName = hintName ?? 'WireStringEnum';
    ensureStringEnumEmitted(enumName, schema.enum, ctx);
    return enumName;
  }

  // anyOf with null → Optional
  if (Array.isArray(schema['anyOf'])) {
    const variants = schema['anyOf'] as JsonSchema[];
    const nullVariants = variants.filter((v) => v['type'] === 'null');
    const nonNull = variants.filter((v) => v['type'] !== 'null');
    if (nullVariants.length > 0 && nonNull.length === 1) {
      return `${schemaToSwiftType(nonNull[0]!, root, ctx, hintName)}?`;
    }
    // Generic union without discriminator → fall back to JSONValue
    return 'JSONValue';
  }

  // oneOf with discriminator → 已经在 ensureTypeEmitted 中处理；这里返回 hintName
  if (Array.isArray(schema['oneOf'])) {
    const oneOf = schema['oneOf'] as JsonSchema[];
    if (isObj(schema['discriminator'])) {
      // 必须有 hintName 才能生成 enum
      if (!hintName) {
        throw new Error('Inline oneOf+discriminator without hintName not supported; use $ref');
      }
      ensureUnionTypeEmitted(hintName, schema, root, ctx);
      return hintName;
    }
    // oneOf 无 discriminator → JSONValue
    return 'JSONValue';
  }

  // type-based
  const t = schema['type'];
  if (t === 'string') return 'String';
  if (t === 'integer') return 'Int';
  if (t === 'number') return 'Double';
  if (t === 'boolean') return 'Bool';
  if (t === 'null') return 'NSNull';
  if (t === 'array') {
    // 标准 array：items 是单个 schema
    if (isObj(schema['items'])) {
      const items = schema['items'] as JsonSchema;
      return `[${schemaToSwiftType(items, root, ctx, hintName ? `${hintName}Item` : undefined)}]`;
    }
    // tuple-form array（z.tuple）：items 是 schema 数组——
    // 如果所有 item 同类型，用该类型；否则降级 JSONValue。Swift 没有
    // 异构 tuple 的 Codable 直接支持，统一拼装数组类型保持简洁。
    if (Array.isArray(schema['items'])) {
      const itemArr = schema['items'] as JsonSchema[];
      if (itemArr.length === 0) return '[JSONValue]';
      const types = itemArr
        .filter((i) => isObj(i))
        .map((i) => schemaToSwiftType(i, root, ctx, hintName ? `${hintName}Item` : undefined));
      const allSame = types.every((tp) => tp === types[0]);
      return allSame ? `[${types[0]}]` : '[JSONValue]';
    }
    return '[JSONValue]';
  }
  if (t === 'object' || (typeof t === 'undefined' && isObj(schema['properties']))) {
    // **关键修复（W1-Review P0-1）**：
    // zod 的 `z.record(z.unknown())` 输出 JSON Schema `{type: "object", additionalProperties: {}}`
    // 没有 `properties`。如果直接 emit 空 struct（即使有 hintName），decode 时
    // Swift Codable 会**静默丢掉所有字段**——tool_use.input / mcp_tool_use.input
    // 等任意 JSON record 字段会被吞，re-encode 后变成 `{}`。
    //
    // 修复策略：当 schema 是"纯 additionalProperties only"（无 properties），
    // 总是返回 `[String: JSONValue]` 字典类型，**忽略 hintName**——这才是
    // `Record<string, unknown>` 在 Swift 的等价类型。
    const hasProperties = isObj(schema['properties']) && Object.keys(schema['properties'] as object).length > 0;
    if (!hasProperties) {
      return '[String: JSONValue]';
    }
    if (!hintName) {
      return '[String: JSONValue]';
    }
    ensureObjectTypeEmitted(hintName, schema, root, ctx);
    return hintName;
  }

  // Multiple types (e.g. ["string", "null"]) → Optional
  if (Array.isArray(t)) {
    const types = t as string[];
    const nullable = types.includes('null');
    const nonNull = types.filter((x) => x !== 'null');
    if (nonNull.length === 1) {
      const baseSchema: JsonSchema = { ...schema, type: nonNull[0]! };
      return `${schemaToSwiftType(baseSchema, root, ctx, hintName)}${nullable ? '?' : ''}`;
    }
    return 'JSONValue';
  }

  return 'JSONValue';
}

function ensureTypeEmitted(
  name: string,
  schema: JsonSchema,
  root: JsonSchema,
  ctx: CodegenContext,
): void {
  if (ctx.emittedTypes.has(name) || ctx.inProgress.has(name)) return;
  ctx.inProgress.add(name);

  if (Array.isArray(schema['oneOf']) && isObj(schema['discriminator'])) {
    ensureUnionTypeEmitted(name, schema, root, ctx);
  } else if (
    schema['type'] === 'object' ||
    (typeof schema['type'] === 'undefined' && isObj(schema['properties']))
  ) {
    ensureObjectTypeEmitted(name, schema, root, ctx);
  } else {
    // typealias for simple types / non-discriminated unions
    const swiftType = schemaToSwiftType(schema, root, ctx, name);
    // string enum 已在 schemaToSwiftType 内 emit 具名 enum，勿再 typealias 自引用
    if (swiftType !== name) {
      ctx.output.push(`public typealias ${name} = ${swiftType}`);
    }
  }

  ctx.inProgress.delete(name);
  ctx.emittedTypes.add(name);
}

interface FieldInfo {
  jsonName: string;
  swiftName: string;
  swiftType: string;
  isOptional: boolean;
  doc: string | null;
}

function getFieldsForObject(
  schema: JsonSchema,
  root: JsonSchema,
  ctx: CodegenContext,
  parentName: string,
): FieldInfo[] {
  const props = isObj(schema['properties']) ? schema['properties'] : {};
  const required = new Set(Array.isArray(schema['required']) ? (schema['required'] as string[]) : []);
  const fields: FieldInfo[] = [];

  for (const [propName, propSchema] of Object.entries(props)) {
    if (!isObj(propSchema)) continue;
    const isOptional = !required.has(propName);
    const hintName = `${parentName}${snakeToPascal(propName)}`;

    let swiftType: string;
    try {
      swiftType = schemaToSwiftType(propSchema, root, ctx, hintName);
    } catch (e) {
      throw new Error(`Failed to resolve ${parentName}.${propName}: ${(e as Error).message}`);
    }

    if (isOptional && !swiftType.endsWith('?')) {
      swiftType = `${swiftType}?`;
    }

    fields.push({
      jsonName: propName,
      swiftName: safeIdent(snakeToCamel(propName)),
      swiftType,
      isOptional,
      doc: typeof propSchema['description'] === 'string' ? propSchema['description'] : null,
    });
  }

  return fields;
}

function ensureObjectTypeEmitted(
  name: string,
  schema: JsonSchema,
  root: JsonSchema,
  ctx: CodegenContext,
): void {
  if (ctx.emittedTypes.has(name)) return;

  // 先解析所有字段（这会递归 emit 子类型）
  const fields = getFieldsForObject(schema, root, ctx, name);
  const lines: string[] = [];

  lines.push(`public struct ${name}: Codable, Hashable, Sendable {`);
  // 字段
  for (const f of fields) {
    if (f.doc) lines.push(`    /// ${f.doc.replace(/\n/g, '\n    /// ')}`);
    lines.push(`    public let ${f.swiftName}: ${f.swiftType}`);
  }
  lines.push('');

  // 主初始化器
  if (fields.length > 0) {
    const params = fields
      .map((f) =>
        f.isOptional
          ? `${f.swiftName}: ${f.swiftType} = nil`
          : `${f.swiftName}: ${f.swiftType}`,
      )
      .join(', ');
    lines.push(`    public init(${params}) {`);
    for (const f of fields) {
      lines.push(`        self.${f.swiftName} = ${f.swiftName}`);
    }
    lines.push('    }');
    lines.push('');
  } else {
    lines.push('    public init() {}');
    lines.push('');
  }

  // CodingKeys（field name 跟 JSON name 不一致时需要）
  const needsCustomKeys = fields.some((f) => f.swiftName !== f.jsonName && !f.jsonName.startsWith('_'));
  const hasUnderscoreFields = fields.some((f) => f.jsonName.startsWith('_'));
  if (needsCustomKeys || hasUnderscoreFields) {
    lines.push('    public enum CodingKeys: String, CodingKey {');
    for (const f of fields) {
      if (f.swiftName === f.jsonName) {
        lines.push(`        case ${f.swiftName}`);
      } else {
        // safeIdent 加了反引号，这里去掉
        const cleanName = f.swiftName.replace(/^`(.+)`$/, '$1');
        lines.push(`        case ${cleanName} = "${f.jsonName}"`);
      }
    }
    lines.push('    }');
  }

  lines.push('}');
  lines.push('');

  ctx.output.push(lines.join('\n'));
  ctx.emittedTypes.add(name);
}

interface UnionVariant {
  literal: string;
  caseName: string;
  payloadType: string;
}

/**
 * Stream envelope 的 event_type 字面量 → 独立 schema 已生成的 canonical struct。
 * AnyContentBlockStreamEvent union 必须引用这些类型，禁止 inline 重复 emit 同形 struct。
 */
const STREAM_ENVELOPE_PAYLOAD_BY_EVENT_TYPE: Record<string, string> = {
  'agent.stream.message_start': 'MessageStart',
  'agent.stream.message_delta': 'MessageDelta',
  'agent.stream.message_stop': 'MessageStop',
  'agent.stream.content_block_start': 'ContentBlockStart',
  'agent.stream.content_block_delta': 'ContentBlockDelta',
  'agent.stream.content_block_stop': 'ContentBlockStop',
};

function ensureUnionTypeEmitted(
  name: string,
  schema: JsonSchema,
  root: JsonSchema,
  ctx: CodegenContext,
): void {
  if (ctx.emittedTypes.has(name)) return;

  const oneOf = schema['oneOf'] as JsonSchema[];
  const discProp =
    isObj(schema['discriminator']) && typeof schema['discriminator']['propertyName'] === 'string'
      ? (schema['discriminator']['propertyName'] as string)
      : 'type';

  const variants: UnionVariant[] = [];

  for (const variant of oneOf) {
    const resolved = resolveIfRef(variant, root);
    const variantSchema = resolved.schema;

    // 找到 discriminator 字段的 const 值
    const props = isObj(variantSchema['properties']) ? variantSchema['properties'] : {};
    const discField = isObj(props[discProp]) ? props[discProp] : null;
    if (!discField || typeof discField['const'] !== 'string') {
      throw new Error(`Variant in ${name} oneOf has no const literal for ${discProp}: ${JSON.stringify(variantSchema).slice(0, 200)}`);
    }
    const literal = discField['const'];
    const caseName = literalToCaseName(literal);

    // payload type — 如果 variant 是 ref，用 ref 名；否则 inline 生成 nested type
    let payloadType: string;
    if (resolved.refTypeName) {
      payloadType = resolved.refTypeName;
      ensureTypeEmitted(payloadType, variantSchema, root, ctx);
    } else {
      const canonicalPayload =
        discProp === 'event_type' ? STREAM_ENVELOPE_PAYLOAD_BY_EVENT_TYPE[literal] : undefined;
      if (canonicalPayload) {
        payloadType = canonicalPayload;
        if (!ctx.emittedTypes.has(canonicalPayload)) {
          throw new Error(
            `${name}: envelope payload '${canonicalPayload}' for event_type='${literal}' ` +
              'not yet emitted — process any_event.json after envelope schemas',
          );
        }
      } else {
        // Inline variant → 生成 nested type 名
        payloadType = `${name}${snakeToPascal(literal)}Payload`;
        ensureObjectTypeEmitted(payloadType, variantSchema, root, ctx);
      }
    }

    variants.push({ literal, caseName, payloadType });
  }

  // Generate enum
  const lines: string[] = [];
  lines.push(`public enum ${name}: Codable, Hashable, Sendable {`);
  for (const v of variants) {
    lines.push(`    case ${v.caseName}(${v.payloadType})`);
  }
  lines.push('');

  // Discriminator helper
  lines.push(`    public var ${snakeToCamel(discProp)}: String {`);
  lines.push('        switch self {');
  for (const v of variants) {
    lines.push(`        case .${v.caseName}: return "${v.literal}"`);
  }
  lines.push('        }');
  lines.push('    }');
  lines.push('');

  // _DiscriminatorPeek inner type
  lines.push('    private struct _DiscriminatorPeek: Codable {');
  lines.push(`        let ${snakeToCamel(discProp)}: String`);
  if (snakeToCamel(discProp) !== discProp) {
    lines.push('        enum CodingKeys: String, CodingKey {');
    lines.push(`            case ${snakeToCamel(discProp)} = "${discProp}"`);
    lines.push('        }');
  }
  lines.push('    }');
  lines.push('');

  // init(from:)
  lines.push('    public init(from decoder: Decoder) throws {');
  lines.push('        let container = try decoder.singleValueContainer()');
  lines.push('        let peek = try container.decode(_DiscriminatorPeek.self)');
  lines.push(`        switch peek.${snakeToCamel(discProp)} {`);
  for (const v of variants) {
    lines.push(`        case "${v.literal}":`);
    lines.push(`            self = .${v.caseName}(try container.decode(${v.payloadType}.self))`);
  }
  lines.push('        default:');
  lines.push(
    `            throw DecodingError.dataCorruptedError(in: container, debugDescription: "Unknown ${discProp} '\\(peek.${snakeToCamel(discProp)})' for ${name}")`,
  );
  lines.push('        }');
  lines.push('    }');
  lines.push('');

  // encode(to:)
  lines.push('    public func encode(to encoder: Encoder) throws {');
  lines.push('        var container = encoder.singleValueContainer()');
  lines.push('        switch self {');
  for (const v of variants) {
    lines.push(`        case .${v.caseName}(let payload):`);
    lines.push('            try container.encode(payload)');
  }
  lines.push('        }');
  lines.push('    }');
  lines.push('}');
  lines.push('');

  ctx.output.push(lines.join('\n'));
  ctx.emittedTypes.add(name);
}

const JSON_VALUE_HELPER = `
/// Type-safe JSON 任意值（Swift Codable 不直接支持 Any）。
/// 用于 \`tool_use.input\` 等 \`Record<string, unknown>\` 类型字段。
public enum JSONValue: Codable, Hashable, Sendable {
    case null
    case bool(Bool)
    case int(Int)
    case double(Double)
    case string(String)
    case array([JSONValue])
    case object([String: JSONValue])

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if container.decodeNil() {
            self = .null
        } else if let v = try? container.decode(Bool.self) {
            self = .bool(v)
        } else if let v = try? container.decode(Int.self) {
            self = .int(v)
        } else if let v = try? container.decode(Double.self) {
            self = .double(v)
        } else if let v = try? container.decode(String.self) {
            self = .string(v)
        } else if let v = try? container.decode([JSONValue].self) {
            self = .array(v)
        } else if let v = try? container.decode([String: JSONValue].self) {
            self = .object(v)
        } else {
            throw DecodingError.dataCorruptedError(
                in: container,
                debugDescription: "JSONValue: unsupported value"
            )
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .null:        try container.encodeNil()
        case .bool(let v): try container.encode(v)
        case .int(let v):  try container.encode(v)
        case .double(let v): try container.encode(v)
        case .string(let v): try container.encode(v)
        case .array(let v):  try container.encode(v)
        case .object(let v): try container.encode(v)
        }
    }
}
`;

export function generateSwiftFile(
  schema: JsonSchema,
  baseName: string,
  emittedTypes: Set<string>,
): string {
  const ctx: CodegenContext = {
    emittedTypes,
    inProgress: new Set(),
    output: [],
    baseName,
  };

  // Process definitions first (let them be available for refs)
  for (const defKey of ['definitions', '$defs'] as const) {
    const defs = schema[defKey];
    if (isObj(defs)) {
      for (const [defName, defSchema] of Object.entries(defs)) {
        if (isObj(defSchema)) {
          const typeName = snakeToPascal(defName);
          ensureTypeEmitted(typeName, defSchema, schema, ctx);
        }
      }
    }
  }

  // Top-level schema (root)
  const rootName = snakeToPascal(baseName);
  if (typeof schema['$ref'] === 'string') {
    const refStr = schema['$ref'];
    const refLast = refStr.split('/').pop() || '';
    if (/^\d+$/.test(refLast)) {
      // root ref 末段是数字（如 #/definitions/ContentBlock/anyOf/20）——
      // 这会让生成的类型名变成 `_20` / `ContentBlock_20` 等噪声名。
      // 改为直接解析 ref 取出 variant schema，用 baseName 作为根类型名生成。
      const resolved = resolveRef(refStr, schema);
      ensureTypeEmitted(rootName, resolved, schema, ctx);
    } else {
      const refName = refToTypeName(refStr);
      if (refName !== rootName) {
        ctx.output.push(`public typealias ${rootName} = ${refName}`);
      }
    }
  } else {
    ensureTypeEmitted(rootName, schema, schema, ctx);
  }

  // Compose output
  const parts: string[] = [HEADER];
  // 仅在第一个 generated 文件中放 JSONValue helper
  if (!emittedTypes.has('__JSONValue_emitted__')) {
    parts.push(JSON_VALUE_HELPER);
    emittedTypes.add('__JSONValue_emitted__');
  }
  parts.push(...ctx.output);
  return parts.join('\n');
}
