# Generated by Django 4.2.7 on 2026-04-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FtsOutboxPg',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('index_name', models.CharField(max_length=64)),
                ('doc_id', models.CharField(max_length=64)),
                ('action', models.CharField(choices=[('upsert', 'Upsert'), ('delete', 'Delete')], max_length=16)),
                ('workteam_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('last_error', models.CharField(blank=True, default='', max_length=512)),
            ],
            options={
                'db_table': 'fts_outbox_pg',
                'indexes': [models.Index(condition=models.Q(('processed_at__isnull', True)), fields=['processed_at', 'created_at'], name='fts_outbox_pg_pending_idx'), models.Index(fields=['index_name', 'doc_id'], name='fts_outbox_pg_idx_doc_idx'), models.Index(condition=models.Q(('processed_at__isnull', True)), fields=['workteam_id', 'processed_at'], name='fts_outbox_pg_wt_pending_idx')],
            },
        ),
        migrations.CreateModel(
            name='FtsOutbox',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('index_name', models.CharField(max_length=64)),
                ('doc_id', models.CharField(max_length=64)),
                ('action', models.CharField(choices=[('upsert', 'Upsert'), ('delete', 'Delete')], max_length=16)),
                ('workteam_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('last_error', models.CharField(blank=True, default='', max_length=512)),
            ],
            options={
                'db_table': 'fts_outbox',
                'indexes': [models.Index(fields=['processed_at', 'created_at'], name='fts_outbox_proc_created_idx'), models.Index(fields=['index_name', 'doc_id'], name='fts_outbox_idx_doc_idx'), models.Index(fields=['workteam_id', 'processed_at'], name='fts_outbox_wt_proc_idx')],
            },
        ),
    ]
