# Generated by Django 4.2.7 on 2026-04-17 13:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('workteam_id', models.UUIDField(db_index=True)),
                ('query', models.TextField()),
                ('types', models.CharField(blank=True, default='', max_length=64)),
                ('result_count', models.IntegerField()),
                ('took_ms', models.IntegerField()),
                ('degraded', models.BooleanField(default=False)),
                ('notice', models.CharField(blank=True, max_length=64, null=True)),
                ('clicked_result_id', models.CharField(blank=True, max_length=64, null=True)),
                ('clicked_result_type', models.CharField(blank=True, max_length=32, null=True)),
                ('clicked_position', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fts_analytics',
                'indexes': [models.Index(fields=['workteam_id', '-created_at'], name='fts_analyti_worktea_b10eec_idx'), models.Index(fields=['result_count', '-created_at'], name='fts_analyti_result__6fc0cc_idx'), models.Index(fields=['user_id', '-created_at'], name='fts_analyti_user_id_195a1a_idx')],
            },
        ),
    ]
