# Generated by Django 4.2.7 on 2026-07-07 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fts', '0003_rename_workteam_to_organization'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='searchanalytics',
            new_name='fts_analyti_organiz_575b98_idx',
            old_name='fts_analyti_worktea_b10eec_idx',
        ),
    ]
