# Generated by Django 4.2.7 on 2026-03-04 20:27

import apps.users.membership.models
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipTier',
            fields=[
                ('id', models.CharField(default=apps.users.membership.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('tier_type', models.CharField(help_text='如: free, basic, pro', max_length=50, unique=True, verbose_name='等级标识')),
                ('name', models.CharField(max_length=100, verbose_name='显示名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='价格（元）')),
                ('duration_months', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='时长（月）')),
                ('max_tables', models.IntegerField(default=10, help_text='-1表示无限制', verbose_name='最大表格数')),
                ('max_records_per_table', models.IntegerField(default=1000, help_text='-1表示无限制', verbose_name='每表最大记录数')),
                ('max_api_calls_per_day', models.IntegerField(default=100, help_text='-1表示无限制', verbose_name='每日API调用上限')),
                ('max_crawl_tasks_per_day', models.IntegerField(default=10, help_text='-1表示无限制', verbose_name='每日采集任务上限')),
                ('llm_token_quota_per_month', models.IntegerField(default=10000, help_text='-1表示无限制，0表示无配额', validators=[django.core.validators.MinValueValidator(-1)], verbose_name='每月LLM Token配额')),
                ('included_storage_bytes', models.BigIntegerField(default=0, help_text='该等级赠送的存储额度，同步到 workspace entitlement', validators=[django.core.validators.MinValueValidator(0)], verbose_name='赠送存储容量（字节）')),
                ('included_llm_credits_monthly', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='该等级每月赠送的LLM点券额度，同步到 workspace entitlement', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='每月赠送LLM额度（点券）')),
                ('max_members', models.IntegerField(default=-1, help_text='-1表示无限制', verbose_name='最大成员数')),
                ('base_seats', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='套餐包含基础席位数')),
                ('extra_seat_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='每额外席位月费（元）')),
                ('features', models.JSONField(default=dict, help_text='示例: {"ai_field": true, "advanced_export": true}', verbose_name='功能权限')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '会员等级',
                'verbose_name_plural': '会员等级',
                'db_table': 'users_membership_tier',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.CharField(default=apps.users.membership.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='工作空间ID')),
                ('status', models.CharField(choices=[('active', '有效'), ('expired', '已过期')], db_index=True, default='active', max_length=20, verbose_name='状态')),
                ('start_date', models.DateTimeField(verbose_name='开始时间')),
                ('end_date', models.DateTimeField(db_index=True, verbose_name='到期时间')),
                ('related_order_id', models.CharField(blank=True, db_index=True, max_length=36, verbose_name='关联订单ID')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='自动续费')),
                ('purchased_by', models.CharField(blank=True, help_text='记录为哪个用户发起的购买操作', max_length=36, verbose_name='购买者用户ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workspace_memberships', to='membership.membershiptier', verbose_name='会员等级')),
            ],
            options={
                'verbose_name': '工作空间会员',
                'verbose_name_plural': '工作空间会员',
                'db_table': 'users_membership_workspace_membership',
                'ordering': ['-created_at'],
            },
            bases=(apps.users.membership.models.MembershipStatusMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.CharField(default=apps.users.membership.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', '有效'), ('expired', '已过期')], db_index=True, default='active', max_length=20, verbose_name='状态')),
                ('start_date', models.DateTimeField(verbose_name='开始时间')),
                ('end_date', models.DateTimeField(db_index=True, verbose_name='到期时间')),
                ('related_order_id', models.CharField(blank=True, db_index=True, max_length=36, verbose_name='关联订单ID')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='自动续费')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='membership.membershiptier', verbose_name='会员等级')),
            ],
            options={
                'verbose_name': '用户会员',
                'verbose_name_plural': '用户会员',
                'db_table': 'users_membership_user_membership',
                'ordering': ['-created_at'],
            },
            bases=(apps.users.membership.models.MembershipStatusMixin, models.Model),
        ),
    ]
