# Generated by Django 4.2.7 on 2026-03-04 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='user',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddIndex(
            model_name='membershiptier',
            index=models.Index(fields=['tier_type'], name='users_membe_tier_ty_0500a7_idx'),
        ),
        migrations.AddIndex(
            model_name='membershiptier',
            index=models.Index(fields=['is_active', 'sort_order'], name='users_membe_is_acti_aeed10_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacemembership',
            index=models.Index(fields=['workspace_id', 'status'], name='users_membe_workspa_e5d848_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacemembership',
            index=models.Index(fields=['status', 'end_date'], name='users_membe_status_184b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='usermembership',
            index=models.Index(fields=['user', 'status'], name='users_membe_user_id_bfc99a_idx'),
        ),
        migrations.AddIndex(
            model_name='usermembership',
            index=models.Index(fields=['status', 'end_date'], name='users_membe_status_7eb3f1_idx'),
        ),
    ]
