# Generated by Django 4.2.7 on 2026-03-06 02:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptier',
            name='trash_retention_days',
            field=models.IntegerField(default=30, help_text='该等级的回收站资源保留天数，默认 30 天', validators=[django.core.validators.MinValueValidator(1)], verbose_name='回收站保留天数'),
        ),
    ]
