# Generated by Django 4.2.7 on 2026-03-06 23:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_add_trash_retention_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptier',
            name='llm_token_quota_per_month',
            field=models.IntegerField(default=10000, help_text='[DEPRECATED] 已被 included_llm_credits_monthly（workspace 级点券预算）替代。仅在无 workspace_id 的 legacy 路径中仍被使用。-1表示无限制，0表示无配额', validators=[django.core.validators.MinValueValidator(-1)], verbose_name='每月LLM Token配额'),
        ),
    ]
