# Generated by Django 4.2.7 on 2026-03-07 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_alter_membershiptier_llm_token_quota_per_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershiptier',
            name='llm_token_quota_per_month',
        ),
    ]
