# Generated by Django 4.2.7 on 2026-03-19 02:11

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_workspace_to_workteam_rename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workteammembership',
            options={'ordering': ['-created_at'], 'verbose_name': '工作团队会员', 'verbose_name_plural': '工作团队会员'},
        ),
        migrations.RemoveIndex(
            model_name='workteammembership',
            name='users_membe_workspa_e5d848_idx',
        ),
        migrations.AlterField(
            model_name='membershiptier',
            name='included_llm_credits_monthly',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='该等级每月赠送的LLM点券额度，同步到 workteam entitlement', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='每月赠送LLM额度（点券）'),
        ),
        migrations.AlterField(
            model_name='membershiptier',
            name='included_storage_bytes',
            field=models.BigIntegerField(default=0, help_text='该等级赠送的存储额度，同步到 workteam entitlement', validators=[django.core.validators.MinValueValidator(0)], verbose_name='赠送存储容量（字节）'),
        ),
        migrations.AlterField(
            model_name='membershiptier',
            name='max_api_calls_per_day',
            field=models.IntegerField(default=100, help_text='Legacy, not enforced. 实际限流见 ApiToken.rate_limit', verbose_name='[Legacy] 每日API调用上限'),
        ),
        migrations.AlterField(
            model_name='membershiptier',
            name='max_crawl_tasks_per_day',
            field=models.IntegerField(default=10, help_text='Legacy, not enforced. ExtractionTask 已移除', verbose_name='[Legacy] 每日采集任务上限'),
        ),
        migrations.AlterField(
            model_name='membershiptier',
            name='max_members',
            field=models.IntegerField(default=-1, help_text='-1表示无限制。注意：seed data 中 free=3/basic=5/pro=20/enterprise=-1；手动新建时需按实际等级手动设置，default=-1 仅作字段兜底。', verbose_name='最大成员数'),
        ),
        migrations.AlterField(
            model_name='membershiptier',
            name='trash_retention_days',
            field=models.IntegerField(default=30, help_text='该等级的回收站资源保留天数。seed data: free=14, basic=30, pro=60, enterprise=90；手动新建时按实际等级设置，default=30 仅作字段兜底。', validators=[django.core.validators.MinValueValidator(1)], verbose_name='回收站保留天数'),
        ),
        migrations.AlterField(
            model_name='workteammembership',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workteam_memberships', to='membership.membershiptier', verbose_name='会员等级'),
        ),
        migrations.AlterField(
            model_name='workteammembership',
            name='workteam_id',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='工作团队ID'),
        ),
        migrations.AddIndex(
            model_name='workteammembership',
            index=models.Index(fields=['workteam_id', 'status'], name='users_membe_worktea_43ee8e_idx'),
        ),
    ]
