# Generated by Django 4.2.7 on 2026-04-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_repair_workspace_to_workteam_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptier',
            name='max_conversations_per_day',
            field=models.IntegerField(default=-1, help_text='-1表示无限制。seed data: free=50, basic=200, pro=1000, enterprise=-1；通过 Redis 计数器 + BillingUsageEvent fallback 执行检查。', verbose_name='每日最大对话次数'),
        ),
    ]
