# Generated by Django 4.2.7 on 2026-05-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0010_add_max_conversations_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptier',
            name='features',
            field=models.JSONField(default=dict, help_text='示例: {"api_access": true, "advanced_export": true}', verbose_name='功能权限'),
        ),
    ]
