# Generated by Django 4.2.7 on 2026-07-07 22:05

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0016_rename_workteam_to_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationmembership',
            options={'ordering': ['-created_at'], 'verbose_name': '组织会员', 'verbose_name_plural': '组织会员'},
        ),
        migrations.RenameIndex(
            model_name='organizationmembership',
            new_name='users_membe_organiz_65e97b_idx',
            old_name='users_membe_worktea_43ee8e_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationmembership',
            new_name='users_membe_status_2ce426_idx',
            old_name='users_membe_status_184b7f_idx',
        ),
        migrations.AlterField(
            model_name='membershiptier',
            name='included_llm_credits_monthly',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='该等级每月赠送的LLM点券额度，同步到 organization entitlement', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='每月赠送LLM额度（点券）'),
        ),
        migrations.AlterField(
            model_name='membershiptier',
            name='included_storage_bytes',
            field=models.BigIntegerField(default=0, help_text='该等级赠送的存储额度，同步到 organization entitlement', validators=[django.core.validators.MinValueValidator(0)], verbose_name='赠送存储容量（字节）'),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='organization_id',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_memberships', to='membership.membershiptier', verbose_name='会员等级'),
        ),
    ]
