# Generated by Django 4.2.7 on 2026-07-28

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membership', '0017_alter_organizationmembership_options_and_more'),
        ('tabtinspace', '0133_collection_privacy_cleanup_7657'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='billing_cycle',
            field=models.CharField(
                blank=True,
                choices=[('monthly', '月付'), ('yearly', '年付')],
                max_length=20,
                null=True,
                verbose_name='计费周期',
            ),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='current_actual_paid_period_price',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='完整周期成交价快照，不是升级补差金额；历史事实不可恢复时保持为空。',
                max_digits=12,
                null=True,
                verbose_name='当前完整周期实际成交价',
            ),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='grace_period_end',
            field=models.DateTimeField(
                blank=True,
                help_text='PR2 仅预留字段；运行时宽限逻辑由后续生命周期服务统一。',
                null=True,
                verbose_name='宽限期截止时间',
            ),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='lifecycle_version',
            field=models.PositiveBigIntegerField(
                blank=True,
                help_text='用于报价和套餐变更的乐观并发控制。',
                null=True,
                verbose_name='生命周期版本',
            ),
        ),
        migrations.CreateModel(
            name='OrganizationMembershipChangeLog',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'change_type',
                    models.CharField(
                        choices=[
                            ('new', '新购'),
                            ('renew', '续费'),
                            ('upgrade', '升级'),
                            ('downgrade', '降级'),
                            ('switch', '同级或周期切换'),
                            ('expire', '到期'),
                            ('free_downgrade', '降为免费版'),
                            ('cancel_change', '取消变更'),
                            ('admin_adjust', '管理员调整'),
                            ('refund_revoke', '退款撤销'),
                            ('suspend', '暂停'),
                            ('resume', '恢复'),
                        ],
                        max_length=32,
                        verbose_name='变更类型',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('payment_pending', '待支付'),
                            ('paid', '已支付'),
                            ('pending', '待生效'),
                            ('applying', '应用中'),
                            ('applied', '已应用'),
                            ('failed', '失败'),
                            ('cancelled', '已取消'),
                        ],
                        max_length=32,
                        verbose_name='处理状态',
                    ),
                ),
                (
                    'from_tier_snapshot',
                    models.JSONField(blank=True, default=dict, verbose_name='原套餐快照'),
                ),
                (
                    'to_tier_snapshot',
                    models.JSONField(blank=True, default=dict, verbose_name='目标套餐快照'),
                ),
                (
                    'from_billing_cycle',
                    models.CharField(
                        blank=True,
                        choices=[('monthly', '月付'), ('yearly', '年付')],
                        max_length=20,
                        null=True,
                        verbose_name='原计费周期',
                    ),
                ),
                (
                    'to_billing_cycle',
                    models.CharField(
                        blank=True,
                        choices=[('monthly', '月付'), ('yearly', '年付')],
                        max_length=20,
                        null=True,
                        verbose_name='目标计费周期',
                    ),
                ),
                (
                    'requested_at',
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name='申请时间',
                    ),
                ),
                (
                    'effective_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='计划生效时间'),
                ),
                (
                    'applied_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='实际生效时间'),
                ),
                (
                    'payment_order_id',
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text='仅保存 PaymentOrder 主键字符串，不保存或混用 order_no。',
                        max_length=64,
                        null=True,
                        verbose_name='支付订单主键',
                    ),
                ),
                (
                    'list_amount',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name='目标周期原价',
                    ),
                ),
                (
                    'current_value',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name='当前剩余价值',
                    ),
                ),
                (
                    'target_value',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name='目标剩余价值',
                    ),
                ),
                (
                    'discount_amount',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name='优惠金额',
                    ),
                ),
                (
                    'payable_amount',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name='实际应付金额',
                    ),
                ),
                ('reason', models.TextField(blank=True, default='', verbose_name='变更原因')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                (
                    'from_tier',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='membership.membershiptier',
                        verbose_name='原套餐',
                    ),
                ),
                (
                    'membership',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='change_logs',
                        to='membership.organizationmembership',
                        verbose_name='关联会员',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='membership_change_logs',
                        to='tabtinspace.organization',
                        verbose_name='组织',
                    ),
                ),
                (
                    'requested_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='申请人',
                    ),
                ),
                (
                    'to_tier',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='membership.membershiptier',
                        verbose_name='目标套餐',
                    ),
                ),
            ],
            options={
                'verbose_name': '组织套餐变更记录',
                'verbose_name_plural': '组织套餐变更记录',
                'db_table': 'users_membership_organization_change_log',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(
                        fields=['organization', 'created_at'],
                        name='memchg_org_created_idx',
                    ),
                    models.Index(
                        fields=['organization', 'status', 'effective_at'],
                        name='memchg_org_status_eff_idx',
                    ),
                    models.Index(
                        fields=['membership', 'created_at'],
                        name='memchg_member_created_idx',
                    ),
                    models.Index(
                        fields=['change_type', 'status'],
                        name='memchg_type_status_idx',
                    ),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        condition=Q(payment_order_id__isnull=False),
                        fields=('payment_order_id',),
                        name='uniq_membership_change_payment_order',
                    ),
                    models.UniqueConstraint(
                        condition=Q(
                            change_type__in=['downgrade', 'switch'],
                            status='pending',
                        ),
                        fields=('organization',),
                        name='uniq_pending_membership_plan_per_org',
                    ),
                    models.CheckConstraint(
                        check=Q(payment_order_id__isnull=True)
                        | ~Q(payment_order_id=''),
                        name='membership_change_payment_order_nonempty',
                    ),
                ],
            },
        ),
    ]
