# Generated by Django 4.2.7 on 2026-03-04 20:27

import apps.extensions.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('api_key', 'API Key'), ('oauth', 'OAuth Token'), ('secret', 'Secret / Password'), ('website_login', 'Website Login'), ('other', 'Other')], default='api_key', max_length=20)),
                ('service_name', models.CharField(help_text='服务标识，如 openai / serper / sendgrid', max_length=100)),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('encrypted_data', apps.extensions.fields.EncryptedJSONField(default=dict, help_text="加密存储的凭据数据，格式 {'key': '...', 'secret': '...', ...}")),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='非敏感元数据（描述、标签等）')),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'credential_vault_user_credential',
                'ordering': ['-created_at'],
            },
        ),
    ]
