# Generated by Django 4.2.7 on 2026-03-04 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credential_vault', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredential',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='usercredential',
            index=models.Index(fields=['user', 'category'], name='credential__user_id_2f974c_idx'),
        ),
        migrations.AddIndex(
            model_name='usercredential',
            index=models.Index(fields=['user', 'service_name'], name='credential__user_id_76dbc6_idx'),
        ),
    ]
