# Generated by Django 4.2.7 on 2026-03-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential_vault', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredential',
            name='category',
            field=models.CharField(choices=[('api_key', 'API Key'), ('oauth', 'OAuth Token'), ('secret', 'Secret / Password'), ('website_login', 'Website Login'), ('app_login', 'App Login'), ('other', 'Other')], default='api_key', max_length=20),
        ),
    ]
