# Generated by Django 4.2.7 on 2026-05-05 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credential_vault', '0006_user_onboarding_state'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='saveblacklistentry',
            new_name='credential__user_id_73e45c_idx',
            old_name='cred_save_bl_user_domain_idx',
        ),
    ]
