# Generated by Django 5.2.4 on 2025-11-14 08:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedSchema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Schema ID', primary_key=True, serialize=False)),
                ('thread_id', models.CharField(db_index=True, help_text='Thread ID（探索会话 ID）', max_length=100)),
                ('user_id', models.UUIDField(db_index=True, help_text='用户 ID')),
                ('url', models.CharField(help_text='原始 URL', max_length=500)),
                ('domain', models.CharField(db_index=True, help_text='域名（用于缓存）', max_length=200)),
                ('url_pattern', models.CharField(blank=True, help_text='URL 模式（用于匹配复用，如 /product/{id}）', max_length=500)),
                ('schema_json', models.JSONField(help_text='完整的 Schema（PostgreSQL JSONB）')),
                ('modules_used', models.JSONField(help_text='使用的模块列表（PostgreSQL JSONB）')),
                ('confidence', models.FloatField(help_text='置信度（0-1）')),
                ('sample_data', models.JSONField(blank=True, help_text='采样数据', null=True)),
                ('validation_stats', models.JSONField(blank=True, help_text='验证统计', null=True)),
                ('usage_count', models.IntegerField(default=0, help_text='被复用次数')),
                ('success_rate', models.FloatField(blank=True, help_text='成功率（0-1）', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='最后使用时间', null=True)),
            ],
            options={
                'verbose_name': 'Generated Schema',
                'verbose_name_plural': 'Generated Schemas',
                'db_table': 'generated_schemas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['domain'], name='idx_schema_domain'), models.Index(fields=['url_pattern'], name='idx_schema_url_pattern'), models.Index(fields=['-created_at'], name='idx_schema_created'), models.Index(fields=['user_id'], name='idx_schema_user'), models.Index(fields=['thread_id'], name='idx_schema_thread')],
            },
        ),
        migrations.CreateModel(
            name='SchemaTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='模板 ID', primary_key=True, serialize=False)),
                ('module_name', models.CharField(db_index=True, help_text='模块名称（如 basic_schema, pagination_schema）', max_length=50, unique=True)),
                ('template_json', models.JSONField(help_text='模板定义（PostgreSQL JSONB）')),
                ('description', models.TextField(blank=True, help_text='模板描述')),
                ('version', models.CharField(default='1.0.0', help_text='模板版本', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
            ],
            options={
                'verbose_name': 'Schema Template',
                'verbose_name_plural': 'Schema Templates',
                'db_table': 'schema_templates',
                'ordering': ['module_name'],
                'indexes': [models.Index(fields=['module_name'], name='idx_template_module'), models.Index(fields=['is_active'], name='idx_template_active')],
            },
        ),
        migrations.CreateModel(
            name='SchemaUsageLog',
            fields=[
                ('id', models.BigAutoField(help_text='日志 ID', primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True, help_text='用户 ID')),
                ('url', models.CharField(help_text='使用的 URL', max_length=500)),
                ('instruction', models.TextField(blank=True, help_text='用户指令')),
                ('success', models.BooleanField(help_text='是否成功')),
                ('extracted_count', models.IntegerField(blank=True, help_text='提取了多少条数据', null=True)),
                ('error_message', models.TextField(blank=True, help_text='错误信息（失败时）')),
                ('execution_time_ms', models.IntegerField(blank=True, help_text='执行时间（毫秒）', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('schema', models.ForeignKey(help_text='关联的 Schema', on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='schema_discovery.generatedschema')),
            ],
            options={
                'verbose_name': 'Schema Usage Log',
                'verbose_name_plural': 'Schema Usage Logs',
                'db_table': 'schema_usage_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['schema_id'], name='idx_log_schema'), models.Index(fields=['user_id'], name='idx_log_user'), models.Index(fields=['-created_at'], name='idx_log_created'), models.Index(fields=['success'], name='idx_log_success')],
            },
        ),
    ]
