# Generated by Django 4.2.7 on 2026-03-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerecord',
            name='workspace_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='文件归属的工作空间，用于存储计量', max_length=100, verbose_name='工作空间ID'),
        ),
    ]
