# Generated by Django 4.2.7 on 2026-03-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0002_add_workspace_id_to_filerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileusage',
            name='module',
            field=models.CharField(choices=[('chat', 'Chat 对话'), ('tabdata', 'TabData 表格'), ('tabdoc', 'TabDoc 文档'), ('tabdesign', 'TabDesign 设计'), ('tabslide', 'TabSlide 幻灯片'), ('tabvideo', 'TabVideo 视频'), ('tabmail', 'TabMail 邮件'), ('tabmemo', 'TabMemo 碎片'), ('tabchat', 'TabChat 即时通讯'), ('tabwhiteboard', 'TabWhiteboard 画布'), ('tabcode', 'TabCode 代码'), ('media_generation', '媒体生成'), ('crawl', 'Crawl 采集'), ('other', '其他')], db_index=True, max_length=32, verbose_name='来源模块'),
        ),
    ]
