# Generated by Django 4.2.7 on 2026-03-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0005_alter_fileusage_module_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='filerecord',
            index=models.Index(fields=['upload_user', 'status', 'created_at'], name='services_os_upload__2b2f23_idx'),
        ),
    ]
