# Generated by Django 4.2.7 on 2026-03-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0007_workspace_to_workteam_rename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerecord',
            name='workteam_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='文件归属的工作团队，用于存储计量', max_length=100, verbose_name='工作团队ID'),
        ),
        migrations.AlterField(
            model_name='ossadminactionlog',
            name='action_type',
            field=models.CharField(choices=[('batch_delete', '批量删除'), ('repair_workteam_scope', '修复 workteam 归属')], db_index=True, max_length=64, verbose_name='动作类型'),
        ),
        migrations.AlterField(
            model_name='ossadminactionlog',
            name='workteam_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='当治理动作只涉及单个工作团队时写入；跨工作团队动作留空', max_length=100, verbose_name='主工作团队ID'),
        ),
        migrations.AlterField(
            model_name='ossadminactionlog',
            name='workteam_ids',
            field=models.JSONField(default=list, help_text='治理动作影响的工作团队 ID 列表', verbose_name='影响的工作团队列表'),
        ),
        migrations.AlterField(
            model_name='ossadminactionlog',
            name='workteam_ids_text',
            field=models.TextField(blank=True, default='', help_text='格式: |workteam_id_1|workteam_id_2|，用于高性能模糊检索', verbose_name='影响工作团队检索文本'),
        ),
        migrations.AlterField(
            model_name='uploadtask',
            name='workteam_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='上传任务归属的工作团队，用于清理和后台筛选', max_length=100, verbose_name='工作团队ID'),
        ),
    ]
