# Generated by Django 4.2.7 on 2026-04-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0008_alter_filerecord_workteam_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerecord',
            name='hash_algorithm',
            field=models.CharField(blank=True, db_index=True, default='', help_text='md5 / sha256 / sha256-sampled，空=未知(旧数据)', max_length=32, verbose_name='哈希算法'),
        ),
    ]
