# Generated by Django 4.2.7 on 2026-07-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0012_rename_workteam_to_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerecord',
            name='organization_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='文件归属的组织，用于存储计量', max_length=100, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='ossadminactionlog',
            name='action_type',
            field=models.CharField(choices=[('batch_delete', '批量删除'), ('repair_organization_scope', '修复 organization 归属')], db_index=True, max_length=64, verbose_name='动作类型'),
        ),
        migrations.AlterField(
            model_name='ossadminactionlog',
            name='organization_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='当治理动作只涉及单个组织时写入；跨组织动作留空', max_length=100, verbose_name='主组织ID'),
        ),
        migrations.AlterField(
            model_name='ossadminactionlog',
            name='organization_ids',
            field=models.JSONField(default=list, help_text='治理动作影响的组织 ID 列表', verbose_name='影响的组织列表'),
        ),
        migrations.AlterField(
            model_name='ossadminactionlog',
            name='organization_ids_text',
            field=models.TextField(blank=True, default='', help_text='格式: |organization_id_1|organization_id_2|，用于高性能模糊检索', verbose_name='影响组织检索文本'),
        ),
        migrations.AlterField(
            model_name='uploadtask',
            name='organization_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='上传任务归属的组织，用于清理和后台筛选', max_length=100, verbose_name='组织ID'),
        ),
    ]
