# Generated by Django 4.2.7 on 2026-07-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0013_alter_filerecord_organization_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerecord',
            name='access_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='访问URL'),
        ),
        migrations.AlterField(
            model_name='filerecord',
            name='cdn_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='CDN URL'),
        ),
    ]
