# Generated by Django 4.2.7 on 2026-03-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmrequest',
            name='usage_estimated',
            field=models.BooleanField(default=False, verbose_name='用量是否为估算值'),
        ),
        migrations.AddField(
            model_name='llmusagefact',
            name='usage_estimated',
            field=models.BooleanField(default=False, verbose_name='用量是否为估算值'),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='custom_billing_config',
            field=models.JSONField(blank=True, default=dict, help_text='支持高级计费配置：cache_read_input_price_per_1k, cache_write_input_price_per_1k（缓存差异化计价）；tiered_pricing.tiers（阶梯计费，按输入 token 总量分档定价，每档含 max_input_tokens / input_price_per_1k / output_price_per_1k / cache_creation_price_per_1k / cache_hit_price_per_1k）；input_cost_per_image, output_cost_per_image, input_cost_per_audio_per_second, output_cost_per_video_per_second 等', verbose_name='自定义计费配置'),
        ),
    ]
