# Generated by Django 4.2.7 on 2026-03-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_add_usage_estimated_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmprovider',
            name='runtime_cooldown_multiplier',
            field=models.IntegerField(default=1, help_text='指数退避：half-open 再次失败时翻倍，成功时重置为 1', verbose_name='冷却期倍数'),
        ),
        migrations.AddField(
            model_name='llmprovider',
            name='runtime_cooldown_until',
            field=models.DateTimeField(blank=True, help_text='UNHEALTHY 后的冷却期截止，过后进入 half-open 允许试探', null=True, verbose_name='熔断冷却截止时间'),
        ),
    ]
