# Generated by Django 4.2.7 on 2026-03-19 02:11

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0004_workspace_to_workteam_rename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='llmusagebudgetpolicy',
            options={'ordering': ['workteam_id'], 'verbose_name': 'LLM用量预算策略', 'verbose_name_plural': 'LLM用量预算策略'},
        ),
        migrations.RemoveIndex(
            model_name='llmadminauditlog',
            name='services_ll_workspa_03d800_idx',
        ),
        migrations.RemoveIndex(
            model_name='llmprovider',
            name='ll_ws_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='llmprovider',
            name='ll_user_ws_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='llmusagebudgetpolicy',
            name='ll_usage_budget_ws_idx',
        ),
        migrations.RemoveIndex(
            model_name='llmusagefact',
            name='ll_usage_ws_time_idx',
        ),
        migrations.AlterUniqueTogether(
            name='llmprovider',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='llmadminauditlog',
            name='workteam_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='工作团队ID'),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='max_tokens',
            field=models.IntegerField(help_text='上下文总容量（context window）。历史字段 max_tokens，等价于 context_window_tokens。', validators=[django.core.validators.MinValueValidator(1)], verbose_name='上下文总容量(Token)'),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='llm.llmprovider', verbose_name='服务提供商'),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='scope',
            field=models.CharField(choices=[('global', '全局'), ('workspace', '工作团队'), ('user', '个人')], default='global', max_length=20, verbose_name='配置范围'),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='workteam_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='工作团队ID'),
        ),
        migrations.AlterField(
            model_name='llmproviderprobelog',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='probe_logs', to='llm.llmprovider', verbose_name='渠道'),
        ),
        migrations.AlterField(
            model_name='llmrequest',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='llm.llmmodel', verbose_name='使用模型'),
        ),
        migrations.AlterField(
            model_name='llmusagebudgetpolicy',
            name='workteam_id',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='工作团队ID'),
        ),
        migrations.AlterField(
            model_name='llmusagefact',
            name='input_cost',
            field=models.DecimalField(blank=True, decimal_places=6, default=Decimal('0'), max_digits=16, null=True, verbose_name='输入成本'),
        ),
        migrations.AlterField(
            model_name='llmusagefact',
            name='output_cost',
            field=models.DecimalField(blank=True, decimal_places=6, default=Decimal('0'), max_digits=16, null=True, verbose_name='输出成本'),
        ),
        migrations.AlterField(
            model_name='llmusagefact',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=6, default=Decimal('0'), max_digits=16, null=True, verbose_name='总成本'),
        ),
        migrations.AlterField(
            model_name='llmusagefact',
            name='workteam_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='工作团队ID'),
        ),
        migrations.AlterField(
            model_name='llmusagestatistics',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='llm.llmmodel', verbose_name='模型'),
        ),
        migrations.AlterField(
            model_name='llmusagestatistics',
            name='total_cost',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16, verbose_name='总成本'),
        ),
        migrations.AlterField(
            model_name='llmusagestatistics',
            name='total_input_cost',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16, verbose_name='总输入成本'),
        ),
        migrations.AlterField(
            model_name='llmusagestatistics',
            name='total_output_cost',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16, verbose_name='总输出成本'),
        ),
        migrations.AlterField(
            model_name='llmusagestatistics',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True, verbose_name='用户ID'),
        ),
        migrations.AddIndex(
            model_name='llmadminauditlog',
            index=models.Index(fields=['workteam_id', 'created_at'], name='services_ll_workspa_03d800_idx'),
        ),
        migrations.AddIndex(
            model_name='llmprovider',
            index=models.Index(fields=['workteam_id', 'is_active'], name='ll_ws_active_idx'),
        ),
        migrations.AddIndex(
            model_name='llmprovider',
            index=models.Index(fields=['user_id', 'workteam_id', 'is_active'], name='ll_user_ws_active_idx'),
        ),
        migrations.AddIndex(
            model_name='llmusagebudgetpolicy',
            index=models.Index(fields=['workteam_id', 'is_active'], name='ll_usage_budget_ws_idx'),
        ),
        migrations.AddIndex(
            model_name='llmusagefact',
            index=models.Index(fields=['workteam_id', 'occurred_at'], name='ll_usage_ws_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='llmprovider',
            constraint=models.UniqueConstraint(condition=models.Q(('user_id__isnull', True), ('workteam_id__isnull', True)), fields=('scope', 'provider_key'), name='uniq_provider_global'),
        ),
        migrations.AddConstraint(
            model_name='llmprovider',
            constraint=models.UniqueConstraint(condition=models.Q(('user_id__isnull', True), ('workteam_id__isnull', False)), fields=('scope', 'workteam_id', 'provider_key'), name='uniq_provider_workspace'),
        ),
        migrations.AddConstraint(
            model_name='llmprovider',
            constraint=models.UniqueConstraint(condition=models.Q(('user_id__isnull', False)), fields=('scope', 'workteam_id', 'user_id', 'provider_key'), name='uniq_provider_user'),
        ),
    ]
