# Generated by Django 4.2.7 on 2026-03-27 03:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0005_alter_llmusagebudgetpolicy_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmmodel',
            name='mode',
            field=models.CharField(choices=[('chat', '聊天模型'), ('embedding', '嵌入模型'), ('completion', '补全模型'), ('image_generation', '图像生成'), ('video_generation', '视频生成'), ('audio_transcription', '音频转录'), ('audio_speech', '语音合成'), ('audio_generation', '音频生成'), ('moderation', '内容审核'), ('other', '其他')], default='chat', help_text='模型的用途/模式（如 chat, embedding 等）', max_length=50, verbose_name='模型模式'),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='name',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('codex', 'OpenAI Codex'), ('qwen', '通义千问'), ('claude', 'Claude'), ('gemini', 'Gemini'), ('moonshot', 'Moonshot'), ('minimax', 'MiniMax'), ('minimax_bgm', 'MiniMax BGM'), ('zenmux', 'ZenMux'), ('local', '本地模型'), ('bytedance', '字节跳动'), ('dashscope', '阿里云百炼')], max_length=50, verbose_name='提供商名称'),
        ),
        migrations.CreateModel(
            name='LLMProviderKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='便于识别的名称，如"主 Key"、"备 Key-OpenRouter"', max_length=100, verbose_name='密钥标签')),
                ('api_key', models.CharField(max_length=500, verbose_name='API 密钥')),
                ('key_type', models.CharField(choices=[('api_key', 'API Key'), ('oauth', 'OAuth Token'), ('token', 'Bearer Token')], default='api_key', max_length=20, verbose_name='密钥类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('priority', models.IntegerField(default=0, help_text='数值越大优先级越高；相同优先级时按最久未用排序', verbose_name='优先级')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最近使用时间')),
                ('error_count', models.IntegerField(default=0, verbose_name='连续错误次数')),
                ('cooldown_until', models.DateTimeField(blank=True, help_text='rate_limit/timeout 等临时错误触发的短冷却', null=True, verbose_name='冷却截止时间')),
                ('disabled_until', models.DateTimeField(blank=True, help_text='billing/auth 等持久错误触发的长禁用', null=True, verbose_name='禁用截止时间')),
                ('disabled_reason', models.CharField(blank=True, default='', max_length=50, verbose_name='禁用原因')),
                ('last_error_reason', models.CharField(blank=True, default='', max_length=50, verbose_name='最近错误分类')),
                ('total_requests', models.BigIntegerField(default=0, verbose_name='总请求数')),
                ('total_tokens', models.BigIntegerField(default=0, verbose_name='总 Token 数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='llm.llmprovider', verbose_name='所属渠道')),
            ],
            options={
                'verbose_name': 'LLM 渠道密钥',
                'verbose_name_plural': 'LLM 渠道密钥',
                'db_table': 'services_llm_provider_key',
                'ordering': ['-priority', 'last_used_at', 'created_at'],
                'indexes': [models.Index(fields=['provider', 'is_active'], name='ll_pkey_provider_active_idx'), models.Index(fields=['cooldown_until'], name='ll_pkey_cooldown_idx'), models.Index(fields=['disabled_until'], name='ll_pkey_disabled_idx')],
            },
        ),
    ]
