# Generated by Django 4.2.7 on 2026-03-27 00:39
"""
scope 枚举值 'workspace' → 'workteam'：
- AlterField 更新 choices
- RunSQL 更新已有数据行
"""

from django.db import migrations, models


def _update_scope_if_column_exists(schema_editor, table_name, from_value, to_value):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        table_names = connection.introspection.table_names(cursor)
        if table_name not in table_names:
            return
        columns = {
            column.name if hasattr(column, "name") else column[0]
            for column in connection.introspection.get_table_description(cursor, table_name)
        }
        if "scope" not in columns:
            return
        quoted_table = schema_editor.quote_name(table_name)
        cursor.execute(
            f"UPDATE {quoted_table} SET scope = %s WHERE scope = %s",
            [to_value, from_value],
        )


def _forward_update_scope(apps, schema_editor):
    _update_scope_if_column_exists(
        schema_editor,
        "services_llm_provider",
        "workspace",
        "workteam",
    )
    # `services_llm_model` 在现有 schema 中从未声明过 `scope` 列；
    # 某些旧环境若残留该列，仍保持兼容迁移。
    _update_scope_if_column_exists(
        schema_editor,
        "services_llm_model",
        "workspace",
        "workteam",
    )


def _reverse_update_scope(apps, schema_editor):
    _update_scope_if_column_exists(
        schema_editor,
        "services_llm_provider",
        "workteam",
        "workspace",
    )
    _update_scope_if_column_exists(
        schema_editor,
        "services_llm_model",
        "workteam",
        "workspace",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0005_alter_llmusagebudgetpolicy_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmmodel',
            name='mode',
            field=models.CharField(choices=[('chat', '聊天模型'), ('embedding', '嵌入模型'), ('completion', '补全模型'), ('image_generation', '图像生成'), ('video_generation', '视频生成'), ('audio_transcription', '音频转录'), ('audio_speech', '语音合成'), ('audio_generation', '音频生成'), ('moderation', '内容审核'), ('other', '其他')], default='chat', help_text='模型的用途/模式（如 chat, embedding 等）', max_length=50, verbose_name='模型模式'),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='name',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('codex', 'OpenAI Codex'), ('qwen', '通义千问'), ('claude', 'Claude'), ('gemini', 'Gemini'), ('moonshot', 'Moonshot'), ('minimax', 'MiniMax'), ('minimax_bgm', 'MiniMax BGM'), ('zenmux', 'ZenMux'), ('local', '本地模型'), ('bytedance', '字节跳动'), ('dashscope', '阿里云百炼')], max_length=50, verbose_name='提供商名称'),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='scope',
            field=models.CharField(choices=[('global', '全局'), ('workteam', '工作团队'), ('user', '个人')], default='global', max_length=20, verbose_name='配置范围'),
        ),
        migrations.RunPython(
            _forward_update_scope,
            _reverse_update_scope,
        ),
    ]
