# Generated by Django 4.2.7 on 2026-03-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0006_add_provider_key_model'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='llmproviderkey',
            constraint=models.UniqueConstraint(fields=('provider', 'api_key'), name='uniq_provider_api_key'),
        ),
    ]
