# Generated by Django 4.2.7 on 2026-03-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0006_scope_workspace_to_workteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmprovider',
            name='name',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('codex', 'OpenAI Codex'), ('qwen', '通义千问'), ('claude', 'Claude'), ('gemini', 'Gemini'), ('moonshot', 'Moonshot'), ('minimax', 'MiniMax'), ('minimax_bgm', 'MiniMax BGM'), ('zenmux', 'ZenMux'), ('local', '本地模型'), ('bytedance', '字节跳动'), ('dashscope', '阿里云百炼'), ('fal', 'fal.ai'), ('replicate', 'Replicate')], max_length=50, verbose_name='提供商名称'),
        ),
    ]
