# Generated by Django 4.2.7 on 2026-03-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0007_add_provider_key_unique_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='llmproviderkey',
            name='uniq_provider_api_key',
        ),
        migrations.RemoveField(
            model_name='llmproviderkey',
            name='api_key',
        ),
        migrations.AddField(
            model_name='llmproviderkey',
            name='encrypted_api_key',
            field=models.TextField(blank=True, default='', help_text='Fernet 加密后的密文，通过 api_key property 透明读写', verbose_name='加密 API 密钥'),
        ),
        migrations.AddConstraint(
            model_name='llmproviderkey',
            constraint=models.UniqueConstraint(fields=('provider', 'label'), name='uniq_provider_key_label'),
        ),
    ]
