# Generated by Django 4.2.7 on 2026-03-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0007_add_fal_replicate_provider_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmrequest',
            name='workteam_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True, verbose_name='工作团队ID'),
        ),
        migrations.AddIndex(
            model_name='llmrequest',
            index=models.Index(fields=['workteam_id', 'created_at'], name='ll_req_wt_time_idx'),
        ),
    ]
