# Generated by Django 4.2.7

import logging

from django.db import migrations, models

logger = logging.getLogger(__name__)


def encrypt_provider_api_keys(apps, schema_editor):
    LLMProvider = apps.get_model('llm', 'LLMProvider')
    f = None
    try:
        from apps.tabtinspace.models import SecureCredential

        f = SecureCredential._get_fernet()
    except Exception as exc:
        logger.warning(
            "[llm migration 0009] Fernet 不可用，迁移将 api_key 原文写入 encrypted_api_key（请配置 CREDENTIAL_ENCRYPTION_KEY 后轮换密钥）: %s",
            exc,
        )

    for row in LLMProvider.objects.exclude(api_key='').iterator():
        plain = row.api_key
        if not plain:
            continue
        if f is not None:
            try:
                enc = f.encrypt(plain.encode()).decode()
            except Exception:
                enc = plain
        else:
            enc = plain
        row.encrypted_api_key = enc
        row.save(update_fields=['encrypted_api_key'])


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0008_encrypt_provider_key_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmprovider',
            name='encrypted_api_key',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Fernet 加密密文；通过 api_key 属性透明读写（与 LLMProviderKey 一致）',
                verbose_name='加密 API 密钥',
            ),
        ),
        migrations.RunPython(encrypt_provider_api_keys, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='llmprovider',
            name='api_key',
        ),
    ]
