# Generated by Django 4.2.7 on 2026-03-31 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0008_add_workteam_id_to_llmrequest'),
        ('llm', '0009_encrypt_llmprovider_api_key'),
    ]

    operations = [
    ]
