# Generated by Django 4.2.7 on 2026-04-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0019_llm_capability_drift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmmodel',
            name='wire_adapter_disabled',
            field=models.BooleanField(default=False, help_text='True 时该模型走兜底图片归一路径（仅 image_fetcher.normalize_image_urls，不走完整 wire_adapter 适配链）；用于 W2+ 单 model 灰度回滚。', verbose_name='WireAdapter 禁用'),
        ),
    ]
