# Generated by Django 4.2.7 on 2026-05-05 16:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0022_v01_schema_overhaul'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='llmadminauditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'LLM 管理员审计日志', 'verbose_name_plural': 'LLM 管理员审计日志'},
        ),
        migrations.AlterModelOptions(
            name='llmmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'LLM 模型', 'verbose_name_plural': 'LLM 模型'},
        ),
        migrations.AlterModelOptions(
            name='llmprovider',
            options={'ordering': ['-priority', '-created_at'], 'verbose_name': 'LLM 服务提供商', 'verbose_name_plural': 'LLM 服务提供商'},
        ),
        migrations.AlterModelOptions(
            name='llmscenebinding',
            options={'ordering': ['scene_key'], 'verbose_name': 'LLM 场景绑定', 'verbose_name_plural': 'LLM 场景绑定'},
        ),
        migrations.AlterModelOptions(
            name='llmusagefact',
            options={'ordering': ['-occurred_at'], 'verbose_name': 'LLM 用量事实', 'verbose_name_plural': 'LLM 用量事实'},
        ),
        migrations.RemoveConstraint(
            model_name='llmprovider',
            name='uniq_provider_workspace',
        ),
        migrations.RemoveConstraint(
            model_name='llmproviderkey',
            name='uniq_provider_key_label',
        ),
        migrations.RenameIndex(
            model_name='llmadminauditlog',
            new_name='services_ll_action_342374_idx',
            old_name='services_ll_action_420f28_idx',
        ),
        migrations.RenameIndex(
            model_name='llmadminauditlog',
            new_name='services_ll_target__921b38_idx',
            old_name='services_ll_target__4c9df5_idx',
        ),
        migrations.RenameIndex(
            model_name='llmadminauditlog',
            new_name='services_ll_worktea_e0bbd3_idx',
            old_name='services_ll_workspa_03d800_idx',
        ),
        migrations.RenameIndex(
            model_name='llmadminauditlog',
            new_name='services_ll_operato_1e3389_idx',
            old_name='services_ll_operato_a9af37_idx',
        ),
        migrations.RenameIndex(
            model_name='llmproviderkey',
            new_name='services_ll_cooldow_33d1c9_idx',
            old_name='ll_pkey_cooldown_idx',
        ),
        migrations.RenameIndex(
            model_name='llmproviderkey',
            new_name='services_ll_disable_57301e_idx',
            old_name='ll_pkey_disabled_idx',
        ),
        migrations.AlterField(
            model_name='llmadminauditlog',
            name='model_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True, verbose_name='模型 ID'),
        ),
        migrations.AlterField(
            model_name='llmadminauditlog',
            name='operator_id',
            field=models.CharField(db_index=True, max_length=36, verbose_name='操作人 ID'),
        ),
        migrations.AlterField(
            model_name='llmadminauditlog',
            name='provider_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True, verbose_name='渠道 ID'),
        ),
        migrations.AlterField(
            model_name='llmadminauditlog',
            name='target_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='目标 ID'),
        ),
        migrations.AlterField(
            model_name='llmadminauditlog',
            name='workteam_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='工作团队 ID'),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='billing_type',
            field=models.CharField(choices=[('token', 'Token'), ('request', 'Request'), ('time', 'Time'), ('custom', 'Custom')], default='token', max_length=20, verbose_name='计费类型'),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='capabilities_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='能力配置'),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='context_window_tokens',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='上下文窗口(Token)'),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='custom_billing_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='自定义计费配置'),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='input_price_per_1k',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='输入价格(每1K)'),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='max_input_tokens',
            field=models.IntegerField(blank=True, null=True, verbose_name='最大输入 Token 数'),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='max_output_tokens',
            field=models.IntegerField(blank=True, null=True, verbose_name='最大输出 Token 数'),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='output_price_per_1k',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='输出价格(每1K)'),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='price_per_request',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='每次请求价格'),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='price_per_second',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='每秒价格'),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='llm.llmprovider', verbose_name='服务提供商'),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='wave_status',
            field=models.CharField(choices=[('ready', 'Ready'), ('w2_pending', 'W2 Pending'), ('w3_pending', 'W3 Pending')], db_index=True, default='ready', max_length=16, verbose_name='Wave 状态'),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='base_url',
            field=models.URLField(verbose_name='API 基础 URL'),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='encrypted_api_key',
            field=models.TextField(blank=True, default='', verbose_name='加密 API 密钥'),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='health_check_interval_sec',
            field=models.IntegerField(default=60, verbose_name='健康检查间隔(秒)'),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='runtime_cooldown_multiplier',
            field=models.IntegerField(default=1, verbose_name='冷却期倍数'),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='runtime_cooldown_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='熔断冷却截止时间'),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='runtime_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('healthy', 'Healthy'), ('degraded', 'Degraded'), ('unhealthy', 'Unhealthy')], db_index=True, default='unknown', max_length=20, verbose_name='运行状态'),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='scope',
            field=models.CharField(choices=[('global', 'Global'), ('workteam', 'Workteam'), ('user', 'User')], db_index=True, default='global', max_length=20, verbose_name='配置范围'),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='workteam_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='工作团队 ID'),
        ),
        migrations.AlterField(
            model_name='llmproviderkey',
            name='cooldown_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='冷却截止时间'),
        ),
        migrations.AlterField(
            model_name='llmproviderkey',
            name='disabled_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='禁用截止时间'),
        ),
        migrations.AlterField(
            model_name='llmproviderkey',
            name='encrypted_api_key',
            field=models.TextField(blank=True, default='', verbose_name='加密 API 密钥'),
        ),
        migrations.AlterField(
            model_name='llmproviderkey',
            name='key_type',
            field=models.CharField(choices=[('api_key', 'API Key'), ('oauth', 'OAuth'), ('token', 'Token')], default='api_key', max_length=20, verbose_name='密钥类型'),
        ),
        migrations.AlterField(
            model_name='llmproviderkey',
            name='label',
            field=models.CharField(max_length=100, verbose_name='密钥标签'),
        ),
        migrations.AlterField(
            model_name='llmproviderkey',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='llmscenebinding',
            name='default_params',
            field=models.JSONField(blank=True, default=dict, verbose_name='默认参数'),
        ),
        migrations.AlterField(
            model_name='llmscenebinding',
            name='fallback_models',
            field=models.JSONField(blank=True, default=list, verbose_name='回退模型列表'),
        ),
        migrations.AlterField(
            model_name='llmscenebinding',
            name='scene_key',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='场景标识'),
        ),
        migrations.AlterField(
            model_name='llmusagefact',
            name='attempt_count',
            field=models.IntegerField(default=1, verbose_name='尝试次数'),
        ),
        migrations.AlterField(
            model_name='llmusagefact',
            name='cache_creation_input_tokens',
            field=models.BigIntegerField(default=0, verbose_name='缓存写入输入 Token'),
        ),
        migrations.AlterField(
            model_name='llmusagefact',
            name='cache_read_input_tokens',
            field=models.BigIntegerField(default=0, verbose_name='缓存命中输入 Token'),
        ),
        migrations.AlterField(
            model_name='llmusagefact',
            name='input_tokens',
            field=models.BigIntegerField(default=0, verbose_name='输入 Token'),
        ),
        migrations.AlterField(
            model_name='llmusagefact',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_facts', to='llm.llmmodel', verbose_name='模型'),
        ),
        migrations.AlterField(
            model_name='llmusagefact',
            name='output_tokens',
            field=models.BigIntegerField(default=0, verbose_name='输出 Token'),
        ),
        migrations.AlterField(
            model_name='llmusagefact',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_facts', to='llm.llmprovider', verbose_name='渠道'),
        ),
        migrations.AlterField(
            model_name='llmusagefact',
            name='request_id',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='请求 ID'),
        ),
        migrations.AlterField(
            model_name='llmusagefact',
            name='total_tokens',
            field=models.BigIntegerField(default=0, verbose_name='总 Token'),
        ),
        migrations.AlterField(
            model_name='llmusagefact',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True, verbose_name='用户 ID'),
        ),
        migrations.AlterField(
            model_name='llmusagefact',
            name='workteam_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='工作团队 ID'),
        ),
        migrations.AlterUniqueTogether(
            name='llmproviderkey',
            unique_together={('provider', 'label')},
        ),
        migrations.AddConstraint(
            model_name='llmprovider',
            constraint=models.UniqueConstraint(condition=models.Q(('user_id__isnull', True), ('workteam_id__isnull', False)), fields=('scope', 'workteam_id', 'provider_key'), name='uniq_provider_workteam'),
        ),
    ]
