# Generated by Django 4.2.7 on 2026-05-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0030_drop_provider_base_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmmodel",
            name="base_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="HTTP/WS 调用拼装时使用的端点。每个 Model 必须有自己的 base_url（v0.1.x 不再回退到 Provider.base_url——Provider.base_url 已删）。",
                verbose_name="端点 URL",
            ),
        ),
    ]
