# Generated by Django 4.2.7 on 2026-07-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0035_rename_workteam_to_organization'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='llmadminauditlog',
            new_name='services_ll_organiz_e2200e_idx',
            old_name='services_ll_worktea_e0bbd3_idx',
        ),
        migrations.AlterField(
            model_name='llmadminauditlog',
            name='organization_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='组织 ID'),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='organization_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='组织 ID'),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='scope',
            field=models.CharField(choices=[('global', 'Global'), ('organization', 'Organization'), ('user', 'User')], db_index=True, default='global', max_length=20, verbose_name='配置范围'),
        ),
        migrations.AlterField(
            model_name='llmusagefact',
            name='effective_provider_scope',
            field=models.CharField(choices=[('global', 'Global'), ('organization', 'Organization'), ('user', 'User')], db_index=True, max_length=20, verbose_name='实际渠道范围'),
        ),
        migrations.AlterField(
            model_name='llmusagefact',
            name='organization_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='组织 ID'),
        ),
    ]
