# Generated by Django 4.2.7 on 2026-08-03 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0051_add_kimi_k3_model'),
        ('llm', '0051_merge_seed_evolving_and_runtime_controls'),
    ]

    operations = [
    ]
