# Generated by Django 4.2.7 on 2026-08-06 05:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0056_kimi_k2x_binary_thinking_correction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelGatewayProjectionBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('database_alias', models.CharField(max_length=64)),
                ('package_key', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='必须是小写、连字符分隔的稳定标识', regex='^[a-z0-9]+(?:-[a-z0-9]+)*$')])),
                ('deployment_key', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='必须是小写、连字符分隔的稳定标识', regex='^[a-z0-9]+(?:-[a-z0-9]+)*$')])),
                ('binding_key', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='必须是小写、连字符分隔的稳定标识', regex='^[a-z0-9]+(?:-[a-z0-9]+)*$')])),
                ('existing_provider_uuid', models.UUIDField(blank=True, null=True)),
                ('provider_create_candidate_key', models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='必须是小写、连字符分隔的稳定标识', regex='^[a-z0-9]+(?:-[a-z0-9]+)*$')])),
                ('existing_model_uuid', models.UUIDField(blank=True, null=True)),
                ('model_create_candidate_key', models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='必须是小写、连字符分隔的稳定标识', regex='^[a-z0-9]+(?:-[a-z0-9]+)*$')])),
                ('lifecycle', models.CharField(choices=[('unbound', 'Unbound'), ('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], default='unbound', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'services_llm_gateway_projection_binding',
            },
        ),
        migrations.CreateModel(
            name='ModelGatewayProjectionRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('projection_revision', models.PositiveIntegerField()),
                ('projection_hash', models.CharField(max_length=71, validators=[django.core.validators.RegexValidator(message='必须是带 sha256: 前缀的 64 位小写十六进制哈希', regex='^sha256:[0-9a-f]{64}$')])),
                ('package_identity', models.JSONField()),
                ('deployment_ref', models.JSONField()),
                ('binding_ref', models.JSONField()),
                ('artifact_closure', models.JSONField(default=list)),
                ('generated_factual_fields', models.JSONField(default=list)),
                ('commercial_fields', models.JSONField(default=list)),
                ('preserved_operational_field_names', models.JSONField(default=list)),
                ('secret_field_classifications', models.JSONField(default=list)),
                ('unmanaged_fields', models.JSONField(default=list)),
                ('validation_summary', models.JSONField(default=dict)),
                ('behavior_blockers', models.JSONField(default=list)),
                ('readiness_blockers', models.JSONField(default=list)),
                ('projection_metadata', models.JSONField(default=dict)),
                ('prepared_at', models.DateTimeField()),
                ('prepared_by_actor_id', models.CharField(max_length=128)),
                ('review_ticket', models.CharField(blank=True, max_length=128, null=True)),
                ('source_environment', models.CharField(max_length=64)),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projection_revisions', to='llm.modelgatewayprojectionbinding')),
                ('previous_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='llm.modelgatewayprojectionrevision')),
            ],
            options={
                'db_table': 'services_llm_gateway_projection_revision',
            },
        ),
        migrations.CreateModel(
            name='ModelGatewayProjectionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('prepared', 'Prepared'), ('apply', 'Apply'), ('rollback', 'Rollback'), ('retire', 'Retire'), ('failed', 'Failed')], max_length=16)),
                ('result', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed'), ('rejected', 'Rejected')], max_length=16)),
                ('actor_id', models.CharField(max_length=128)),
                ('ticket_reference', models.CharField(blank=True, max_length=128, null=True)),
                ('safe_reason', models.CharField(max_length=512)),
                ('safe_error_code', models.CharField(blank=True, max_length=128, null=True)),
                ('safe_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projection_events', to='llm.modelgatewayprojectionbinding')),
                ('previous_projection_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='llm.modelgatewayprojectionrevision')),
                ('projection_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projection_events', to='llm.modelgatewayprojectionrevision')),
            ],
            options={
                'db_table': 'services_llm_gateway_projection_event',
            },
        ),
        migrations.AddField(
            model_name='modelgatewayprojectionbinding',
            name='current_projection_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='llm.modelgatewayprojectionrevision'),
        ),
        migrations.AddIndex(
            model_name='modelgatewayprojectionrevision',
            index=models.Index(fields=['binding', 'projection_revision'], name='llm_gw_rev_binding_rev'),
        ),
        migrations.AddIndex(
            model_name='modelgatewayprojectionrevision',
            index=models.Index(fields=['projection_hash'], name='llm_gw_rev_hash'),
        ),
        migrations.AddIndex(
            model_name='modelgatewayprojectionrevision',
            index=models.Index(fields=['prepared_at'], name='llm_gw_rev_prepared'),
        ),
        migrations.AddConstraint(
            model_name='modelgatewayprojectionrevision',
            constraint=models.UniqueConstraint(fields=('binding', 'projection_revision'), name='uniq_llm_gw_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='modelgatewayprojectionrevision',
            constraint=models.UniqueConstraint(fields=('binding', 'projection_hash'), name='uniq_llm_gw_revision_hash'),
        ),
        migrations.AddConstraint(
            model_name='modelgatewayprojectionrevision',
            constraint=models.CheckConstraint(check=models.Q(('projection_revision__gt', 0)), name='ck_llm_gw_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='modelgatewayprojectionrevision',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('prepared_by_actor_id', ''), _negated=True), models.Q(('source_environment', ''), _negated=True)), name='ck_llm_gw_revision_audit_nonempty'),
        ),
        migrations.AddIndex(
            model_name='modelgatewayprojectionevent',
            index=models.Index(fields=['binding', 'created_at'], name='llm_gw_evt_binding_time'),
        ),
        migrations.AddIndex(
            model_name='modelgatewayprojectionevent',
            index=models.Index(fields=['projection_revision', 'action'], name='llm_gw_evt_revision_action'),
        ),
        migrations.AddIndex(
            model_name='modelgatewayprojectionevent',
            index=models.Index(fields=['action', 'result'], name='llm_gw_evt_action_result'),
        ),
        migrations.AddConstraint(
            model_name='modelgatewayprojectionevent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('actor_id', ''), _negated=True), models.Q(('safe_reason', ''), _negated=True)), name='ck_llm_gw_event_audit_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='modelgatewayprojectionbinding',
            constraint=models.UniqueConstraint(fields=('database_alias', 'package_key', 'deployment_key', 'binding_key'), name='uniq_llm_gw_binding_identity'),
        ),
        migrations.AddConstraint(
            model_name='modelgatewayprojectionbinding',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('existing_provider_uuid__isnull', False), ('provider_create_candidate_key__isnull', True)), models.Q(('existing_provider_uuid__isnull', True), ('provider_create_candidate_key__isnull', False)), _connector='OR'), name='ck_llm_gw_provider_target_xor'),
        ),
        migrations.AddConstraint(
            model_name='modelgatewayprojectionbinding',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('existing_model_uuid__isnull', False), ('model_create_candidate_key__isnull', True)), models.Q(('existing_model_uuid__isnull', True), ('model_create_candidate_key__isnull', False)), _connector='OR'), name='ck_llm_gw_model_target_xor'),
        ),
        migrations.AddConstraint(
            model_name='modelgatewayprojectionbinding',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('database_alias', ''), _negated=True), models.Q(('package_key', ''), _negated=True), models.Q(('deployment_key', ''), _negated=True), models.Q(('binding_key', ''), _negated=True)), name='ck_llm_gw_binding_keys_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='modelgatewayprojectionbinding',
            constraint=models.CheckConstraint(check=models.Q(('provider_create_candidate_key__isnull', True), ('provider_create_candidate_key__regex', '^[a-z0-9]+(?:-[a-z0-9]+)*$'), _connector='OR'), name='ck_llm_gw_provider_candidate_key'),
        ),
        migrations.AddConstraint(
            model_name='modelgatewayprojectionbinding',
            constraint=models.CheckConstraint(check=models.Q(('model_create_candidate_key__isnull', True), ('model_create_candidate_key__regex', '^[a-z0-9]+(?:-[a-z0-9]+)*$'), _connector='OR'), name='ck_llm_gw_model_candidate_key'),
        ),
    ]
