# Generated by Django 4.2.7 on 2026-03-04 20:27

import apps.users.wallet.models
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.CharField(default=apps.users.wallet.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('credits', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='点券余额')),
                ('credits_precise', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='点券余额(精确)')),
                ('credits_frozen', models.BigIntegerField(default=0, help_text='预留字段，用于处理退款等场景', validators=[django.core.validators.MinValueValidator(0)], verbose_name='冻结点券')),
                ('credits_frozen_precise', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='预留字段，用于处理退款等场景', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='冻结点券(精确)')),
                ('llm_tokens_used_this_month', models.BigIntegerField(default=0, help_text='统计字段，每月1号重置', validators=[django.core.validators.MinValueValidator(0)], verbose_name='本月已用Token')),
                ('llm_tokens_reset_at', models.DateTimeField(default=apps.users.wallet.models.get_default_reset_time, help_text='下次重置时间', verbose_name='Token统计重置时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户钱包',
                'verbose_name_plural': '用户钱包',
                'db_table': 'users_wallet_user_wallet',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceWallet',
            fields=[
                ('id', models.CharField(default=apps.users.wallet.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('credits', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='点券余额')),
                ('credits_precise', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='点券余额(精确)')),
                ('credits_frozen', models.BigIntegerField(default=0, help_text='预留字段，用于处理退款等场景', validators=[django.core.validators.MinValueValidator(0)], verbose_name='冻结点券')),
                ('credits_frozen_precise', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='预留字段，用于处理退款等场景', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='冻结点券(精确)')),
                ('llm_tokens_used_this_month', models.BigIntegerField(default=0, help_text='统计字段，每月1号重置', validators=[django.core.validators.MinValueValidator(0)], verbose_name='本月已用Token')),
                ('llm_tokens_reset_at', models.DateTimeField(default=apps.users.wallet.models.get_default_reset_time, help_text='下次重置时间', verbose_name='Token统计重置时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('workspace_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='工作空间ID')),
            ],
            options={
                'verbose_name': '工作空间钱包',
                'verbose_name_plural': '工作空间钱包',
                'db_table': 'users_wallet_workspace_wallet',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditPackage',
            fields=[
                ('id', models.CharField(default=apps.users.wallet.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='套餐名称')),
                ('description', models.TextField(blank=True, verbose_name='套餐描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='价格（元）')),
                ('credits_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='基础点券数')),
                ('bonus_credits', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='赠送点券数')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '点券套餐',
                'verbose_name_plural': '点券套餐',
                'db_table': 'users_wallet_credit_package',
                'ordering': ['sort_order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='users_walle_is_acti_5ff134_idx')],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.CharField(default=apps.users.wallet.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('recharge', '充值'), ('consume', '消费'), ('grant', '赠送'), ('expire', '过期')], db_index=True, max_length=20, verbose_name='交易类型')),
                ('amount', models.BigIntegerField(verbose_name='点券数量')),
                ('amount_precise', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20, verbose_name='点券数量(精确)')),
                ('balance_before', models.BigIntegerField(verbose_name='变动前余额')),
                ('balance_before_precise', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20, verbose_name='变动前余额(精确)')),
                ('balance_after', models.BigIntegerField(verbose_name='变动后余额')),
                ('balance_after_precise', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20, verbose_name='变动后余额(精确)')),
                ('workspace_id', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='工作空间ID')),
                ('operator_user_id', models.CharField(blank=True, db_index=True, default='', help_text='记录执行操作的用户ID，用于审计', max_length=36, verbose_name='操作人用户ID')),
                ('related_order_id', models.CharField(blank=True, db_index=True, max_length=36, verbose_name='关联订单ID')),
                ('description', models.TextField(verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.userwallet', verbose_name='用户钱包')),
                ('workspace_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.workspacewallet', verbose_name='工作空间钱包')),
            ],
            options={
                'verbose_name': '钱包交易',
                'verbose_name_plural': '钱包交易',
                'db_table': 'users_wallet_transaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', 'created_at'], name='users_walle_wallet__71a572_idx'), models.Index(fields=['transaction_type', 'created_at'], name='users_walle_transac_6c321c_idx'), models.Index(fields=['related_order_id'], name='users_walle_related_1a5bf0_idx'), models.Index(fields=['workspace_id', 'created_at'], name='users_walle_workspa_f43632_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.CheckConstraint(check=models.Q(('wallet__isnull', True), ('workspace_wallet__isnull', True), _negated=True), name='tx_must_have_owner'),
        ),
        migrations.AddIndex(
            model_name='userwallet',
            index=models.Index(fields=['user'], name='users_walle_user_id_1e524c_idx'),
        ),
    ]
