# Generated by Django 4.2.7 on 2026-03-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('recharge', '充值'), ('consume', '消费'), ('grant', '赠送'), ('expire', '过期'), ('refund', '退款'), ('freeze', '冻结'), ('unfreeze', '解冻')], db_index=True, max_length=20, verbose_name='交易类型'),
        ),
    ]
