# Generated by Django 4.2.7 on 2026-03-07 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_wallettransaction_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwallet',
            name='llm_tokens_reset_at',
        ),
        migrations.RemoveField(
            model_name='userwallet',
            name='llm_tokens_used_this_month',
        ),
        migrations.RemoveField(
            model_name='workspacewallet',
            name='llm_tokens_reset_at',
        ),
        migrations.RemoveField(
            model_name='workspacewallet',
            name='llm_tokens_used_this_month',
        ),
    ]
