# Generated by Django 4.2.7 on 2026-03-17 05:31

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_remove_llm_token_stats_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='credits_frozen',
            field=models.BigIntegerField(default=0, help_text='预留字段（当前恒为 0，Service 层无冻结/解冻实现）。启用前须实现完整的 freeze_credits / unfreeze_credits 方法。', validators=[django.core.validators.MinValueValidator(0)], verbose_name='冻结点券'),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='credits_frozen_precise',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='预留字段（当前恒为 0，Service 层无冻结/解冻实现）。启用前须实现完整的 freeze_credits / unfreeze_credits 方法。', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='冻结点券(精确)'),
        ),
        migrations.AlterField(
            model_name='workspacewallet',
            name='credits_frozen',
            field=models.BigIntegerField(default=0, help_text='预留字段（当前恒为 0，Service 层无冻结/解冻实现）。启用前须实现完整的 freeze_credits / unfreeze_credits 方法。', validators=[django.core.validators.MinValueValidator(0)], verbose_name='冻结点券'),
        ),
        migrations.AlterField(
            model_name='workspacewallet',
            name='credits_frozen_precise',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='预留字段（当前恒为 0，Service 层无冻结/解冻实现）。启用前须实现完整的 freeze_credits / unfreeze_credits 方法。', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='冻结点券(精确)'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.CheckConstraint(check=models.Q(('wallet__isnull', True), ('workspace_wallet__isnull', True), _connector='OR'), name='tx_owner_mutually_exclusive'),
        ),
    ]
