# Generated by Django 4.2.7 on 2026-03-19 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_workspace_to_workteam_rename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workteamwallet',
            options={'ordering': ['-created_at'], 'verbose_name': '工作团队钱包', 'verbose_name_plural': '工作团队钱包'},
        ),
        migrations.RemoveConstraint(
            model_name='wallettransaction',
            name='tx_must_have_owner',
        ),
        migrations.RemoveConstraint(
            model_name='wallettransaction',
            name='tx_owner_mutually_exclusive',
        ),
        migrations.RemoveIndex(
            model_name='wallettransaction',
            name='users_walle_workspa_f43632_idx',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='workspace_wallet',
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='workteam_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.workteamwallet', verbose_name='工作团队钱包'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='workteam_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='工作团队ID'),
        ),
        migrations.AlterField(
            model_name='workteamwallet',
            name='workteam_id',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='工作团队ID'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['workteam_id', 'created_at'], name='users_walle_worktea_d43983_idx'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.CheckConstraint(check=models.Q(('wallet__isnull', True), ('workteam_wallet__isnull', True), _negated=True), name='tx_must_have_owner'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.CheckConstraint(check=models.Q(('wallet__isnull', True), ('workteam_wallet__isnull', True), _connector='OR'), name='tx_owner_mutually_exclusive'),
        ),
    ]
