# Generated by Django 4.2.7 on 2026-03-30 16:25

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_workteamwallet_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='reference_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='WAL-07: 用于冻结/解冻记录的幂等匹配。格式：freeze:{run_id}:{iteration}', max_length=255, verbose_name='引用键'),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='credits_frozen',
            field=models.BigIntegerField(default=0, help_text='当前冻结中的点券（整数近似值），由 sync_display_balances() 从精确值同步。', validators=[django.core.validators.MinValueValidator(0)], verbose_name='冻结点券'),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='credits_frozen_precise',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='当前冻结中的点券精确值，由 CreditsService 的 freeze/settle/release 方法维护。', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='冻结点券(精确)'),
        ),
        migrations.AlterField(
            model_name='workteamwallet',
            name='credits_frozen',
            field=models.BigIntegerField(default=0, help_text='当前冻结中的点券（整数近似值），由 sync_display_balances() 从精确值同步。', validators=[django.core.validators.MinValueValidator(0)], verbose_name='冻结点券'),
        ),
        migrations.AlterField(
            model_name='workteamwallet',
            name='credits_frozen_precise',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='当前冻结中的点券精确值，由 CreditsService 的 freeze/settle/release 方法维护。', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='冻结点券(精确)'),
        ),
    ]
