# Generated by Django 4.2.7 on 2026-04-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_repair_workspace_to_workteam_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='reference_key',
            field=models.CharField(blank=True, default='', help_text='WAL-07: 用于冻结/解冻记录的幂等匹配。格式：freeze:{run_id}:{iteration}', max_length=255, verbose_name='引用键'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['transaction_type', 'reference_key'], name='users_walle_transac_241ae9_idx'),
        ),
    ]
