# Generated by Django 4.2.7 on 2026-07-07 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0016_rename_workteam_to_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationwallet',
            options={'ordering': ['-created_at'], 'verbose_name': '组织钱包', 'verbose_name_plural': '组织钱包'},
        ),
        migrations.RenameIndex(
            model_name='wallettransaction',
            new_name='users_walle_organiz_0f5b88_idx',
            old_name='users_walle_worktea_d43983_idx',
        ),
        migrations.AlterField(
            model_name='organizationwallet',
            name='organization_id',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='organization_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='organization_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.organizationwallet', verbose_name='组织钱包'),
        ),
    ]
