/**
 * Step 3: 生成 Python（Pydantic v2 + Annotated[Union, Discriminator] + extra='ignore'）。
 *
 * 工具链：datamodel-code-generator → 后处理 .py 文件
 *
 * 后处理修复（W0 PoC §4 P0）：
 *   1. extra='forbid' → extra='ignore'（**产品决策点**，下方详述）
 *   2. Field(discriminator='X') → Discriminator('X') 新语法（嵌套 union 错误信息从 303 行降到 1 行）
 *   3. PurpleContent / TentacledContent / FluffyContent 等"颜色命名"重命名（W0-L4）
 *
 * ──────────────────────────────────────────────────────────────────────
 * 产品决策：Pydantic extra='ignore' 而非 'forbid'（W1 P2-B 说明）
 * ──────────────────────────────────────────────────────────────────────
 * Wave 1 派发 prompt 写的是 `extra=forbid`，本包后处理强制改为 `extra='ignore'`，
 * 是经过 trade-off 后的产品决策——不是漏改。
 *
 * 选 'ignore' 的理由：
 *   1. **Anthropic SSE 上游加字段是常态**：Anthropic 不定期在 message_delta /
 *      content_block 上加新字段（如 `cache_creation_input_tokens` /
 *      `cache_read_input_tokens` / `service_tier` / 各种 beta 头里的实验字段）。
 *      forbid 会让 daemon 在上游 minor 升级当天就崩溃，violation 总控 §0.7
 *      的"下游必须能容忍上游 minor 升级"红线。
 *   2. **forward-compat（v2 → v3 平滑升级）**：Wave 7 升级 protocol_version
 *      `v2 → v3` 时，先发的 daemon / 客户端必须能 parse 后发版本带新字段的
 *      payload。forbid 让这种"客户端先升 daemon 后升"或反过来的部署变得脆弱。
 *   3. **iOS / Android 历史 lag**：手机端发版周期 ≥ 7 天（审核），daemon 一
 *      周加新字段，老 iOS/Android 还在用 forbid 就会全员崩溃。
 *
 * 不选 'ignore' 的代价（明确知道在放弃什么）：
 *   - schema 错了（如下游应该写 `text` 但写成 `txt`）会被静默通过——但 Pydantic
 *     v2 的 **顶层 discriminator 仍然 fail-fast**：未知 `type='fictional_v3_block'`
 *     仍然会 raise ValidationError（实测见 round-trip Suite 4 "未知 type 字面量
 *     必须被拒绝"）。所以 ignore 只放过"已知 block 上的未知字段"，不会放过
 *     "未知 block type 字面量"。
 *   - 调试时漏字段不报错——靠 round-trip 测试 Suite 1 的"原始 fixture 字段保真"
 *     闸（见 wire-protocol.md §4.3 红线）拦回归。
 *
 * 文档相关章节：`docs/agent-runtime/wire-protocol.md` §"Pydantic extra 策略"
 *
 * 输出：generated/python/*.py
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { resolve } from 'node:path';
import { GENERATED_PYTHON_DIR, SCHEMAS_DIR, TOOLS } from './lib/paths.js';
import { postProcessPydantic } from './lib/post_pydantic.js';

if (!existsSync(TOOLS.datamodelCodegen)) {
  console.error(
    `✘ datamodel-codegen 不存在 (${TOOLS.datamodelCodegen})。请先：\n` +
      `   /opt/homebrew/bin/python3.11 -m venv packages/wire-codegen/.venv\n` +
      `   packages/wire-codegen/.venv/bin/pip install 'datamodel-code-generator[http]' 'pydantic>=2.0'`,
  );
  process.exit(1);
}

if (existsSync(GENERATED_PYTHON_DIR)) {
  rmSync(GENERATED_PYTHON_DIR, { recursive: true });
}
mkdirSync(GENERATED_PYTHON_DIR, { recursive: true });

const schemaFiles = readdirSync(SCHEMAS_DIR).filter((f) => f.endsWith('.json'));
console.log(`[03_gen_python] 准备生成 ${schemaFiles.length} 个 Pydantic 模型...`);

let okCount = 0;
let failCount = 0;

for (const schemaFile of schemaFiles) {
  const baseName = schemaFile.replace(/\.json$/, '');
  const inputPath = resolve(SCHEMAS_DIR, schemaFile);
  const outputPath = resolve(GENERATED_PYTHON_DIR, `${baseName}.py`);

  const result = spawnSync(
    TOOLS.datamodelCodegen,
    [
      '--input',
      inputPath,
      '--input-file-type',
      'jsonschema',
      '--output-model-type',
      'pydantic_v2.BaseModel',
      '--output',
      outputPath,
      '--use-annotated',
      '--use-union-operator',
      '--use-double-quotes',
      '--use-default',
      '--target-python-version',
      '3.10',
      // 关掉 timestamp header——否则同 schema 跑两次输出 hash 不同，08_check 永远 drift
      '--disable-timestamp',
    ],
    { encoding: 'utf-8', stdio: ['inherit', 'pipe', 'pipe'] },
  );

  if (result.status !== 0) {
    console.error(`  ✘ ${schemaFile}: ${result.stderr}`);
    failCount++;
    continue;
  }

  // 后处理
  const raw = readFileSync(outputPath, 'utf-8');
  const patched = postProcessPydantic(raw, baseName);
  writeFileSync(outputPath, patched);

  console.log(`  ✔ ${baseName}.py`);
  okCount++;
}

// 写一个 __init__.py 让 wire_generated 成为 package，方便 vendor in 后 import
const initPath = resolve(GENERATED_PYTHON_DIR, '__init__.py');
writeFileSync(
  initPath,
  `"""TabTin wire protocol generated types (Pydantic v2).

Generated by @tabtin/wire-codegen — DO NOT EDIT MANUALLY.

Source: packages/agent-wire/src/stream-content-block.ts
Run \`pnpm --filter @tabtin/wire-codegen codegen\` to regenerate.
"""
`,
);

console.log(`\n[03_gen_python] 完成：${okCount} ok, ${failCount} fail → ${GENERATED_PYTHON_DIR}`);
if (failCount > 0) process.exit(1);
