# Generated by Django 4.2.7 on 2026-03-04 20:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='tencent', max_length=50, verbose_name='服务提供商')),
                ('smtp_host', models.CharField(max_length=200, verbose_name='SMTP服务器')),
                ('smtp_port', models.PositiveIntegerField(default=465, verbose_name='SMTP端口')),
                ('use_ssl', models.BooleanField(default=True, verbose_name='使用SSL')),
                ('use_tls', models.BooleanField(default=False, verbose_name='使用TLS')),
                ('default_sender', models.EmailField(max_length=254, verbose_name='默认发件人')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '邮件服务配置',
                'verbose_name_plural': '邮件服务配置',
                'db_table': 'services_email_config',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_name', models.CharField(max_length=100, unique=True, verbose_name='模板名称')),
                ('template_subject', models.CharField(max_length=200, verbose_name='邮件主题模板')),
                ('template_content', models.TextField(verbose_name='邮件内容模板')),
                ('template_type', models.CharField(choices=[('verification', '验证码'), ('welcome', '欢迎邮件'), ('notification', '通知'), ('marketing', '营销'), ('system', '系统邮件'), ('other', '其他')], default='notification', max_length=20, verbose_name='模板类型')),
                ('content_type', models.CharField(choices=[('html', 'HTML'), ('plain', '纯文本')], default='html', max_length=10, verbose_name='内容类型')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('disabled', '禁用')], default='active', max_length=20, verbose_name='状态')),
                ('required_params', models.JSONField(default=list, help_text='模板中需要的参数列表', verbose_name='必需参数')),
                ('description', models.TextField(blank=True, verbose_name='模板描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '邮件模板',
                'verbose_name_plural': '邮件模板',
                'db_table': 'services_email_template',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['template_name'], name='services_em_templat_5fb471_idx'), models.Index(fields=['template_type'], name='services_em_templat_6bbcec_idx'), models.Index(fields=['status'], name='services_em_status_119899_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, verbose_name='统计日期')),
                ('provider', models.CharField(db_index=True, max_length=50, verbose_name='服务提供商')),
                ('template_name', models.CharField(db_index=True, max_length=100, verbose_name='模板名称')),
                ('total_sent', models.PositiveIntegerField(default=0, verbose_name='发送总数')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='成功数量')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='失败数量')),
                ('delivered_count', models.PositiveIntegerField(default=0, verbose_name='送达数量')),
                ('opened_count', models.PositiveIntegerField(default=0, verbose_name='打开数量')),
                ('clicked_count', models.PositiveIntegerField(default=0, verbose_name='点击数量')),
                ('bounced_count', models.PositiveIntegerField(default=0, verbose_name='退回数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '邮件统计',
                'verbose_name_plural': '邮件统计',
                'db_table': 'services_email_statistics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'provider'], name='services_em_date_856bfd_idx'), models.Index(fields=['date', 'template_name'], name='services_em_date_880f68_idx')],
                'unique_together': {('date', 'provider', 'template_name')},
            },
        ),
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(db_index=True, max_length=254, verbose_name='收件人邮箱')),
                ('sender_email', models.EmailField(max_length=254, verbose_name='发件人邮箱')),
                ('subject', models.CharField(max_length=500, verbose_name='邮件主题')),
                ('content', models.TextField(verbose_name='邮件内容')),
                ('content_type', models.CharField(choices=[('html', 'HTML'), ('plain', '纯文本')], default='html', max_length=10, verbose_name='内容类型')),
                ('template_name', models.CharField(blank=True, max_length=100, verbose_name='模板名称')),
                ('template_params', models.JSONField(default=dict, verbose_name='模板参数')),
                ('status', models.CharField(choices=[('pending', '发送中'), ('success', '发送成功'), ('failed', '发送失败'), ('bounced', '退回'), ('delivered', '已送达'), ('opened', '已打开'), ('clicked', '已点击')], db_index=True, default='pending', max_length=20, verbose_name='发送状态')),
                ('priority', models.CharField(choices=[('low', '低'), ('normal', '普通'), ('high', '高'), ('urgent', '紧急')], default='normal', max_length=10, verbose_name='优先级')),
                ('provider', models.CharField(default='tencent', max_length=50, verbose_name='服务提供商')),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='消息ID')),
                ('request_id', models.CharField(blank=True, max_length=200, verbose_name='请求ID')),
                ('response_data', models.JSONField(default=dict, verbose_name='响应数据')),
                ('error_code', models.CharField(blank=True, max_length=100, verbose_name='错误代码')),
                ('error_message', models.TextField(blank=True, verbose_name='错误消息')),
                ('has_attachments', models.BooleanField(default=False, verbose_name='是否有附件')),
                ('attachments_info', models.JSONField(default=list, verbose_name='附件信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='送达时间')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='打开时间')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='点击时间')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='重试次数')),
                ('open_count', models.PositiveIntegerField(default=0, verbose_name='打开次数')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='点击次数')),
            ],
            options={
                'verbose_name': '邮件发送记录',
                'verbose_name_plural': '邮件发送记录',
                'db_table': 'services_email_record',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_email', 'created_at'], name='services_em_recipie_320e57_idx'), models.Index(fields=['template_name', 'created_at'], name='services_em_templat_77f0d1_idx'), models.Index(fields=['status', 'created_at'], name='services_em_status_f3c9a1_idx'), models.Index(fields=['provider', 'created_at'], name='services_em_provide_588627_idx'), models.Index(fields=['priority', 'created_at'], name='services_em_priorit_de5394_idx')],
            },
        ),
    ]
