# Generated by Django 4.2.7 on 2026-06-05 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('email', '0002_emailrecord_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_records', to=settings.AUTH_USER_MODEL, verbose_name='发送用户'),
        ),
    ]
