# Generated by Django 4.2.7 on 2026-05-05 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='skill',
            new_name='skills_skil_owner_u_ae0170_idx',
            old_name='skills_skil_owner_u_3eba37_idx',
        ),
        migrations.RenameIndex(
            model_name='skill',
            new_name='skills_skil_worktea_e5b8c1_idx',
            old_name='skills_skil_worktea_5f6c0a_idx',
        ),
        migrations.RenameIndex(
            model_name='skill',
            new_name='skills_skil_visibil_4c3863_idx',
            old_name='skills_skil_visibil_60f527_idx',
        ),
        migrations.RenameIndex(
            model_name='skill',
            new_name='skills_skil_package_59cb6e_idx',
            old_name='skills_skil_package_a4f1e0_idx',
        ),
        migrations.RenameIndex(
            model_name='skillenablement',
            new_name='skills_enab_user_id_f0b806_idx',
            old_name='skills_enab_user_id_a31cc7_idx',
        ),
        migrations.RenameIndex(
            model_name='skillenablement',
            new_name='skills_enab_skill_i_82019f_idx',
            old_name='skills_enab_skill_i_f3f7f2_idx',
        ),
        migrations.RenameIndex(
            model_name='skillenablement',
            new_name='skills_enab_skill_c_2448d6_idx',
            old_name='skills_enab_skill_c_e8b1c5_idx',
        ),
        migrations.RenameIndex(
            model_name='skillpublishedversion',
            new_name='skills_publ_skill_i_880919_idx',
            old_name='skills_publ_skill_i_25db96_idx',
        ),
    ]
