# Generated by Django 4.2.7 on 2026-06-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0007_remove_skillpublishedversion_uq_published_skill_version_label_nonempty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="latest_version_seq",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="指向 SkillPublishedVersion.version_seq；尚未绑定已发布版本时为 NULL。",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="skillenablement",
            name="installed_version_seq",
            field=models.PositiveIntegerField(
                blank=True,
                help_text=(
                    "当前本地装的版本（D3 启用时拉最新）；NULL 表示本地可编辑 Skill 尚未"
                    "绑定已发布版本。platform / app / device 来源 = NULL（跟代码走，"
                    "无云端版本）。"
                ),
                null=True,
            ),
        ),
    ]
