# Generated by Django 4.2.7 on 2026-07-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0010_rename_workteam_to_organization'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='skill',
            new_name='skills_skil_organiz_5dd095_idx',
            old_name='skills_skil_worktea_e5b8c1_idx',
        ),
        migrations.AlterField(
            model_name='skill',
            name='organization_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='visibility=organization 时归属 organization（跨库软引用）。', null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('organization', 'Organization'), ('public', 'Public')], default='private', help_text='Skill 级可见范围（D5）。仅控制谁能新启用，不影响已启用者。', max_length=16),
        ),
        migrations.AlterField(
            model_name='skillpublishedversion',
            name='review_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='not_required', help_text='审核状态（D13）。private / organization = not_required；public 必审。', max_length=16),
        ),
    ]
