# Generated by Django 4.2.7 on 2026-07-06 14:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_restore_agent_indexes'),
        ('skills', '0011_rename_skills_skil_worktea_e5b8c1_idx_skills_skil_organiz_5dd095_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSkillLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_canonical_key', models.CharField(db_index=True, help_text='Canonical key（用于 LocalSkillRegistry 检索）。格式：user:<slug> / platform:<id> / app:<app_id>/<id> / device:<id>。', max_length=160)),
                ('source', models.CharField(help_text='冗余 source 标记（platform/app/device/user），语义同 SkillEnablement.source。', max_length=16)),
                ('skill_id', models.UUIDField(blank=True, db_index=True, help_text='user 来源时指向 Skill 表行；platform/app/device 来源为 NULL（同 SkillEnablement 约定）。', null=True)),
                ('enabled', models.BooleanField(default=True, help_text='是否注入（行存在=已携带）。停用置 False 保留行；摘除才删行。')),
                ('config_json', models.JSONField(blank=True, default=dict, help_text='Agent 对该 Skill 的私有配置，语义同 SkillEnablement.config_json。')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(db_column='agent_id', help_text='携带该 skill 的 Agent（携带集跟 agent 走）。', on_delete=django.db.models.deletion.CASCADE, related_name='skill_links', to='agent.agent')),
            ],
            options={
                'verbose_name': 'Agent Skill Link',
                'verbose_name_plural': 'Agent Skill Links',
                'db_table': 'skills_agent_link',
                'indexes': [models.Index(fields=['agent', 'enabled'], name='skills_agen_agent_i_ac487f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='agentskilllink',
            constraint=models.UniqueConstraint(fields=('agent', 'skill_canonical_key'), name='uq_agent_skill_link'),
        ),
    ]
