# Generated by Django 4.2.7 on 2026-07-12 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0012_skill_import_source_url'),
        ('skills', '0014_3266_enablement_device_anchor'),
    ]

    operations = [
    ]
