# Generated by Django 4.2.7 on 2026-07-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0018_drop_enablement_legacy_columns'),
        ('skills', '0018_user_skill_preference_default_on'),
    ]

    operations = [
    ]
