# Generated by Django 4.2.7 on 2026-03-04 20:27

from django.db import migrations, models
import pgvector.django
from pgvector.django import VectorExtension
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # 在创建 VectorField 列之前确保 pgvector extension 已装到当前 DB。
        # `CREATE EXTENSION IF NOT EXISTS vector;` 在已存在时幂等无副作用。
        # 仅在 PostgreSQL 上生效；Django MySQL backend 会忽略此 operation。
        # （生产 PG 上 extension 已就绪，Layer B CI 上需新建——配合 pgvector/pgvector
        # service container image 让 extension package 可用。）
        VectorExtension(),
        migrations.CreateModel(
            name='ToolEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_id', models.UUIDField(db_index=True, verbose_name='工具 ID')),
                ('tool_name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='工具名')),
                ('content_hash', models.CharField(help_text='当工具描述变化时触发重新 embedding', max_length=64, verbose_name='内容哈希')),
                ('embedding', pgvector.django.VectorField(dimensions=1536, verbose_name='向量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '工具向量',
                'verbose_name_plural': '工具向量',
                'db_table': 'capabilities_tool_embedding',
            },
        ),
        migrations.CreateModel(
            name='ToolSkillLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(db_index=True, max_length=128, verbose_name='工具名')),
                ('skill_key', models.CharField(db_index=True, max_length=128, verbose_name='Skill 标识')),
                ('relation_type', models.CharField(choices=[('required', '必需'), ('optional', '可选'), ('activates', '动态激活'), ('references', '引用')], default='references', max_length=32, verbose_name='关联类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '工具-Skill 关联',
                'verbose_name_plural': '工具-Skill 关联',
                'db_table': 'capabilities_tool_skill_link',
                'indexes': [models.Index(fields=['tool_name'], name='capabilitie_tool_na_e73f93_idx'), models.Index(fields=['skill_key'], name='capabilitie_skill_k_be1854_idx')],
                'unique_together': {('tool_name', 'skill_key')},
            },
        ),
        migrations.CreateModel(
            name='RegisteredTool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='如 sql_query、crawl_clean_html、execute_in_terminal', max_length=128, unique=True, verbose_name='工具唯一名')),
                ('display_name', models.CharField(max_length=128, verbose_name='显示名')),
                ('description', models.TextField(help_text='也用于生成 embedding', verbose_name='描述')),
                ('category', models.CharField(choices=[('app', 'App 业务工具'), ('runtime', '运行时工具'), ('service', '服务工具'), ('extension', 'Extension 工具'), ('platform', '平台工具'), ('custom', '自定义工具')], db_index=True, max_length=64, verbose_name='分类')),
                ('provider_id', models.CharField(db_index=True, help_text='如 tabdata, terminal, llm 等', max_length=64, verbose_name='提供者 ID')),
                ('domain', models.CharField(db_index=True, max_length=64, verbose_name='ToolHub domain')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('interface_type', models.CharField(choices=[('function_call', 'Function Call'), ('cli', 'CLI Command'), ('api', 'HTTP API'), ('hybrid', 'Hybrid')], default='function_call', max_length=32, verbose_name='接口形态')),
                ('execution_target', models.CharField(choices=[('frontend', '前端执行'), ('backend', '后端执行'), ('hybrid', '混合执行')], default='backend', max_length=32, verbose_name='执行位置')),
                ('parameters_schema', models.JSONField(blank=True, default=dict, verbose_name='入参 JSON Schema')),
                ('return_schema', models.JSONField(blank=True, default=dict, verbose_name='返回值 Schema')),
                ('risk_level', models.CharField(choices=[('safe', '安全'), ('review', '需审核'), ('strict', '严格限制')], default='safe', max_length=16, verbose_name='风险等级')),
                ('permissions', models.JSONField(blank=True, default=list, verbose_name='所需权限')),
                ('optional', models.BooleanField(default=False, verbose_name='是否可选工具')),
                ('source', models.CharField(choices=[('builtin', '内置（代码定义）'), ('manifest', 'Manifest（action-tools）'), ('extension', 'Extension 提供'), ('custom', '自定义（API 创建）')], db_index=True, max_length=32, verbose_name='来源')),
                ('source_ref', models.CharField(blank=True, default='', help_text='来源路径或 ID，如 multiagent/tools/table', max_length=256, verbose_name='来源引用')),
                ('version', models.CharField(default='0.0.0', max_length=32, verbose_name='版本')),
                ('documentation', models.TextField(blank=True, default='', verbose_name='详细文档')),
                ('examples', models.JSONField(blank=True, default=list, verbose_name='调用示例')),
                ('status', models.CharField(choices=[('active', '启用'), ('deprecated', '已弃用'), ('disabled', '已禁用')], db_index=True, default='active', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '注册工具',
                'verbose_name_plural': '注册工具',
                'db_table': 'capabilities_registered_tool',
                'ordering': ['category', 'provider_id', 'name'],
                'indexes': [models.Index(fields=['category', 'provider_id'], name='capabilitie_categor_71c2a9_idx'), models.Index(fields=['domain'], name='capabilitie_domain_aa8753_idx'), models.Index(fields=['source'], name='capabilitie_source_6de49b_idx')],
            },
        ),
    ]
