# Generated by Django 4.2.7 on 2026-03-18 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capabilities', '0002_add_hnsw_index'),
        ('capabilities', '0002_alter_toolembedding_dimensions_1024'),
    ]

    operations = [
    ]
