# Generated by Django 4.2.7 on 2026-04-01 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capabilities', '0003_merge_20260318_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredtool',
            name='source_ref',
            field=models.CharField(blank=True, default='', help_text='来源路径或 ID，如 orchestration/tools/table', max_length=256, verbose_name='来源引用'),
        ),
    ]
