// ════════════════════════════════════════════════════════════════════
// 自动生成 — DO NOT EDIT MANUALLY
// Generated by @tabtin/wire-codegen (Wave 1 协议层)
// Source: packages/agent-wire/src/stream-content-block.ts (zod SSoT)
// 重新生成: pnpm --filter @tabtin/wire-codegen codegen
// 文档: docs/agent-runtime/wire-protocol.md
// ════════════════════════════════════════════════════════════════════

import Foundation

public struct AskInteractionRequestAskUserPayloadQuestionsItemOptionsItem: Codable, Hashable, Sendable {
    public let id: String
    public let label: String
    public let description: String
    public let preview: String?

    public init(id: String, label: String, description: String, preview: String? = nil) {
        self.id = id
        self.label = label
        self.description = description
        self.preview = preview
    }

}

public struct AskInteractionRequestAskUserPayloadQuestionsItemOtherOption: Codable, Hashable, Sendable {
    public let id: String?
    public let label: String
    public let description: String
    public let preview: String?

    public init(id: String? = nil, label: String, description: String, preview: String? = nil) {
        self.id = id
        self.label = label
        self.description = description
        self.preview = preview
    }

}

public struct AskInteractionRequestAskUserPayloadQuestionsItem: Codable, Hashable, Sendable {
    public let id: String
    public let prompt: String
    public let header: String
    public let options: [AskInteractionRequestAskUserPayloadQuestionsItemOptionsItem]
    public let otherOption: AskInteractionRequestAskUserPayloadQuestionsItemOtherOption?
    public let allowMultiple: Bool?
    public let allowFreeText: Bool?

    public init(id: String, prompt: String, header: String, options: [AskInteractionRequestAskUserPayloadQuestionsItemOptionsItem], otherOption: AskInteractionRequestAskUserPayloadQuestionsItemOtherOption? = nil, allowMultiple: Bool? = nil, allowFreeText: Bool? = nil) {
        self.id = id
        self.prompt = prompt
        self.header = header
        self.options = options
        self.otherOption = otherOption
        self.allowMultiple = allowMultiple
        self.allowFreeText = allowFreeText
    }

    public enum CodingKeys: String, CodingKey {
        case id
        case prompt
        case header
        case options
        case otherOption = "other_option"
        case allowMultiple = "allow_multiple"
        case allowFreeText = "allow_free_text"
    }
}

public struct AskInteractionRequestAskUserPayload: Codable, Hashable, Sendable {
    public let requestId: String
    public let toolName: String
    public let title: String?
    public let questions: [AskInteractionRequestAskUserPayloadQuestionsItem]
    public let schemaVersion: Int?
    public let interactionType: String
    public let blockingPolicy: String
    public let intent: String
    public let formMode: String
    public let message: String?
    public let messageId: String?
    public let toolCallId: String?
    public let interruptId: String?
    public let traceId: String?
    public let presetId: String?

    public init(requestId: String, toolName: String, title: String? = nil, questions: [AskInteractionRequestAskUserPayloadQuestionsItem], schemaVersion: Int? = nil, interactionType: String, blockingPolicy: String, intent: String, formMode: String, message: String? = nil, messageId: String? = nil, toolCallId: String? = nil, interruptId: String? = nil, traceId: String? = nil, presetId: String? = nil) {
        self.requestId = requestId
        self.toolName = toolName
        self.title = title
        self.questions = questions
        self.schemaVersion = schemaVersion
        self.interactionType = interactionType
        self.blockingPolicy = blockingPolicy
        self.intent = intent
        self.formMode = formMode
        self.message = message
        self.messageId = messageId
        self.toolCallId = toolCallId
        self.interruptId = interruptId
        self.traceId = traceId
        self.presetId = presetId
    }

    public enum CodingKeys: String, CodingKey {
        case requestId = "request_id"
        case toolName = "tool_name"
        case title
        case questions
        case schemaVersion = "schema_version"
        case interactionType = "interaction_type"
        case blockingPolicy = "blocking_policy"
        case intent
        case formMode = "form_mode"
        case message
        case messageId = "message_id"
        case toolCallId = "tool_call_id"
        case interruptId = "interrupt_id"
        case traceId = "trace_id"
        case presetId = "preset_id"
    }
}

public struct AskInteractionRequestAskFormPayloadFieldsItem: Codable, Hashable, Sendable {
    public let key: String
    public let label: String
    public let type: String?
    public let description: String?
    public let placeholder: String?

    public init(key: String, label: String, type: String? = nil, description: String? = nil, placeholder: String? = nil) {
        self.key = key
        self.label = label
        self.type = type
        self.description = description
        self.placeholder = placeholder
    }

}

public struct AskInteractionRequestAskFormPayload: Codable, Hashable, Sendable {
    public let requestId: String
    public let toolName: String
    public let title: String
    public let fields: [AskInteractionRequestAskFormPayloadFieldsItem]
    public let addons: [JSONValue]?
    public let submitLabel: String?
    public let schemaVersion: Int?
    public let interactionType: String
    public let blockingPolicy: String
    public let intent: String
    public let formMode: String
    public let message: String?
    public let messageId: String?
    public let toolCallId: String?
    public let interruptId: String?
    public let traceId: String?
    public let presetId: String?

    public init(requestId: String, toolName: String, title: String, fields: [AskInteractionRequestAskFormPayloadFieldsItem], addons: [JSONValue]? = nil, submitLabel: String? = nil, schemaVersion: Int? = nil, interactionType: String, blockingPolicy: String, intent: String, formMode: String, message: String? = nil, messageId: String? = nil, toolCallId: String? = nil, interruptId: String? = nil, traceId: String? = nil, presetId: String? = nil) {
        self.requestId = requestId
        self.toolName = toolName
        self.title = title
        self.fields = fields
        self.addons = addons
        self.submitLabel = submitLabel
        self.schemaVersion = schemaVersion
        self.interactionType = interactionType
        self.blockingPolicy = blockingPolicy
        self.intent = intent
        self.formMode = formMode
        self.message = message
        self.messageId = messageId
        self.toolCallId = toolCallId
        self.interruptId = interruptId
        self.traceId = traceId
        self.presetId = presetId
    }

    public enum CodingKeys: String, CodingKey {
        case requestId = "request_id"
        case toolName = "tool_name"
        case title
        case fields
        case addons
        case submitLabel = "submit_label"
        case schemaVersion = "schema_version"
        case interactionType = "interaction_type"
        case blockingPolicy = "blocking_policy"
        case intent
        case formMode = "form_mode"
        case message
        case messageId = "message_id"
        case toolCallId = "tool_call_id"
        case interruptId = "interrupt_id"
        case traceId = "trace_id"
        case presetId = "preset_id"
    }
}

public enum AskInteractionRequestRequestApprovalPayloadRiskLevel: String, Codable, Hashable, Sendable {
    case safe = "safe"
    case review = "review"
    case high = "high"
}

public struct AskInteractionRequestRequestApprovalPayload: Codable, Hashable, Sendable {
    public let requestId: String
    public let toolName: String
    public let title: String
    public let rationale: String
    public let riskLevel: AskInteractionRequestRequestApprovalPayloadRiskLevel
    public let details: JSONValue?
    public let submitLabel: String?
    public let declineLabel: String?
    public let schemaVersion: Int?
    public let interactionType: String
    public let blockingPolicy: String
    public let intent: String
    public let formMode: String
    public let message: String?
    public let messageId: String?
    public let toolCallId: String?
    public let interruptId: String?
    public let traceId: String?
    public let presetId: String?

    public init(requestId: String, toolName: String, title: String, rationale: String, riskLevel: AskInteractionRequestRequestApprovalPayloadRiskLevel, details: JSONValue? = nil, submitLabel: String? = nil, declineLabel: String? = nil, schemaVersion: Int? = nil, interactionType: String, blockingPolicy: String, intent: String, formMode: String, message: String? = nil, messageId: String? = nil, toolCallId: String? = nil, interruptId: String? = nil, traceId: String? = nil, presetId: String? = nil) {
        self.requestId = requestId
        self.toolName = toolName
        self.title = title
        self.rationale = rationale
        self.riskLevel = riskLevel
        self.details = details
        self.submitLabel = submitLabel
        self.declineLabel = declineLabel
        self.schemaVersion = schemaVersion
        self.interactionType = interactionType
        self.blockingPolicy = blockingPolicy
        self.intent = intent
        self.formMode = formMode
        self.message = message
        self.messageId = messageId
        self.toolCallId = toolCallId
        self.interruptId = interruptId
        self.traceId = traceId
        self.presetId = presetId
    }

    public enum CodingKeys: String, CodingKey {
        case requestId = "request_id"
        case toolName = "tool_name"
        case title
        case rationale
        case riskLevel = "risk_level"
        case details
        case submitLabel = "submit_label"
        case declineLabel = "decline_label"
        case schemaVersion = "schema_version"
        case interactionType = "interaction_type"
        case blockingPolicy = "blocking_policy"
        case intent
        case formMode = "form_mode"
        case message
        case messageId = "message_id"
        case toolCallId = "tool_call_id"
        case interruptId = "interrupt_id"
        case traceId = "trace_id"
        case presetId = "preset_id"
    }
}

public enum AskInteractionRequest: Codable, Hashable, Sendable {
    case askUser(AskInteractionRequestAskUserPayload)
    case askForm(AskInteractionRequestAskFormPayload)
    case requestApproval(AskInteractionRequestRequestApprovalPayload)

    public var toolName: String {
        switch self {
        case .askUser: return "ask_user"
        case .askForm: return "ask_form"
        case .requestApproval: return "request_approval"
        }
    }

    private struct _DiscriminatorPeek: Codable {
        let toolName: String
        enum CodingKeys: String, CodingKey {
            case toolName = "tool_name"
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let peek = try container.decode(_DiscriminatorPeek.self)
        switch peek.toolName {
        case "ask_user":
            self = .askUser(try container.decode(AskInteractionRequestAskUserPayload.self))
        case "ask_form":
            self = .askForm(try container.decode(AskInteractionRequestAskFormPayload.self))
        case "request_approval":
            self = .requestApproval(try container.decode(AskInteractionRequestRequestApprovalPayload.self))
        default:
            throw DecodingError.dataCorruptedError(in: container, debugDescription: "Unknown tool_name '\(peek.toolName)' for AskInteractionRequest")
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .askUser(let payload):
            try container.encode(payload)
        case .askForm(let payload):
            try container.encode(payload)
        case .requestApproval(let payload):
            try container.encode(payload)
        }
    }
}
