// ════════════════════════════════════════════════════════════════════
// 自动生成 — DO NOT EDIT MANUALLY
// Generated by @tabtin/wire-codegen (Wave 1 协议层)
// Source: packages/agent-wire/src/stream-content-block.ts (zod SSoT)
// 重新生成: pnpm --filter @tabtin/wire-codegen codegen
// 文档: docs/agent-runtime/wire-protocol.md
// ════════════════════════════════════════════════════════════════════

import Foundation

public struct StreamSystemNotice: Codable, Hashable, Sendable {
    public let content: String
    public let noticeType: String?
    public let severity: String?
    public let source: String?
    public let backendType: String?
    public let taskId: String?

    public init(content: String, noticeType: String? = nil, severity: String? = nil, source: String? = nil, backendType: String? = nil, taskId: String? = nil) {
        self.content = content
        self.noticeType = noticeType
        self.severity = severity
        self.source = source
        self.backendType = backendType
        self.taskId = taskId
    }

    public enum CodingKeys: String, CodingKey {
        case content
        case noticeType = "notice_type"
        case severity
        case source
        case backendType = "backend_type"
        case taskId = "task_id"
    }
}
