// ════════════════════════════════════════════════════════════════════
// 自动生成 — DO NOT EDIT MANUALLY
// Generated by @tabtin/wire-codegen (Wave 1 协议层)
// Source: packages/agent-wire/src/stream-content-block.ts (zod SSoT)
// 重新生成: pnpm --filter @tabtin/wire-codegen codegen
// 文档: docs/agent-runtime/wire-protocol.md
// ════════════════════════════════════════════════════════════════════

import Foundation

public enum AnyOf_20RefKind: String, Codable, Hashable, Sendable {
    case web = "web"
    case doc = "doc"
    case table = "table"
    case code = "code"
    case memo = "memo"
}

public struct AnyOf_20SnapshotWebPayload: Codable, Hashable, Sendable {
    public let kind: String
    public let url: String
    public let title: String?
    public let preview: String?
    public let selectedText: String?

    public init(kind: String, url: String, title: String? = nil, preview: String? = nil, selectedText: String? = nil) {
        self.kind = kind
        self.url = url
        self.title = title
        self.preview = preview
        self.selectedText = selectedText
    }

    public enum CodingKeys: String, CodingKey {
        case kind
        case url
        case title
        case preview
        case selectedText = "selected_text"
    }
}

public struct AnyOf_20SnapshotDocPayload: Codable, Hashable, Sendable {
    public let kind: String
    public let docId: String
    public let page: Int?
    public let bbox: [Double]?
    public let preview: String?

    public init(kind: String, docId: String, page: Int? = nil, bbox: [Double]? = nil, preview: String? = nil) {
        self.kind = kind
        self.docId = docId
        self.page = page
        self.bbox = bbox
        self.preview = preview
    }

    public enum CodingKeys: String, CodingKey {
        case kind
        case docId = "doc_id"
        case page
        case bbox
        case preview
    }
}

public struct AnyOf_20SnapshotTablePayload: Codable, Hashable, Sendable {
    public let kind: String
    public let tableId: String
    public let rowIds: [String]?
    public let fieldIds: [String]?
    public let csvPreview: String?

    public init(kind: String, tableId: String, rowIds: [String]? = nil, fieldIds: [String]? = nil, csvPreview: String? = nil) {
        self.kind = kind
        self.tableId = tableId
        self.rowIds = rowIds
        self.fieldIds = fieldIds
        self.csvPreview = csvPreview
    }

    public enum CodingKeys: String, CodingKey {
        case kind
        case tableId = "table_id"
        case rowIds = "row_ids"
        case fieldIds = "field_ids"
        case csvPreview = "csv_preview"
    }
}

public struct AnyOf_20SnapshotCodePayload: Codable, Hashable, Sendable {
    public let kind: String
    public let filePath: String
    public let startLine: Int
    public let endLine: Int
    public let codeExcerpt: String
    public let lang: String?

    public init(kind: String, filePath: String, startLine: Int, endLine: Int, codeExcerpt: String, lang: String? = nil) {
        self.kind = kind
        self.filePath = filePath
        self.startLine = startLine
        self.endLine = endLine
        self.codeExcerpt = codeExcerpt
        self.lang = lang
    }

    public enum CodingKeys: String, CodingKey {
        case kind
        case filePath = "file_path"
        case startLine = "start_line"
        case endLine = "end_line"
        case codeExcerpt = "code_excerpt"
        case lang
    }
}

public struct AnyOf_20SnapshotMemoPayload: Codable, Hashable, Sendable {
    public let kind: String
    public let memoId: String
    public let preview: String?

    public init(kind: String, memoId: String, preview: String? = nil) {
        self.kind = kind
        self.memoId = memoId
        self.preview = preview
    }

    public enum CodingKeys: String, CodingKey {
        case kind
        case memoId = "memo_id"
        case preview
    }
}

public enum AnyOf_20Snapshot: Codable, Hashable, Sendable {
    case web(AnyOf_20SnapshotWebPayload)
    case doc(AnyOf_20SnapshotDocPayload)
    case table(AnyOf_20SnapshotTablePayload)
    case code(AnyOf_20SnapshotCodePayload)
    case memo(AnyOf_20SnapshotMemoPayload)

    public var kind: String {
        switch self {
        case .web: return "web"
        case .doc: return "doc"
        case .table: return "table"
        case .code: return "code"
        case .memo: return "memo"
        }
    }

    private struct _DiscriminatorPeek: Codable {
        let kind: String
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let peek = try container.decode(_DiscriminatorPeek.self)
        switch peek.kind {
        case "web":
            self = .web(try container.decode(AnyOf_20SnapshotWebPayload.self))
        case "doc":
            self = .doc(try container.decode(AnyOf_20SnapshotDocPayload.self))
        case "table":
            self = .table(try container.decode(AnyOf_20SnapshotTablePayload.self))
        case "code":
            self = .code(try container.decode(AnyOf_20SnapshotCodePayload.self))
        case "memo":
            self = .memo(try container.decode(AnyOf_20SnapshotMemoPayload.self))
        default:
            throw DecodingError.dataCorruptedError(in: container, debugDescription: "Unknown kind '\(peek.kind)' for AnyOf_20Snapshot")
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .web(let payload):
            try container.encode(payload)
        case .doc(let payload):
            try container.encode(payload)
        case .table(let payload):
            try container.encode(payload)
        case .code(let payload):
            try container.encode(payload)
        case .memo(let payload):
            try container.encode(payload)
        }
    }
}

public struct AnyOf_20: Codable, Hashable, Sendable {
    public let type: String
    public let sourceId: String
    public let refKind: AnyOf_20RefKind
    public let snapshot: AnyOf_20Snapshot

    public init(type: String, sourceId: String, refKind: AnyOf_20RefKind, snapshot: AnyOf_20Snapshot) {
        self.type = type
        self.sourceId = sourceId
        self.refKind = refKind
        self.snapshot = snapshot
    }

    public enum CodingKeys: String, CodingKey {
        case type
        case sourceId = "source_id"
        case refKind = "ref_kind"
        case snapshot
    }
}

public typealias TabTinSourceRefBlock = AnyOf_20
public typealias TabtinSourceRefBlock = TabTinSourceRefBlock