import { describe, it, expect } from 'vitest'
import { buildExcludeContent, CHECKPOINT_EXCLUDE_PATTERNS } from '../exclusions.js'

describe('buildExcludeContent', () => {
  it('should include all CHECKPOINT_EXCLUDE_PATTERNS when called without arguments', () => {
    const content = buildExcludeContent()
    for (const pattern of CHECKPOINT_EXCLUDE_PATTERNS) {
      expect(content).toContain(pattern)
    }
    expect(content).toContain('# Auto-generated by TabTin Checkpoint')
  })

  it('should include LFS patterns under "# LFS patterns" section', () => {
    const lfsPatterns = ['*.psd', '*.ai']
    const content = buildExcludeContent(lfsPatterns)
    expect(content).toContain('# LFS patterns')
    expect(content).toContain('*.psd')
    expect(content).toContain('*.ai')
  })

  it('should include user excludes under "# User repo .git/info/exclude" section', () => {
    const userExcludes = ['my-secret/', 'temp-data/']
    const content = buildExcludeContent([], userExcludes)
    expect(content).toContain('# User repo .git/info/exclude')
    expect(content).toContain('my-secret/')
    expect(content).toContain('temp-data/')
  })

  it('should include both LFS and user excludes sections when both provided', () => {
    const lfsPatterns = ['*.psd']
    const userExcludes = ['my-secret/']
    const content = buildExcludeContent(lfsPatterns, userExcludes)

    expect(content).toContain('# LFS patterns')
    expect(content).toContain('*.psd')
    expect(content).toContain('# User repo .git/info/exclude')
    expect(content).toContain('my-secret/')

    const lfsIdx = content.indexOf('# LFS patterns')
    const userIdx = content.indexOf('# User repo .git/info/exclude')
    expect(lfsIdx).toBeLessThan(userIdx)
  })

  it('should not include section headers when empty arrays provided', () => {
    const content = buildExcludeContent([], [])
    expect(content).not.toContain('# LFS patterns')
    expect(content).not.toContain('# User repo .git/info/exclude')
    for (const pattern of CHECKPOINT_EXCLUDE_PATTERNS) {
      expect(content).toContain(pattern)
    }
  })
})
