# Generated by Django 4.2.7 on 2026-08-10 06:45

import apps.extensions.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tabtinspace', '0140_backfill_mcpconnection_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginRelayPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=253)),
                ('encrypted_payload', apps.extensions.fields.EncryptedJSONField(default=list, help_text='Encrypted short-lived relay cookie payload')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('consumed', 'Consumed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_relay_packages', to='tabtinspace.workspace')),
                ('target_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_relay_packages', to='tabtinspace.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_relay_packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'login_relay_package',
                'indexes': [models.Index(fields=['user', 'status', 'created_at'], name='login_relay_user_state_idx')],
                'constraints': [models.CheckConstraint(check=models.Q(models.Q(('consumed_at__isnull', True), ('status', 'pending')), models.Q(('consumed_at__isnull', False), ('status', 'consumed')), _connector='OR'), name='login_relay_status_time_ck')],
            },
        ),
    ]
