"""TabTin wire protocol generated types (Pydantic v2).

Generated by @tabtin/wire-codegen — DO NOT EDIT MANUALLY.

Source: packages/agent-wire/src/stream-content-block.ts
Run `pnpm --filter @tabtin/wire-codegen codegen` to regenerate.
"""
