# Generated by Django 4.2.7 on 2026-03-04 20:27

import apps.services.common.base_models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('agent_space_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(default='', max_length=255)),
                ('local_path', models.TextField(blank=True, default='')),
                ('git_remote_url', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
            ],
            options={
                'db_table': 'tabcode_code_project',
            },
            bases=(models.Model, apps.services.common.base_models.ContextSyncMixin),
        ),
    ]
