# Generated by Django 4.2.7 on 2026-03-04 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tabcode', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='codeproject',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabcode_projects_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='codeproject',
            index=models.Index(fields=['agent_space_id', 'status'], name='tc_proj_status_idx'),
        ),
    ]
