# Generated by Django 4.2.7 on 2026-03-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabcode', '0003_add_trash_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='codeproject',
            name='tc_proj_status_idx',
        ),
        migrations.AlterField(
            model_name='codeproject',
            name='agent_space_id',
            field=models.UUIDField(db_column='agent_space_id', db_index=True),
        ),
        migrations.RenameField(
            model_name='codeproject',
            old_name='agent_space_id',
            new_name='space_id',
        ),
        migrations.AddField(
            model_name='codeproject',
            name='owner_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='codeproject',
            index=models.Index(fields=['space_id', 'status'], name='tc_proj_status_idx'),
        ),
    ]
