# Generated by Django 4.2.7 on 2026-03-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabcode', '0004_remove_codeproject_tc_proj_status_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeproject',
            name='space_id',
            field=models.UUIDField(db_index=True),
        ),
    ]
