# Generated by Django 4.2.7 on 2026-06-05 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tabcode', '0006_workspace_to_workteam_rename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeproject',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabcode_projects_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
