# Generated by Django 4.2.7 on 2026-06-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabcode', '0007_alter_codeproject_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeproject',
            name='space_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
