# Generated by Django 4.2.7 on 2026-03-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_errors', '0005_add_app_version_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='clienterrorevent',
            name='idx_event_fp_user',
        ),
        migrations.RemoveIndex(
            model_name='clienterrorgroup',
            name='idx_group_last_seen',
        ),
        migrations.RemoveIndex(
            model_name='clienterrorgroup',
            name='idx_group_status',
        ),
        migrations.AlterField(
            model_name='release',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sourcemapfile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
