# Generated by Django 4.2.7 on 2026-05-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_errors', '0006_remove_clienterrorevent_idx_event_fp_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienterrorevent',
            name='component_stack',
            field=models.TextField(blank=True, default='', verbose_name='React 组件栈'),
        ),
    ]
