# Generated by Django 4.2.7 on 2026-03-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FailedTaskRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=255)),
                ('task_name', models.CharField(max_length=500)),
                ('args', models.JSONField(default=list)),
                ('kwargs', models.JSONField(default=dict)),
                ('exception', models.TextField()),
                ('traceback', models.TextField(blank=True, default='')),
                ('retries', models.IntegerField(default=0)),
                ('failed_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'maintenance_failed_task_record',
                'ordering': ['-failed_at'],
            },
        ),
    ]
