/**
 * Exclusions 单元测试
 */

import { describe, it, expect } from 'vitest'
import { CHECKPOINT_EXCLUDE_PATTERNS, buildExcludeContent } from '@tabtin/checkpoint-core'

describe('CHECKPOINT_EXCLUDE_PATTERNS', () => {
  it('should include node_modules', () => {
    expect(CHECKPOINT_EXCLUDE_PATTERNS).toContain('node_modules/')
  })

  it('should include dist', () => {
    expect(CHECKPOINT_EXCLUDE_PATTERNS).toContain('dist/')
  })

  it('should include lock files', () => {
    expect(CHECKPOINT_EXCLUDE_PATTERNS).toContain('pnpm-lock.yaml')
    expect(CHECKPOINT_EXCLUDE_PATTERNS).toContain('package-lock.json')
  })

  it('should include media files', () => {
    expect(CHECKPOINT_EXCLUDE_PATTERNS).toContain('*.jpg')
    expect(CHECKPOINT_EXCLUDE_PATTERNS).toContain('*.png')
    expect(CHECKPOINT_EXCLUDE_PATTERNS).toContain('*.mp4')
  })

  it('should include .env files', () => {
    expect(CHECKPOINT_EXCLUDE_PATTERNS).toContain('.env')
    expect(CHECKPOINT_EXCLUDE_PATTERNS).toContain('.env.*')
  })
})

describe('buildExcludeContent', () => {
  it('should produce a valid string with a header', () => {
    const content = buildExcludeContent()
    expect(content).toContain('Auto-generated by TabTin Checkpoint')
    expect(content).toContain('node_modules/')
    expect(content.endsWith('\n')).toBe(true)
  })

  it('should append extra patterns', () => {
    const content = buildExcludeContent(['*.custom', 'my-dir/'])
    expect(content).toContain('*.custom')
    expect(content).toContain('my-dir/')
  })
})
