# Squashed migration: billing 0001 → 0014
# Generated by Django 4.2.7, manually optimized.
#
# 生产环境已执行过 0001–0014 全部旧 migration，本文件仅用于：
#   1. 新环境（含测试数据库）从零建表
#   2. 所有实例确认升级后可删除旧文件

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.migrations.operations.special
import django.utils.timezone
import uuid


def copy_budget_data(apps, schema_editor):
    """从旧表 services_llm_usage_budget_policy 复制数据（幂等）。"""
    connection = schema_editor.connection
    # 旧表是否存在用 introspection 判定，不用 try/except 探测：PostgreSQL 下
    # 一条失败的探测 SQL 会毒化整个迁移事务（"current transaction is aborted"），
    # 后续 create_model / 落账全部连带失败——single_pg 单库迁移即卡在此处。
    # MySQL 容忍这种探测，PG 不容忍，故改成不依赖捕异常的存在性检查。
    if "services_llm_usage_budget_policy" not in connection.introspection.table_names():
        return
    with connection.cursor() as cursor:
        cursor.execute("SELECT COUNT(*) FROM services_llm_usage_budget_policy")
        old_count = cursor.fetchone()[0]
        if old_count == 0:
            return
        cursor.execute("SELECT COUNT(*) FROM services_billing_budget_policy")
        if cursor.fetchone()[0] > 0:
            return
        cursor.execute("""
            INSERT INTO services_billing_budget_policy
                (id, workspace_id, warning_threshold_percent, critical_threshold_percent,
                 block_on_critical, is_active, created_at, updated_at)
            SELECT id, workspace_id, warning_threshold_percent, critical_threshold_percent,
                   block_on_critical, is_active, created_at, updated_at
            FROM services_llm_usage_budget_policy
        """)


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        # ── BillingInvoice (最终状态) ─────────────────────────────
        migrations.CreateModel(
            name='BillingInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='账单号')),
                ('workspace_id', models.CharField(db_index=True, max_length=100, verbose_name='工作空间ID')),
                ('period_start', models.DateField(db_index=True, verbose_name='账期开始')),
                ('period_end', models.DateField(db_index=True, verbose_name='账期结束')),
                ('status', models.CharField(
                    choices=[
                        ('draft', '草稿'), ('open', '待支付'), ('paid', '已支付'),
                        ('failed', '扣款失败'), ('cancelled', '已取消'),
                        ('refunded', '已退款'), ('partially_refunded', '部分退款'),
                    ],
                    db_index=True, default='draft', max_length=20, verbose_name='状态',
                )),
                ('currency', models.CharField(default='CREDITS', max_length=12, verbose_name='币种')),
                ('subtotal_amount', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24, verbose_name='小计')),
                ('discount_amount', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24, verbose_name='优惠')),
                ('total_amount', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24, verbose_name='应付总额')),
                ('metadata', models.JSONField(default=dict, verbose_name='扩展元数据')),
                ('collection_attempt_count', models.IntegerField(db_index=True, default=0, verbose_name='扣款尝试次数')),
                ('refunded_amount', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24, verbose_name='已退款金额')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='退款时间')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='出账时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '账单',
                'verbose_name_plural': '账单',
                'db_table': 'services_billing_invoice',
                'ordering': ['-period_start', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='billinginvoice',
            index=models.Index(fields=['workspace_id', 'status', 'period_start'], name='services_bi_workspa_f6ef83_idx'),
        ),
        migrations.AddIndex(
            model_name='billinginvoice',
            index=models.Index(fields=['period_start', 'period_end'], name='services_bi_period__7820a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='billinginvoice',
            unique_together={('workspace_id', 'period_start', 'period_end')},
        ),

        # ── BillingInvoiceLine ────────────────────────────────────
        migrations.CreateModel(
            name='BillingInvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(db_index=True, max_length=100, verbose_name='工作空间ID')),
                ('meter_key', models.CharField(db_index=True, max_length=200, verbose_name='计量项')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='描述')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=24, verbose_name='数量')),
                ('unit', models.CharField(default='unit', max_length=40, verbose_name='单位')),
                ('unit_price', models.DecimalField(decimal_places=8, max_digits=24, verbose_name='单价')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=24, verbose_name='金额')),
                ('metadata', models.JSONField(default=dict, verbose_name='扩展元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.billinginvoice', verbose_name='所属账单')),
            ],
            options={
                'verbose_name': '账单明细',
                'verbose_name_plural': '账单明细',
                'db_table': 'services_billing_invoice_line',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='billinginvoiceline',
            index=models.Index(fields=['invoice', 'meter_key'], name='services_bi_invoice_9691df_idx'),
        ),
        migrations.AddIndex(
            model_name='billinginvoiceline',
            index=models.Index(fields=['workspace_id', 'meter_key'], name='services_bi_workspa_32b846_idx'),
        ),

        # ── BillingUsageEvent (最终状态) ──────────────────────────
        migrations.CreateModel(
            name='BillingUsageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='工作空间ID')),
                ('user_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='用户ID')),
                ('meter_key', models.CharField(db_index=True, max_length=200, verbose_name='计量项')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='数量')),
                ('unit', models.CharField(default='unit', max_length=40, verbose_name='单位')),
                ('unit_price', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='单价')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='金额')),
                ('currency', models.CharField(default='CNY', max_length=12, verbose_name='币种')),
                ('provider_key', models.CharField(blank=True, default='', max_length=100, verbose_name='渠道标识')),
                ('model_name', models.CharField(blank=True, default='', max_length=120, verbose_name='模型名称')),
                ('biz_type', models.CharField(blank=True, default='', max_length=60, verbose_name='业务类型')),
                ('biz_id', models.CharField(blank=True, default='', max_length=100, verbose_name='业务ID')),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=160, unique=True, verbose_name='幂等键')),
                ('metadata', models.JSONField(default=dict, verbose_name='扩展元数据')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='发生时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '计费用量事件',
                'verbose_name_plural': '计费用量事件',
                'db_table': 'services_billing_usage_event',
                'ordering': ['-occurred_at', '-created_at'],
                'indexes': [
                    models.Index(fields=['workspace_id', 'meter_key', 'occurred_at'], name='services_bi_workspa_f3617d_idx'),
                    models.Index(fields=['user_id', 'occurred_at'], name='services_bi_user_id_f4e5d3_idx'),
                    models.Index(fields=['biz_type', 'biz_id'], name='services_bi_biz_typ_8cd3ba_idx'),
                ],
            },
        ),
        migrations.AddIndex(
            model_name='billingusageevent',
            index=models.Index(fields=['meter_key', 'occurred_at'], name='services_bi_meter_k_7cd9a9_idx'),
        ),

        # ── BillingUsageDaily ─────────────────────────────────────
        migrations.CreateModel(
            name='BillingUsageDaily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(db_index=True, max_length=100, verbose_name='工作空间ID')),
                ('usage_date', models.DateField(db_index=True, verbose_name='用量日期')),
                ('meter_key', models.CharField(db_index=True, max_length=200, verbose_name='计量项')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=24, verbose_name='聚合数量')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=24, verbose_name='聚合金额')),
                ('currency', models.CharField(default='CREDITS', max_length=12, verbose_name='币种')),
                ('source_event_count', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='来源事件数')),
                ('extra', models.JSONField(default=dict, verbose_name='扩展数据')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='生成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '计费日聚合',
                'verbose_name_plural': '计费日聚合',
                'db_table': 'services_billing_usage_daily',
                'ordering': ['-usage_date', '-updated_at'],
                'indexes': [
                    models.Index(fields=['workspace_id', 'usage_date'], name='services_bi_workspa_ccea3b_idx'),
                    models.Index(fields=['workspace_id', 'meter_key', 'usage_date'], name='services_bi_workspa_0fae66_idx'),
                ],
                'unique_together': {('workspace_id', 'usage_date', 'meter_key')},
            },
        ),

        # ── WorkspaceStorageUsage ─────────────────────────────────
        migrations.CreateModel(
            name='WorkspaceStorageUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='工作空间ID')),
                ('active_file_count', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='当前有效文件数')),
                ('active_storage_bytes', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='当前有效占用字节')),
                ('total_uploaded_bytes', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='累计上传字节')),
                ('total_released_bytes', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='累计释放字节')),
                ('last_metered_at', models.DateTimeField(blank=True, null=True, verbose_name='最近计量时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工作空间附件空间使用',
                'verbose_name_plural': '工作空间附件空间使用',
                'db_table': 'services_billing_workspace_storage_usage',
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [
                    models.Index(fields=['workspace_id'], name='services_bi_workspa_746cb9_idx'),
                    models.Index(fields=['active_storage_bytes', 'updated_at'], name='services_bi_active__199903_idx'),
                ],
            },
        ),

        # ── WorkspaceLlmMonthlyBudget ─────────────────────────────
        migrations.CreateModel(
            name='WorkspaceLlmMonthlyBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(db_index=True, max_length=100, verbose_name='工作空间ID')),
                ('cycle_month', models.DateField(db_index=True, verbose_name='结算月份（每月1号）')),
                ('included_credits', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='月度预算总额（点券）')),
                ('consumed_credits', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='已消耗预算（点券）')),
                ('overflow_credits', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='超预算额度（仅预算模式）')),
                ('updated_from_entitlement_at', models.DateTimeField(blank=True, null=True, verbose_name='最近同步权益时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工作空间LLM月预算',
                'verbose_name_plural': '工作空间LLM月预算',
                'db_table': 'services_billing_workspace_llm_monthly_budget',
                'ordering': ['-cycle_month', '-updated_at'],
                'indexes': [models.Index(fields=['workspace_id', 'cycle_month'], name='services_bi_workspa_3084df_idx')],
                'unique_together': {('workspace_id', 'cycle_month')},
            },
        ),

        # ── WorkspaceBillingPolicy ────────────────────────────────
        migrations.CreateModel(
            name='WorkspaceBillingPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='工作空间ID')),
                ('storage_billing_mode', models.CharField(choices=[('package_only', '仅套餐'), ('paygo_only', '仅按量'), ('package_plus_paygo', '套餐+按量')], default='package_plus_paygo', max_length=40, verbose_name='存储计费模式')),
                ('llm_billing_mode', models.CharField(choices=[('quota_then_paygo', '预算优先后按量'), ('paygo_only', '仅按量'), ('quota_only', '仅预算')], default='quota_then_paygo', max_length=40, verbose_name='LLM计费模式')),
                ('currency', models.CharField(default='CREDITS', max_length=12, verbose_name='计费币种')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('metadata', models.JSONField(default=dict, verbose_name='扩展元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工作空间计费策略',
                'verbose_name_plural': '工作空间计费策略',
                'db_table': 'services_billing_workspace_policy',
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['workspace_id', 'is_active'], name='services_bi_workspa_1a7b98_idx')],
            },
        ),

        # ── WorkspaceBillingEntitlement ───────────────────────────
        migrations.CreateModel(
            name='WorkspaceBillingEntitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='工作空间ID')),
                ('included_storage_bytes', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='赠送存储容量（字节）')),
                ('purchased_storage_bytes', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='增值包存储容量（字节）')),
                ('included_llm_credits_monthly', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='每月赠送LLM额度（点券）')),
                ('effective_from', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='生效开始时间')),
                ('effective_to', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='生效结束时间')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('metadata', models.JSONField(default=dict, verbose_name='扩展元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工作空间计费权益',
                'verbose_name_plural': '工作空间计费权益',
                'db_table': 'services_billing_workspace_entitlement',
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [
                    models.Index(fields=['workspace_id', 'is_active'], name='services_bi_workspa_0469ae_idx'),
                    models.Index(fields=['effective_from', 'effective_to'], name='services_bi_effecti_ab02b4_idx'),
                ],
            },
        ),

        # ── MeterPricing ─────────────────────────────────────────
        migrations.CreateModel(
            name='MeterPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meter_key', models.CharField(db_index=True, max_length=200, verbose_name='计量项')),
                ('scope', models.CharField(choices=[('global', '全局'), ('workspace', '工作空间')], db_index=True, default='global', max_length=20, verbose_name='作用域')),
                ('workspace_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='工作空间ID')),
                ('provider_key', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='渠道标识')),
                ('model_name', models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='模型名称')),
                ('unit', models.CharField(default='unit', max_length=40, verbose_name='计价单位')),
                ('unit_price', models.DecimalField(decimal_places=8, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='单价')),
                ('currency', models.CharField(default='CNY', max_length=12, verbose_name='币种')),
                ('precision', models.PositiveSmallIntegerField(default=4, verbose_name='账务精度')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级')),
                ('effective_from', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='生效开始时间')),
                ('effective_to', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='生效结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '计量定价',
                'verbose_name_plural': '计量定价',
                'db_table': 'services_billing_meter_pricing',
                'ordering': ['-priority', '-effective_from', '-created_at'],
                'indexes': [
                    models.Index(fields=['meter_key', 'scope', 'workspace_id', 'is_active'], name='services_bi_meter_k_593ca3_idx'),
                    models.Index(fields=['provider_key', 'model_name', 'is_active'], name='services_bi_provide_74f730_idx'),
                    models.Index(fields=['effective_from', 'effective_to'], name='services_bi_effecti_a3b952_idx'),
                ],
            },
        ),

        # ── BillingBudgetPolicy ───────────────────────────────────
        migrations.CreateModel(
            name='BillingBudgetPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='工作空间ID')),
                ('warning_threshold_percent', models.DecimalField(decimal_places=2, default=Decimal('80'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('500'))], verbose_name='预警阈值(%)')),
                ('critical_threshold_percent', models.DecimalField(decimal_places=2, default=Decimal('100'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('500'))], verbose_name='严重阈值(%)')),
                ('block_on_critical', models.BooleanField(default=False, help_text='启用后，达到严重阈值时将拒绝新的请求', verbose_name='严重阈值硬阻断')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用量预算策略',
                'verbose_name_plural': '用量预算策略',
                'db_table': 'services_billing_budget_policy',
                'ordering': ['workspace_id'],
            },
        ),
        migrations.AddIndex(
            model_name='billingbudgetpolicy',
            index=models.Index(fields=['workspace_id', 'is_active'], name='billing_budget_ws_idx'),
        ),

        # ── 数据迁移：从旧 BudgetPolicy 表拷贝 ────────────────────
        migrations.RunPython(
            code=copy_budget_data,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),

        # ── BillingAdminAuditLog ──────────────────────────────────
        migrations.CreateModel(
            name='BillingAdminAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin_user_id', models.CharField(db_index=True, max_length=36, verbose_name='管理员ID')),
                ('action', models.CharField(db_index=True, max_length=50, verbose_name='操作动作')),
                ('target_type', models.CharField(db_index=True, max_length=50, verbose_name='目标类型')),
                ('target_id', models.CharField(max_length=100, verbose_name='目标ID')),
                ('workspace_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='工作空间ID')),
                ('detail', models.JSONField(default=dict, verbose_name='变更详情')),
                ('ip_address', models.CharField(blank=True, max_length=45, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '计费审计日志',
                'verbose_name_plural': '计费审计日志',
                'db_table': 'services_billing_admin_audit_log',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['admin_user_id', 'created_at'], name='billing_audit_admin_idx'),
                    models.Index(fields=['action', 'target_type'], name='billing_audit_action_idx'),
                ],
            },
        ),

        # ── BillingReconciliationReport ───────────────────────────
        migrations.CreateModel(
            name='BillingReconciliationReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField(db_index=True, verbose_name='对账日期')),
                ('workspace_id', models.CharField(blank=True, db_index=True, default='', help_text='空=全局汇总', max_length=100, verbose_name='工作空间ID')),
                ('billing_total', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20, verbose_name='BillingUsageEvent 汇总金额')),
                ('wallet_total', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20, verbose_name='WalletTransaction 消费汇总')),
                ('diff_amount', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20, verbose_name='差额（billing - wallet）')),
                ('diff_pct', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, verbose_name='差异百分比')),
                ('status', models.CharField(choices=[('matched', '匹配'), ('warning', '差异预警'), ('mismatch', '严重不匹配')], db_index=True, default='matched', max_length=20, verbose_name='对账状态')),
                ('detail_json', models.JSONField(default=dict, verbose_name='详细信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '计费对账报告',
                'verbose_name_plural': '计费对账报告',
                'db_table': 'services_billing_reconciliation_report',
                'ordering': ['-report_date', '-created_at'],
                'indexes': [models.Index(fields=['report_date', 'status'], name='services_bi_report__13635d_idx')],
                'unique_together': {('report_date', 'workspace_id')},
            },
        ),

        # ── BillingAnomalyAlert (最终状态) ────────────────────────
        migrations.CreateModel(
            name='BillingAnomalyAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(
                    choices=[
                        ('spike', '消费突增'), ('abuse', '疑似滥用'),
                        ('pattern', '异常模式'), ('charge_failed', '计费失败'),
                    ],
                    db_index=True, max_length=20, verbose_name='告警类型',
                )),
                ('severity', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('critical', '严重')], db_index=True, default='warning', max_length=20, verbose_name='严重程度')),
                ('workspace_id', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='工作空间ID')),
                ('user_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='用户ID')),
                ('metric_name', models.CharField(max_length=100, verbose_name='指标名称')),
                ('current_value', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='当前值')),
                ('baseline_value', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20, verbose_name='基线值')),
                ('threshold_ratio', models.DecimalField(decimal_places=2, default=Decimal('5'), max_digits=10, verbose_name='阈值倍率')),
                ('message', models.TextField(verbose_name='告警消息')),
                ('is_resolved', models.BooleanField(db_index=True, default=False, verbose_name='是否已处理')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '计费异常告警',
                'verbose_name_plural': '计费异常告警',
                'db_table': 'services_billing_anomaly_alert',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['severity', 'is_resolved', 'created_at'], name='services_bi_severit_a8d0a0_idx'),
                    models.Index(fields=['workspace_id', 'created_at'], name='services_bi_workspa_3bed48_idx'),
                    models.Index(fields=['user_id', 'created_at'], name='services_bi_user_id_6ec74c_idx'),
                ],
            },
        ),
    ]
