# Generated by Django 4.2.7 on 2026-03-07 12:30

from decimal import Decimal
import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_squashed_0001_0014"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoragePackagePlan",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120, verbose_name="套餐名称")),
                ("description", models.TextField(blank=True, default="", verbose_name="套餐描述")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="售价（元）",
                    ),
                ),
                (
                    "storage_bytes",
                    models.BigIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="基础容量（字节）",
                    ),
                ),
                (
                    "bonus_storage_bytes",
                    models.BigIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="赠送容量（字节）",
                    ),
                ),
                (
                    "duration_months",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="有效期（月）",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="是否启用")),
                ("metadata", models.JSONField(default=dict, verbose_name="扩展元数据")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "存储套餐",
                "verbose_name_plural": "存储套餐",
                "db_table": "services_billing_storage_package_plan",
                "ordering": ["sort_order", "-created_at"],
                "indexes": [
                    models.Index(fields=["is_active", "sort_order"], name="bill_sp_active_sort_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceStorageSubscription",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("workspace_id", models.CharField(db_index=True, max_length=100, verbose_name="工作空间ID")),
                (
                    "order_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=36,
                        null=True,
                        unique=True,
                        verbose_name="关联支付订单ID",
                    ),
                ),
                ("purchased_by", models.CharField(blank=True, default="", max_length=36, verbose_name="购买用户ID")),
                (
                    "storage_bytes",
                    models.BigIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="生效容量（字节）",
                    ),
                ),
                (
                    "start_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="开始时间",
                    ),
                ),
                ("end_at", models.DateTimeField(db_index=True, verbose_name="结束时间")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "生效中"), ("expired", "已过期"), ("cancelled", "已取消")],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("auto_renew", models.BooleanField(default=False, verbose_name="自动续费")),
                ("metadata", models.JSONField(default=dict, verbose_name="扩展元数据")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "package_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="billing.storagepackageplan",
                        verbose_name="套餐",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作空间存储订阅",
                "verbose_name_plural": "工作空间存储订阅",
                "db_table": "services_billing_workspace_storage_subscription",
                "ordering": ["-end_at", "-created_at"],
                "indexes": [
                    models.Index(fields=["workspace_id", "status", "end_at"], name="bill_ws_sub_status_end_idx"),
                    models.Index(fields=["workspace_id", "start_at"], name="bill_ws_sub_start_idx"),
                ],
            },
        ),
    ]
