# Generated by Django 4.2.7 on 2026-03-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_workspace_lifecycle_cleanup_job'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='storagepackageplan',
            new_name='services_bi_is_acti_1e7786_idx',
            old_name='bill_sp_active_sort_idx',
        ),
        migrations.RenameIndex(
            model_name='workspacestoragesubscription',
            new_name='services_bi_workspa_9106ff_idx',
            old_name='bill_ws_sub_status_end_idx',
        ),
        migrations.RenameIndex(
            model_name='workspacestoragesubscription',
            new_name='services_bi_workspa_673836_idx',
            old_name='bill_ws_sub_start_idx',
        ),
        migrations.AlterField(
            model_name='billinganomalyalert',
            name='alert_type',
            field=models.CharField(choices=[('spike', '消费突增'), ('abuse', '疑似滥用'), ('pattern', '异常模式'), ('charge_failed', '计费失败'), ('cleanup_failed', '清理失败')], db_index=True, max_length=20, verbose_name='告警类型'),
        ),
    ]
