# Generated by Django 4.2.7 on 2026-03-16 08:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_rename_bill_sp_active_sort_idx_services_bi_is_acti_1e7786_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceServicePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='工作空间ID')),
                ('enable_media_image', models.BooleanField(default=True, verbose_name='AI 文生图')),
                ('enable_media_video', models.BooleanField(default=True, verbose_name='AI 视频生成')),
                ('enable_speech_asr', models.BooleanField(default=True, verbose_name='语音识别')),
                ('enable_speech_tts', models.BooleanField(default=True, verbose_name='语音合成')),
                ('enable_rag_embedding', models.BooleanField(default=True, verbose_name='RAG 向量化')),
                ('enable_web_search', models.BooleanField(default=True, verbose_name='网页搜索')),
                ('enable_auto_doc_index', models.BooleanField(default=True, verbose_name='文档自动索引')),
                ('enable_auto_code_index', models.BooleanField(default=True, verbose_name='代码自动索引')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(blank=True, default='', max_length=64, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '工作空间服务策略',
                'verbose_name_plural': '工作空间服务策略',
                'db_table': 'services_billing_workspace_service_policy',
                'indexes': [models.Index(fields=['workspace_id'], name='services_bi_workspa_7bc7bb_idx')],
            },
        ),
    ]
