# Generated by Django 4.2.7 on 2026-03-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_rename_bill_sp_active_sort_idx_services_bi_is_acti_1e7786_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingbudgetpolicy',
            name='budget_limit_credits',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, help_text='XM-16: 与 included_credits 解耦的独立预算上限。设置后优先使用此值作为预算告警分母，解决 free tier included=0 时预算告警永不触发的问题。', max_digits=16, null=True, verbose_name='显式预算上限(点券)'),
        ),
    ]
