# Generated by Django 4.2.7 on 2026-03-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_add_workspace_service_policy'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='workspaceservicepolicy',
            name='services_bi_workspa_7bc7bb_idx',
        ),
        migrations.AddField(
            model_name='workspaceservicepolicy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
    ]
