# Generated by Django 4.2.7 on 2026-03-18 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_add_budget_limit_credits'),
        ('billing', '0007_update_service_policy_model'),
    ]

    operations = [
    ]
