# Generated by Django 4.2.7 on 2026-03-19 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_workspace_to_workteam_rename'),
        ('billing', '0008_merge_20260318_1550'),
    ]

    operations = [
    ]
