# Generated by Django 4.2.7 on 2026-03-19 02:11

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_merge_20260319_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingbudgetpolicy',
            options={'ordering': ['workteam_id'], 'verbose_name': '用量预算策略', 'verbose_name_plural': '用量预算策略'},
        ),
        migrations.AlterModelOptions(
            name='workteambillingentitlement',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name': '工作团队计费权益', 'verbose_name_plural': '工作团队计费权益'},
        ),
        migrations.AlterModelOptions(
            name='workteambillingpolicy',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name': '工作团队计费策略', 'verbose_name_plural': '工作团队计费策略'},
        ),
        migrations.AlterModelOptions(
            name='workteamlifecyclecleanupjob',
            options={'ordering': ['status', 'next_retry_at', '-updated_at'], 'verbose_name': '工作团队生命周期清理作业', 'verbose_name_plural': '工作团队生命周期清理作业'},
        ),
        migrations.AlterModelOptions(
            name='workteamllmmonthlybudget',
            options={'ordering': ['-cycle_month', '-updated_at'], 'verbose_name': '工作团队LLM月预算', 'verbose_name_plural': '工作团队LLM月预算'},
        ),
        migrations.AlterModelOptions(
            name='workteamstoragesubscription',
            options={'ordering': ['-end_at', '-created_at'], 'verbose_name': '工作团队存储订阅', 'verbose_name_plural': '工作团队存储订阅'},
        ),
        migrations.AlterModelOptions(
            name='workteamstorageusage',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name': '工作团队附件空间使用', 'verbose_name_plural': '工作团队附件空间使用'},
        ),
        migrations.RemoveIndex(
            model_name='billinganomalyalert',
            name='services_bi_workspa_3bed48_idx',
        ),
        migrations.RemoveIndex(
            model_name='billingbudgetpolicy',
            name='billing_budget_ws_idx',
        ),
        migrations.RemoveIndex(
            model_name='billinginvoice',
            name='services_bi_workspa_f6ef83_idx',
        ),
        migrations.RemoveIndex(
            model_name='billinginvoiceline',
            name='services_bi_workspa_32b846_idx',
        ),
        migrations.RemoveIndex(
            model_name='billingusagedaily',
            name='services_bi_workspa_ccea3b_idx',
        ),
        migrations.RemoveIndex(
            model_name='billingusagedaily',
            name='services_bi_workspa_0fae66_idx',
        ),
        migrations.RemoveIndex(
            model_name='billingusageevent',
            name='services_bi_workspa_f3617d_idx',
        ),
        migrations.RemoveIndex(
            model_name='meterpricing',
            name='services_bi_meter_k_593ca3_idx',
        ),
        migrations.RemoveIndex(
            model_name='workteambillingentitlement',
            name='services_bi_workspa_0469ae_idx',
        ),
        migrations.RemoveIndex(
            model_name='workteambillingpolicy',
            name='services_bi_workspa_1a7b98_idx',
        ),
        migrations.RemoveIndex(
            model_name='workteamllmmonthlybudget',
            name='services_bi_workspa_3084df_idx',
        ),
        migrations.RemoveIndex(
            model_name='workteamstoragesubscription',
            name='services_bi_workspa_9106ff_idx',
        ),
        migrations.RemoveIndex(
            model_name='workteamstoragesubscription',
            name='services_bi_workspa_673836_idx',
        ),
        migrations.RemoveIndex(
            model_name='workteamstorageusage',
            name='services_bi_workspa_746cb9_idx',
        ),
        migrations.RenameIndex(
            model_name='workteambillingentitlement',
            new_name='services_bi_effecti_b79a20_idx',
            old_name='services_bi_effecti_ab02b4_idx',
        ),
        migrations.RenameIndex(
            model_name='workteamstorageusage',
            new_name='services_bi_active__53e7c1_idx',
            old_name='services_bi_active__199903_idx',
        ),
        migrations.AlterField(
            model_name='billingadminauditlog',
            name='workteam_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='工作团队ID'),
        ),
        migrations.AlterField(
            model_name='billinganomalyalert',
            name='workteam_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='工作团队ID'),
        ),
        migrations.AlterField(
            model_name='billingbudgetpolicy',
            name='workteam_id',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='工作团队ID'),
        ),
        migrations.AlterField(
            model_name='billinginvoice',
            name='workteam_id',
            field=models.CharField(db_index=True, max_length=100, verbose_name='工作团队ID'),
        ),
        migrations.AlterField(
            model_name='billinginvoiceline',
            name='workteam_id',
            field=models.CharField(db_index=True, max_length=100, verbose_name='工作团队ID'),
        ),
        migrations.AlterField(
            model_name='billingreconciliationreport',
            name='workteam_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='空=全局汇总', max_length=100, verbose_name='工作团队ID'),
        ),
        migrations.AlterField(
            model_name='billingusagedaily',
            name='workteam_id',
            field=models.CharField(db_index=True, max_length=100, verbose_name='工作团队ID'),
        ),
        migrations.AlterField(
            model_name='billingusageevent',
            name='workteam_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='工作团队ID'),
        ),
        migrations.AlterField(
            model_name='meterpricing',
            name='scope',
            field=models.CharField(choices=[('global', '全局'), ('workteam', '工作团队')], db_index=True, default='global', max_length=20, verbose_name='作用域'),
        ),
        migrations.AlterField(
            model_name='meterpricing',
            name='workteam_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='工作团队ID'),
        ),
        migrations.AlterField(
            model_name='workteambillingentitlement',
            name='workteam_id',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='工作团队ID'),
        ),
        migrations.AlterField(
            model_name='workteambillingpolicy',
            name='workteam_id',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='工作团队ID'),
        ),
        migrations.AlterField(
            model_name='workteamlifecyclecleanupjob',
            name='trigger_source',
            field=models.CharField(db_index=True, default='workteam_delete', max_length=50, verbose_name='触发来源'),
        ),
        migrations.AlterField(
            model_name='workteamlifecyclecleanupjob',
            name='workteam_id',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='工作团队ID'),
        ),
        migrations.AlterField(
            model_name='workteamllmmonthlybudget',
            name='overflow_credits',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='仅 quota_only 模式下超出配额的免费溢出量；quota_then_paygo 模式下超额走 paygo，此字段恒为 0。', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='免费溢出量（quota_only 模式专用）'),
        ),
        migrations.AlterField(
            model_name='workteamllmmonthlybudget',
            name='workteam_id',
            field=models.CharField(db_index=True, max_length=100, verbose_name='工作团队ID'),
        ),
        migrations.AlterField(
            model_name='workteamstoragesubscription',
            name='workteam_id',
            field=models.CharField(db_index=True, max_length=100, verbose_name='工作团队ID'),
        ),
        migrations.AlterField(
            model_name='workteamstorageusage',
            name='workteam_id',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='工作团队ID'),
        ),
        migrations.AddIndex(
            model_name='billinganomalyalert',
            index=models.Index(fields=['workteam_id', 'created_at'], name='services_bi_worktea_83a05f_idx'),
        ),
        migrations.AddIndex(
            model_name='billingbudgetpolicy',
            index=models.Index(fields=['workteam_id', 'is_active'], name='billing_budget_ws_idx'),
        ),
        migrations.AddIndex(
            model_name='billinginvoice',
            index=models.Index(fields=['workteam_id', 'status', 'period_start'], name='services_bi_worktea_1bbe36_idx'),
        ),
        migrations.AddIndex(
            model_name='billinginvoiceline',
            index=models.Index(fields=['workteam_id', 'meter_key'], name='services_bi_worktea_088cad_idx'),
        ),
        migrations.AddIndex(
            model_name='billingusagedaily',
            index=models.Index(fields=['workteam_id', 'usage_date'], name='services_bi_worktea_2e43b2_idx'),
        ),
        migrations.AddIndex(
            model_name='billingusagedaily',
            index=models.Index(fields=['workteam_id', 'meter_key', 'usage_date'], name='services_bi_worktea_bb4e2c_idx'),
        ),
        migrations.AddIndex(
            model_name='billingusageevent',
            index=models.Index(fields=['workteam_id', 'meter_key', 'occurred_at'], name='services_bi_worktea_64e75d_idx'),
        ),
        migrations.AddIndex(
            model_name='meterpricing',
            index=models.Index(fields=['meter_key', 'scope', 'workteam_id', 'is_active'], name='services_bi_meter_k_b82b23_idx'),
        ),
        migrations.AddIndex(
            model_name='workteambillingentitlement',
            index=models.Index(fields=['workteam_id', 'is_active'], name='services_bi_worktea_820c7b_idx'),
        ),
        migrations.AddIndex(
            model_name='workteambillingpolicy',
            index=models.Index(fields=['workteam_id', 'is_active'], name='services_bi_worktea_9de6ea_idx'),
        ),
        migrations.AddIndex(
            model_name='workteamllmmonthlybudget',
            index=models.Index(fields=['workteam_id', 'cycle_month'], name='services_bi_worktea_3dbf4e_idx'),
        ),
        migrations.AddIndex(
            model_name='workteamstoragesubscription',
            index=models.Index(fields=['workteam_id', 'status', 'end_at'], name='services_bi_worktea_8fbeb4_idx'),
        ),
        migrations.AddIndex(
            model_name='workteamstoragesubscription',
            index=models.Index(fields=['workteam_id', 'start_at'], name='services_bi_worktea_b25e60_idx'),
        ),
        migrations.AddIndex(
            model_name='workteamstorageusage',
            index=models.Index(fields=['workteam_id'], name='services_bi_worktea_bc1a55_idx'),
        ),
        migrations.AlterModelTable(
            name='workteambillingentitlement',
            table='services_billing_workteam_entitlement',
        ),
        migrations.AlterModelTable(
            name='workteambillingpolicy',
            table='services_billing_workteam_policy',
        ),
        migrations.AlterModelTable(
            name='workteamlifecyclecleanupjob',
            table='services_billing_workteam_lifecycle_cleanup_job',
        ),
        migrations.AlterModelTable(
            name='workteamllmmonthlybudget',
            table='services_billing_workteam_llm_monthly_budget',
        ),
        migrations.AlterModelTable(
            name='workteamstoragesubscription',
            table='services_billing_workteam_storage_subscription',
        ),
        migrations.AlterModelTable(
            name='workteamstorageusage',
            table='services_billing_workteam_storage_usage',
        ),
    ]
