# Generated by Django 4.2.7 on 2026-03-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_billing_usage_event_via_share_id_generated_column'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workteamservicepolicy',
            options={'verbose_name': '工作团队服务策略', 'verbose_name_plural': '工作团队服务策略'},
        ),
        migrations.AddField(
            model_name='workteamservicepolicy',
            name='enable_docparse',
            field=models.BooleanField(default=True, verbose_name='文档解析'),
        ),
        migrations.AddField(
            model_name='workteamservicepolicy',
            name='enable_media_audio',
            field=models.BooleanField(default=True, verbose_name='AI 音频/BGM 生成'),
        ),
        migrations.AlterField(
            model_name='workteamservicepolicy',
            name='workteam_id',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='工作团队ID'),
        ),
    ]
