# Generated by Django 4.2.7 on 2026-04-07 13:35

import apps.services.billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_widen_billing_usage_event_biz_id_idempotency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinganomalyalert',
            name='alert_type',
            field=models.CharField(choices=[('spike', '消费突增'), ('abuse', '疑似滥用'), ('pattern', '异常模式'), ('charge_failed', '计费失败'), ('cleanup_failed', '清理失败'), ('frozen_leak', '冻结泄漏')], db_index=True, max_length=20, verbose_name='告警类型'),
        ),
        migrations.AlterField(
            model_name='billingusageevent',
            name='idempotency_key',
            field=models.CharField(blank=True, default=apps.services.billing.models.generate_usage_event_idempotency_key, max_length=255, unique=True, verbose_name='幂等键'),
        ),
    ]
