# Generated by Django 4.2.7 on 2026-04-07 15:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_billingruntimeconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='workteamstorageusage',
            name='eod_snapshot_bytes',
            field=models.BigIntegerField(default=0, verbose_name='日末快照字节数'),
        ),
        migrations.AddField(
            model_name='workteamstorageusage',
            name='eod_snapshot_date',
            field=models.DateField(blank=True, null=True, verbose_name='日末快照日期'),
        ),
        migrations.AlterField(
            model_name='billinganomalyalert',
            name='alert_type',
            field=models.CharField(choices=[('spike', '消费突增'), ('abuse', '疑似滥用'), ('pattern', '异常模式'), ('charge_failed', '计费失败'), ('cleanup_failed', '清理失败'), ('frozen_leak', '冻结泄漏'), ('refund_inconsistency', '退款不一致'), ('zero_price_model', '零价格模型')], db_index=True, max_length=20, verbose_name='告警类型'),
        ),
        migrations.AlterField(
            model_name='billingruntimeconfig',
            name='balance_recheck_interval',
            field=models.IntegerField(default=1, help_text='Agent 运行中每 N 轮 LLM 调用复检一次余额', verbose_name='余额复检间隔（每 N 轮）'),
        ),
        migrations.AlterField(
            model_name='billingruntimeconfig',
            name='cache_discount_config',
            field=models.JSONField(blank=True, default=dict, help_text='格式: {"anthropic": {"cache_read_ratio": 0.1, "cache_write_ratio": 1.25}, ...}', verbose_name='Provider 缓存折扣率配置'),
        ),
        migrations.AlterField(
            model_name='billingruntimeconfig',
            name='credits_per_yuan',
            field=models.IntegerField(default=100, help_text='1 元 = N 点券，影响冻结金额预估和前端费用展示', verbose_name='点券/元换算比例'),
        ),
        migrations.AlterField(
            model_name='billingruntimeconfig',
            name='failopen_max_credits',
            field=models.DecimalField(decimal_places=4, default=Decimal('10'), help_text='fail-open 期间允许的最大累计放行金额', max_digits=10, verbose_name='Fail-open 累计金额上限（点券）'),
        ),
        migrations.AlterField(
            model_name='billingruntimeconfig',
            name='freeze_fallback_credits',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.5'), help_text='首轮或无法估算时的保底冻结金额', max_digits=10, verbose_name='冻结保底金额（点券）'),
        ),
        migrations.AlterField(
            model_name='billingruntimeconfig',
            name='min_balance_threshold',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.01'), help_text='团队可用余额低于此值时阻断 LLM 调用', max_digits=10, verbose_name='余额放行最低阈值（点券）'),
        ),
        migrations.AlterField(
            model_name='billingruntimeconfig',
            name='precheck_fail_threshold',
            field=models.IntegerField(default=10, help_text='预检连续异常超过此次数后切换为 fail-closed', verbose_name='Fail-open 连续异常阈值'),
        ),
        migrations.AlterField(
            model_name='billingruntimeconfig',
            name='precheck_fail_window',
            field=models.IntegerField(default=60, help_text='超过此秒数无新异常时自动重置计数器', verbose_name='Fail-open 异常窗口（秒）'),
        ),
        migrations.AlterField(
            model_name='billingruntimeconfig',
            name='pricing_cache_ttl',
            field=models.IntegerField(default=60, help_text='MeterPricing 查询结果的 Redis 缓存有效期', verbose_name='定价缓存 TTL（秒）'),
        ),
        migrations.AlterField(
            model_name='billingruntimeconfig',
            name='stale_freeze_threshold_minutes',
            field=models.IntegerField(default=120, help_text='超过此时长未结算/释放的冻结将被定时任务清理', verbose_name='冻结超时阈值（分钟）'),
        ),
    ]
