# Generated by Django 4.2.7 on 2026-04-07 16:04

from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_billingruntimeconfig_show_per_message_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberLlmBudgetPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workteam_id', models.CharField(db_index=True, max_length=100)),
                ('user_id', models.CharField(db_index=True, default='__default__', help_text="具体用户 ID，或 '__default__' 表示角色/默认策略", max_length=36)),
                ('target_role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='__default__', help_text="具体角色（角色策略），或 '__default__'（默认策略/个人策略）", max_length=20)),
                ('monthly_credits_limit', models.DecimalField(blank=True, decimal_places=4, help_text='月度点券上限，NULL 表示不限', max_digits=12, null=True)),
                ('daily_credits_limit', models.DecimalField(blank=True, decimal_places=4, help_text='日度点券上限，NULL 表示不限', max_digits=12, null=True)),
                ('max_model_tier', models.CharField(choices=[('standard', '标准'), ('premium', '高级'), ('enterprise', '不限')], default='enterprise', help_text='允许使用的最高模型等级', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'services_billing_member_llm_budget_policy',
            },
        ),
        migrations.CreateModel(
            name='MemberLlmUsageCounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workteam_id', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=36)),
                ('cycle_date', models.DateField(help_text='月度=月首日, 日度=当天')),
                ('cycle_type', models.CharField(choices=[('monthly', '月度'), ('daily', '日度')], max_length=10)),
                ('consumed_credits', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'services_billing_member_usage_counter',
                'indexes': [models.Index(fields=['workteam_id', 'user_id', 'cycle_type', 'cycle_date'], name='services_bi_worktea_48a661_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='memberllmusagecounter',
            constraint=models.UniqueConstraint(fields=('workteam_id', 'user_id', 'cycle_date', 'cycle_type'), name='uniq_member_usage_counter'),
        ),
        migrations.AddIndex(
            model_name='memberllmbudgetpolicy',
            index=models.Index(fields=['workteam_id', 'is_active'], name='services_bi_worktea_1c6f5d_idx'),
        ),
        migrations.AddConstraint(
            model_name='memberllmbudgetpolicy',
            constraint=models.UniqueConstraint(fields=('workteam_id', 'user_id', 'target_role'), name='uniq_member_budget_policy'),
        ),
    ]
