# Generated by Django 4.2.7 on 2026-04-07 16:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_member_budget_control'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberllmbudgetpolicy',
            options={'verbose_name': '成员预算策略', 'verbose_name_plural': '成员预算策略'},
        ),
        migrations.AlterModelOptions(
            name='memberllmusagecounter',
            options={'verbose_name': '成员用量计数器', 'verbose_name_plural': '成员用量计数器'},
        ),
        migrations.AlterField(
            model_name='memberllmbudgetpolicy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='memberllmbudgetpolicy',
            name='daily_credits_limit',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='NULL 表示不限', max_digits=12, null=True, verbose_name='日度点券上限'),
        ),
        migrations.AlterField(
            model_name='memberllmbudgetpolicy',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='memberllmbudgetpolicy',
            name='max_model_tier',
            field=models.CharField(choices=[('standard', '标准'), ('premium', '高级'), ('enterprise', '不限')], default='enterprise', help_text='允许使用的最高模型等级', max_length=20, verbose_name='最高模型等级'),
        ),
        migrations.AlterField(
            model_name='memberllmbudgetpolicy',
            name='monthly_credits_limit',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='NULL 表示不限', max_digits=12, null=True, verbose_name='月度点券上限'),
        ),
        migrations.AlterField(
            model_name='memberllmbudgetpolicy',
            name='target_role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='__default__', help_text="具体角色（角色策略），或 '__default__'（默认策略/个人策略）", max_length=20, verbose_name='目标角色'),
        ),
        migrations.AlterField(
            model_name='memberllmbudgetpolicy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='memberllmbudgetpolicy',
            name='user_id',
            field=models.CharField(db_index=True, default='__default__', help_text="具体用户 ID，或 '__default__' 表示角色/默认策略", max_length=36, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='memberllmbudgetpolicy',
            name='workteam_id',
            field=models.CharField(db_index=True, max_length=100, verbose_name='工作团队ID'),
        ),
        migrations.AlterField(
            model_name='memberllmusagecounter',
            name='consumed_credits',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20, verbose_name='已消耗点券'),
        ),
        migrations.AlterField(
            model_name='memberllmusagecounter',
            name='cycle_date',
            field=models.DateField(help_text='月度=月首日, 日度=当天', verbose_name='周期日期'),
        ),
        migrations.AlterField(
            model_name='memberllmusagecounter',
            name='cycle_type',
            field=models.CharField(choices=[('monthly', '月度'), ('daily', '日度')], max_length=10, verbose_name='周期类型'),
        ),
        migrations.AlterField(
            model_name='memberllmusagecounter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='memberllmusagecounter',
            name='user_id',
            field=models.CharField(max_length=36, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='memberllmusagecounter',
            name='workteam_id',
            field=models.CharField(max_length=100, verbose_name='工作团队ID'),
        ),
    ]
