# Generated by Django 4.2.7 on 2026-04-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_show_per_message_cost_default_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberllmbudgetpolicy',
            name='target_role',
            field=models.CharField(default='__default__', help_text="具体角色（角色策略），或 '__default__'（默认策略/个人策略）。合法角色由 ROLE_CHOICES 定义，API 层校验。", max_length=20, verbose_name='目标角色'),
        ),
    ]
