# Generated by Django 4.2.7 on 2026-05-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0024_fix_collation_utf8mb4_unicode_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingruntimeconfig',
            name='fail_open_24h_block_threshold',
            field=models.IntegerField(default=50, help_text='单 workteam 在 24 小时内 fail-open 累计超过此次数后自动冻结服务', verbose_name='Fail-open 24h 阻断阈值'),
        ),
        migrations.AddField(
            model_name='billingruntimeconfig',
            name='internal_llm_call_balance_guard_floor',
            field=models.IntegerField(default=500, help_text='与百分比取 max，避免低余额时误杀基础记忆功能', verbose_name='内部 LLM 调用余额守护下限（点券）'),
        ),
        migrations.AddField(
            model_name='billingruntimeconfig',
            name='internal_llm_call_balance_guard_pct',
            field=models.IntegerField(default=20, help_text='internal_llm_call 一小时累计成本超过 max(余额×此百分比, floor) 时强制阻断', verbose_name='内部 LLM 调用余额守护百分比'),
        ),
        migrations.AddField(
            model_name='billingruntimeconfig',
            name='large_charge_review_threshold_credits',
            field=models.IntegerField(default=1000, help_text='单次扣费超过此值进入待审核，不直接扣款', verbose_name='大额扣费审核阈值（点券）'),
        ),
        migrations.AddField(
            model_name='billingruntimeconfig',
            name='sync_charge_threshold_credits',
            field=models.IntegerField(default=100, help_text='单次预期金额 ≥ 此值走同步扣款，否则进入异步聚合', verbose_name='同步扣款阈值（点券）'),
        ),
        migrations.AddField(
            model_name='billingusageevent',
            name='aggregation_key',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='聚合批次ID'),
        ),
        migrations.AddField(
            model_name='billingusageevent',
            name='charge_status',
            field=models.CharField(choices=[('charged', '已同步扣款'), ('pending', '待聚合'), ('aggregated', '已聚合扣款'), ('failed', '扣款失败')], db_index=True, default='charged', max_length=20, verbose_name='扣款状态'),
        ),
        migrations.AddField(
            model_name='billingusageevent',
            name='charged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实际扣款时间'),
        ),
        migrations.AddIndex(
            model_name='billingusageevent',
            index=models.Index(fields=['charge_status', 'created_at'], name='services_bi_charge__024d45_idx'),
        ),
    ]
