# Generated by Django 4.2.7 on 2026-07-07 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0032_workteam_credit_ledger'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='workteamcreditledger',
                    new_name='services_bi_worktea_e8831e_idx',
                    old_name='services_bi_worktea_5df6e4_idx',
                ),
                migrations.RenameIndex(
                    model_name='workteamcreditledger',
                    new_name='services_bi_user_id_427567_idx',
                    old_name='services_bi_user_id_13cb56_idx',
                ),
                migrations.RenameIndex(
                    model_name='workteamcreditledger',
                    new_name='services_bi_ledger__5378c4_idx',
                    old_name='services_bi_ledger__f21e21_idx',
                ),
                migrations.RenameIndex(
                    model_name='workteamcreditledger',
                    new_name='services_bi_related_08377f_idx',
                    old_name='services_bi_related_7ea87e_idx',
                ),
                migrations.RenameIndex(
                    model_name='workteamcreditledger',
                    new_name='services_bi_related_49764c_idx',
                    old_name='services_bi_related_8a50e4_idx',
                ),
            ],
        ),
    ]
