# Generated by Django 4.2.7 on 2026-07-07 22:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0034_rename_workteam_to_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingbudgetpolicy',
            options={'ordering': ['organization_id'], 'verbose_name': '用量预算策略', 'verbose_name_plural': '用量预算策略'},
        ),
        migrations.AlterModelOptions(
            name='organizationaddonentitlement',
            options={'ordering': ['-expires_at', '-created_at'], 'verbose_name': '组织增值包权益', 'verbose_name_plural': '组织增值包权益'},
        ),
        migrations.AlterModelOptions(
            name='organizationbillingentitlement',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name': '组织计费权益', 'verbose_name_plural': '组织计费权益'},
        ),
        migrations.AlterModelOptions(
            name='organizationbillingpolicy',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name': '组织计费策略', 'verbose_name_plural': '组织计费策略'},
        ),
        migrations.AlterModelOptions(
            name='organizationcreditledger',
            options={'ordering': ['-created_at'], 'verbose_name': '组织点券流水', 'verbose_name_plural': '组织点券流水'},
        ),
        migrations.AlterModelOptions(
            name='organizationlifecyclecleanupjob',
            options={'ordering': ['status', 'next_retry_at', '-updated_at'], 'verbose_name': '组织生命周期清理作业', 'verbose_name_plural': '组织生命周期清理作业'},
        ),
        migrations.AlterModelOptions(
            name='organizationllmmonthlybudget',
            options={'ordering': ['-cycle_month', '-updated_at'], 'verbose_name': '组织LLM月预算', 'verbose_name_plural': '组织LLM月预算'},
        ),
        migrations.AlterModelOptions(
            name='organizationservicepolicy',
            options={'verbose_name': '组织服务策略', 'verbose_name_plural': '组织服务策略'},
        ),
        migrations.AlterModelOptions(
            name='organizationstoragesubscription',
            options={'ordering': ['-end_at', '-created_at'], 'verbose_name': '组织存储订阅', 'verbose_name_plural': '组织存储订阅'},
        ),
        migrations.AlterModelOptions(
            name='organizationstorageusage',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name': '组织附件空间使用', 'verbose_name_plural': '组织附件空间使用'},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='billinganomalyalert',
                    new_name='services_bi_organiz_7f6499_idx',
                    old_name='services_bi_worktea_83a05f_idx',
                ),
                migrations.RenameIndex(
                    model_name='billinginvoice',
                    new_name='services_bi_organiz_138b6c_idx',
                    old_name='services_bi_worktea_1bbe36_idx',
                ),
                migrations.RenameIndex(
                    model_name='billinginvoiceline',
                    new_name='services_bi_organiz_b635d3_idx',
                    old_name='services_bi_worktea_088cad_idx',
                ),
                migrations.RenameIndex(
                    model_name='billingusagedaily',
                    new_name='services_bi_organiz_8010a2_idx',
                    old_name='services_bi_worktea_2e43b2_idx',
                ),
                migrations.RenameIndex(
                    model_name='billingusagedaily',
                    new_name='services_bi_organiz_274f6e_idx',
                    old_name='services_bi_worktea_bb4e2c_idx',
                ),
                migrations.RenameIndex(
                    model_name='billingusageevent',
                    new_name='services_bi_organiz_fcef4a_idx',
                    old_name='services_bi_worktea_64e75d_idx',
                ),
                migrations.RenameIndex(
                    model_name='billingusageevent',
                    new_name='services_bi_organiz_20c5ce_idx',
                    old_name='services_bi_worktea_8cf61c_idx',
                ),
                migrations.RenameIndex(
                    model_name='memberllmbudgetpolicy',
                    new_name='services_bi_organiz_ff029c_idx',
                    old_name='services_bi_worktea_1c6f5d_idx',
                ),
                migrations.RenameIndex(
                    model_name='memberllmusagecounter',
                    new_name='services_bi_organiz_9b2a92_idx',
                    old_name='services_bi_worktea_48a661_idx',
                ),
                migrations.RenameIndex(
                    model_name='meterpricing',
                    new_name='services_bi_meter_k_1b8e2a_idx',
                    old_name='services_bi_meter_k_b82b23_idx',
                ),
                migrations.RenameIndex(
                    model_name='organizationaddonentitlement',
                    new_name='services_bi_organiz_96cecf_idx',
                    old_name='services_bi_worktea_051f46_idx',
                ),
                migrations.RenameIndex(
                    model_name='organizationaddonentitlement',
                    new_name='services_bi_organiz_9454b8_idx',
                    old_name='services_bi_worktea_fa528e_idx',
                ),
                migrations.RenameIndex(
                    model_name='organizationaddonentitlement',
                    new_name='services_bi_starts__7d90d4_idx',
                    old_name='services_bi_starts__00e5eb_idx',
                ),
                migrations.RenameIndex(
                    model_name='organizationbillingentitlement',
                    new_name='services_bi_organiz_5a3f40_idx',
                    old_name='services_bi_worktea_820c7b_idx',
                ),
                migrations.RenameIndex(
                    model_name='organizationbillingentitlement',
                    new_name='services_bi_effecti_52e8de_idx',
                    old_name='services_bi_effecti_b79a20_idx',
                ),
                migrations.RenameIndex(
                    model_name='organizationbillingpolicy',
                    new_name='services_bi_organiz_f59f03_idx',
                    old_name='services_bi_worktea_9de6ea_idx',
                ),
                migrations.RenameIndex(
                    model_name='organizationcreditledger',
                    new_name='services_bi_organiz_0377e3_idx',
                    old_name='services_bi_worktea_e8831e_idx',
                ),
                migrations.RenameIndex(
                    model_name='organizationcreditledger',
                    new_name='services_bi_user_id_60064a_idx',
                    old_name='services_bi_user_id_427567_idx',
                ),
                migrations.RenameIndex(
                    model_name='organizationcreditledger',
                    new_name='services_bi_ledger__7abcce_idx',
                    old_name='services_bi_ledger__5378c4_idx',
                ),
                migrations.RenameIndex(
                    model_name='organizationcreditledger',
                    new_name='services_bi_related_97708d_idx',
                    old_name='services_bi_related_08377f_idx',
                ),
                migrations.RenameIndex(
                    model_name='organizationcreditledger',
                    new_name='services_bi_related_7eab51_idx',
                    old_name='services_bi_related_49764c_idx',
                ),
                migrations.RenameIndex(
                    model_name='organizationllmmonthlybudget',
                    new_name='services_bi_organiz_4504a4_idx',
                    old_name='services_bi_worktea_3dbf4e_idx',
                ),
                migrations.RenameIndex(
                    model_name='organizationstoragesubscription',
                    new_name='services_bi_organiz_f0ec2c_idx',
                    old_name='services_bi_worktea_8fbeb4_idx',
                ),
                migrations.RenameIndex(
                    model_name='organizationstoragesubscription',
                    new_name='services_bi_organiz_60fe4a_idx',
                    old_name='services_bi_worktea_b25e60_idx',
                ),
                migrations.RenameIndex(
                    model_name='organizationstorageusage',
                    new_name='services_bi_organiz_580fb6_idx',
                    old_name='services_bi_worktea_bc1a55_idx',
                ),
                migrations.RenameIndex(
                    model_name='organizationstorageusage',
                    new_name='services_bi_active__ba2834_idx',
                    old_name='services_bi_active__53e7c1_idx',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='billingadminauditlog',
            name='organization_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='billinganomalyalert',
            name='organization_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='billingbudgetpolicy',
            name='organization_id',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='billingdispute',
            name='organization_id',
            field=models.CharField(db_index=True, max_length=100, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='billinginvoice',
            name='organization_id',
            field=models.CharField(db_index=True, max_length=100, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='billinginvoiceline',
            name='organization_id',
            field=models.CharField(db_index=True, max_length=100, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='billingreconciliationreport',
            name='organization_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='空=全局汇总', max_length=100, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='billingruntimeconfig',
            name='fail_open_24h_block_threshold',
            field=models.IntegerField(default=50, help_text='单 organization 在 24 小时内 fail-open 累计超过此次数后自动冻结服务', verbose_name='Fail-open 24h 阻断阈值'),
        ),
        migrations.AlterField(
            model_name='billingruntimeconfig',
            name='min_balance_threshold',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.01'), help_text='组织可用余额低于此值时阻断 LLM 调用', max_digits=10, verbose_name='余额放行最低阈值（点券）'),
        ),
        migrations.AlterField(
            model_name='billingusagedaily',
            name='organization_id',
            field=models.CharField(db_index=True, max_length=100, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='billingusageevent',
            name='organization_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='memberllmbudgetpolicy',
            name='organization_id',
            field=models.CharField(db_index=True, max_length=100, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='memberllmusagecounter',
            name='organization_id',
            field=models.CharField(max_length=100, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='meterpricing',
            name='organization_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='meterpricing',
            name='scope',
            field=models.CharField(choices=[('global', '全局'), ('organization', '组织')], db_index=True, default='global', max_length=20, verbose_name='作用域'),
        ),
        migrations.AlterField(
            model_name='organizationaddonentitlement',
            name='organization_id',
            field=models.CharField(db_index=True, max_length=100, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='organizationbillingentitlement',
            name='organization_id',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='organizationbillingpolicy',
            name='organization_id',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='organizationcreditledger',
            name='organization_id',
            field=models.CharField(db_index=True, max_length=100, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='organizationlifecyclecleanupjob',
            name='organization_id',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='organizationlifecyclecleanupjob',
            name='trigger_source',
            field=models.CharField(db_index=True, default='organization_delete', max_length=50, verbose_name='触发来源'),
        ),
        migrations.AlterField(
            model_name='organizationllmmonthlybudget',
            name='organization_id',
            field=models.CharField(db_index=True, max_length=100, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='organizationservicepolicy',
            name='organization_id',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='organizationstoragesubscription',
            name='organization_id',
            field=models.CharField(db_index=True, max_length=100, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='organizationstorageusage',
            name='organization_id',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='组织ID'),
        ),
    ]
