# Generated by Django 4.2.7 on 2026-07-09
#
# LLM 计费改造：只扣点券（月度配额 + 自动补充），用尽即停。
# 1. OrganizationBillingPolicy 新增自动补充 4 字段，llm_billing_mode 默认改 quota_only；
# 2. 数据迁移：存量组织策略全部切到 quota_only（含 quota_then_paygo / paygo_only），
#    自动补充默认关闭，由管理员在「AI 服务开关」页自助开启。
#
# topup_credits 已由 0036_organization_llm_budget_topup_default 落库，本迁移不再重复 AddField。
#
# 注：makemigrations 同时检出了一批 verbose_name/Meta 级别的历史 drift（与本任务无关），
# 已从本迁移剔除，避免污染 diff；该 drift 待独立收口。

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


def _auto_topup_fields():
    return [
        (
            "auto_topup_enabled",
            models.BooleanField(default=False, verbose_name="LLM点券自动补充开关"),
        ),
        (
            "auto_topup_credits",
            models.DecimalField(
                decimal_places=8,
                default=Decimal("1000"),
                max_digits=20,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="每次自动补充量（credits）",
            ),
        ),
        (
            "auto_topup_threshold_credits",
            models.DecimalField(
                decimal_places=8,
                default=Decimal("0"),
                max_digits=20,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="自动补充触发阈值（配额剩余低于此值时触发）",
            ),
        ),
        (
            "auto_topup_monthly_cap_credits",
            models.DecimalField(
                decimal_places=8,
                default=Decimal("10000"),
                max_digits=20,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="每月自动补充上限（credits）",
            ),
        ),
    ]


def ensure_auto_topup_columns(apps, schema_editor):
    """补齐缺失列，兼容历史热修已提前创建部分或全部列的数据库。"""
    organization_billing_policy = apps.get_model("billing", "OrganizationBillingPolicy")
    table_name = organization_billing_policy._meta.db_table
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        existing_columns = {
            column.name
            for column in connection.introspection.get_table_description(cursor, table_name)
        }

    for field_name, field in _auto_topup_fields():
        if field_name in existing_columns:
            continue
        field.set_attributes_from_name(field_name)
        schema_editor.add_field(organization_billing_policy, field)


def forwards_set_quota_only(apps, schema_editor):
    """存量组织策略统一切换到 quota_only（用尽即停）。"""
    OrganizationBillingPolicy = apps.get_model("billing", "OrganizationBillingPolicy")
    OrganizationBillingPolicy.objects.exclude(llm_billing_mode="quota_only").update(
        llm_billing_mode="quota_only",
    )


def backwards_noop(apps, schema_editor):
    """不可精确回滚（原模式已丢失），保留 quota_only。"""


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0036_organization_llm_budget_topup_default'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(ensure_auto_topup_columns, backwards_noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="organizationbillingpolicy",
                    name="auto_topup_enabled",
                    field=models.BooleanField(
                        default=False,
                        verbose_name="LLM点券自动补充开关",
                    ),
                ),
                migrations.AddField(
                    model_name="organizationbillingpolicy",
                    name="auto_topup_credits",
                    field=models.DecimalField(
                        decimal_places=8,
                        default=Decimal("1000"),
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="每次自动补充量（credits）",
                    ),
                ),
                migrations.AddField(
                    model_name="organizationbillingpolicy",
                    name="auto_topup_threshold_credits",
                    field=models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0"),
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="自动补充触发阈值（配额剩余低于此值时触发）",
                    ),
                ),
                migrations.AddField(
                    model_name="organizationbillingpolicy",
                    name="auto_topup_monthly_cap_credits",
                    field=models.DecimalField(
                        decimal_places=8,
                        default=Decimal("10000"),
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="每月自动补充上限（credits）",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='organizationbillingpolicy',
            name='llm_billing_mode',
            field=models.CharField(choices=[('quota_then_paygo', '预算优先后按量'), ('paygo_only', '仅按量'), ('quota_only', '仅预算')], default='quota_only', max_length=40, verbose_name='LLM计费模式'),
        ),
        migrations.RunPython(forwards_set_quota_only, backwards_noop),
    ]
