# Generated by Django 4.2.7 on 2026-07-29

from decimal import Decimal
import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabtinspace", "0134_workspace_default_full_access_8004"),
        ("billing", "0040_billingusageevent_attempt_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderCreditCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=100, unique=True, verbose_name="活动编码"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="活动名称")),
                (
                    "provider_key",
                    models.CharField(max_length=64, verbose_name="供应商稳定标识"),
                ),
                (
                    "eligible_model_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text=(
                            "空数组表示该 provider 下全部模型可用；"
                            "非空时按模型 UUID 精确匹配。"
                        ),
                        verbose_name="可用模型UUID",
                    ),
                ),
                (
                    "credits_amount",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="单次发放额度",
                    ),
                ),
                (
                    "total_budget_credits",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="活动总预算",
                    ),
                ),
                (
                    "granted_credits",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0"),
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="已发放额度",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("active", "生效"),
                            ("paused", "暂停"),
                            ("ended", "结束"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "start_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="开始时间",
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="结束时间",
                    ),
                ),
                (
                    "expire_days",
                    models.PositiveIntegerField(
                        default=30,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="发放后有效天数",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="扩展元数据",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "供应商额度活动",
                "verbose_name_plural": "供应商额度活动",
                "db_table": "services_billing_provider_credit_campaign",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProviderCreditGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider_key",
                    models.CharField(
                        max_length=64,
                        verbose_name="供应商稳定标识快照",
                    ),
                ),
                (
                    "eligible_model_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="可用模型UUID快照",
                    ),
                ),
                (
                    "total_credits",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="发放总额",
                    ),
                ),
                (
                    "consumed_credits",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0"),
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="已消费额度",
                    ),
                ),
                (
                    "remaining_credits",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="可用余额",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "可用"),
                            ("exhausted", "已用尽"),
                            ("expired", "已过期"),
                            ("revoked", "已撤销"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "grant_source",
                    models.CharField(
                        choices=[
                            ("campaign", "活动"),
                            ("admin", "管理员"),
                            ("membership", "会员权益"),
                        ],
                        default="campaign",
                        max_length=20,
                        verbose_name="发放来源",
                    ),
                ),
                (
                    "effective_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="生效时间",
                    ),
                ),
                (
                    "expire_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="过期时间",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="扩展元数据",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grants",
                        to="billing.providercreditcampaign",
                        verbose_name="活动",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_column="organization_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provider_credit_grants",
                        to="tabtinspace.organization",
                        verbose_name="组织",
                    ),
                ),
            ],
            options={
                "verbose_name": "供应商额度发放",
                "verbose_name_plural": "供应商额度发放",
                "db_table": "services_billing_provider_credit_grant",
                "ordering": ["expire_at", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProviderCreditTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("grant", "发放"),
                            ("consume", "消费"),
                            ("expire", "过期"),
                            ("refund", "退款"),
                            ("adjust", "调整"),
                        ],
                        max_length=20,
                        verbose_name="流水类型",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="发放/退款为正，消费/过期为负，调整可正可负。",
                        max_digits=20,
                        verbose_name="余额变动",
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="变动后余额",
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="关联类型",
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="关联ID",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="幂等键",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="扩展元数据",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "grant",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="billing.providercreditgrant",
                        verbose_name="发放批次",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_column="organization_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provider_credit_transactions",
                        to="tabtinspace.organization",
                        verbose_name="组织",
                    ),
                ),
            ],
            options={
                "verbose_name": "供应商额度流水",
                "verbose_name_plural": "供应商额度流水",
                "db_table": "services_billing_provider_credit_transaction",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="providercreditcampaign",
            index=models.Index(
                fields=["provider_key", "status"],
                name="pcred_camp_prov_status_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="providercreditcampaign",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("credits_amount__gte", 0),
                    ("total_budget_credits__gte", 0),
                    ("granted_credits__gte", 0),
                ),
                name="provider_credit_campaign_amounts_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="providercreditcampaign",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("granted_credits__lte", models.F("total_budget_credits"))
                ),
                name="provider_credit_campaign_granted_within_budget",
            ),
        ),
        migrations.AddConstraint(
            model_name="providercreditcampaign",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("end_at__isnull", True),
                    ("end_at__gt", models.F("start_at")),
                    _connector="OR",
                ),
                name="provider_credit_campaign_valid_window",
            ),
        ),
        migrations.AddIndex(
            model_name="providercreditgrant",
            index=models.Index(
                fields=["organization", "status"],
                name="pcredit_grant_org_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="providercreditgrant",
            index=models.Index(
                fields=["provider_key", "status"],
                name="pcred_grant_prov_stat_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="providercreditgrant",
            index=models.Index(
                fields=["expire_at"],
                name="pcredit_grant_expire_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="providercreditgrant",
            constraint=models.UniqueConstraint(
                fields=("organization", "campaign"),
                name="uniq_provider_credit_grant_org_campaign",
            ),
        ),
        migrations.AddConstraint(
            model_name="providercreditgrant",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("total_credits__gte", 0),
                    ("consumed_credits__gte", 0),
                    ("remaining_credits__gte", 0),
                ),
                name="provider_credit_grant_balances_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="providercreditgrant",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("expire_at__isnull", True),
                    ("expire_at__gt", models.F("effective_at")),
                    _connector="OR",
                ),
                name="provider_credit_grant_valid_window",
            ),
        ),
        migrations.AddIndex(
            model_name="providercredittransaction",
            index=models.Index(
                fields=["grant"],
                name="pcredit_tx_grant_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="providercredittransaction",
            index=models.Index(
                fields=["created_at"],
                name="pcredit_tx_created_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="providercredittransaction",
            constraint=models.CheckConstraint(
                check=models.Q(("balance_after__gte", 0)),
                name="provider_credit_transaction_balance_nonnegative",
            ),
        ),
    ]
