# Generated by Django 4.2.7 on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0041_provider_credit_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="providercreditcampaign",
            name="enabled",
            field=models.BooleanField(
                db_index=True,
                default=True,
                verbose_name="是否允许发放",
            ),
        ),
        migrations.AddField(
            model_name="providercreditcampaign",
            name="membership_plan_codes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="仅匹配 MembershipTier.tier_type；禁止使用展示名称。",
                verbose_name="适用会员套餐编码",
            ),
        ),
        migrations.AddField(
            model_name="providercreditcampaign",
            name="trigger_type",
            field=models.CharField(
                choices=[
                    ("manual", "手动"),
                    ("new_org", "新组织"),
                    ("membership", "会员权益"),
                ],
                db_index=True,
                default="manual",
                max_length=20,
                verbose_name="自动发放触发类型",
            ),
        ),
        migrations.AddIndex(
            model_name="providercreditcampaign",
            index=models.Index(
                fields=["trigger_type", "enabled", "status"],
                name="pcred_camp_trigger_idx",
            ),
        ),
    ]
