# Generated by Django 4.2.7 on 2026-08-07 06:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0045_reconcile_unpublished_auto_topup_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationcreditledger',
            options={'ordering': ['-created_at'], 'verbose_name': '组织credits流水', 'verbose_name_plural': '组织credits流水'},
        ),
        migrations.AlterField(
            model_name='billingbudgetpolicy',
            name='budget_limit_credits',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, help_text='XM-16: 与 included_credits 解耦的独立预算上限。设置后优先使用此值作为预算告警分母，解决 free tier included=0 时预算告警永不触发的问题。', max_digits=16, null=True, verbose_name='显式预算上限(credits)'),
        ),
        migrations.AlterField(
            model_name='billingruntimeconfig',
            name='credits_per_yuan',
            field=models.IntegerField(default=100, help_text='1 元 = N credits，影响冻结金额预估和前端费用展示', verbose_name='credits/元换算比例'),
        ),
        migrations.AlterField(
            model_name='billingruntimeconfig',
            name='failopen_max_credits',
            field=models.DecimalField(decimal_places=4, default=Decimal('10'), help_text='fail-open 期间允许的最大累计放行金额', max_digits=10, verbose_name='Fail-open 累计金额上限（credits）'),
        ),
        migrations.AlterField(
            model_name='billingruntimeconfig',
            name='freeze_fallback_credits',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.5'), help_text='首轮或无法估算时的保底冻结金额', max_digits=10, verbose_name='冻结保底金额（credits）'),
        ),
        migrations.AlterField(
            model_name='billingruntimeconfig',
            name='internal_llm_call_balance_guard_floor',
            field=models.IntegerField(default=500, help_text='与百分比取 max，避免低余额时误杀基础记忆功能', verbose_name='内部 LLM 调用余额守护下限（credits）'),
        ),
        migrations.AlterField(
            model_name='billingruntimeconfig',
            name='large_charge_review_threshold_credits',
            field=models.IntegerField(default=1000, help_text='单次扣费超过此值进入待审核，不直接扣款', verbose_name='大额扣费审核阈值（credits）'),
        ),
        migrations.AlterField(
            model_name='billingruntimeconfig',
            name='min_balance_threshold',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.01'), help_text='组织可用余额低于此值时阻断 LLM 调用', max_digits=10, verbose_name='余额放行最低阈值（credits）'),
        ),
        migrations.AlterField(
            model_name='billingruntimeconfig',
            name='show_per_message_cost',
            field=models.BooleanField(default=True, help_text='是否在前端 assistant 消息气泡上展示本条消息消耗的 credits 数。PRD-04 Wave 5：默认 True（透明承诺），管理员可按需关闭。', verbose_name='展示每条消息费用'),
        ),
        migrations.AlterField(
            model_name='billingruntimeconfig',
            name='sync_charge_threshold_credits',
            field=models.IntegerField(default=100, help_text='单次预期金额 ≥ 此值走同步扣款，否则进入异步聚合', verbose_name='同步扣款阈值（credits）'),
        ),
        migrations.AlterField(
            model_name='memberllmbudgetpolicy',
            name='daily_credits_limit',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='NULL 表示不限', max_digits=12, null=True, verbose_name='日度 credits 上限'),
        ),
        migrations.AlterField(
            model_name='memberllmbudgetpolicy',
            name='monthly_credits_limit',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='NULL 表示不限', max_digits=12, null=True, verbose_name='月度 credits 上限'),
        ),
        migrations.AlterField(
            model_name='memberllmusagecounter',
            name='consumed_credits',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20, verbose_name='已消耗 credits'),
        ),
        migrations.AlterField(
            model_name='organizationbillingentitlement',
            name='included_llm_credits_monthly',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='每月赠送LLM额度（credits）'),
        ),
        migrations.AlterField(
            model_name='organizationcreditledger',
            name='amount_points',
            field=models.DecimalField(decimal_places=4, help_text='正数=增加，负数=扣减', max_digits=20, verbose_name='变动 credits'),
        ),
        migrations.AlterField(
            model_name='organizationcreditledger',
            name='balance_after_points',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='变更后余额（credits）'),
        ),
        migrations.AlterField(
            model_name='organizationllmmonthlybudget',
            name='consumed_credits',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='已消耗预算（credits）'),
        ),
        migrations.AlterField(
            model_name='organizationllmmonthlybudget',
            name='included_credits',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='月度预算总额（credits）'),
        ),
    ]
