# Generated by Django 4.2.7 on 2026-08-19 11:49

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tabtinspace', '0145_shared_resource_placement_dismissed'),
        ('wallet', '0023_cash_transaction_membership_lifecycle_type'),
        ('billing', '0046_alter_organizationcreditledger_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=36, verbose_name='用户ID')),
                ('logical_search_invocation_id', models.UUIDField(verbose_name='逻辑搜索调用ID')),
                ('request_fingerprint', models.CharField(max_length=64, verbose_name='请求指纹')),
                ('fingerprint_version', models.CharField(max_length=32, verbose_name='指纹版本')),
                ('meter_key', models.CharField(db_index=True, max_length=200, verbose_name='计量项')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='数量')),
                ('unit', models.CharField(default='request', max_length=40, verbose_name='单位')),
                ('unit_price', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='冻结单价')),
                ('total_credits', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='冻结总点券')),
                ('funding_mode', models.CharField(max_length=40, verbose_name='资金模式快照')),
                ('provider_key', models.CharField(blank=True, default='', max_length=100, verbose_name='搜索渠道')),
                ('biz_type', models.CharField(blank=True, default='', max_length=60, verbose_name='业务类型')),
                ('thread_id', models.CharField(blank=True, default='', max_length=128, verbose_name='会话ID')),
                ('status', models.CharField(choices=[('reserved', '已预留'), ('executing', '执行中'), ('settlement_pending', '待结算'), ('committed', '已结算'), ('released', '已释放'), ('expired', '未执行过期'), ('unknown', '结果未知')], db_index=True, default='reserved', max_length=32, verbose_name='状态')),
                ('generation', models.PositiveIntegerField(default=1, verbose_name='执行代次')),
                ('reserved_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='预留时间')),
                ('lease_expires_at', models.DateTimeField(db_index=True, verbose_name='租约到期时间')),
                ('execution_started_at', models.DateTimeField(blank=True, null=True, verbose_name='执行开始时间')),
                ('provider_finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Provider完成时间')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='结算时间')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='释放时间')),
                ('result_reference', models.CharField(blank=True, default='', max_length=255, verbose_name='结果引用')),
                ('result_metadata', models.JSONField(blank=True, default=dict, verbose_name='安全结果元数据')),
                ('first_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='首次异常时间')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='最近核查时间')),
                ('next_recovery_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='下次恢复时间')),
                ('recovery_attempt_count', models.PositiveIntegerField(default=0, verbose_name='恢复次数')),
                ('resolution_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='处置原因')),
                ('resolved_by', models.CharField(blank=True, default='', max_length=100, verbose_name='处置人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tabtinspace.organization', verbose_name='计费组织')),
                ('pricing_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.meterpricing', verbose_name='定价规则快照来源')),
            ],
            options={
                'verbose_name': '计费预留',
                'verbose_name_plural': '计费预留',
                'db_table': 'services_billing_reservation',
            },
        ),
        migrations.AddField(
            model_name='organizationllmmonthlybudget',
            name='active_reserved_credits',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='已被 BillingReservation 冻结、尚未结算的月度额度。', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='活跃预留预算（credits）'),
        ),
        migrations.AddField(
            model_name='providercreditgrant',
            name='active_reserved_credits',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='尚未结算的 BillingReservation 预留额度；不改变 remaining_credits。', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='活跃预留额度'),
        ),
        migrations.AddConstraint(
            model_name='providercreditgrant',
            constraint=models.CheckConstraint(check=models.Q(('active_reserved_credits__gte', 0)), name='pcred_reserved_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='providercreditgrant',
            constraint=models.CheckConstraint(check=models.Q(('active_reserved_credits__lte', models.F('remaining_credits'))), name='pcred_reserved_lte_remaining'),
        ),
        migrations.AddConstraint(
            model_name='organizationllmmonthlybudget',
            constraint=models.CheckConstraint(check=models.Q(('active_reserved_credits__gte', 0)), name='llmbudget_reserved_nonneg'),
        ),
        migrations.CreateModel(
            name='BillingReservationAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(db_index=True, max_length=40, verbose_name='资金来源')),
                ('source_reference', models.CharField(max_length=255, verbose_name='来源引用')),
                ('credits', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='冻结点券')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='资金快照')),
                ('status', models.CharField(choices=[('reserved', '已预留'), ('committed', '已结算'), ('released', '已释放')], db_index=True, default='reserved', max_length=20)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monthly_budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.organizationllmmonthlybudget')),
                ('organization_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wallet.organizationwallet')),
                ('provider_credit_grant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.providercreditgrant')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='billing.billingreservation', verbose_name='计费预留')),
            ],
            options={
                'db_table': 'services_billing_reservation_allocation',
            },
        ),
        migrations.CreateModel(
            name='ProviderAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_key', models.CharField(max_length=100, verbose_name='Provider')),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('generation', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('started', '已开始'), ('succeeded', '成功'), ('failed', '明确失败'), ('unknown', '结果未知')], db_index=True, default='started', max_length=20)),
                ('provider_request_id', models.CharField(blank=True, default='', max_length=255)),
                ('error_code', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_attempts', to='billing.billingreservation')),
            ],
            options={
                'db_table': 'services_billing_provider_attempt',
                'indexes': [models.Index(fields=['reservation', 'outcome'], name='bill_prov_attempt_out_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='providerattempt',
            constraint=models.UniqueConstraint(fields=('reservation', 'generation', 'attempt_number'), name='uniq_provider_attempt_res_generation_number'),
        ),
        migrations.AddIndex(
            model_name='billingreservationallocation',
            index=models.Index(fields=['reservation', 'status'], name='bill_res_alloc_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='billingreservationallocation',
            constraint=models.UniqueConstraint(fields=('reservation', 'source_type', 'source_reference'), name='uniq_billing_reservation_allocation_source'),
        ),
        migrations.AddIndex(
            model_name='billingreservation',
            index=models.Index(fields=['status', 'lease_expires_at'], name='bill_res_status_lease_idx'),
        ),
        migrations.AddIndex(
            model_name='billingreservation',
            index=models.Index(fields=['status', 'next_recovery_at'], name='bill_res_status_recover_idx'),
        ),
        migrations.AddIndex(
            model_name='billingreservation',
            index=models.Index(fields=['organization', 'created_at'], name='bill_res_org_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='billingreservation',
            constraint=models.UniqueConstraint(fields=('organization', 'logical_search_invocation_id'), name='uniq_billing_reservation_org_search_invocation'),
        ),
    ]
