import { act, renderHook } from '@testing-library/react'
import { describe, expect, it, vi } from 'vitest'
import {
  useLoginForm,
  useRegisterForm,
} from '../../../../../packages/tabtin-shared/src/auth-forms/index'

const translations = {
  'zh-CN': {
    'loginForm.errors.sendCodeFailed': '发送验证码失败',
    'loginForm.errors.phoneInvalid': '请输入有效的手机号',
    'loginForm.errors.codeInvalid': '验证码应为6位数字',
    'loginForm.errors.codeRequired': '请输入验证码',
    'registerForm.errors.phoneInvalid': '请输入有效的手机号',
    'registerForm.errors.sendCodeFailed': '发送验证码失败',
    'registerForm.errors.passwordNoWhitespace': '密码不能包含空格，已将空格过滤',
    'registerForm.errors.passwordNoCjk': '密码不能包含中日韩文字，请勿粘贴其他内容',
  },
  'en-US': {
    'loginForm.errors.sendCodeFailed': 'Failed to send code',
    'loginForm.errors.phoneInvalid': 'Please enter a valid phone number',
    'loginForm.errors.codeInvalid': 'Code should be 6 digits',
    'loginForm.errors.codeRequired': 'Please enter verification code',
    'registerForm.errors.phoneInvalid': 'Please enter a valid phone number',
    'registerForm.errors.sendCodeFailed': 'Failed to send code',
    'registerForm.errors.passwordNoWhitespace':
      'Password cannot contain spaces; spaces have been removed',
    'registerForm.errors.passwordNoCjk':
      'Password cannot contain CJK characters; do not paste other content',
  },
} as const

type TestLanguage = keyof typeof translations

function createTranslate(getLanguage: () => TestLanguage) {
  return (key: string, options?: Record<string, unknown>): string => {
    const translated = translations[getLanguage()][key as keyof typeof translations[TestLanguage]]
    if (translated) return translated
    if (typeof options?.defaultValue === 'string') return options.defaultValue
    return key
  }
}

function submitEvent(): React.FormEvent {
  return { preventDefault: vi.fn() } as unknown as React.FormEvent
}

describe('auth form feedback i18n', () => {
  it('binds code login to the challenge generated by this send action ', async () => {
    const loginWithVerificationCode = vi.fn()
    const sendVerificationCode = vi.fn().mockResolvedValue({ message: 'ok' })
    const t = createTranslate(() => 'zh-CN')
    const { result } = renderHook(() =>
      useLoginForm({
        login: vi.fn(),
        loginWithVerificationCode,
        sendVerificationCode,
        error: null,
        setError: vi.fn(),
        translate: t,
        extractError: () => 'Failed to send code',
        initialMethod: 'verification',
      }),
    )

    act(() => result.current.setField('username', '13800138000'))
    await act(async () => result.current.sendCode())
    const challengeKey = sendVerificationCode.mock.calls[0][0].challenge_key
    expect(challengeKey).toMatch(/^[0-9a-f-]{36}$/)

    act(() => result.current.setField('verificationCode', '123456'))
    await act(async () => result.current.submit(submitEvent()))

    expect(loginWithVerificationCode).toHaveBeenCalledWith({
      username: '13800138000',
      verification_code: '123456',
      remember_me: true,
      challenge_key: challengeKey,
    })
  })

  it('retranslates login send-code failures after language changes', async () => {
    let language: TestLanguage = 'zh-CN'
    const sendVerificationCode = vi.fn().mockRejectedValue(new Error('network failed'))
    const t = createTranslate(() => language)

    const { result, rerender } = renderHook(() =>
      useLoginForm({
        login: vi.fn(),
        loginWithVerificationCode: vi.fn(),
        sendVerificationCode,
        error: null,
        setError: vi.fn(),
        translate: t,
        extractError: () => 'Failed to send code',
        initialMethod: 'verification',
      }),
    )

    act(() => result.current.setField('username', '13800138000'))
    await act(async () => {
      await result.current.sendCode()
    })

    expect(result.current.fieldErrors.verificationCode).toBe('发送验证码失败')

    language = 'en-US'
    rerender()

    expect(result.current.fieldErrors.verificationCode).toBe('Failed to send code')
  })

  it('password login only accepts phone number and rejects invalid phone', async () => {
    const login = vi.fn()
    const t = createTranslate(() => 'zh-CN')
    const { result } = renderHook(() =>
      useLoginForm({
        login,
        loginWithVerificationCode: vi.fn(),
        sendVerificationCode: vi.fn(),
        error: null,
        setError: vi.fn(),
        translate: t,
        extractError: () => 'Failed to send code',
        initialMethod: 'password',
      }),
    )

    act(() => {
      result.current.setField('username', 'abc13800xyz')
      result.current.setField('password', 'Secret123!')
    })
    // 字母被净化，剩余不足 11 位
    expect(result.current.username).toBe('13800')

    await act(async () => {
      await result.current.submit(submitEvent())
    })
    expect(login).not.toHaveBeenCalled()
    expect(result.current.fieldErrors.username).toBe('请输入有效的手机号')

    act(() => {
      result.current.setField('username', '13800138000')
    })
    await act(async () => {
      await result.current.submit(submitEvent())
    })
    expect(login).toHaveBeenCalledWith({
      username: '13800138000',
      password: 'Secret123!',
      remember_me: true,
    })
  })

  it('login verification rejects invalid phone before send-code ', async () => {
    const sendVerificationCode = vi.fn()
    const t = createTranslate(() => 'zh-CN')
    const { result } = renderHook(() =>
      useLoginForm({
        login: vi.fn(),
        loginWithVerificationCode: vi.fn(),
        sendVerificationCode,
        error: null,
        setError: vi.fn(),
        translate: t,
        extractError: () => 'Failed to send code',
        initialMethod: 'verification',
      }),
    )

    act(() => result.current.setField('username', '12345'))
    await act(async () => {
      await result.current.sendCode()
    })

    expect(sendVerificationCode).not.toHaveBeenCalled()
    expect(result.current.fieldErrors.username).toBe('请输入有效的手机号')
  })

  it('login verification sanitizes non-digit code and blocks short code submit ', async () => {
    const loginWithVerificationCode = vi.fn()
    const t = createTranslate(() => 'zh-CN')
    const { result } = renderHook(() =>
      useLoginForm({
        login: vi.fn(),
        loginWithVerificationCode,
        sendVerificationCode: vi.fn(),
        error: null,
        setError: vi.fn(),
        translate: t,
        extractError: () => 'Failed to send code',
        initialMethod: 'verification',
      }),
    )

    act(() => {
      result.current.setField('username', '13800138000')
      result.current.setField('verificationCode', 'asdsad')
    })
    expect(result.current.verificationCode).toBe('')

    act(() => {
      result.current.setField('verificationCode', '12ab34')
    })
    expect(result.current.verificationCode).toBe('1234')

    await act(async () => {
      await result.current.submit(submitEvent())
    })

    expect(loginWithVerificationCode).not.toHaveBeenCalled()
    expect(result.current.fieldErrors.verificationCode).toBe('验证码应为6位数字')
  })

  it('retranslates register validation errors after language changes', async () => {
    let language: TestLanguage = 'zh-CN'
    const t = createTranslate(() => language)

    const { result, rerender } = renderHook(() =>
      useRegisterForm({
        register: vi.fn(),
        sendVerificationCode: vi.fn(),
        error: null,
        setError: vi.fn(),
        translate: t,
        extractError: () => 'Failed to send code',
      }),
    )

    act(() => {
      result.current.setField('phone', '111111')
      result.current.setField('password', 'password123')
      result.current.setField('confirmPassword', 'password123')
      result.current.setField('verificationCode', '111111')
    })
    await act(async () => {
      await result.current.submit(submitEvent())
    })

    expect(result.current.fieldErrors.phone).toBe('请输入有效的手机号')

    language = 'en-US'
    rerender()

    expect(result.current.fieldErrors.phone).toBe('Please enter a valid phone number')
  })

  it('register password field strips spaces and rejects CJK on input ()', () => {
    const t = createTranslate(() => 'zh-CN')
    const { result } = renderHook(() =>
      useRegisterForm({
        register: vi.fn(),
        sendVerificationCode: vi.fn(),
        error: null,
        setError: vi.fn(),
        translate: t,
        extractError: () => 'Failed to send code',
      }),
    )

    act(() => {
      result.current.setField('password', 'Abcd 1234!')
    })
    expect(result.current.password).toBe('Abcd1234!')
    expect(result.current.fieldErrors.password).toBe('密码不能包含空格，已将空格过滤')

    act(() => {
      result.current.setField('password', '这个报错的原因 Education')
    })
    expect(result.current.password).toBe('')
    expect(result.current.fieldErrors.password).toBe(
      '密码不能包含中日韩文字，请勿粘贴其他内容',
    )
  })
})
