# Generated by Django 4.2.7 on 2026-03-04 20:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VersionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(db_index=True, help_text='docs / table / design / slide / video / canvas', max_length=20, verbose_name='资源类型')),
                ('resource_id', models.UUIDField(db_index=True, help_text='对应模块的主资源 ID（document_id / table_id / project_id / file_id）', verbose_name='资源 ID')),
                ('blob', models.BinaryField(help_text='zlib 压缩的全量快照或增量 diff', verbose_name='版本数据')),
                ('blob_size', models.PositiveIntegerField(default=0, verbose_name='blob 原始字节数')),
                ('is_snapshot', models.BooleanField(default=True, help_text='True=全量快照, False=增量 diff', verbose_name='全量快照')),
                ('editor_type', models.CharField(blank=True, db_index=True, default='user', help_text='user / agent / system', max_length=16, verbose_name='编辑者类型')),
                ('editor_id', models.CharField(blank=True, default='', max_length=64, verbose_name='编辑者 ID')),
                ('editor_name', models.CharField(blank=True, default='', max_length=128, verbose_name='编辑者名称')),
                ('expired_at', models.DateTimeField(blank=True, db_index=True, help_text='NULL=永不过期（命名版本/置顶版本）', null=True, verbose_name='过期时间')),
                ('is_named', models.BooleanField(default=False, verbose_name='命名版本')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='版本名称')),
                ('pinned', models.BooleanField(default=False, verbose_name='置顶')),
                ('workspace_id', models.UUIDField(blank=True, db_index=True, help_text='用于按工作空间隔离版本数据', null=True, verbose_name='工作空间 ID')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='如 page_count, shape_count, record_count, version/revn 等', verbose_name='模块特有元数据')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('base_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diffs', to='collab.versionhistory', verbose_name='增量 diff 的基版本')),
            ],
            options={
                'verbose_name': '版本历史',
                'verbose_name_plural': '版本历史',
                'db_table': 'collab_version_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpaceCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(db_index=True, verbose_name='工作空间 ID')),
                ('agent_space_id', models.UUIDField(db_index=True, verbose_name='Agent Space ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='检查点名称')),
                ('version_refs', models.JSONField(default=dict, help_text='{"resource_type:resource_id": "version_history_id", ...}', verbose_name='资源版本引用')),
                ('file_checkpoint_hash', models.CharField(blank=True, default='', help_text='Shadow Git commit hash（TabCode 文件快照）', max_length=64, verbose_name='文件系统检查点')),
                ('agent_run_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='关联 Agent Run')),
                ('trigger', models.CharField(default='manual', help_text='manual / agent_start / agent_end / auto', max_length=20, verbose_name='触发方式')),
                ('editor_type', models.CharField(blank=True, default='user', max_length=16)),
                ('editor_id', models.CharField(blank=True, default='', max_length=64)),
                ('editor_name', models.CharField(blank=True, default='', max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': '空间检查点',
                'verbose_name_plural': '空间检查点',
                'db_table': 'collab_space_checkpoint',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent_space_id', '-created_at'], name='idx_sc_space_time')],
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(db_index=True, max_length=20, verbose_name='资源类型')),
                ('resource_id', models.UUIDField(db_index=True, verbose_name='资源 ID')),
                ('change_type', models.CharField(help_text='create / update / delete / restore', max_length=20, verbose_name='变更类型')),
                ('summary', models.CharField(blank=True, default='', help_text='人可读的操作描述', max_length=500, verbose_name='变更摘要')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='结构化的变更内容，格式由各模块 adapter 定义', verbose_name='变更详情')),
                ('editor_type', models.CharField(blank=True, db_index=True, default='user', max_length=16, verbose_name='编辑者类型')),
                ('editor_id', models.CharField(blank=True, default='', max_length=64, verbose_name='编辑者 ID')),
                ('editor_name', models.CharField(blank=True, default='', max_length=128, verbose_name='编辑者名称')),
                ('agent_run_id', models.CharField(blank=True, db_index=True, default='', help_text='关联同一轮 Agent 操作的所有跨模块变更', max_length=64, verbose_name='Agent Run ID')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='附加信息')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('version_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='collab.versionhistory', verbose_name='关联版本')),
            ],
            options={
                'verbose_name': '变更记录',
                'verbose_name_plural': '变更记录',
                'db_table': 'collab_change_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='versionhistory',
            index=models.Index(fields=['resource_type', 'resource_id', '-created_at'], name='idx_vh_resource_time'),
        ),
        migrations.AddIndex(
            model_name='versionhistory',
            index=models.Index(fields=['resource_type', 'resource_id', 'is_snapshot'], name='idx_vh_resource_snapshot'),
        ),
        migrations.AddIndex(
            model_name='changelog',
            index=models.Index(fields=['resource_type', 'resource_id', '-created_at'], name='idx_cl_resource_time'),
        ),
        migrations.AddIndex(
            model_name='changelog',
            index=models.Index(fields=['agent_run_id', '-created_at'], name='idx_cl_agent_run'),
        ),
    ]
