# Generated by Django 4.2.7 on 2026-03-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='spacecheckpoint',
            name='idx_sc_space_time',
        ),
        migrations.AlterField(
            model_name='spacecheckpoint',
            name='agent_space_id',
            field=models.UUIDField(db_column='agent_space_id', db_index=True, verbose_name='Agent Space ID'),
        ),
        migrations.RenameField(
            model_name='spacecheckpoint',
            old_name='agent_space_id',
            new_name='space_id',
        ),
        migrations.AddIndex(
            model_name='spacecheckpoint',
            index=models.Index(fields=['space_id', '-created_at'], name='idx_sc_space_time'),
        ),
    ]
