# Generated by Django 4.2.7 on 2026-03-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0004_workspace_to_workteam_rename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacecheckpoint',
            name='workteam_id',
            field=models.UUIDField(db_index=True, verbose_name='工作团队 ID'),
        ),
        migrations.AlterField(
            model_name='versionhistory',
            name='workteam_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='用于按工作团队隔离版本数据', null=True, verbose_name='工作团队 ID'),
        ),
    ]
