# Generated by Django 4.2.7 on 2026-03-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0005_alter_spacecheckpoint_workteam_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='spacecheckpoint',
            index=models.Index(fields=['space_id', 'file_checkpoint_hash'], name='idx_sc_space_filehash'),
        ),
    ]
