# Generated by Django 4.2.7 on 2026-04-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0006_add_space_checkpoint_filehash_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='产生该变更的 ChatSession ID。跨库读优化的反范式设计——ChangeLog 在 PG，ChatSession 在 MySQL，无法跨库 JOIN', max_length=64, verbose_name='关联会话 ID'),
        ),
    ]
