# Generated by Django 4.2.7 on 2026-04-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0007_changelog_add_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacecheckpoint',
            name='anchor_message_id',
            field=models.CharField(blank=True, default='', help_text='产生该 checkpoint 的 assistant 消息 ID，用于前端 scrollToMessage 定位', max_length=64, verbose_name='锚定消息 ID'),
        ),
        migrations.AddField(
            model_name='spacecheckpoint',
            name='anchor_session_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='产生该 checkpoint 的 ChatSession ID，用于快速定位对话', max_length=64, verbose_name='锚定会话 ID'),
        ),
    ]
