# Generated by Django 4.2.7 on 2026-04-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0008_spacecheckpoint_add_anchor_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='change_type',
            field=models.CharField(help_text='create / update / delete / restore / schema_version_token_bumped / field_restore', max_length=64, verbose_name='变更类型'),
        ),
    ]
