# Generated by Django 4.2.7 on 2026-07-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0011_rename_workteam_to_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacecheckpoint',
            name='organization_id',
            field=models.UUIDField(db_index=True, verbose_name='组织 ID'),
        ),
        migrations.AlterField(
            model_name='versionhistory',
            name='organization_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='用于按组织隔离版本数据', null=True, verbose_name='组织 ID'),
        ),
    ]
