# Generated by Django 4.2.7 on 2026-04-23 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPortrait',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workteam_id', models.UUIDField(db_index=True, help_text='(user, workteam_id) 复合唯一——一个用户在每个 Workteam 最多一份画像', verbose_name='所属 Workteam')),
                ('content_md', models.TextField(blank=True, default='', help_text='5 段叙事，由蒸馏 Agent 整体重写。空字符串表示 Portrait 尚未生成。', verbose_name='画像 Markdown')),
                ('version', models.PositiveIntegerField(default=0, help_text='每成功蒸馏一次 +1，初始为 0（未蒸馏）', verbose_name='蒸馏版本号')),
                ('last_distilled_at', models.DateTimeField(blank=True, help_text='增量检测的锚点：对比 MAX(memo.created_at) 决定是否需要新一轮蒸馏', null=True, verbose_name='上次蒸馏成功时间')),
                ('last_distill_status', models.CharField(choices=[('idle', '空闲（从未蒸馏 / 上次蒸馏成功）'), ('pending', '蒸馏中'), ('failed', '上次蒸馏失败')], default='idle', max_length=16, verbose_name='上次蒸馏状态')),
                ('last_distill_error', models.TextField(blank=True, default='', help_text='last_distill_status=failed 时填充，便于 UI 展示和调试', verbose_name='上次蒸馏错误信息')),
                ('pending_hints', models.JSONField(blank=True, default=list, help_text='用户最近提交的 hint，蒸馏完成后清空', verbose_name='待处理 hint 列表')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='portraits_v2', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '用户画像',
                'verbose_name_plural': '用户画像',
                'db_table': 'user_portrait_portrait',
            },
        ),
        migrations.CreateModel(
            name='UserPortraitSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_at_snapshot', models.PositiveIntegerField(help_text='即 portrait.version；保留以便排序展示', verbose_name='快照时刻的版本号')),
                ('content_md', models.TextField(blank=True, default='', verbose_name='快照内容（Markdown）')),
                ('trigger_reason', models.CharField(choices=[('scheduled', '定时任务'), ('hint', '用户提交 hint'), ('manual', '用户手动触发')], default='scheduled', max_length=32, verbose_name='触发原因')),
                ('input_summary', models.JSONField(blank=True, default=dict, help_text='例：{"memo_count": 42, "hint_count": 1}', verbose_name='蒸馏输入摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='快照创建时间')),
                ('portrait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='user_portrait.userportrait', verbose_name='所属画像')),
            ],
            options={
                'verbose_name': '画像快照',
                'verbose_name_plural': '画像快照',
                'db_table': 'user_portrait_snapshot',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['portrait', '-created_at'], name='ups_portrait_created_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='userportrait',
            index=models.Index(fields=['workteam_id'], name='up_workteam_idx'),
        ),
        migrations.AddIndex(
            model_name='userportrait',
            index=models.Index(fields=['last_distilled_at'], name='up_last_distilled_idx'),
        ),
        migrations.AddIndex(
            model_name='userportrait',
            index=models.Index(fields=['last_distill_status'], name='up_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='userportrait',
            constraint=models.UniqueConstraint(fields=('user', 'workteam_id'), name='up_user_workteam_unique'),
        ),
    ]
