# Generated by Django 4.2.7 on 2026-06-05 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_portrait', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userportrait',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portraits_v2', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
    ]
