# Generated by Django 4.2.7 on 2026-07-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portrait', '0003_rename_workteam_to_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userportrait',
            name='organization_id',
            field=models.UUIDField(db_index=True, help_text='(user, organization_id) 复合唯一——一个用户在每个 Organization 最多一份画像', verbose_name='所属 Organization'),
        ),
    ]
