"""TabSite 错误码"""


class ErrorCode:
    SITE_NOT_FOUND = "SITE_NOT_FOUND"
    SITE_ARCHIVED = "SITE_ARCHIVED"
    VERSION_NOT_FOUND = "VERSION_NOT_FOUND"
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    SLUG_CONFLICT = "SLUG_CONFLICT"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    BUILD_FAILED = "BUILD_FAILED"
    PUBLISH_FAILED = "PUBLISH_FAILED"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
