# Generated by Django 4.2.7 on 2026-03-04 20:27

import apps.services.common.base_models
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import uuid
from tabtin.migration_utils import PostgresOnlyOperation


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('agent_space_id', models.UUIDField(db_index=True)),
                ('content_json', models.JSONField(blank=True, default=dict, help_text='结构化内容，TipTap/ProseMirror JSON 格式', verbose_name='ProseMirror JSON')),
                ('content_plaintext', models.TextField(blank=True, default='', help_text='由 content_json 提取的纯文本，用于全文搜索和列表预览', verbose_name='纯文本（搜索用）')),
                ('content_markdown', models.TextField(blank=True, default='', help_text='Markdown 格式副本，用于快速编辑和 Agent 读取', verbose_name='Markdown 副本')),
                ('color', models.CharField(blank=True, choices=[('', '无颜色'), ('yellow', '黄色'), ('blue', '蓝色'), ('green', '绿色'), ('pink', '粉色'), ('purple', '紫色'), ('orange', '橙色'), ('gray', '灰色')], default='', help_text='可选值: yellow/blue/green/pink/purple/orange/gray', max_length=20, verbose_name='卡片颜色')),
                ('source', models.CharField(choices=[('manual', '手动输入'), ('browser', '浏览器采集'), ('share', '移动端分享'), ('api', 'API 推送'), ('agent', 'Agent 创建')], default='manual', help_text='来源标识: manual/browser/share/api/agent', max_length=50, verbose_name='来源')),
                ('source_url', models.URLField(blank=True, default='', help_text='碎片来源的原始 URL（浏览器采集等场景）', max_length=2048, verbose_name='来源 URL')),
                ('is_pinned', models.BooleanField(default=False, help_text='置顶碎片在列表中排在最前面', verbose_name='置顶')),
                ('tags', models.JSONField(blank=True, default=list, help_text='用户手动添加的标签列表，如 ["设计", "灵感"]', verbose_name='用户标签')),
                ('ai_tags', models.JSONField(blank=True, default=list, help_text='由 AI 自动分析生成的标签列表', verbose_name='AI 自动标签')),
                ('bookmark_url', models.URLField(blank=True, default='', max_length=2048, verbose_name='书签 URL')),
                ('bookmark_title', models.CharField(blank=True, default='', max_length=500, verbose_name='书签标题')),
                ('bookmark_description', models.TextField(blank=True, default='', verbose_name='书签描述')),
                ('bookmark_image', models.URLField(blank=True, default='', max_length=2048, verbose_name='书签缩略图')),
                ('status', models.CharField(choices=[('active', '活跃'), ('archived', '已归档')], db_index=True, default='active', help_text='碎片生命周期状态: active/archived', max_length=20, verbose_name='状态')),
            ],
            options={
                'db_table': 'tabmemo_memo',
                'ordering': ['-is_pinned', '-created_at'],
            },
            bases=(models.Model, apps.services.common.base_models.ContextSyncMixin),
        ),
        PostgresOnlyOperation(
            migrations.AddField(
                model_name='memo',
                name='search_vector',
                field=django.contrib.postgres.search.SearchVectorField(blank=True, help_text='PostgreSQL tsvector，由 content_plaintext + bookmark + tags 生成', null=True, verbose_name='搜索向量'),
            ),
        ),
        migrations.CreateModel(
            name='MemoAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_type', models.CharField(choices=[('image', '图片'), ('file', '文件'), ('video', '视频'), ('audio', '音频')], help_text='附件类型: image/file/video/audio', max_length=20, verbose_name='文件类型')),
                ('file_url', models.URLField(help_text='文件在 OSS 中的访问地址', max_length=2048, verbose_name='OSS URL')),
                ('file_name', models.CharField(max_length=500, verbose_name='文件名')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='文件大小（字节）', verbose_name='文件大小(bytes)')),
                ('mime_type', models.CharField(blank=True, default='', max_length=100, verbose_name='MIME 类型')),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=2048, verbose_name='缩略图 URL')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序序号')),
            ],
            options={
                'db_table': 'tabmemo_attachment',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('agent_space_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=255, verbose_name='集合名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('icon', models.CharField(blank=True, default='', max_length=50, verbose_name='图标')),
                ('color', models.CharField(blank=True, default='', max_length=20, verbose_name='颜色')),
                ('is_smart', models.BooleanField(default=False, help_text='智能集合基于 smart_filter 自动匹配碎片', verbose_name='智能集合')),
                ('smart_filter', models.JSONField(blank=True, default=dict, help_text='例: {"tags": ["设计"], "keywords": ["UI"]}', verbose_name='智能过滤条件')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序序号')),
            ],
            options={
                'db_table': 'tabmemo_collection',
                'ordering': ['sort_order', 'created_at'],
            },
            bases=(models.Model, apps.services.common.base_models.ContextSyncMixin),
        ),
        migrations.CreateModel(
            name='MemoCollectionMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序序号')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memo_memberships', to='tabmemo.memocollection')),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_memberships', to='tabmemo.memo')),
            ],
            options={
                'db_table': 'tabmemo_membership',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
