# Generated by Django 4.2.7 on 2026-03-04 20:27

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
from tabtin.migration_utils import PostgresOnlyOperation


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tabmemo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='memocollection',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memoattachment',
            name='memo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tabmemo.memo'),
        ),
        migrations.AddField(
            model_name='memo',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memo',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='memocollectionmembership',
            unique_together={('memo', 'collection')},
        ),
        migrations.AddIndex(
            model_name='memocollection',
            index=models.Index(fields=['workspace_id', 'agent_space_id'], name='tm_coll_ws_as_idx'),
        ),
        migrations.AddIndex(
            model_name='memo',
            index=models.Index(fields=['workspace_id', 'agent_space_id', 'status'], name='tm_ws_as_status_idx'),
        ),
        migrations.AddIndex(
            model_name='memo',
            index=models.Index(fields=['workspace_id', 'agent_space_id', '-created_at'], name='tm_ws_as_created_idx'),
        ),
        PostgresOnlyOperation(
            migrations.AddIndex(
                model_name='memo',
                index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='tm_search_gin_idx'),
            ),
        ),
        PostgresOnlyOperation(
            migrations.AddIndex(
                model_name='memo',
                index=django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='tm_tags_gin_idx'),
            ),
        ),
    ]
