# Generated by Django 4.2.7 on 2026-03-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabmemo', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='previous_status',
            field=models.CharField(blank=True, default='', help_text='进入回收站前的 status 值，恢复时回到此状态', max_length=20, verbose_name='回收前状态'),
        ),
        migrations.AddField(
            model_name='memo',
            name='trashed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='进入回收站的时间，为 NULL 表示不在回收站', null=True, verbose_name='回收站时间'),
        ),
        migrations.AddField(
            model_name='memo',
            name='trashed_by',
            field=models.UUIDField(blank=True, help_text='将资源移入回收站的用户 ID', null=True, verbose_name='回收站操作人'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='status',
            field=models.CharField(choices=[('active', '活跃'), ('archived', '已归档'), ('trashed', '已删除')], db_index=True, default='active', help_text='碎片生命周期状态: active/archived', max_length=20, verbose_name='状态'),
        ),
    ]
