# Generated by Django 4.2.7 on 2026-03-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabmemo', '0003_add_trash_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='memo',
            name='tm_ws_as_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='memo',
            name='tm_ws_as_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='memocollection',
            name='tm_coll_ws_as_idx',
        ),
        migrations.AlterField(
            model_name='memo',
            name='agent_space_id',
            field=models.UUIDField(db_column='agent_space_id', db_index=True),
        ),
        migrations.RenameField(
            model_name='memo',
            old_name='agent_space_id',
            new_name='space_id',
        ),
        migrations.AlterField(
            model_name='memocollection',
            name='agent_space_id',
            field=models.UUIDField(db_column='agent_space_id', db_index=True),
        ),
        migrations.RenameField(
            model_name='memocollection',
            old_name='agent_space_id',
            new_name='space_id',
        ),
        migrations.AddField(
            model_name='memo',
            name='owner_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='memocollection',
            name='owner_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='memo',
            index=models.Index(fields=['workspace_id', 'space_id', 'status'], name='tm_ws_as_status_idx'),
        ),
        migrations.AddIndex(
            model_name='memo',
            index=models.Index(fields=['workspace_id', 'space_id', '-created_at'], name='tm_ws_as_created_idx'),
        ),
        migrations.AddIndex(
            model_name='memocollection',
            index=models.Index(fields=['workspace_id', 'space_id'], name='tm_coll_ws_as_idx'),
        ),
    ]
