# Generated by Django 4.2.7 on 2026-03-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabmemo', '0004_remove_memo_tm_ws_as_status_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='space_id',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='memocollection',
            name='space_id',
            field=models.UUIDField(db_index=True),
        ),
    ]
