# Generated by Django 4.2.7 on 2026-03-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabmemo', '0007_backfill_owner_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='memo',
            index=models.Index(condition=models.Q(('space_id__isnull', True)), fields=['workspace_id', 'owner_id', 'status'], name='tm_ws_owner_status_idx'),
        ),
    ]
