# Generated by Django 4.2.7 on 2026-03-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabmemo', '0008_add_owner_status_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='importance',
            field=models.PositiveSmallIntegerField(blank=True, help_text='重要程度 1-5，Agent 创建的 memo 使用此字段', null=True, verbose_name='重要性'),
        ),
        migrations.AddField(
            model_name='memo',
            name='memo_type',
            field=models.CharField(choices=[('note', '笔记'), ('bookmark', '书签'), ('about_you', '关于你'), ('insight', '洞察'), ('task_summary', '任务摘要'), ('skill', '技能')], db_index=True, default='note', help_text='碎片类型: note/bookmark/about_you/insight/task_summary/skill', max_length=30, verbose_name='碎片类型'),
        ),
        migrations.AddIndex(
            model_name='memo',
            index=models.Index(condition=models.Q(('space_id__isnull', False)), fields=['space_id', 'memo_type', 'status'], name='tm_space_type_status_idx'),
        ),
    ]
