# Generated by Django 4.2.7 on 2026-03-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabmemo', '0009_add_memo_type_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='source',
            field=models.CharField(choices=[('manual', '手动输入'), ('browser', '浏览器采集'), ('share', '移动端分享'), ('api', 'API 推送'), ('agent', 'Agent 创建'), ('voice', '语音输入')], default='manual', help_text='来源标识: manual/browser/share/api/agent', max_length=50, verbose_name='来源'),
        ),
    ]
