# Generated by Django 4.2.7 on 2026-03-16 09:20

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabmemo', '0010_add_voice_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, help_text='PostgreSQL tsvector，由 content_plaintext + bookmark + tags + ai_tags 生成；由 Service 层维护，无数据库触发器', null=True, verbose_name='搜索向量'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='status',
            field=models.CharField(choices=[('active', '活跃'), ('archived', '已归档'), ('trashed', '已删除')], db_index=True, default='active', help_text='碎片生命周期状态: active/archived/trashed', max_length=20, verbose_name='状态'),
        ),
        migrations.AddIndex(
            model_name='memocollectionmembership',
            index=models.Index(fields=['collection', 'sort_order'], name='tm_membership_coll_sort_idx'),
        ),
        migrations.AddConstraint(
            model_name='memo',
            constraint=models.CheckConstraint(check=models.Q(('importance__isnull', True), models.Q(('importance__gte', 1), ('importance__lte', 5)), _connector='OR'), name='tm_importance_range_1_5'),
        ),
    ]
