# Generated by Django 4.2.7 on 2026-03-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabmemo', '0011_alter_memo_search_vector_alter_memo_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='memocollectionmembership',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='memocollection',
            name='previous_status',
            field=models.CharField(blank=True, default='', help_text='进入回收站前的 status 值，恢复时回到此状态', max_length=20, verbose_name='回收前状态'),
        ),
        migrations.AddField(
            model_name='memocollection',
            name='status',
            field=models.CharField(choices=[('active', '活跃'), ('trashed', '已删除')], db_index=True, default='active', help_text='集合生命周期状态: active/trashed', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='memocollection',
            name='trashed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='进入回收站的时间，为 NULL 表示不在回收站', null=True, verbose_name='回收站时间'),
        ),
        migrations.AddField(
            model_name='memocollection',
            name='trashed_by',
            field=models.UUIDField(blank=True, help_text='将资源移入回收站的用户 ID', null=True, verbose_name='回收站操作人'),
        ),
        migrations.AlterField(
            model_name='memoagentgrant',
            name='granted_by',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='memo',
            index=models.Index(fields=['workspace_id', 'space_id', '-created_at'], name='tm_ws_space_created_idx'),
        ),
        migrations.AddIndex(
            model_name='memo',
            index=models.Index(fields=['workspace_id', 'owner_id', '-created_at'], name='tm_ws_owner_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='memocollectionmembership',
            constraint=models.UniqueConstraint(fields=('memo', 'collection'), name='tm_membership_memo_coll_uniq'),
        ),
    ]
