# Generated by Django 4.2.7 on 2026-03-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabmemo', '0015_workspace_to_workteam_rename'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='memo',
            name='tm_ws_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='memo',
            name='tm_ws_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='memo',
            name='tm_ws_as_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='memo',
            name='tm_ws_owner_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='memo',
            name='tm_ws_space_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='memo',
            name='tm_ws_owner_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='memoagentgrant',
            name='tm_grant_space_ws_idx',
        ),
        migrations.RemoveIndex(
            model_name='memocollection',
            name='tm_coll_ws_as_idx',
        ),
        migrations.AlterField(
            model_name='memo',
            name='source',
            field=models.CharField(choices=[('manual', '手动输入'), ('browser', '浏览器采集'), ('share', '移动端分享'), ('api', 'API 推送'), ('agent', 'Agent 创建'), ('voice', '语音输入')], default='manual', help_text='来源标识: manual/browser/share/api/agent/voice', max_length=50, verbose_name='来源'),
        ),
        migrations.AddIndex(
            model_name='memo',
            index=models.Index(fields=['workteam_id', 'status'], name='tm_ws_status_idx'),
        ),
        migrations.AddIndex(
            model_name='memo',
            index=models.Index(fields=['workteam_id', '-created_at'], name='tm_ws_created_idx'),
        ),
        migrations.AddIndex(
            model_name='memo',
            index=models.Index(condition=models.Q(('space_id__isnull', False)), fields=['workteam_id', 'space_id', 'status'], name='tm_ws_as_status_idx'),
        ),
        migrations.AddIndex(
            model_name='memo',
            index=models.Index(condition=models.Q(('space_id__isnull', True)), fields=['workteam_id', 'owner_id', 'status'], name='tm_ws_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='memo',
            index=models.Index(fields=['workteam_id', 'space_id', '-created_at'], name='tm_ws_space_created_idx'),
        ),
        migrations.AddIndex(
            model_name='memo',
            index=models.Index(fields=['workteam_id', 'owner_id', '-created_at'], name='tm_ws_owner_created_idx'),
        ),
        migrations.AddIndex(
            model_name='memoagentgrant',
            index=models.Index(fields=['target_space_id', 'workteam_id'], name='tm_grant_space_ws_idx'),
        ),
        migrations.AddIndex(
            model_name='memocollection',
            index=models.Index(fields=['workteam_id', 'space_id'], name='tm_coll_ws_as_idx'),
        ),
    ]
