# Generated by Django 4.2.7 on 2026-06-09 10:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tabmemo', '0017_alter_memo_created_by_alter_memo_updated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoRecordStyle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.UUIDField(db_index=True, help_text='(user_id, workteam_id) 复合唯一——一个用户在每个 Workteam 一份记录风格', verbose_name='所属用户')),
                ('workteam_id', models.UUIDField(db_index=True, verbose_name='所属 Workteam')),
                ('enabled', models.BooleanField(default=True, help_text='关闭后该用户在本 Workteam 的所有 Agent 不再蒸馏写入笔记', verbose_name='记录总开关')),
                ('style', models.CharField(choices=[('faithful', '忠实记录'), ('minimal', '极简'), ('companion', '洞察伙伴'), ('custom', '自定义')], default='faithful', help_text='faithful/minimal/companion/custom；custom 时读 custom_config', max_length=20, verbose_name='记录风格')),
                ('custom_config', models.JSONField(blank=True, default=dict, help_text='style=custom 时生效，例: {"density":"moderate","depth":"with_judgment","tone":"warm","focus":["about_user","method"]}', verbose_name='自定义维度')),
                ('extra_preference', models.TextField(blank=True, default='', help_text='用户自由文本偏好，作为受控变量注入蒸馏 prompt 固定槽位（非裸 prompt）', verbose_name='额外记录偏好')),
            ],
            options={
                'verbose_name': '记忆记录风格',
                'verbose_name_plural': '记忆记录风格',
                'db_table': 'tabmemo_record_style',
            },
        ),
        migrations.AddConstraint(
            model_name='memorecordstyle',
            constraint=models.UniqueConstraint(fields=('user_id', 'workteam_id'), name='tm_record_style_user_ws_uniq'),
        ),
    ]
