# Generated by Django 4.2.7 on 2026-06-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabmemo', '0018_memorecordstyle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='memo_type',
            field=models.CharField(choices=[('note', '笔记'), ('bookmark', '书签'), ('about_you', '关于你'), ('insight', '洞察'), ('task_summary', '任务摘要')], db_index=True, default='note', help_text='碎片类型: note/bookmark/about_you/insight/task_summary', max_length=30, verbose_name='碎片类型'),
        ),
    ]
