# Generated by Django 4.2.7 on 2026-06-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabmemo', '0019_alter_memo_memo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorecordstyle',
            name='user_id',
            field=models.UUIDField(help_text='(user_id, workteam_id) 复合唯一——一个用户在每个 Workteam 一份记录风格', verbose_name='所属用户'),
        ),
    ]
