# Generated by Django 4.2.7 on 2026-07-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabmemo', '0021_rename_workteam_to_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorecordstyle',
            name='enabled',
            field=models.BooleanField(default=True, help_text='关闭后该用户在本 Organization 的所有 Agent 不再蒸馏写入笔记', verbose_name='记录总开关'),
        ),
        migrations.AlterField(
            model_name='memorecordstyle',
            name='organization_id',
            field=models.UUIDField(db_index=True, verbose_name='所属 Organization'),
        ),
        migrations.AlterField(
            model_name='memorecordstyle',
            name='user_id',
            field=models.UUIDField(help_text='(user_id, organization_id) 复合唯一——一个用户在每个 Organization 一份记录风格', verbose_name='所属用户'),
        ),
    ]
