# Generated by Django 4.2.7 on 2026-03-04 20:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=64, verbose_name='接收用户 ID')),
                ('workspace_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='关联工作空间 ID')),
                ('type', models.CharField(choices=[('invite_received', '收到邀请'), ('invite_accepted', '邀请被接受'), ('member_added', '被添加为成员'), ('member_removed', '被移除'), ('role_changed', '角色变更'), ('ownership_transfer', '所有权转让'), ('resource_shared', '资源被共享'), ('quota_warning', '配额预警'), ('system', '系统通知'), ('extension_event', 'Extension 事件通知')], max_length=50, verbose_name='通知类型')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('body', models.TextField(blank=True, default='', verbose_name='正文')),
                ('metadata', models.JSONField(default=dict, verbose_name='附加数据')),
                ('source_event_id', models.CharField(blank=True, default='', max_length=100, verbose_name='来源事件ID')),
                ('source_extension_id', models.CharField(blank=True, default='', max_length=64, verbose_name='来源 Extension')),
                ('agent_space_id', models.CharField(blank=True, default='', max_length=100, verbose_name='AgentSpace ID')),
                ('priority', models.CharField(default='normal', max_length=16, verbose_name='优先级')),
                ('channels_delivered', models.JSONField(default=list, verbose_name='已投递渠道')),
                ('category', models.CharField(default='general', max_length=64, verbose_name='分类')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='是否已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='已读时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'notification_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'is_read', '-created_at'], name='notif_user_read_time_idx'), models.Index(fields=['user_id', 'workspace_id'], name='notif_user_ws_idx')],
            },
        ),
    ]
