# Generated by Django 4.2.7 on 2026-03-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='agent_space_id',
            field=models.CharField(blank=True, db_column='agent_space_id', default='', max_length=100, verbose_name='AgentSpace ID'),
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='agent_space_id',
            new_name='space_id',
        ),
    ]
