# Generated by Django 4.2.7 on 2026-03-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notification_agent_space_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='space_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='所属空间'),
        ),
    ]
