# Generated by Django 4.2.7 on 2026-03-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_workspace_to_workteam_rename'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notif_user_ws_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='workteam_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='关联工作团队 ID'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user_id', 'workteam_id'], name='notif_user_ws_idx'),
        ),
    ]
