# Generated by Django 4.2.7 on 2026-07-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_rename_workteam_to_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='organization_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='关联组织 ID'),
        ),
    ]
