# Generated by Django 4.2.7 on 2026-07-02 11:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0011_alter_notification_type_resource_access_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicePushRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=64, verbose_name='接收用户 ID')),
                ('device_fingerprint', models.CharField(blank=True, default='', help_text='软引用 tabtinspace.Device.fingerprint，仅用于排障归因，可为空', max_length=128, verbose_name='设备指纹')),
                ('provider', models.CharField(choices=[('tencent_push', '腾讯云推送 Push (TIMPush)')], default='tencent_push', max_length=32, verbose_name='推送服务商')),
                ('registration_id', models.CharField(max_length=255, verbose_name='推送注册 ID')),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=16, verbose_name='平台')),
                ('app_version', models.CharField(blank=True, default='', max_length=32, verbose_name='App 版本')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='最近上报时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '设备推送注册',
                'verbose_name_plural': '设备推送注册',
                'db_table': 'notification_device_push_registration',
                'indexes': [models.Index(fields=['user_id', 'is_active'], name='push_reg_user_active_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='devicepushregistration',
            constraint=models.UniqueConstraint(fields=('provider', 'registration_id'), name='push_reg_provider_regid_uniq'),
        ),
    ]
