# Generated by Django 4.2.7 on 2026-03-04 20:27

import apps.services.common.base_models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlideChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.BigIntegerField(help_text='本次变更产生的版本号')),
                ('change_type', models.CharField(choices=[('save_pages', '保存页面'), ('collab_persist', '协作同步'), ('update_element', '修改元素'), ('create_slides', 'AI 生成'), ('import_pptx', '导入 PPTX'), ('restore_history', '恢复历史版本'), ('update_meta', '更新元数据')], max_length=32)),
                ('summary', models.CharField(blank=True, default='', max_length=500)),
                ('pages_affected', models.JSONField(blank=True, default=None, help_text='受影响的页面 ID 列表（可选）', null=True)),
                ('editor_type', models.CharField(blank=True, default='', max_length=16)),
                ('editor_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tabslide_change',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SlideElementChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_id', models.CharField(help_text='所在页面 ID', max_length=64)),
                ('element_id', models.CharField(help_text='元素 ID', max_length=64)),
                ('version', models.BigIntegerField(help_text='该变更对应的项目版本号')),
                ('change_type', models.CharField(choices=[('create', '新增元素'), ('update', '修改元素属性'), ('delete', '删除元素'), ('move', '移动/缩放'), ('style', '样式变更')], default='update', max_length=32)),
                ('changed_fields', models.JSONField(default=list, help_text='变更的属性名列表，如 ["x", "y", "width", "content"]')),
                ('before_data', models.JSONField(blank=True, help_text='变更前的属性值（仅变更字段）', null=True)),
                ('after_data', models.JSONField(blank=True, help_text='变更后的属性值（仅变更字段）', null=True)),
                ('editor_type', models.CharField(default='human', help_text='human / agent / system', max_length=16)),
                ('editor_id', models.CharField(blank=True, default='', help_text='编辑者 user ID 或 agent ID', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tabslide_element_change',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SlideHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(verbose_name='Workspace ID')),
                ('version', models.BigIntegerField(help_text='创建快照时的 project.latest_version')),
                ('blob', models.BinaryField(verbose_name='zlib 压缩数据（全量快照或增量 diff）')),
                ('page_meta_snapshot', models.JSONField(blank=True, default=None, null=True, verbose_name='page_meta 快照')),
                ('page_count', models.IntegerField(default=0)),
                ('is_snapshot', models.BooleanField(default=True, help_text='True=全量快照（zlib JSON），False=增量 diff')),
                ('blob_size', models.IntegerField(default=0, help_text='blob 的字节数（用于存储分析和告警）')),
                ('editor_type', models.CharField(blank=True, default='', max_length=16, verbose_name='触发者类型 (human/agent)')),
                ('editor_id', models.CharField(blank=True, default='', max_length=64, verbose_name='触发者 ID')),
                ('expired_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='过期时间（TTL，命名版本为 NULL）')),
                ('is_named', models.BooleanField(default=False, verbose_name='是否用户手动保存的命名版本')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='版本名称')),
                ('pinned', models.BooleanField(default=False, verbose_name='是否置顶（不受 TTL/降采样影响）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tabslide_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SlidePage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_id', models.CharField(help_text='前端页面 ID（slide.id），同一 project 下唯一', max_length=64)),
                ('elements_data', models.JSONField(default=list, help_text='该页的 PPTElement[] JSON')),
                ('html_source', models.TextField(blank=True, default='', help_text="HTML-native 页面源码；当 content_format='html' 时为唯一真相源")),
                ('content_format', models.CharField(default='json', help_text='页面内容格式：json（elements_data 权威）/ html（html_source 权威）', max_length=16)),
                ('background', models.JSONField(blank=True, default=None, help_text='SlideBackground 配置', null=True)),
                ('master_elements', models.JSONField(blank=True, default=None, help_text='母版/版式只读元素层 PPTElement[]', null=True)),
                ('layout_ref', models.JSONField(blank=True, default=None, help_text='SlideLayoutRef 版式引用', null=True)),
                ('remark', models.TextField(blank=True, default='', help_text='演讲者备注')),
                ('animations', models.JSONField(blank=True, default=None, help_text='PPTAnimation[] 元素动画集合', null=True)),
                ('turning_mode', models.CharField(blank=True, default='', help_text='翻页动画模式', max_length=32)),
                ('order', models.FloatField(default=0, help_text='页面排序位置（支持中间插入，同 TabData record order）')),
                ('version', models.BigIntegerField(default=0, help_text='页面级版本号（从 project.latest_version 分配）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tabslide_page',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SlidePageCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_id', models.CharField(help_text='对应 SlidePage.page_id', max_length=64)),
                ('content_hash', models.CharField(help_text='页面 elements_data 的 SHA256，用于判断缓存是否有效', max_length=64)),
                ('slide_xml', models.BinaryField(help_text='zlib 压缩的 slide XML（PPTX 内部格式）')),
                ('rels_xml', models.BinaryField(blank=True, help_text='zlib 压缩的 slide relationships XML', null=True)),
                ('media_refs', models.JSONField(default=list, help_text='该页引用的媒体文件列表 [{rId, target, content_type}]')),
                ('version', models.BigIntegerField(help_text='缓存创建时的页面版本')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tabslide_page_cache',
            },
        ),
        migrations.CreateModel(
            name='SlidePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(choices=[('user', 'User'), ('role', 'Role'), ('agent', 'Agent')], max_length=20)),
                ('subject_id', models.CharField(max_length=64)),
                ('permission', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('admin', 'Admin')], default='viewer', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('granted_by', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '演示文稿权限',
                'verbose_name_plural': '演示文稿权限',
                'db_table': 'tabslide_slide_permission',
            },
        ),
        migrations.CreateModel(
            name='SlideProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('agent_space_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(default='未命名演示文稿', max_length=255)),
                ('preset', models.CharField(choices=[('ppt', 'TabSlide 演示文稿 (1920×1080)'), ('xiaohongshu', '小红书笔记 (1080×1440)'), ('poster', '海报 (自定义)'), ('custom', '自定义尺寸')], default='ppt', max_length=32)),
                ('canvas_width', models.IntegerField(default=1920)),
                ('canvas_height', models.IntegerField(default=1080)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('pages_data', models.JSONField(blank=True, default=None, help_text='[DEPRECATED] 旧版全量页面 JSON，已被 SlidePage 替代', null=True)),
                ('page_meta', models.JSONField(blank=True, default=None, help_text='[DEPRECATED] 旧版页面元数据，已合并到 SlidePage 列', null=True)),
                ('font_meta', models.JSONField(blank=True, default=None, help_text='字体嵌入元数据 {embedded_fonts: [...], theme_fonts: {...}}', null=True)),
                ('theme', models.JSONField(blank=True, help_text='主题配色/字体配置 JSON', null=True)),
                ('latest_version', models.BigIntegerField(default=0, help_text='单调递增版本号，每次 save_pages / update_element 时 +1，CAS 防并发覆盖')),
                ('last_editor_type', models.CharField(blank=True, default='', help_text='最后编辑者类型: human / agent', max_length=16)),
                ('last_editor_id', models.CharField(blank=True, default='', help_text='最后编辑者 ID (user_id / agent_id)', max_length=64)),
                ('page_count', models.IntegerField(default=0)),
                ('thumbnail', models.CharField(blank=True, default='', max_length=512)),
                ('pptx_file', models.CharField(blank=True, default='', help_text='[废弃] 旧版本地临时路径，保留字段兼容，新逻辑使用 pptx_oss_url', max_length=512)),
                ('pptx_oss_url', models.CharField(blank=True, default='', help_text='最近一次生成的 PPTX 文件 OSS URL（持久化，替代本地临时路径）', max_length=1024)),
                ('pptx_dirty', models.BooleanField(default=True, help_text='SlidePage 变更后标记为脏，导出时重新生成 PPTX')),
                ('dirty_page_ids', models.JSONField(blank=True, default=None, help_text='自上次 PPTX 生成以来变更的页面 ID 列表（增量脏标记，Phase 3）', null=True)),
            ],
            options={
                'db_table': 'tabslide_project',
                'ordering': ['-updated_at'],
            },
            bases=(models.Model, apps.services.common.base_models.ContextSyncMixin),
        ),
    ]
