# Generated by Django 4.2.7 on 2026-03-04 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tabslide', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='slideproject',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slide_projects_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slideproject',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slide_projects_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slidepermission',
            name='slide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='tabslide.slideproject'),
        ),
        migrations.AddField(
            model_name='slidepagecache',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_caches', to='tabslide.slideproject'),
        ),
        migrations.AddField(
            model_name='slidepage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide_pages', to='tabslide.slideproject'),
        ),
        migrations.AddField(
            model_name='slidehistory',
            name='base_history',
            field=models.ForeignKey(blank=True, help_text='增量 diff 的基版本（is_snapshot=False 时指向最近的全量锚点）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diff_children', to='tabslide.slidehistory'),
        ),
        migrations.AddField(
            model_name='slidehistory',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='tabslide.slideproject'),
        ),
        migrations.AddField(
            model_name='slideelementchange',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_changes', to='tabslide.slideproject'),
        ),
        migrations.AddField(
            model_name='slidechange',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='tabslide.slideproject'),
        ),
        migrations.AddIndex(
            model_name='slideproject',
            index=models.Index(fields=['workspace_id', 'agent_space_id'], name='ppt_ws_proj_idx'),
        ),
        migrations.AddIndex(
            model_name='slideproject',
            index=models.Index(fields=['created_by', '-updated_at'], name='ppt_user_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='slidepermission',
            index=models.Index(fields=['slide', 'is_active'], name='tabslide_perm_slide_active_idx'),
        ),
        migrations.AddIndex(
            model_name='slidepermission',
            index=models.Index(fields=['subject_type', 'subject_id'], name='tabslide_perm_subject_idx'),
        ),
        migrations.AddConstraint(
            model_name='slidepermission',
            constraint=models.UniqueConstraint(fields=('slide', 'subject_type', 'subject_id'), name='tabslide_perm_unique_subject'),
        ),
        migrations.AddIndex(
            model_name='slidepagecache',
            index=models.Index(fields=['project', '-updated_at'], name='slidepagecache_proj_upd_idx'),
        ),
        migrations.AddConstraint(
            model_name='slidepagecache',
            constraint=models.UniqueConstraint(fields=('project', 'page_id'), name='slidepagecache_proj_page_uniq'),
        ),
        migrations.AddIndex(
            model_name='slidepage',
            index=models.Index(fields=['project', 'order'], name='slidepage_proj_order_idx'),
        ),
        migrations.AddIndex(
            model_name='slidepage',
            index=models.Index(fields=['project', 'version'], name='slidepage_proj_ver_idx'),
        ),
        migrations.AddConstraint(
            model_name='slidepage',
            constraint=models.UniqueConstraint(fields=('project', 'page_id'), name='slidepage_proj_pageid_uniq'),
        ),
        migrations.AddIndex(
            model_name='slidehistory',
            index=models.Index(fields=['project', 'created_at'], name='slidehist_proj_created_idx'),
        ),
        migrations.AddIndex(
            model_name='slidehistory',
            index=models.Index(fields=['project', 'is_named'], name='slidehist_proj_named_idx'),
        ),
        migrations.AddIndex(
            model_name='slidehistory',
            index=models.Index(fields=['project', 'version'], name='slidehist_proj_ver_idx'),
        ),
        migrations.AddIndex(
            model_name='slidehistory',
            index=models.Index(fields=['project', 'is_snapshot', '-created_at'], name='slidehist_proj_snap_idx'),
        ),
        migrations.AddIndex(
            model_name='slideelementchange',
            index=models.Index(fields=['project', 'page_id', 'element_id', '-created_at'], name='elemchange_proj_page_el_idx'),
        ),
        migrations.AddIndex(
            model_name='slideelementchange',
            index=models.Index(fields=['project', '-created_at'], name='elemchange_proj_created_idx'),
        ),
        migrations.AddIndex(
            model_name='slideelementchange',
            index=models.Index(fields=['project', 'version'], name='elemchange_proj_ver_idx'),
        ),
        migrations.AddIndex(
            model_name='slidechange',
            index=models.Index(fields=['project', '-version'], name='slidechange_proj_ver_idx'),
        ),
        migrations.AddIndex(
            model_name='slidechange',
            index=models.Index(fields=['project', 'created_at'], name='slidechange_proj_time_idx'),
        ),
    ]
