# Generated by Django 4.2.7 on 2026-03-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabslide', '0004_slide_admin_action_log'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='slideproject',
            name='ppt_ws_proj_idx',
        ),
        migrations.AlterField(
            model_name='slideproject',
            name='agent_space_id',
            field=models.UUIDField(db_column='agent_space_id', db_index=True),
        ),
        migrations.RenameField(
            model_name='slideproject',
            old_name='agent_space_id',
            new_name='space_id',
        ),
        migrations.AddField(
            model_name='slideproject',
            name='owner_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='slideproject',
            index=models.Index(fields=['workspace_id', 'space_id'], name='ppt_ws_proj_idx'),
        ),
    ]
