# Generated by Django 4.2.7 on 2026-03-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabslide', '0005_remove_slideproject_ppt_ws_proj_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideproject',
            name='space_id',
            field=models.UUIDField(db_index=True),
        ),
    ]
