# Generated by Django 4.2.7 on 2026-03-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabslide', '0006_alter_slideproject_space_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidepage',
            name='section_tag',
            field=models.JSONField(blank=True, default=None, help_text='章节标签 {id, title}（用于大纲视图和 Agent 结构化导航）', null=True),
        ),
        migrations.AddField(
            model_name='slidepage',
            name='slide_notes',
            field=models.JSONField(blank=True, default=None, help_text='批注数组 SlideNote[]（与 remark 演讲备注区分）', null=True),
        ),
        migrations.AddField(
            model_name='slidepage',
            name='slide_type',
            field=models.CharField(blank=True, default='', help_text='页面语义类型（cover/contents/transition/content/end）', max_length=32),
        ),
        migrations.AlterField(
            model_name='slidepage',
            name='content_format',
            field=models.CharField(choices=[('json', 'JSON'), ('html', 'HTML')], default='json', help_text='页面内容格式：json（elements_data 权威）/ html（html_source 权威）', max_length=16),
        ),
        migrations.AlterField(
            model_name='slideproject',
            name='preset',
            field=models.CharField(choices=[('ppt', 'TabSlide 演示文稿 (1920×1080)'), ('4:3', '4:3 传统比例 (1024×768)'), ('xiaohongshu', '小红书笔记 (1080×1440)'), ('poster', '海报 (1080×1920)'), ('custom', '自定义尺寸')], default='ppt', max_length=32),
        ),
    ]
