# Generated by Django 4.2.7 on 2026-03-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabslide', '0007_add_section_tag_slide_type_slide_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidepage',
            name='section_tag',
            field=models.JSONField(blank=True, default=None, help_text='章节标签 {id, title}，用于大纲视图分组', null=True),
        ),
        migrations.AlterField(
            model_name='slidepage',
            name='slide_notes',
            field=models.JSONField(blank=True, default=None, help_text='批注数组 SlideNote[]，与演讲备注 remark 独立', null=True),
        ),
        migrations.AlterField(
            model_name='slidepage',
            name='slide_type',
            field=models.CharField(blank=True, default='', help_text='页面语义类型：cover/contents/transition/content/end', max_length=32),
        ),
        migrations.AddIndex(
            model_name='slideproject',
            index=models.Index(fields=['workspace_id', 'space_id', 'status'], name='ppt_ws_proj_status_idx'),
        ),
    ]
