# Generated by Django 4.2.7 on 2026-03-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabslide', '0009_workspace_to_workteam_rename'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='slideproject',
            name='ppt_ws_proj_idx',
        ),
        migrations.RemoveIndex(
            model_name='slideproject',
            name='ppt_ws_proj_status_idx',
        ),
        migrations.AddField(
            model_name='slideelementchange',
            name='expired_at',
            field=models.DateTimeField(blank=True, default=None, help_text='过期时间（DB 层保底约束）。命名版本关联的变更设为 None（永不过期），其余由 save 逻辑设置为 created_at + TTL', null=True),
        ),
        migrations.AlterField(
            model_name='slidehistory',
            name='workteam_id',
            field=models.UUIDField(verbose_name='Workteam ID'),
        ),
        migrations.AddIndex(
            model_name='slideelementchange',
            index=models.Index(fields=['created_at'], name='elemchange_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='slideelementchange',
            index=models.Index(condition=models.Q(('expired_at__isnull', False)), fields=['expired_at'], name='elemchange_expired_at_idx'),
        ),
        migrations.AddIndex(
            model_name='slideproject',
            index=models.Index(fields=['workteam_id', 'space_id'], name='ppt_ws_proj_idx'),
        ),
        migrations.AddIndex(
            model_name='slideproject',
            index=models.Index(fields=['workteam_id', 'space_id', 'status'], name='ppt_ws_proj_status_idx'),
        ),
    ]
