# Generated by Django 4.2.7 on 2026-03-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabslide', '0010_remove_slideproject_ppt_ws_proj_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideelementchange',
            name='editor_type',
            field=models.CharField(default='user', help_text='user / agent / system', max_length=16),
        ),
        migrations.AlterField(
            model_name='slidehistory',
            name='editor_type',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='触发者类型 (user/agent)'),
        ),
        migrations.AlterField(
            model_name='slideproject',
            name='last_editor_type',
            field=models.CharField(blank=True, default='', help_text='最后编辑者类型: user / agent', max_length=16),
        ),
    ]
