# Generated by Django 4.2.7 on 2026-04-01 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabslide', '0011_alter_slideelementchange_editor_type_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidechange',
            name='agent_run_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='关联 Agent 操作批次的 run_id', max_length=64),
        ),
    ]
