# Generated by Django 4.2.7 on 2026-04-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabslide', '0013_alter_slidepermission_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidepermission',
            name='granted_by',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='授权人 ID'),
        ),
        migrations.AlterField(
            model_name='slidepermission',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否生效'),
        ),
        migrations.AlterField(
            model_name='slidepermission',
            name='permission',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('admin', 'Admin'), ('owner', 'Owner')], default='viewer', max_length=20, verbose_name='权限级别'),
        ),
        migrations.AlterField(
            model_name='slidepermission',
            name='subject_id',
            field=models.CharField(max_length=64, verbose_name='权限主体 ID'),
        ),
        migrations.AlterField(
            model_name='slidepermission',
            name='subject_type',
            field=models.CharField(choices=[('user', 'User'), ('role', 'Role'), ('agent', 'Agent')], max_length=20, verbose_name='权限主体类型'),
        ),
    ]
