# Generated by Django 4.2.7 on 2026-05-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabslide", "0014_alter_slidepermission_granted_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slidepage",
            name="content_format",
            field=models.CharField(
                choices=[("json", "JSON"), ("html", "HTML (deprecated, 仅存量兼容)")],
                default="json",
                help_text="@deprecated 永远落 'json'。HTML 模式已下线（2026-05），字段待 Phase 5 删除。",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="slidepage",
            name="html_source",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Agent 创作期 HTML 原文快照（read-only after creation）。仅作 Agent 后续创作的'风格参考语料'，**不参与渲染、不参与协同、不参与导出**。运行时真相源是 elements_data（PPTElement[]）。由 _SEALED_AFTER_CREATION_MODEL_FIELDS 守卫保证创建后不再被任何写入路径更新。",
            ),
        ),
    ]
