# Generated by Django 4.2.7 on 2026-06-05 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tabslide', '0015_alter_slidepage_content_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideproject',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slide_projects_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='slideproject',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slide_projects_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
