# Generated by Django 4.2.7 on 2026-06-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabslide', '0016_alter_slideproject_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideproject',
            name='space_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
