# Generated by Django 4.2.7 on 2026-07-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabslide', '0018_rename_workteam_to_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidehistory',
            name='organization_id',
            field=models.UUIDField(verbose_name='Organization ID'),
        ),
    ]
