# Generated by Django 4.2.7 on 2026-07-07 08:55
# Renumbered from 0018_canvas_default_1280 after rebase onto release/260727
# (which already has 0018_rename_workteam_to_organization + 0019).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabslide', '0019_alter_slidehistory_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideproject',
            name='canvas_height',
            field=models.IntegerField(default=720),
        ),
        migrations.AlterField(
            model_name='slideproject',
            name='canvas_width',
            field=models.IntegerField(default=1280),
        ),
        migrations.AlterField(
            model_name='slideproject',
            name='preset',
            field=models.CharField(choices=[('ppt', 'TabSlide 演示文稿 (1280×720)'), ('4:3', '4:3 传统比例 (1024×768)'), ('xiaohongshu', '小红书笔记 (1080×1440)'), ('poster', '海报 (1080×1920)'), ('custom', '自定义尺寸')], default='ppt', max_length=32),
        ),
    ]
