# Generated by Django 4.2.7 on 2026-07-09 10:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(help_text='访问地址 /dl/<slug>，如 mac-arm64、win-x64、campaign-2026q3', max_length=64, unique=True, verbose_name='短链标识')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='备注')),
                ('target_type', models.CharField(choices=[('static', '固定 URL'), ('latest_release', '跟随最新发版')], default='latest_release', max_length=20, verbose_name='目标类型')),
                ('target_url', models.URLField(blank=True, default='', help_text='target_type=static 时使用', max_length=2048, verbose_name='固定目标 URL')),
                ('release_platform', models.CharField(blank=True, choices=[('mac', 'macOS'), ('win', 'Windows'), ('linux', 'Linux')], default='', max_length=10, verbose_name='发版平台')),
                ('release_arch', models.CharField(blank=True, choices=[('x64', 'x64'), ('arm64', 'ARM64')], default='', max_length=10, verbose_name='发版架构')),
                ('release_channel', models.CharField(blank=True, default='stable', max_length=20, verbose_name='发版通道')),
                ('channel', models.CharField(blank=True, default='', max_length=64, verbose_name='渠道标签')),
                ('utm_source', models.CharField(blank=True, default='', max_length=128, verbose_name='UTM Source')),
                ('utm_medium', models.CharField(blank=True, default='', max_length=128, verbose_name='UTM Medium')),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=128, verbose_name='UTM Campaign')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='累计点击')),
                ('last_clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='最近点击时间')),
                ('created_by_id', models.UUIDField(blank=True, null=True, verbose_name='创建人')),
                ('updated_by_id', models.UUIDField(blank=True, null=True, verbose_name='更新人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '下载短链',
                'verbose_name_plural': '下载短链',
                'db_table': 'analytics_short_link',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('web', '官网'), ('electron', '桌面客户端'), ('daemon', 'Daemon'), ('mobile', '移动端'), ('server', '服务端'), ('other', '其它')], db_index=True, default='web', max_length=32, verbose_name='事件来源')),
                ('event_name', models.CharField(db_index=True, help_text='如 page_view / download / cta_click', max_length=64, verbose_name='事件名')),
                ('occurred_at', models.DateTimeField(db_index=True, help_text='事件真实发生时间（客户端提供，缺省用入库时间）', verbose_name='发生时间')),
                ('anon_id', models.CharField(blank=True, default='', max_length=64, verbose_name='匿名访客 ID')),
                ('session_id', models.CharField(blank=True, default='', max_length=64, verbose_name='会话 ID')),
                ('user_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='用户 ID')),
                ('path', models.CharField(blank=True, default='', max_length=512, verbose_name='页面路径')),
                ('referrer', models.CharField(blank=True, default='', max_length=1024, verbose_name='来源 URL')),
                ('referrer_host', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='来源域名')),
                ('utm_source', models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='UTM Source')),
                ('utm_medium', models.CharField(blank=True, default='', max_length=128, verbose_name='UTM Medium')),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=128, verbose_name='UTM Campaign')),
                ('platform', models.CharField(blank=True, default='', max_length=32, verbose_name='平台')),
                ('arch', models.CharField(blank=True, default='', max_length=16, verbose_name='架构')),
                ('app_version', models.CharField(blank=True, default='', max_length=64, verbose_name='版本')),
                ('geo_country', models.CharField(blank=True, default='', max_length=8, verbose_name='国家/地区')),
                ('ua_hash', models.CharField(blank=True, default='', help_text='User-Agent 的哈希，用于粗粒度去重，不存原始 UA（隐私）', max_length=64, verbose_name='UA 指纹')),
                ('props', models.JSONField(blank=True, default=dict, verbose_name='事件属性')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='入库时间')),
                ('short_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='analytics.shortlink', verbose_name='关联短链')),
            ],
            options={
                'verbose_name': '埋点事件',
                'verbose_name_plural': '埋点事件',
                'db_table': 'analytics_event',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['source', 'event_name', 'occurred_at'], name='ana_evt_src_name_time_idx'), models.Index(fields=['event_name', 'occurred_at'], name='ana_evt_name_time_idx')],
            },
        ),
    ]
