# Generated by Django 4.2.7 on 2026-07-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsevent',
            name='geo_province',
            field=models.CharField(blank=True, db_index=True, default='', help_text='采集入口用客户端 IP 现算，只落地域、不存原始 IP（隐私）', max_length=64, verbose_name='省份/州'),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='geo_country',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='国家/地区'),
        ),
    ]
