# Generated by Django 4.2.7 on 2026-03-04 20:27

from django.db import migrations, models
import pgvector.django
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_id', models.UUIDField(db_index=True, verbose_name='表格ID')),
                ('content', models.TextField(verbose_name='向量化的原文本')),
                ('content_hash', models.CharField(db_index=True, max_length=64, verbose_name='内容哈希')),
                ('embedding', pgvector.django.VectorField(dimensions=1536, verbose_name='向量')),
                ('metadata', models.JSONField(default=dict, verbose_name='元数据')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('success', '成功'), ('failed', '失败')], default='success', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '表格向量索引',
                'verbose_name_plural': '表格向量索引',
                'db_table': 'rag_table_embedding',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['table_id', 'version'], name='rag_table_e_table_i_d16973_idx'), models.Index(fields=['content_hash'], name='rag_table_e_content_a27d0e_idx'), models.Index(fields=['status'], name='rag_table_e_status_493959_idx')],
                'unique_together': {('table_id', 'version')},
            },
        ),
        migrations.CreateModel(
            name='SkillEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_key', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='技能唯一标识')),
                ('source', models.CharField(db_index=True, help_text='app / system / market / managed / custom', max_length=20, verbose_name='来源')),
                ('content', models.TextField(verbose_name='向量化的原文本')),
                ('content_hash', models.CharField(db_index=True, max_length=64, verbose_name='内容哈希')),
                ('embedding', pgvector.django.VectorField(dimensions=1536, verbose_name='向量')),
                ('metadata', models.JSONField(default=dict, help_text='name, description, location, tags, auto_activate_for', verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '技能向量索引',
                'verbose_name_plural': '技能向量索引',
                'db_table': 'rag_skill_embedding',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['source'], name='rag_skill_e_source_658631_idx'), models.Index(fields=['content_hash'], name='rag_skill_e_content_d4f945_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True, verbose_name='用户ID')),
                ('session_id', models.UUIDField(blank=True, null=True, verbose_name='会话ID')),
                ('query', models.TextField(verbose_name='查询文本')),
                ('query_embedding', pgvector.django.VectorField(blank=True, dimensions=1536, null=True, verbose_name='查询向量')),
                ('results_count', models.IntegerField(verbose_name='结果数量')),
                ('top_similarity_score', models.FloatField(verbose_name='最高相似度')),
                ('response_time_ms', models.IntegerField(verbose_name='响应时间(毫秒)')),
                ('filters', models.JSONField(default=dict, verbose_name='过滤条件')),
                ('user_feedback', models.CharField(blank=True, choices=[('helpful', '有帮助'), ('not_helpful', '无帮助')], max_length=20, verbose_name='用户反馈')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '检索日志',
                'verbose_name_plural': '检索日志',
                'db_table': 'rag_search_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'created_at'], name='rag_search__user_id_9ffb94_idx'), models.Index(fields=['session_id'], name='rag_search__session_b95ade_idx'), models.Index(fields=['created_at'], name='rag_search__created_b3a146_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecordEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_id', models.UUIDField(db_index=True, verbose_name='记录ID')),
                ('table_id', models.UUIDField(db_index=True, verbose_name='表格ID')),
                ('content', models.TextField(verbose_name='向量化的原文本')),
                ('content_hash', models.CharField(db_index=True, max_length=64, verbose_name='内容哈希')),
                ('embedding', pgvector.django.VectorField(dimensions=1536, verbose_name='向量')),
                ('metadata', models.JSONField(default=dict, verbose_name='元数据')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('success', '成功'), ('failed', '失败')], default='success', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '记录向量索引',
                'verbose_name_plural': '记录向量索引',
                'db_table': 'rag_record_embedding',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['record_id', 'version'], name='rag_record__record__b6998c_idx'), models.Index(fields=['table_id', 'priority'], name='rag_record__table_i_1837b8_idx'), models.Index(fields=['content_hash'], name='rag_record__content_15b0ca_idx'), models.Index(fields=['status'], name='rag_record__status_548380_idx'), models.Index(fields=['created_at'], name='rag_record__created_600b20_idx')],
                'unique_together': {('record_id', 'version')},
            },
        ),
        migrations.CreateModel(
            name='EmbeddingTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('table', '表格'), ('record', '记录'), ('batch', '批量')], max_length=20, verbose_name='任务类型')),
                ('target_id', models.UUIDField(verbose_name='目标ID')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('success', '成功'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Celery任务ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '向量化任务',
                'verbose_name_plural': '向量化任务',
                'db_table': 'rag_embedding_task',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='rag_embeddi_status_057263_idx'), models.Index(fields=['task_type', 'target_id'], name='rag_embeddi_task_ty_26dd53_idx'), models.Index(fields=['celery_task_id'], name='rag_embeddi_celery__e14df8_idx')],
            },
        ),
    ]
