# Generated by Django 4.2.7 on 2026-03-06 14:00

from django.db import migrations, models
import pgvector.django
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0004_embeddingtask_workspace_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeChunkEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_id', models.CharField(db_index=True, help_text='{workspace_id}:{sha256(project_root)[:16]}', max_length=255, verbose_name='项目标识')),
                ('workspace_id', models.UUIDField(db_index=True, verbose_name='工作空间ID')),
                ('file_path', models.CharField(max_length=1024, verbose_name='文件路径')),
                ('start_line', models.IntegerField(verbose_name='起始行')),
                ('end_line', models.IntegerField(verbose_name='结束行')),
                ('signature', models.CharField(blank=True, default='', max_length=255, verbose_name='签名')),
                ('kind', models.CharField(choices=[('function', '函数'), ('class', '类'), ('method', '方法'), ('interface', '接口'), ('module', '模块'), ('block', '代码块')], default='block', max_length=20, verbose_name='代码块类型')),
                ('language', models.CharField(max_length=30, verbose_name='编程语言')),
                ('content', models.TextField(verbose_name='代码内容')),
                ('content_hash', models.CharField(db_index=True, max_length=64, verbose_name='内容哈希')),
                ('embedding', pgvector.django.VectorField(blank=True, dimensions=1536, null=True, verbose_name='向量')),
                ('metadata', models.JSONField(default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '代码块向量索引',
                'verbose_name_plural': '代码块向量索引',
                'db_table': 'rag_code_chunk_embedding',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='documentembedding',
            new_name='rag_documen_status_96166d_idx',
            old_name='rag_docemb_status_idx',
        ),
        migrations.RenameIndex(
            model_name='documentembedding',
            new_name='rag_documen_workspa_a7382b_idx',
            old_name='rag_docemb_ws_status_idx',
        ),
        migrations.AlterField(
            model_name='embeddingtask',
            name='task_type',
            field=models.CharField(choices=[('table', '表格'), ('record', '记录'), ('batch', '批量'), ('document', '文档')], max_length=20, verbose_name='任务类型'),
        ),
        migrations.AddIndex(
            model_name='codechunkembedding',
            index=models.Index(fields=['project_id', 'file_path'], name='rag_code_ch_project_6ec634_idx'),
        ),
        migrations.AddIndex(
            model_name='codechunkembedding',
            index=models.Index(fields=['workspace_id'], name='rag_code_ch_workspa_d11b86_idx'),
        ),
        migrations.AddIndex(
            model_name='codechunkembedding',
            index=models.Index(fields=['content_hash'], name='rag_code_ch_content_418017_idx'),
        ),
        migrations.AddIndex(
            model_name='codechunkembedding',
            index=models.Index(fields=['language'], name='rag_code_ch_languag_1c1baa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='codechunkembedding',
            unique_together={('project_id', 'file_path', 'start_line', 'end_line')},
        ),
    ]
