# Generated by Django 4.2.7 on 2026-03-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0005_code_chunk_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddingtask',
            name='task_type',
            field=models.CharField(choices=[('table', '表格'), ('record', '记录'), ('batch', '批量'), ('document', '文档'), ('code', '代码')], max_length=20, verbose_name='任务类型'),
        ),
    ]
