# Generated by Django 4.2.7 on 2026-03-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0007_add_code_chunk_hnsw_and_partial_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentembedding',
            name='agent_space_id',
            field=models.UUIDField(db_column='agent_space_id', db_index=True, verbose_name='智能体空间ID'),
        ),
        migrations.RenameField(
            model_name='documentembedding',
            old_name='agent_space_id',
            new_name='space_id',
        ),
    ]
