# Generated by Django 4.2.7 on 2026-03-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0008_alter_documentembedding_agent_space_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentembedding',
            name='space_id',
            field=models.UUIDField(db_index=True, verbose_name='所属空间'),
        ),
    ]
