# Generated by Django 4.2.7 on 2026-03-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0009_alter_documentembedding_space_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentembedding',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='recordembedding',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='tableembedding',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
