# Generated by Django 4.2.7 on 2026-03-18 01:20

from django.db import migrations, models


def mark_orphan_chunks_failed(apps, schema_editor):
    """RC-011: 将 embedding=NULL 的孤儿 chunk 状态标记为 failed，使其可被重新索引。"""
    CodeChunkEmbedding = apps.get_model('rag', 'CodeChunkEmbedding')
    db_alias = schema_editor.connection.alias
    CodeChunkEmbedding.objects.using(db_alias).filter(
        embedding__isnull=True
    ).update(status='failed', error_message='orphan_embedding_null')


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0011_tableembedding_workspace_id_recordembedding_workspace_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='codechunkembedding',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='错误信息'),
        ),
        migrations.AddField(
            model_name='codechunkembedding',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('success', '成功'), ('failed', '失败')], db_index=True, default='pending', help_text='pending=等待向量化, processing=向量化中, success=已完成, failed=向量化失败', max_length=20, verbose_name='状态'),
        ),
        migrations.AddIndex(
            model_name='codechunkembedding',
            index=models.Index(fields=['status'], name='rag_code_ch_status_a60ff6_idx'),
        ),
        migrations.AddIndex(
            model_name='codechunkembedding',
            index=models.Index(fields=['project_id', 'status'], name='rag_code_ch_project_3d8135_idx'),
        ),
        migrations.RunPython(mark_orphan_chunks_failed, migrations.RunPython.noop),
    ]
