# Generated by Django 4.2.7 on 2026-03-18 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0014_alter_embedding_dimensions_1024'),
        ('rag', '0014_ensure_embedding_tables_exist'),
        ('rag', '0014_skillembedding_workspace_id_space_id'),
    ]

    operations = [
    ]
