# Generated by Django 4.2.7 on 2026-03-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0016_workspace_to_workteam_rename'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='codechunkembedding',
            name='rag_code_ch_workspa_d11b86_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentembedding',
            name='rag_documen_workspa_a7382b_idx',
        ),
        migrations.RemoveIndex(
            model_name='skillembedding',
            name='rag_skill_emb_workspace_idx',
        ),
        migrations.RenameIndex(
            model_name='skillembedding',
            new_name='rag_skill_e_space_i_16625b_idx',
            old_name='rag_skill_emb_space_idx',
        ),
        migrations.RemoveField(
            model_name='embeddingtask',
            name='workspace_id',
        ),
        migrations.RemoveField(
            model_name='recordembedding',
            name='workspace_id',
        ),
        migrations.RemoveField(
            model_name='skillembedding',
            name='workspace_id',
        ),
        migrations.RemoveField(
            model_name='tableembedding',
            name='workspace_id',
        ),
        migrations.AddField(
            model_name='embeddingtask',
            name='workteam_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='冗余字段，用于快速按 workteam 过滤任务', null=True, verbose_name='工作团队ID'),
        ),
        migrations.AddField(
            model_name='recordembedding',
            name='workteam_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='冗余顶层字段，用于高效按 workteam 过滤；与 metadata.workteam_id 保持同步', null=True, verbose_name='工作团队ID'),
        ),
        migrations.AddField(
            model_name='skillembedding',
            name='workteam_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='冗余顶层字段，用于高效按 workteam 过滤；与 metadata.workteam_id 保持同步', null=True, verbose_name='工作团队ID'),
        ),
        migrations.AddField(
            model_name='tableembedding',
            name='workteam_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='冗余顶层字段，用于高效按 workteam 过滤；与 metadata.workteam_id 保持同步', null=True, verbose_name='工作团队ID'),
        ),
        migrations.AlterField(
            model_name='codechunkembedding',
            name='project_id',
            field=models.CharField(db_index=True, help_text='{workteam_id}:{sha256(project_root)[:16]}', max_length=255, verbose_name='项目标识'),
        ),
        migrations.AlterField(
            model_name='codechunkembedding',
            name='workteam_id',
            field=models.UUIDField(db_index=True, verbose_name='工作团队ID'),
        ),
        migrations.AlterField(
            model_name='documentembedding',
            name='workteam_id',
            field=models.UUIDField(db_index=True, verbose_name='工作团队ID'),
        ),
        migrations.AlterField(
            model_name='embeddingtask',
            name='task_type',
            field=models.CharField(choices=[('table', '表格'), ('record', '记录'), ('batch', '批量'), ('document', '文档'), ('code', '代码'), ('skill', '技能'), ('mail', '邮件')], max_length=20, verbose_name='任务类型'),
        ),
        migrations.AddIndex(
            model_name='codechunkembedding',
            index=models.Index(fields=['workteam_id'], name='rag_code_ch_worktea_fd670a_idx'),
        ),
        migrations.AddIndex(
            model_name='documentembedding',
            index=models.Index(fields=['workteam_id', 'status'], name='rag_documen_worktea_d12940_idx'),
        ),
        migrations.AddIndex(
            model_name='skillembedding',
            index=models.Index(fields=['workteam_id'], name='rag_skill_e_worktea_bd4190_idx'),
        ),
    ]
