# Generated by Django 4.2.7 on 2026-04-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0018_backfill_workteam_id_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillembedding',
            name='workteam_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='冗余顶层字段，用于高效按 workteam 过滤；系统/平台级 Skill 无 workteam 时为 NULL', null=True, verbose_name='工作团队ID'),
        ),
    ]
