# Generated by Django 4.2.7 on 2026-04-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0019_skill_embedding_workteam_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillembedding',
            name='source',
            field=models.CharField(db_index=True, help_text='platform / app / user（旧值 system/market/managed 经兼容层自动映射）', max_length=20, verbose_name='来源'),
        ),
    ]
