# Generated by Django 4.2.7 on 2026-07-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0022_rename_workteam_to_organization'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='codechunkembedding',
            new_name='rag_code_ch_organiz_ec5657_idx',
            old_name='rag_code_ch_worktea_fd670a_idx',
        ),
        migrations.RenameIndex(
            model_name='documentembedding',
            new_name='rag_documen_organiz_5146a3_idx',
            old_name='rag_documen_worktea_d12940_idx',
        ),
        migrations.RenameIndex(
            model_name='skillembedding',
            new_name='rag_skill_e_organiz_8828d4_idx',
            old_name='rag_skill_e_worktea_bd4190_idx',
        ),
        migrations.AlterField(
            model_name='codechunkembedding',
            name='organization_id',
            field=models.UUIDField(db_index=True, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='codechunkembedding',
            name='project_id',
            field=models.CharField(db_index=True, help_text='{organization_id}:{sha256(project_root)[:16]}', max_length=255, verbose_name='项目标识'),
        ),
        migrations.AlterField(
            model_name='documentembedding',
            name='organization_id',
            field=models.UUIDField(db_index=True, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='embeddingtask',
            name='organization_id',
            field=models.UUIDField(db_index=True, help_text='冗余字段，用于快速按 organization 过滤任务', verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='recordembedding',
            name='organization_id',
            field=models.UUIDField(db_index=True, help_text='冗余顶层字段，用于高效按 organization 过滤；与 metadata.organization_id 保持同步', verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='skillembedding',
            name='organization_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='冗余顶层字段，用于高效按 organization 过滤；系统/平台级 Skill 无 organization 时为 NULL', null=True, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='tableembedding',
            name='organization_id',
            field=models.UUIDField(db_index=True, help_text='冗余顶层字段，用于高效按 organization 过滤；与 metadata.organization_id 保持同步', verbose_name='组织ID'),
        ),
    ]
